In [2]:
import os
import pandas as pd
import numpy as np
from statsmodels.stats.proportion import proportions_ztest
import matplotlib.pyplot as plt
import statsmodels.api as sm
from sklearn.linear_model import LogisticRegression

In [3]:
pd.set_option('display.max_columns',900)

In [4]:
df=pd.read_csv('df.csv')

C:\Users\enabi\miniconda3\envs\Projects\lib\site-packages\IPython\core\interactiveshell.py:3071: DtypeWarning: Columns (102) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [5]:
df.head(1)

,Unnamed: 0,Date,HomeTeam,AwayTeam,Final_Home_goals,Final_Away_goals,Half_Time_Home_Goals,Half_Time_Away_Goals,Half_Time_Result,Crowd_Attendance,Referee,Home_Shots,Away_Shots,Home_Shots_Target,Away_Shots_Target,Home_Woodwork,Away_Woodwork,Home_Corners,Away_Corners,Home_Fouls,Away_Fouls,Home_Offsides,Away_Offsides,Home_Yellow_Cards,Away_Yellow_Cards,Home_Red_Cards,Away_Red_Cards,Home_Bookings_Points,Away_Bookings_Points,GBH,GBD,GBA,IWH,IWD,IWA,LBH,LBD,LBA,SBH,SBD,SBA,WHH,WHD,WHA,SYH,SYD,SYA,B365H,B365D,B365A,SOH,SOD,SOA,GB>2.5,GB<2.5,B365>2.5,B365<2.5,GBAHH,GBAHA,GBAH,LBAHH,LBAHA,LBAH,B365AHH,B365AHA,B365AH,BWH,BWD,BWA,SJH,SJD,SJA,VCH,VCD,VCA,Bb1X2,BbMxH,BbAvH,BbMxD,BbAvD,BbMxA,BbAvA,BbOU,BbMx>2.5,BbAv>2.5,BbMx<2.5,BbAv<2.5,BbAH,BbAHh,BbMxAHH,BbAvAHH,BbMxAHA,BbAvAHA,BSH,BSD,BSA,PSH,PSD,PSA,PSCH,PSCD,PSCA,Time,MaxH,MaxD,MaxA,AvgH,AvgD,AvgA,P>2.5,P<2.5,Max>2.5,Max<2.5,Avg>2.5,Avg<2.5,AHh,PAHH,PAHA,MaxAHH,MaxAHA,AvgAHH,AvgAHA,B365CH,B365CD,B365CA,BWCH,BWCD,BWCA,IWCH,IWCD,IWCA,WHCH,WHCD,WHCA,VCCH,VCCD,VCCA,MaxCH,MaxCD,MaxCA,AvgCH,AvgCD,AvgCA,B365C>2.5,B365C<2.5,PC>2.5,PC<2.5,MaxC>2.5,MaxC<2.5,AvgC>2.5,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,Season,Final_result,Winner,Home_score,Away_score,Corners_ratio
0,0,2000-08-19,Charlton,Man City,4.0,0.0,2.0,0.0,1,20043.0,Rob Harris,17.0,8.0,14.0,4.0,2.0,1.0,6.0,6.0,13.0,12.0,8.0,6.0,1.0,2.0,0.0,0.0,10.0,20.0,2.0,3.0,3.2,2.2,2.9,2.7,2.2,3.25,2.75,2.2,3.25,2.88,2.1,3.2,3.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,Charlton,3.0,0.0,0.5

In [6]:
del df['Unnamed: 0']

In [7]:
df2=df.copy()

In [8]:
df2.shape

(7508, 165)

In [9]:
col= df2.loc[:,'Date':'Away_Bookings_Points'].columns
col

Index(['Date', 'HomeTeam', 'AwayTeam', 'Final_Home_goals', 'Final_Away_goals',
       'Half_Time_Home_Goals', 'Half_Time_Away_Goals', 'Half_Time_Result',
       'Crowd_Attendance', 'Referee', 'Home_Shots', 'Away_Shots',
       'Home_Shots_Target', 'Away_Shots_Target', 'Home_Woodwork',
       'Away_Woodwork', 'Home_Corners', 'Away_Corners', 'Home_Fouls',
       'Away_Fouls', 'Home_Offsides', 'Away_Offsides', 'Home_Yellow_Cards',
       'Away_Yellow_Cards', 'Home_Red_Cards', 'Away_Red_Cards',
       'Home_Bookings_Points', 'Away_Bookings_Points'],
      dtype='object')

In [10]:
#list(col)+['Final_result','Home_score','Away_score']

In [11]:
df2= df2.loc[:,list(col)+['Final_result','Home_score','Away_score']]
df2.head(2)

,Date,HomeTeam,AwayTeam,Final_Home_goals,Final_Away_goals,Half_Time_Home_Goals,Half_Time_Away_Goals,Half_Time_Result,Crowd_Attendance,Referee,Home_Shots,Away_Shots,Home_Shots_Target,Away_Shots_Target,Home_Woodwork,Away_Woodwork,Home_Corners,Away_Corners,Home_Fouls,Away_Fouls,Home_Offsides,Away_Offsides,Home_Yellow_Cards,Away_Yellow_Cards,Home_Red_Cards,Away_Red_Cards,Home_Bookings_Points,Away_Bookings_Points,Final_result,Home_score,Away_score
0,2000-08-19,Charlton,Man City,4.0,0.0,2.0,0.0,1,20043.0,Rob Harris,17.0,8.0,14.0,4.0,2.0,1.0,6.0,6.0,13.0,12.0,8.0,6.0,1.0,2.0,0.0,0.0,10.0,20.0,1.0,3.0,0.0
1,2000-08-19,Chelsea,West Ham,4.0,2.0,1.0,0.0,1,34914.0,Graham Barber,17.0,12.0,10.0,5.0,1.0,0.0,7.0,7.0,19.0,14.0,2.0,3.0,1.0,2.0,0.0,0.0,10.0,20.0,1.0,3.0,0.0

In [12]:
df2.shape

(7508, 31)

In [13]:
df2.sort_values('Date', inplace=True)

In [14]:
df2.head()

,Date,HomeTeam,AwayTeam,Final_Home_goals,Final_Away_goals,Half_Time_Home_Goals,Half_Time_Away_Goals,Half_Time_Result,Crowd_Attendance,Referee,Home_Shots,Away_Shots,Home_Shots_Target,Away_Shots_Target,Home_Woodwork,Away_Woodwork,Home_Corners,Away_Corners,Home_Fouls,Away_Fouls,Home_Offsides,Away_Offsides,Home_Yellow_Cards,Away_Yellow_Cards,Home_Red_Cards,Away_Red_Cards,Home_Bookings_Points,Away_Bookings_Points,Final_result,Home_score,Away_score
0,2000-08-19,Charlton,Man City,4.0,0.0,2.0,0.0,1,20043.0,Rob Harris,17.0,8.0,14.0,4.0,2.0,1.0,6.0,6.0,13.0,12.0,8.0,6.0,1.0,2.0,0.0,0.0,10.0,20.0,1.0,3.0,0.0
1,2000-08-19,Chelsea,West Ham,4.0,2.0,1.0,0.0,1,34914.0,Graham Barber,17.0,12.0,10.0,5.0,1.0,0.0,7.0,7.0,19.0,14.0,2.0,3.0,1.0,2.0,0.0,0.0,10.0,20.0,1.0,3.0,0.0
2,2000-08-19,Coventry,Middlesbrough,1.0,3.0,1.0,1.0,2,20624.0,Barry Knight,6.0,16.0,3.0,9.0,0.0,1.0,8.0,4.0,15.0,21.0,1.0,3.0,5.0,3.0,1.0,0.0,75.0,30.0,3.0,0.0,3.0
3,2000-08-19,Derby,Southampton,2.0,2.0,1.0,2.0,3,27223.0,Andy D'Urso,6.0,13.0,4.0,6.0,0.0,0.0,5.0,8.0,11.0,13.0,0.0,2.0,1.0,1.0,0.0,0.0,10.0,10.0,2.0,1.0,1.0
4,2000-08-19,Leeds,Everton,2.0,0.0,2.0,0.0,1,40010.0,Dermot Gallagher,17.0,12.0,8.0,6.0,0.0,0.0,6.0,4.0,21.0,20.0,6.0,1.0,1.0,3.0,0.0,0.0,10.0,30.0,1.0,3.0,0.0

In [15]:
shh = df2.groupby(['HomeTeam']).shift()
shh.head(5)

,Date,AwayTeam,Final_Home_goals,Final_Away_goals,Half_Time_Home_Goals,Half_Time_Away_Goals,Half_Time_Result,Crowd_Attendance,Referee,Home_Shots,Away_Shots,Home_Shots_Target,Away_Shots_Target,Home_Woodwork,Away_Woodwork,Home_Corners,Away_Corners,Home_Fouls,Away_Fouls,Home_Offsides,Away_Offsides,Home_Yellow_Cards,Away_Yellow_Cards,Home_Red_Cards,Away_Red_Cards,Home_Bookings_Points,Away_Bookings_Points,Final_result,Home_score,Away_score
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
shh = df2.groupby(['HomeTeam']).shift()
del shh['Date']
sha = df2.groupby(['AwayTeam']).shift()
del sha['Date']
temp_H =pd.DataFrame(df2[['Date','HomeTeam']]).join(shh)
temp_A =pd.DataFrame(df2[['Date','AwayTeam']]).join(sha)

In [17]:
shh.shape

(7508, 29)

In [18]:
temp_H.loc[temp_H['HomeTeam']=='Charlton'].head(3)

,Date,HomeTeam,AwayTeam,Final_Home_goals,Final_Away_goals,Half_Time_Home_Goals,Half_Time_Away_Goals,Half_Time_Result,Crowd_Attendance,Referee,Home_Shots,Away_Shots,Home_Shots_Target,Away_Shots_Target,Home_Woodwork,Away_Woodwork,Home_Corners,Away_Corners,Home_Fouls,Away_Fouls,Home_Offsides,Away_Offsides,Home_Yellow_Cards,Away_Yellow_Cards,Home_Red_Cards,Away_Red_Cards,Home_Bookings_Points,Away_Bookings_Points,Final_result,Home_score,Away_score
0,2000-08-19,Charlton,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,2000-09-06,Charlton,Man City,4.0,0.0,2.0,0.0,1.0,20043.0,Rob Harris,17.0,8.0,14.0,4.0,2.0,1.0,6.0,6.0,13.0,12.0,8.0,6.0,1.0,2.0,0.0,0.0,10.0,20.0,1.0,3.0,0.0
54,2000-09-16,Charlton,Southampton,1.0,1.0,0.0,0.0,2.0,20043.0,Mark Halsey,8.0,11.0,6.0,3.0,0.0,0.0,10.0,14.0,14.0,16.0,4.0,3.0,3.0,3.0,1.0,0.0,55.0,30.0,2.0,1.0,1.0

In [19]:
df2.loc[df2['HomeTeam']=='Charlton'].head(3)

,Date,HomeTeam,AwayTeam,Final_Home_goals,Final_Away_goals,Half_Time_Home_Goals,Half_Time_Away_Goals,Half_Time_Result,Crowd_Attendance,Referee,Home_Shots,Away_Shots,Home_Shots_Target,Away_Shots_Target,Home_Woodwork,Away_Woodwork,Home_Corners,Away_Corners,Home_Fouls,Away_Fouls,Home_Offsides,Away_Offsides,Home_Yellow_Cards,Away_Yellow_Cards,Home_Red_Cards,Away_Red_Cards,Home_Bookings_Points,Away_Bookings_Points,Final_result,Home_score,Away_score
0,2000-08-19,Charlton,Man City,4.0,0.0,2.0,0.0,1,20043.0,Rob Harris,17.0,8.0,14.0,4.0,2.0,1.0,6.0,6.0,13.0,12.0,8.0,6.0,1.0,2.0,0.0,0.0,10.0,20.0,1.0,3.0,0.0
37,2000-09-06,Charlton,Southampton,1.0,1.0,0.0,0.0,2,20043.0,Mark Halsey,8.0,11.0,6.0,3.0,0.0,0.0,10.0,14.0,14.0,16.0,4.0,3.0,3.0,3.0,1.0,0.0,55.0,30.0,2.0,1.0,1.0
54,2000-09-16,Charlton,Tottenham,1.0,0.0,1.0,0.0,1,20043.0,Jeff Winter,9.0,10.0,5.0,5.0,1.0,1.0,7.0,5.0,8.0,10.0,3.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,0.0

In [20]:
temp_H=temp_H.set_index('Date')
temp_A=temp_A.set_index('Date')

In [21]:
# rolling the 'Final_Home_goals' for each team as a 'HomeTeam'
#df2.groupby(['HomeTeam'])['Final_Home_goals'].rolling(6, min_periods=6).sum()

In [22]:
# merging the above rolling results with the basic df
#res= pd.merge(df2.reset_index(), df2.groupby(['HomeTeam'])['Final_Home_goals'].rolling(6, min_periods=6).sum().reset_index(), on=['HomeTeam', 'Date'])

In [23]:
res1= pd.merge(df2, temp_H.groupby(['HomeTeam']).rolling(6, min_periods=6).sum().reset_index(), suffixes=['','_HomeTeam_sum_6'], on=['HomeTeam', 'Date'])

In [24]:
res1.shape

(7508, 58)

In [25]:
res1.loc[res1['HomeTeam']=='Charlton'].head(7)

,Date,HomeTeam,AwayTeam,Final_Home_goals,Final_Away_goals,Half_Time_Home_Goals,Half_Time_Away_Goals,Half_Time_Result,Crowd_Attendance,Referee,Home_Shots,Away_Shots,Home_Shots_Target,Away_Shots_Target,Home_Woodwork,Away_Woodwork,Home_Corners,Away_Corners,Home_Fouls,Away_Fouls,Home_Offsides,Away_Offsides,Home_Yellow_Cards,Away_Yellow_Cards,Home_Red_Cards,Away_Red_Cards,Home_Bookings_Points,Away_Bookings_Points,Final_result,Home_score,Away_score,Final_Home_goals_HomeTeam_sum_6,Final_Away_goals_HomeTeam_sum_6,Half_Time_Home_Goals_HomeTeam_sum_6,Half_Time_Away_Goals_HomeTeam_sum_6,Half_Time_Result_HomeTeam_sum_6,Crowd_Attendance_HomeTeam_sum_6,Home_Shots_HomeTeam_sum_6,Away_Shots_HomeTeam_sum_6,Home_Shots_Target_HomeTeam_sum_6,Away_Shots_Target_HomeTeam_sum_6,Home_Woodwork_HomeTeam_sum_6,Away_Woodwork_HomeTeam_sum_6,Home_Corners_HomeTeam_sum_6,Away_Corners_HomeTeam_sum_6,Home_Fouls_HomeTeam_sum_6,Away_Fouls_HomeTeam_sum_6,Home_Offsides_HomeTeam_sum_6,Away_Offsides_HomeTeam_sum_6,Home_Yellow_Cards_HomeTeam_sum_6,Away_Yellow_Cards_HomeTeam_sum_6,Home_Red_Cards_HomeTeam_sum_6,Away_Red_Cards_HomeTeam_sum_6,Home_Bookings_Points_HomeTeam_sum_6,Away_Bookings_Points_HomeTeam_sum_6,Final_result_HomeTeam_sum_6,Home_score_HomeTeam_sum_6,Away_score_HomeTeam_sum_6
0,2000-08-19,Charlton,Man City,4.0,0.0,2.0,0.0,1,20043.0,Rob Harris,17.0,8.0,14.0,4.0,2.0,1.0,6.0,6.0,13.0,12.0,8.0,6.0,1.0,2.0,0.0,0.0,10.0,20.0,1.0,3.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,2000-09-06,Charlton,Southampton,1.0,1.0,0.0,0.0,2,20043.0,Mark Halsey,8.0,11.0,6.0,3.0,0.0,0.0,10.0,14.0,14.0,16.0,4.0,3.0,3.0,3.0,1.0,0.0,55.0,30.0,2.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,2000-09-16,Charlton,Tottenham,1.0,0.0,1.0,0.0,1,20043.0,Jeff Winter,9.0,10.0,5.0,5.0,1.0,1.0,7.0,5.0,8.0,10.0,3.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70,2000-09-30,Charlton,Coventry,2.0,2.0,0.0,1.0,3,20043.0,Rob Styles,12.0,10.0,8.0,6.0,1.0,0.0,6.0,6.0,8.0,16.0,5.0,0.0,1.0,2.0,0.0,0.0,10.0,20.0,2.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90,2000-10-21,Charlton,Middlesbrough,1.0,0.0,0.0,0.0,2,20043.0,Mike Riley,5.0,8.0,2.0,6.0,0.0,0.0,5.0,6.0,11.0,19.0,4.0,2.0,2.0,2.0,0.0,0.0,20.0,20.0,1.0,3.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
110,2000-11-04,Charlton,Bradford,2.0,0.0,2.0,0.0,1,19655.0,Neale Barry,11.0,12.0,7.0,8.0,0.0,0.0,3.0,6.0,10.0,20.0,9.0,1.0,0.0,1.0,0.0,1.0,0.0,35.0,1.0,3.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
132,2000-11-18,Charlton,Chelsea,2.0,0.0,1.0,0.0,1,20043.0,Paul Durkin,10.0,13.0,6.0,3.0,0.0,1.0,4.0,5.0,18.0,22.0,5.0,1.0,2.0,3.0,0.0,0.0,20.0,30.0,1.0,3.0,0.0,11.0,3.0,5.0,1.0,10.0,119870.0,62.0,59.0,42.0,32.0,4.0,2.0,37.0,43.0,64.0,93.0,33.0,14.0,7.0,10.0,1.0,1.0,95.0,125.0,8.0,14.0,2.0

In [26]:
# merging the basic df with the results of rolling (sum) every column for each team as a 'HomeTeam'
#res1= pd.merge(df2.reset_index(), df2.groupby(['HomeTeam']).rolling(6, min_periods=6).sum().reset_index(), suffixes=['','_HomeTeam_sum_6'], on=['HomeTeam', 'Date'])

In [27]:
#res1.tail().to_csv('tail_HomeTeam_sum_6.csv')

In [28]:
# merging the basic df with the results of rolling (sum) every column for each team as a 'AwayTeam'
#res2= pd.merge(res1, df2.groupby(['AwayTeam']).rolling(6, min_periods=6).sum().reset_index(), suffixes=['','_AwayTeam_sum_6'], on=['AwayTeam', 'Date'])

In [29]:
res1= pd.merge(res1, temp_A.groupby(['AwayTeam']).rolling(6, min_periods=6).sum().reset_index(), suffixes=['','_AwayTeam_sum_6'], on=['AwayTeam', 'Date'])

In [30]:
res1.head(1)

,Date,HomeTeam,AwayTeam,Final_Home_goals,Final_Away_goals,Half_Time_Home_Goals,Half_Time_Away_Goals,Half_Time_Result,Crowd_Attendance,Referee,Home_Shots,Away_Shots,Home_Shots_Target,Away_Shots_Target,Home_Woodwork,Away_Woodwork,Home_Corners,Away_Corners,Home_Fouls,Away_Fouls,Home_Offsides,Away_Offsides,Home_Yellow_Cards,Away_Yellow_Cards,Home_Red_Cards,Away_Red_Cards,Home_Bookings_Points,Away_Bookings_Points,Final_result,Home_score,Away_score,Final_Home_goals_HomeTeam_sum_6,Final_Away_goals_HomeTeam_sum_6,Half_Time_Home_Goals_HomeTeam_sum_6,Half_Time_Away_Goals_HomeTeam_sum_6,Half_Time_Result_HomeTeam_sum_6,Crowd_Attendance_HomeTeam_sum_6,Home_Shots_HomeTeam_sum_6,Away_Shots_HomeTeam_sum_6,Home_Shots_Target_HomeTeam_sum_6,Away_Shots_Target_HomeTeam_sum_6,Home_Woodwork_HomeTeam_sum_6,Away_Woodwork_HomeTeam_sum_6,Home_Corners_HomeTeam_sum_6,Away_Corners_HomeTeam_sum_6,Home_Fouls_HomeTeam_sum_6,Away_Fouls_HomeTeam_sum_6,Home_Offsides_HomeTeam_sum_6,Away_Offsides_HomeTeam_sum_6,Home_Yellow_Cards_HomeTeam_sum_6,Away_Yellow_Cards_HomeTeam_sum_6,Home_Red_Cards_HomeTeam_sum_6,Away_Red_Cards_HomeTeam_sum_6,Home_Bookings_Points_HomeTeam_sum_6,Away_Bookings_Points_HomeTeam_sum_6,Final_result_HomeTeam_sum_6,Home_score_HomeTeam_sum_6,Away_score_HomeTeam_sum_6,Final_Home_goals_AwayTeam_sum_6,Final_Away_goals_AwayTeam_sum_6,Half_Time_Home_Goals_AwayTeam_sum_6,Half_Time_Away_Goals_AwayTeam_sum_6,Half_Time_Result_AwayTeam_sum_6,Crowd_Attendance_AwayTeam_sum_6,Home_Shots_AwayTeam_sum_6,Away_Shots_AwayTeam_sum_6,Home_Shots_Target_AwayTeam_sum_6,Away_Shots_Target_AwayTeam_sum_6,Home_Woodwork_AwayTeam_sum_6,Away_Woodwork_AwayTeam_sum_6,Home_Corners_AwayTeam_sum_6,Away_Corners_AwayTeam_sum_6,Home_Fouls_AwayTeam_sum_6,Away_Fouls_AwayTeam_sum_6,Home_Offsides_AwayTeam_sum_6,Away_Offsides_AwayTeam_sum_6,Home_Yellow_Cards_AwayTeam_sum_6,Away_Yellow_Cards_AwayTeam_sum_6,Home_Red_Cards_AwayTeam_sum_6,Away_Red_Cards_AwayTeam_sum_6,Home_Bookings_Points_AwayTeam_sum_6,Away_Bookings_Points_AwayTeam_sum_6,Final_result_AwayTeam_sum_6,Home_score_AwayTeam_sum_6,Away_score_AwayTeam_sum_6
0,2000-08-19,Charlton,Man City,4.0,0.0,2.0,0.0,1,20043.0,Rob Harris,17.0,8.0,14.0,4.0,2.0,1.0,6.0,6.0,13.0,12.0,8.0,6.0,1.0,2.0,0.0,0.0,10.0,20.0,1.0,3.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
# merging the basic df with the results of rolling (median) every column for each team as a 'HomeTeam'
#res3= pd.merge(res2, df2.groupby(['HomeTeam']).rolling(6,min_periods=1).median().reset_index(), suffixes=['','_HomeTeam_median_6'], on=['HomeTeam', 'Date'])

In [32]:
res1= pd.merge(res1, temp_H.groupby(['HomeTeam']).rolling(6, min_periods=1).median().reset_index(), suffixes=['','_HomeTeam_median_6'], on=['HomeTeam', 'Date'])

In [33]:
res1.head(1)

,Date,HomeTeam,AwayTeam,Final_Home_goals,Final_Away_goals,Half_Time_Home_Goals,Half_Time_Away_Goals,Half_Time_Result,Crowd_Attendance,Referee,Home_Shots,Away_Shots,Home_Shots_Target,Away_Shots_Target,Home_Woodwork,Away_Woodwork,Home_Corners,Away_Corners,Home_Fouls,Away_Fouls,Home_Offsides,Away_Offsides,Home_Yellow_Cards,Away_Yellow_Cards,Home_Red_Cards,Away_Red_Cards,Home_Bookings_Points,Away_Bookings_Points,Final_result,Home_score,Away_score,Final_Home_goals_HomeTeam_sum_6,Final_Away_goals_HomeTeam_sum_6,Half_Time_Home_Goals_HomeTeam_sum_6,Half_Time_Away_Goals_HomeTeam_sum_6,Half_Time_Result_HomeTeam_sum_6,Crowd_Attendance_HomeTeam_sum_6,Home_Shots_HomeTeam_sum_6,Away_Shots_HomeTeam_sum_6,Home_Shots_Target_HomeTeam_sum_6,Away_Shots_Target_HomeTeam_sum_6,Home_Woodwork_HomeTeam_sum_6,Away_Woodwork_HomeTeam_sum_6,Home_Corners_HomeTeam_sum_6,Away_Corners_HomeTeam_sum_6,Home_Fouls_HomeTeam_sum_6,Away_Fouls_HomeTeam_sum_6,Home_Offsides_HomeTeam_sum_6,Away_Offsides_HomeTeam_sum_6,Home_Yellow_Cards_HomeTeam_sum_6,Away_Yellow_Cards_HomeTeam_sum_6,Home_Red_Cards_HomeTeam_sum_6,Away_Red_Cards_HomeTeam_sum_6,Home_Bookings_Points_HomeTeam_sum_6,Away_Bookings_Points_HomeTeam_sum_6,Final_result_HomeTeam_sum_6,Home_score_HomeTeam_sum_6,Away_score_HomeTeam_sum_6,Final_Home_goals_AwayTeam_sum_6,Final_Away_goals_AwayTeam_sum_6,Half_Time_Home_Goals_AwayTeam_sum_6,Half_Time_Away_Goals_AwayTeam_sum_6,Half_Time_Result_AwayTeam_sum_6,Crowd_Attendance_AwayTeam_sum_6,Home_Shots_AwayTeam_sum_6,Away_Shots_AwayTeam_sum_6,Home_Shots_Target_AwayTeam_sum_6,Away_Shots_Target_AwayTeam_sum_6,Home_Woodwork_AwayTeam_sum_6,Away_Woodwork_AwayTeam_sum_6,Home_Corners_AwayTeam_sum_6,Away_Corners_AwayTeam_sum_6,Home_Fouls_AwayTeam_sum_6,Away_Fouls_AwayTeam_sum_6,Home_Offsides_AwayTeam_sum_6,Away_Offsides_AwayTeam_sum_6,Home_Yellow_Cards_AwayTeam_sum_6,Away_Yellow_Cards_AwayTeam_sum_6,Home_Red_Cards_AwayTeam_sum_6,Away_Red_Cards_AwayTeam_sum_6,Home_Bookings_Points_AwayTeam_sum_6,Away_Bookings_Points_AwayTeam_sum_6,Final_result_AwayTeam_sum_6,Home_score_AwayTeam_sum_6,Away_score_AwayTeam_sum_6,Final_Home_goals_HomeTeam_median_6,Final_Away_goals_HomeTeam_median_6,Half_Time_Home_Goals_HomeTeam_median_6,Half_Time_Away_Goals_HomeTeam_median_6,Half_Time_Result_HomeTeam_median_6,Crowd_Attendance_HomeTeam_median_6,Home_Shots_HomeTeam_median_6,Away_Shots_HomeTeam_median_6,Home_Shots_Target_HomeTeam_median_6,Away_Shots_Target_HomeTeam_median_6,Home_Woodwork_HomeTeam_median_6,Away_Woodwork_HomeTeam_median_6,Home_Corners_HomeTeam_median_6,Away_Corners_HomeTeam_median_6,Home_Fouls_HomeTeam_median_6,Away_Fouls_HomeTeam_median_6,Home_Offsides_HomeTeam_median_6,Away_Offsides_HomeTeam_median_6,Home_Yellow_Cards_HomeTeam_median_6,Away_Yellow_Cards_HomeTeam_median_6,Home_Red_Cards_HomeTeam_median_6,Away_Red_Cards_HomeTeam_median_6,Home_Bookings_Points_HomeTeam_median_6,Away_Bookings_Points_HomeTeam_median_6,Final_result_HomeTeam_median_6,Home_score_HomeTeam_median_6,Away_score_HomeTeam_median_6
0,2000-08-19,Charlton,Man City,4.0,0.0,2.0,0.0,1,20043.0,Rob Harris,17.0,8.0,14.0,4.0,2.0,1.0,6.0,6.0,13.0,12.0,8.0,6.0,1.0,2.0,0.0,0.0,10.0,20.0,1.0,3.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [34]:
# merging the basic df with the results of rolling (median) every column for each team as a 'AwayTeam'
#res4= pd.merge(res3, df2.groupby(['AwayTeam']).rolling(6,min_periods=1).median().reset_index(), suffixes=['','_AwayTeam_median_6'], on=['AwayTeam', 'Date'])

In [35]:
res1= pd.merge(res1, temp_A.groupby(['AwayTeam']).rolling(6, min_periods=1).median().reset_index(), suffixes=['','_AwayTeam_median_6'], on=['AwayTeam', 'Date'])

In [36]:
res1.head(1)

,Date,HomeTeam,AwayTeam,Final_Home_goals,Final_Away_goals,Half_Time_Home_Goals,Half_Time_Away_Goals,Half_Time_Result,Crowd_Attendance,Referee,Home_Shots,Away_Shots,Home_Shots_Target,Away_Shots_Target,Home_Woodwork,Away_Woodwork,Home_Corners,Away_Corners,Home_Fouls,Away_Fouls,Home_Offsides,Away_Offsides,Home_Yellow_Cards,Away_Yellow_Cards,Home_Red_Cards,Away_Red_Cards,Home_Bookings_Points,Away_Bookings_Points,Final_result,Home_score,Away_score,Final_Home_goals_HomeTeam_sum_6,Final_Away_goals_HomeTeam_sum_6,Half_Time_Home_Goals_HomeTeam_sum_6,Half_Time_Away_Goals_HomeTeam_sum_6,Half_Time_Result_HomeTeam_sum_6,Crowd_Attendance_HomeTeam_sum_6,Home_Shots_HomeTeam_sum_6,Away_Shots_HomeTeam_sum_6,Home_Shots_Target_HomeTeam_sum_6,Away_Shots_Target_HomeTeam_sum_6,Home_Woodwork_HomeTeam_sum_6,Away_Woodwork_HomeTeam_sum_6,Home_Corners_HomeTeam_sum_6,Away_Corners_HomeTeam_sum_6,Home_Fouls_HomeTeam_sum_6,Away_Fouls_HomeTeam_sum_6,Home_Offsides_HomeTeam_sum_6,Away_Offsides_HomeTeam_sum_6,Home_Yellow_Cards_HomeTeam_sum_6,Away_Yellow_Cards_HomeTeam_sum_6,Home_Red_Cards_HomeTeam_sum_6,Away_Red_Cards_HomeTeam_sum_6,Home_Bookings_Points_HomeTeam_sum_6,Away_Bookings_Points_HomeTeam_sum_6,Final_result_HomeTeam_sum_6,Home_score_HomeTeam_sum_6,Away_score_HomeTeam_sum_6,Final_Home_goals_AwayTeam_sum_6,Final_Away_goals_AwayTeam_sum_6,Half_Time_Home_Goals_AwayTeam_sum_6,Half_Time_Away_Goals_AwayTeam_sum_6,Half_Time_Result_AwayTeam_sum_6,Crowd_Attendance_AwayTeam_sum_6,Home_Shots_AwayTeam_sum_6,Away_Shots_AwayTeam_sum_6,Home_Shots_Target_AwayTeam_sum_6,Away_Shots_Target_AwayTeam_sum_6,Home_Woodwork_AwayTeam_sum_6,Away_Woodwork_AwayTeam_sum_6,Home_Corners_AwayTeam_sum_6,Away_Corners_AwayTeam_sum_6,Home_Fouls_AwayTeam_sum_6,Away_Fouls_AwayTeam_sum_6,Home_Offsides_AwayTeam_sum_6,Away_Offsides_AwayTeam_sum_6,Home_Yellow_Cards_AwayTeam_sum_6,Away_Yellow_Cards_AwayTeam_sum_6,Home_Red_Cards_AwayTeam_sum_6,Away_Red_Cards_AwayTeam_sum_6,Home_Bookings_Points_AwayTeam_sum_6,Away_Bookings_Points_AwayTeam_sum_6,Final_result_AwayTeam_sum_6,Home_score_AwayTeam_sum_6,Away_score_AwayTeam_sum_6,Final_Home_goals_HomeTeam_median_6,Final_Away_goals_HomeTeam_median_6,Half_Time_Home_Goals_HomeTeam_median_6,Half_Time_Away_Goals_HomeTeam_median_6,Half_Time_Result_HomeTeam_median_6,Crowd_Attendance_HomeTeam_median_6,Home_Shots_HomeTeam_median_6,Away_Shots_HomeTeam_median_6,Home_Shots_Target_HomeTeam_median_6,Away_Shots_Target_HomeTeam_median_6,Home_Woodwork_HomeTeam_median_6,Away_Woodwork_HomeTeam_median_6,Home_Corners_HomeTeam_median_6,Away_Corners_HomeTeam_median_6,Home_Fouls_HomeTeam_median_6,Away_Fouls_HomeTeam_median_6,Home_Offsides_HomeTeam_median_6,Away_Offsides_HomeTeam_median_6,Home_Yellow_Cards_HomeTeam_median_6,Away_Yellow_Cards_HomeTeam_median_6,Home_Red_Cards_HomeTeam_median_6,Away_Red_Cards_HomeTeam_median_6,Home_Bookings_Points_HomeTeam_median_6,Away_Bookings_Points_HomeTeam_median_6,Final_result_HomeTeam_median_6,Home_score_HomeTeam_median_6,Away_score_HomeTeam_median_6,Final_Home_goals_AwayTeam_median_6,Final_Away_goals_AwayTeam_median_6,Half_Time_Home_Goals_AwayTeam_median_6,Half_Time_Away_Goals_AwayTeam_median_6,Half_Time_Result_AwayTeam_median_6,Crowd_Attendance_AwayTeam_median_6,Home_Shots_AwayTeam_median_6,Away_Shots_AwayTeam_median_6,Home_Shots_Target_AwayTeam_median_6,Away_Shots_Target_AwayTeam_median_6,Home_Woodwork_AwayTeam_median_6,Away_Woodwork_AwayTeam_median_6,Home_Corners_AwayTeam_median_6,Away_Corners_AwayTeam_median_6,Home_Fouls_AwayTeam_median_6,Away_Fouls_AwayTeam_median_6,Home_Offsides_AwayTeam_median_6,Away_Offsides_AwayTeam_median_6,Home_Yellow_Cards_AwayTeam_median_6,Away_Yellow_Cards_AwayTeam_median_6,Home_Red_Cards_AwayTeam_median_6,Away_Red_Cards_AwayTeam_median_6,Home_Bookings_Points_AwayTeam_median_6,Away_Bookings_Points_AwayTeam_median_6,Final_result_AwayTeam_median_6,Home_score_AwayTeam_median_6,Away_score_AwayTeam_median_6
0,2000-08-19,Charlton,Man City,4.0,0.0,2.0,0.0,1,20043.0,Rob Harris,17.0,8.0,14.0,4.0,2.0,1.0,6.0,6.0,13.0,12.0,8.0,6.0,1.0,2.0,0.0,0.0,10.0,20.0,1.0,3.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [37]:
res1.shape

(7508, 139)

In [38]:
# merging the basic df with the results of rolling (average) every column for each team as a 'HomeTeam'
#res5= pd.merge(res4, df2.groupby(['HomeTeam']).rolling(6,min_periods=1).mean().reset_index(), suffixes=['','_HomeTeam_average_6'], on=['HomeTeam', 'Date'])

In [39]:
res1= pd.merge(res1, temp_H.groupby(['HomeTeam']).rolling(6, min_periods=1).mean().reset_index(), suffixes=['','_HomeTeam_average_6'], on=['HomeTeam', 'Date'])

In [40]:
res1.head(1)

,Date,HomeTeam,AwayTeam,Final_Home_goals,Final_Away_goals,Half_Time_Home_Goals,Half_Time_Away_Goals,Half_Time_Result,Crowd_Attendance,Referee,Home_Shots,Away_Shots,Home_Shots_Target,Away_Shots_Target,Home_Woodwork,Away_Woodwork,Home_Corners,Away_Corners,Home_Fouls,Away_Fouls,Home_Offsides,Away_Offsides,Home_Yellow_Cards,Away_Yellow_Cards,Home_Red_Cards,Away_Red_Cards,Home_Bookings_Points,Away_Bookings_Points,Final_result,Home_score,Away_score,Final_Home_goals_HomeTeam_sum_6,Final_Away_goals_HomeTeam_sum_6,Half_Time_Home_Goals_HomeTeam_sum_6,Half_Time_Away_Goals_HomeTeam_sum_6,Half_Time_Result_HomeTeam_sum_6,Crowd_Attendance_HomeTeam_sum_6,Home_Shots_HomeTeam_sum_6,Away_Shots_HomeTeam_sum_6,Home_Shots_Target_HomeTeam_sum_6,Away_Shots_Target_HomeTeam_sum_6,Home_Woodwork_HomeTeam_sum_6,Away_Woodwork_HomeTeam_sum_6,Home_Corners_HomeTeam_sum_6,Away_Corners_HomeTeam_sum_6,Home_Fouls_HomeTeam_sum_6,Away_Fouls_HomeTeam_sum_6,Home_Offsides_HomeTeam_sum_6,Away_Offsides_HomeTeam_sum_6,Home_Yellow_Cards_HomeTeam_sum_6,Away_Yellow_Cards_HomeTeam_sum_6,Home_Red_Cards_HomeTeam_sum_6,Away_Red_Cards_HomeTeam_sum_6,Home_Bookings_Points_HomeTeam_sum_6,Away_Bookings_Points_HomeTeam_sum_6,Final_result_HomeTeam_sum_6,Home_score_HomeTeam_sum_6,Away_score_HomeTeam_sum_6,Final_Home_goals_AwayTeam_sum_6,Final_Away_goals_AwayTeam_sum_6,Half_Time_Home_Goals_AwayTeam_sum_6,Half_Time_Away_Goals_AwayTeam_sum_6,Half_Time_Result_AwayTeam_sum_6,Crowd_Attendance_AwayTeam_sum_6,Home_Shots_AwayTeam_sum_6,Away_Shots_AwayTeam_sum_6,Home_Shots_Target_AwayTeam_sum_6,Away_Shots_Target_AwayTeam_sum_6,Home_Woodwork_AwayTeam_sum_6,Away_Woodwork_AwayTeam_sum_6,Home_Corners_AwayTeam_sum_6,Away_Corners_AwayTeam_sum_6,Home_Fouls_AwayTeam_sum_6,Away_Fouls_AwayTeam_sum_6,Home_Offsides_AwayTeam_sum_6,Away_Offsides_AwayTeam_sum_6,Home_Yellow_Cards_AwayTeam_sum_6,Away_Yellow_Cards_AwayTeam_sum_6,Home_Red_Cards_AwayTeam_sum_6,Away_Red_Cards_AwayTeam_sum_6,Home_Bookings_Points_AwayTeam_sum_6,Away_Bookings_Points_AwayTeam_sum_6,Final_result_AwayTeam_sum_6,Home_score_AwayTeam_sum_6,Away_score_AwayTeam_sum_6,Final_Home_goals_HomeTeam_median_6,Final_Away_goals_HomeTeam_median_6,Half_Time_Home_Goals_HomeTeam_median_6,Half_Time_Away_Goals_HomeTeam_median_6,Half_Time_Result_HomeTeam_median_6,Crowd_Attendance_HomeTeam_median_6,Home_Shots_HomeTeam_median_6,Away_Shots_HomeTeam_median_6,Home_Shots_Target_HomeTeam_median_6,Away_Shots_Target_HomeTeam_median_6,Home_Woodwork_HomeTeam_median_6,Away_Woodwork_HomeTeam_median_6,Home_Corners_HomeTeam_median_6,Away_Corners_HomeTeam_median_6,Home_Fouls_HomeTeam_median_6,Away_Fouls_HomeTeam_median_6,Home_Offsides_HomeTeam_median_6,Away_Offsides_HomeTeam_median_6,Home_Yellow_Cards_HomeTeam_median_6,Away_Yellow_Cards_HomeTeam_median_6,Home_Red_Cards_HomeTeam_median_6,Away_Red_Cards_HomeTeam_median_6,Home_Bookings_Points_HomeTeam_median_6,Away_Bookings_Points_HomeTeam_median_6,Final_result_HomeTeam_median_6,Home_score_HomeTeam_median_6,Away_score_HomeTeam_median_6,Final_Home_goals_AwayTeam_median_6,Final_Away_goals_AwayTeam_median_6,Half_Time_Home_Goals_AwayTeam_median_6,Half_Time_Away_Goals_AwayTeam_median_6,Half_Time_Result_AwayTeam_median_6,Crowd_Attendance_AwayTeam_median_6,Home_Shots_AwayTeam_median_6,Away_Shots_AwayTeam_median_6,Home_Shots_Target_AwayTeam_median_6,Away_Shots_Target_AwayTeam_median_6,Home_Woodwork_AwayTeam_median_6,Away_Woodwork_AwayTeam_median_6,Home_Corners_AwayTeam_median_6,Away_Corners_AwayTeam_median_6,Home_Fouls_AwayTeam_median_6,Away_Fouls_AwayTeam_median_6,Home_Offsides_AwayTeam_median_6,Away_Offsides_AwayTeam_median_6,Home_Yellow_Cards_AwayTeam_median_6,Away_Yellow_Cards_AwayTeam_median_6,Home_Red_Cards_AwayTeam_median_6,Away_Red_Cards_AwayTeam_median_6,Home_Bookings_Points_AwayTeam_median_6,Away_Bookings_Points_AwayTeam_median_6,Final_result_AwayTeam_median_6,Home_score_AwayTeam_median_6,Away_score_AwayTeam_median_6,Final_Home_goals_HomeTeam_average_6,Final_Away_goals_HomeTeam_average_6,Half_Time_Home_Goals_HomeTeam_average_6,Half_Time_Away_Goals_HomeTeam_average_6,Half_Time_Result_HomeTeam_average_6,Crowd_Attendance_HomeTeam_average_6,Home_Shots_HomeTeam_average_6,Away_Shots_HomeTeam_average_6,Home_Shots_Target_HomeTeam_average_6,Away_Shots_Target_HomeTeam_average_6,Home_Woodwork_HomeTeam_average_6,Away_Woodwork_HomeTeam_average_6,Home_Corners_HomeTeam_average_6,Away_Corners_HomeTeam_average_6,Home_Fouls_HomeTeam_average_6,Away_Fouls_HomeTeam_average_6,Home_Offsides_HomeTeam_average_6,Away_Offsides_HomeTeam_average_6,Home_Yellow_Cards_HomeTeam_average_6,Away_Yellow_Cards_HomeTeam_average_6,Home_Red_Cards_HomeTeam_average_6,Away_Red_Cards_HomeTeam_average_6,Home_Bookings_Points_HomeTeam_average_6,Away_Bookings_Points_HomeTeam_average_6,Final_result_HomeTeam_average_6,Home_score_HomeTeam_average_6,Away_score_HomeTeam_average_6
0,2000-08-19,Charlton,Man City,4.0,0.0,2.0,0.0,1,20043.0,Rob Harris,17.0,8.0,14.0,4.0,2.0,1.0,6.0,6.0,13.0,12.0,8.0,6.0,1.0,2.0,0.0,0.0,10.0,20.0,1.0,3.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [41]:
# merging the basic df with the results of rolling (average) every column for each team as a 'AwayTeam'
#res6= pd.merge(res5, df2.groupby(['AwayTeam']).rolling(6,min_periods=1).mean().reset_index(), suffixes=['','_AwayTeam_average_6'], on=['AwayTeam', 'Date'])

In [42]:
res1= pd.merge(res1, temp_A.groupby(['AwayTeam']).rolling(6, min_periods=1).mean().reset_index(), suffixes=['','_AwayTeam_average_6'], on=['AwayTeam', 'Date'])

In [43]:
res1.head(1)

,Date,HomeTeam,AwayTeam,Final_Home_goals,Final_Away_goals,Half_Time_Home_Goals,Half_Time_Away_Goals,Half_Time_Result,Crowd_Attendance,Referee,Home_Shots,Away_Shots,Home_Shots_Target,Away_Shots_Target,Home_Woodwork,Away_Woodwork,Home_Corners,Away_Corners,Home_Fouls,Away_Fouls,Home_Offsides,Away_Offsides,Home_Yellow_Cards,Away_Yellow_Cards,Home_Red_Cards,Away_Red_Cards,Home_Bookings_Points,Away_Bookings_Points,Final_result,Home_score,Away_score,Final_Home_goals_HomeTeam_sum_6,Final_Away_goals_HomeTeam_sum_6,Half_Time_Home_Goals_HomeTeam_sum_6,Half_Time_Away_Goals_HomeTeam_sum_6,Half_Time_Result_HomeTeam_sum_6,Crowd_Attendance_HomeTeam_sum_6,Home_Shots_HomeTeam_sum_6,Away_Shots_HomeTeam_sum_6,Home_Shots_Target_HomeTeam_sum_6,Away_Shots_Target_HomeTeam_sum_6,Home_Woodwork_HomeTeam_sum_6,Away_Woodwork_HomeTeam_sum_6,Home_Corners_HomeTeam_sum_6,Away_Corners_HomeTeam_sum_6,Home_Fouls_HomeTeam_sum_6,Away_Fouls_HomeTeam_sum_6,Home_Offsides_HomeTeam_sum_6,Away_Offsides_HomeTeam_sum_6,Home_Yellow_Cards_HomeTeam_sum_6,Away_Yellow_Cards_HomeTeam_sum_6,Home_Red_Cards_HomeTeam_sum_6,Away_Red_Cards_HomeTeam_sum_6,Home_Bookings_Points_HomeTeam_sum_6,Away_Bookings_Points_HomeTeam_sum_6,Final_result_HomeTeam_sum_6,Home_score_HomeTeam_sum_6,Away_score_HomeTeam_sum_6,Final_Home_goals_AwayTeam_sum_6,Final_Away_goals_AwayTeam_sum_6,Half_Time_Home_Goals_AwayTeam_sum_6,Half_Time_Away_Goals_AwayTeam_sum_6,Half_Time_Result_AwayTeam_sum_6,Crowd_Attendance_AwayTeam_sum_6,Home_Shots_AwayTeam_sum_6,Away_Shots_AwayTeam_sum_6,Home_Shots_Target_AwayTeam_sum_6,Away_Shots_Target_AwayTeam_sum_6,Home_Woodwork_AwayTeam_sum_6,Away_Woodwork_AwayTeam_sum_6,Home_Corners_AwayTeam_sum_6,Away_Corners_AwayTeam_sum_6,Home_Fouls_AwayTeam_sum_6,Away_Fouls_AwayTeam_sum_6,Home_Offsides_AwayTeam_sum_6,Away_Offsides_AwayTeam_sum_6,Home_Yellow_Cards_AwayTeam_sum_6,Away_Yellow_Cards_AwayTeam_sum_6,Home_Red_Cards_AwayTeam_sum_6,Away_Red_Cards_AwayTeam_sum_6,Home_Bookings_Points_AwayTeam_sum_6,Away_Bookings_Points_AwayTeam_sum_6,Final_result_AwayTeam_sum_6,Home_score_AwayTeam_sum_6,Away_score_AwayTeam_sum_6,Final_Home_goals_HomeTeam_median_6,Final_Away_goals_HomeTeam_median_6,Half_Time_Home_Goals_HomeTeam_median_6,Half_Time_Away_Goals_HomeTeam_median_6,Half_Time_Result_HomeTeam_median_6,Crowd_Attendance_HomeTeam_median_6,Home_Shots_HomeTeam_median_6,Away_Shots_HomeTeam_median_6,Home_Shots_Target_HomeTeam_median_6,Away_Shots_Target_HomeTeam_median_6,Home_Woodwork_HomeTeam_median_6,Away_Woodwork_HomeTeam_median_6,Home_Corners_HomeTeam_median_6,Away_Corners_HomeTeam_median_6,Home_Fouls_HomeTeam_median_6,Away_Fouls_HomeTeam_median_6,Home_Offsides_HomeTeam_median_6,Away_Offsides_HomeTeam_median_6,Home_Yellow_Cards_HomeTeam_median_6,Away_Yellow_Cards_HomeTeam_median_6,Home_Red_Cards_HomeTeam_median_6,Away_Red_Cards_HomeTeam_median_6,Home_Bookings_Points_HomeTeam_median_6,Away_Bookings_Points_HomeTeam_median_6,Final_result_HomeTeam_median_6,Home_score_HomeTeam_median_6,Away_score_HomeTeam_median_6,Final_Home_goals_AwayTeam_median_6,Final_Away_goals_AwayTeam_median_6,Half_Time_Home_Goals_AwayTeam_median_6,Half_Time_Away_Goals_AwayTeam_median_6,Half_Time_Result_AwayTeam_median_6,Crowd_Attendance_AwayTeam_median_6,Home_Shots_AwayTeam_median_6,Away_Shots_AwayTeam_median_6,Home_Shots_Target_AwayTeam_median_6,Away_Shots_Target_AwayTeam_median_6,Home_Woodwork_AwayTeam_median_6,Away_Woodwork_AwayTeam_median_6,Home_Corners_AwayTeam_median_6,Away_Corners_AwayTeam_median_6,Home_Fouls_AwayTeam_median_6,Away_Fouls_AwayTeam_median_6,Home_Offsides_AwayTeam_median_6,Away_Offsides_AwayTeam_median_6,Home_Yellow_Cards_AwayTeam_median_6,Away_Yellow_Cards_AwayTeam_median_6,Home_Red_Cards_AwayTeam_median_6,Away_Red_Cards_AwayTeam_median_6,Home_Bookings_Points_AwayTeam_median_6,Away_Bookings_Points_AwayTeam_median_6,Final_result_AwayTeam_median_6,Home_score_AwayTeam_median_6,Away_score_AwayTeam_median_6,Final_Home_goals_HomeTeam_average_6,Final_Away_goals_HomeTeam_average_6,Half_Time_Home_Goals_HomeTeam_average_6,Half_Time_Away_Goals_HomeTeam_average_6,Half_Time_Result_HomeTeam_average_6,Crowd_Attendance_HomeTeam_average_6,Home_Shots_HomeTeam_average_6,Away_Shots_HomeTeam_average_6,Home_Shots_Target_HomeTeam_average_6,Away_Shots_Target_HomeTeam_average_6,Home_Woodwork_HomeTeam_average_6,Away_Woodwork_HomeTeam_average_6,Home_Corners_HomeTeam_average_6,Away_Corners_HomeTeam_average_6,Home_Fouls_HomeTeam_average_6,Away_Fouls_HomeTeam_average_6,Home_Offsides_HomeTeam_average_6,Away_Offsides_HomeTeam_average_6,Home_Yellow_Cards_HomeTeam_average_6,Away_Yellow_Cards_HomeTeam_average_6,Home_Red_Cards_HomeTeam_average_6,Away_Red_Cards_HomeTeam_average_6,Home_Bookings_Points_HomeTeam_average_6,Away_Bookings_Points_HomeTeam_average_6,Final_result_HomeTeam_average_6,Home_score_HomeTeam_average_6,Away_score_HomeTeam_average_6,Final_Home_goals_AwayTeam_average_6,Final_Away_goals_AwayTeam_average_6,Half_Time_Home_Goals_AwayTeam_average_6,Half_Time_Away_Goals_AwayTeam_average_6,Half_Time_Result_AwayTeam_average_6,Crowd_Attendance_AwayTeam_average_6,Home_Shots_AwayTeam_average_6,Away_Shots_AwayTeam_average_6,Home_Shots_Target_AwayTeam_average_6,Away_Shots_Target_AwayTeam_average_6,Home_Woodwork_AwayTeam_average_6,Away_Woodwork_AwayTeam_average_6,Home_Corners_AwayTeam_average_6,Away_Corners_AwayTeam_average_6,Home_Fouls_AwayTeam_average_6,Away_Fouls_AwayTeam_average_6,Home_Offsides_AwayTeam_average_6,Away_Offsides_AwayTeam_average_6,Home_Yellow_Cards_AwayTeam_average_6,Away_Yellow_Cards_AwayTeam_average_6,Home_Red_Cards_AwayTeam_average_6,Away_Red_Cards_AwayTeam_average_6,Home_Bookings_Points_AwayTeam_average_6,Away_Bookings_Points_AwayTeam_average_6,Final_result_AwayTeam_average_6,Home_score_AwayTeam_average_6,Away_score_AwayTeam_average_6
0,2000-08-19,Charlton,Man City,4.0,0.0,2.0,0.0,1,20043.0,Rob Harris,17.0,8.0,14.0,4.0,2.0,1.0,6.0,6.0,13.0,12.0,8.0,6.0,1.0,2.0,0.0,0.0,10.0,20.0,1.0,3.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [44]:
res1.loc[res1['HomeTeam']=='Charlton'].head(7)

,Date,HomeTeam,AwayTeam,Final_Home_goals,Final_Away_goals,Half_Time_Home_Goals,Half_Time_Away_Goals,Half_Time_Result,Crowd_Attendance,Referee,Home_Shots,Away_Shots,Home_Shots_Target,Away_Shots_Target,Home_Woodwork,Away_Woodwork,Home_Corners,Away_Corners,Home_Fouls,Away_Fouls,Home_Offsides,Away_Offsides,Home_Yellow_Cards,Away_Yellow_Cards,Home_Red_Cards,Away_Red_Cards,Home_Bookings_Points,Away_Bookings_Points,Final_result,Home_score,Away_score,Final_Home_goals_HomeTeam_sum_6,Final_Away_goals_HomeTeam_sum_6,Half_Time_Home_Goals_HomeTeam_sum_6,Half_Time_Away_Goals_HomeTeam_sum_6,Half_Time_Result_HomeTeam_sum_6,Crowd_Attendance_HomeTeam_sum_6,Home_Shots_HomeTeam_sum_6,Away_Shots_HomeTeam_sum_6,Home_Shots_Target_HomeTeam_sum_6,Away_Shots_Target_HomeTeam_sum_6,Home_Woodwork_HomeTeam_sum_6,Away_Woodwork_HomeTeam_sum_6,Home_Corners_HomeTeam_sum_6,Away_Corners_HomeTeam_sum_6,Home_Fouls_HomeTeam_sum_6,Away_Fouls_HomeTeam_sum_6,Home_Offsides_HomeTeam_sum_6,Away_Offsides_HomeTeam_sum_6,Home_Yellow_Cards_HomeTeam_sum_6,Away_Yellow_Cards_HomeTeam_sum_6,Home_Red_Cards_HomeTeam_sum_6,Away_Red_Cards_HomeTeam_sum_6,Home_Bookings_Points_HomeTeam_sum_6,Away_Bookings_Points_HomeTeam_sum_6,Final_result_HomeTeam_sum_6,Home_score_HomeTeam_sum_6,Away_score_HomeTeam_sum_6,Final_Home_goals_AwayTeam_sum_6,Final_Away_goals_AwayTeam_sum_6,Half_Time_Home_Goals_AwayTeam_sum_6,Half_Time_Away_Goals_AwayTeam_sum_6,Half_Time_Result_AwayTeam_sum_6,Crowd_Attendance_AwayTeam_sum_6,Home_Shots_AwayTeam_sum_6,Away_Shots_AwayTeam_sum_6,Home_Shots_Target_AwayTeam_sum_6,Away_Shots_Target_AwayTeam_sum_6,Home_Woodwork_AwayTeam_sum_6,Away_Woodwork_AwayTeam_sum_6,Home_Corners_AwayTeam_sum_6,Away_Corners_AwayTeam_sum_6,Home_Fouls_AwayTeam_sum_6,Away_Fouls_AwayTeam_sum_6,Home_Offsides_AwayTeam_sum_6,Away_Offsides_AwayTeam_sum_6,Home_Yellow_Cards_AwayTeam_sum_6,Away_Yellow_Cards_AwayTeam_sum_6,Home_Red_Cards_AwayTeam_sum_6,Away_Red_Cards_AwayTeam_sum_6,Home_Bookings_Points_AwayTeam_sum_6,Away_Bookings_Points_AwayTeam_sum_6,Final_result_AwayTeam_sum_6,Home_score_AwayTeam_sum_6,Away_score_AwayTeam_sum_6,Final_Home_goals_HomeTeam_median_6,Final_Away_goals_HomeTeam_median_6,Half_Time_Home_Goals_HomeTeam_median_6,Half_Time_Away_Goals_HomeTeam_median_6,Half_Time_Result_HomeTeam_median_6,Crowd_Attendance_HomeTeam_median_6,Home_Shots_HomeTeam_median_6,Away_Shots_HomeTeam_median_6,Home_Shots_Target_HomeTeam_median_6,Away_Shots_Target_HomeTeam_median_6,Home_Woodwork_HomeTeam_median_6,Away_Woodwork_HomeTeam_median_6,Home_Corners_HomeTeam_median_6,Away_Corners_HomeTeam_median_6,Home_Fouls_HomeTeam_median_6,Away_Fouls_HomeTeam_median_6,Home_Offsides_HomeTeam_median_6,Away_Offsides_HomeTeam_median_6,Home_Yellow_Cards_HomeTeam_median_6,Away_Yellow_Cards_HomeTeam_median_6,Home_Red_Cards_HomeTeam_median_6,Away_Red_Cards_HomeTeam_median_6,Home_Bookings_Points_HomeTeam_median_6,Away_Bookings_Points_HomeTeam_median_6,Final_result_HomeTeam_median_6,Home_score_HomeTeam_median_6,Away_score_HomeTeam_median_6,Final_Home_goals_AwayTeam_median_6,Final_Away_goals_AwayTeam_median_6,Half_Time_Home_Goals_AwayTeam_median_6,Half_Time_Away_Goals_AwayTeam_median_6,Half_Time_Result_AwayTeam_median_6,Crowd_Attendance_AwayTeam_median_6,Home_Shots_AwayTeam_median_6,Away_Shots_AwayTeam_median_6,Home_Shots_Target_AwayTeam_median_6,Away_Shots_Target_AwayTeam_median_6,Home_Woodwork_AwayTeam_median_6,Away_Woodwork_AwayTeam_median_6,Home_Corners_AwayTeam_median_6,Away_Corners_AwayTeam_median_6,Home_Fouls_AwayTeam_median_6,Away_Fouls_AwayTeam_median_6,Home_Offsides_AwayTeam_median_6,Away_Offsides_AwayTeam_median_6,Home_Yellow_Cards_AwayTeam_median_6,Away_Yellow_Cards_AwayTeam_median_6,Home_Red_Cards_AwayTeam_median_6,Away_Red_Cards_AwayTeam_median_6,Home_Bookings_Points_AwayTeam_median_6,Away_Bookings_Points_AwayTeam_median_6,Final_result_AwayTeam_median_6,Home_score_AwayTeam_median_6,Away_score_AwayTeam_median_6,Final_Home_goals_HomeTeam_average_6,Final_Away_goals_HomeTeam_average_6,Half_Time_Home_Goals_HomeTeam_average_6,Half_Time_Away_Goals_HomeTeam_average_6,Half_Time_Result_HomeTeam_average_6,Crowd_Attendance_HomeTeam_average_6,Home_Shots_HomeTeam_average_6,Away_Shots_HomeTeam_average_6,Home_Shots_Target_HomeTeam_average_6,Away_Shots_Target_HomeTeam_average_6,Home_Woodwork_HomeTeam_average_6,Away_Woodwork_HomeTeam_average_6,Home_Corners_HomeTeam_average_6,Away_Corners_HomeTeam_average_6,Home_Fouls_HomeTeam_average_6,Away_Fouls_HomeTeam_average_6,Home_Offsides_HomeTeam_average_6,Away_Offsides_HomeTeam_average_6,Home_Yellow_Cards_HomeTeam_average_6,Away_Yellow_Cards_HomeTeam_average_6,Home_Red_Cards_HomeTeam_average_6,Away_Red_Cards_HomeTeam_average_6,Home_Bookings_Points_HomeTeam_average_6,Away_Bookings_Points_HomeTeam_average_6,Final_result_HomeTeam_average_6,Home_score_HomeTeam_average_6,Away_score_HomeTeam_average_6,Final_Home_goals_AwayTeam_average_6,Final_Away_goals_AwayTeam_average_6,Half_Time_Home_Goals_AwayTeam_average_6,Half_Time_Away_Goals_AwayTeam_average_6,Half_Time_Result_AwayTeam_average_6,Crowd_Attendance_AwayTeam_average_6,Home_Shots_AwayTeam_average_6,Away_Shots_AwayTeam_average_6,Home_Shots_Target_AwayTeam_average_6,Away_Shots_Target_AwayTeam_average_6,Home_Woodwork_AwayTeam_average_6,Away_Woodwork_AwayTeam_average_6,Home_Corners_AwayTeam_average_6,Away_Corners_AwayTeam_average_6,Home_Fouls_AwayTeam_average_6,Away_Fouls_AwayTeam_average_6,Home_Offsides_AwayTeam_average_6,Away_Offsides_AwayTeam_average_6,Home_Yellow_Cards_AwayTeam_average_6,Away_Yellow_Cards_AwayTeam_average_6,Home_Red_Cards_AwayTeam_average_6,Away_Red_Cards_AwayTeam_average_6,Home_Bookings_Points_AwayTeam_average_6,Away_Bookings_Points_AwayTeam_average_6,Final_result_AwayTeam_average_6,Home_score_AwayTeam_average_6,Away_score_AwayTeam_average_6
0,2000-08-19,Charlton,Man City,4.0,0.0,2.0,0.0,1,20043.0,Rob Harris,17.0,8.0,14.0,4.0,2.0,1.0,6.0,6.0,13.0,12.0,8.0,6.0,1.0,2.0,0.0,0.0,10.0,20.0,1.0,3.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,2000-09-06,Charlton,Southampton,1.0,1.0,0.0,0.0,2,20043.0,Mark Halsey,8.0,11.0,6.0,3.0,0.0,0.0,10.0,14.0,14.0,16.0,4.0,3.0,3.0,3.0,1.0,0.0,55.0,30.0,2.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,0.0,2.0,0.0,1.0,20043.0,17.0,8.0,14.0,4.0,2.0,1.0,6.0,6.0,13.0,12.0,8.0,6.0,1.0,2.0,0.0,0.0,10.0,20.0,1.0,3.0,0.0,2.0,2.0,1.0,2.0,3.0,27223.0,6.0,13.0,4.0,6.0,0.0,0.0,5.0,8.0,11.0,13.0,0.0,2.0,1.0,1.0,0.0,0.0,10.0,10.0,2.0,1.0,1.0,4.000000,0.000000,2.000000,0.000000,1.000000,20043.000000,17.000000,8.000000,14.000000,4.000000,2.000000,1.000000,6.000000,6.000000,13.000000,12.000000,8.0,6.000000,1.000000,2.000000,0.000000,0.000000,10.000000,20.000000,1.000000,3.000000,0.000000,2.000000,2.000000,1.000000,2.0,3.000000,27223.000000,6.000000,13.000000,4.000000,6.0,0.000000,0.000000,5.000000,8.000000,11.0,13.000000,0.000000,2.000000,1.000000,1.000000,0.000000,0.000000,10.000000,10.000000,2.000000,1.0,1.0
50,2000-09-16,Charlton,Tottenham,1.0,0.0,1.0,0.0,1,20043.0,Jeff Winter,9.0,10.0,5.0,5.0,1.0,1.0,7.0,5.0,8.0,10.0,3.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.5,0.5,1.0,0.0,1.5,20043.0,12.5,9.5,10.0,3.5,1.0,0.5,8.0,10.0,13.5,14.0,6.0,4.5,2.0,2.5,0.5,0.0,32.5,25.0,1.5,2.0,0.5,1.5,0.5,0.5,0.5,2.0,41413.5,13.5,10.5,6.0,3.0,0.5,0.5,4.5,3.5,11.0,14.0,4.0,3.5,1.0,0.5,0.0,0.0,10.0,5.0,1.5,2.0,0.5,2.500000,0.500000,1.000000,0.000000,1.500000,20043.000000,12.500000,9.500000,10.000000,3.500000,1.000000,0.500000,8.000000,10.000000,13.500000,14.000000,6.0,4.500000,2.000000,2.500000,0.500000,0.000000,32.500000,25.000000,1.500000,2.000000,0.500000,1.500000,0.500000,0.500000,0.5,2.000000,41413.500000,13.500000,10.500000,6.000000,3.0,0.500000,0.500000,4.500000,3.500000,11.0,14.000000,4.000000,3.500000,1.000000,0.500000,0.000000,0.000000,10.000000,5.000000,1.500000,2.0,0.5
70,2000-09-30,Charlton,Coventry,2.0,2.0,0.0,1.0,3,20043.0,Rob Styles,12.0,10.0,8.0,6.0,1.0,0.0,6.0,6.0,8.0,16.0,5.0,0.0,1.0,2.0,0.0,0.0,10.0,20.0,2.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,1.0,0.0,1.0,20043.0,9.0,10.0,6.0,4.0,1.0,1.0,7.0,6.0,13.0,12.0,4.0,3.0,1.0,2.0,0.0,0.0,10.0,20.0,1.0,3.0,0.0,1.0,2.0,0.0,1.0,3.0,34140.0,14.0,7.0,5.0,5.0,0.0,0.0,6.0,5.0,7.0,13.0,3.0,6.0,2.0,3.0,0.0,0.0,20.0,30.0,3.0,0.0,3.0,2.000000,0.333333,1.000000,0.000000,1.333333,20043.000000,11.333333,9.666667,8.333333,4.000000,1.000000,0.666667,7.666667,8.333333,11.666667,12.666667,5.0,3.666667,1.333333,1.666667,0.333333,0.000000,21.666667,16.666667,1.333333,2.333333,0.333333,1.333333,1.666667,0.333333,1.0,2.333333,28911.666667,14.666667,7.333333,7.333333,5.0,0.333333,0.333333,6.333333,4.666667,10.0,15.000000,2.000000,5.333333,2.666667,2.666667,0.000000,0.000000,26.666667,26.666667,2.333333,1.0,2.0
90,2000-10-21,Charlton,Middlesbrough,1.0,0.0,0.0,0.0,2,20043.0,Mike Riley,5.0,8.0,2.0,6.0,0.0,0.0,5.0,6.0,11.0,19.0,4.0,2.0,2.0,2.0,0.0,0.0,20.0,20.0,1.0,3.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.5,0.5,0.5,0.0,1.5,20043.0,10.5,10.0,7.0,4.5,1.0,0.5,6.5,6.0,10.5,14.0,4.5,2.5,1.0,2.0,0.0,0.0,10.0,20.0,1.5,2.0,0.5,1.0,3.0,0.0,1.0,2.5,22457.0,10.0,6.0,4.5,4.5,0.5,0.0,8.5,4.5,11.5,16.0,3.0,2.5,2.5,2.5,0.0,0.0,25.0,25.0,2.5,0.5,2.0,2.000000,0.750000,0.750000,0.250000,1.750000,20043.000000,11.500000,9.750000,8.250000,4.500000,1.000000,0.500000,7.250000,7.750000,10.750000,13.500000,5.0,2.750000,1.250000,1.750000,0.250000,0.000000,18.750000,17.500000,1.500000,2.000000,0.500000,1.500000,2.500000,0.250000,1.0,2.500000,22967.500000,10.500000,8.000000,5.000000,5.0,0.750000,0.250000,8.500000,4.500000,11.0,16.000000,3.000000,2.750000,3.000000,3.000000,0.250000,0.000000,36.250000,30.000000,2.500000,0.5,2.0
110,2000-11-04,Charlton,Bradford,2.0,0.0,2.0,0.0,1,19655.0,Neale Barry,11.0,12.0,7.0,8.0,0.0,0.0,3.0,6.0,10.0,20.0,9.0,1.0,0.0,1.0,0.0,1.0,0.0,35.0,1.0,3.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,0.0,0.0,2.0,20043.0,9.0,10.0,6.0,5.0,1.0,0.0,6.0,6.0,11.0,16.0,4.0,2.0,1.0,2.0,0.0,0.0,10.0,20.0,1.0,3.0,0.0,2.0,0.0,1.0,0.0,1.0,34229.0,14.0,8.0,10.0,4.0,0.0,0.0,5.0,2.0,10.0,10.0,7.0,8.0,0.0,2.0,0.0,0.0,0.0,20.0,1.0,3.0,0.0,1.800000,0.600000,0.600000,0.200000,1.800000,20043.000000,10.200000,9.400000,7.000000,4.800000,0.800000,0.400000,6.800000,7.400000,10.800000,14.600000,4.8,2.600000,1.400000,1.800000,0.200000,0.000000,19.000000,18.000000,1.400000,2.200000,0.400000,2.400000,0.200000,1.200000,0.0,1.200000,39823.000000,15.200000,7.200000,9.000000,3.6,0.400000,0.200000,5.600000,3.200000,10.4,11.200000,6.800000,5.400000,0.800000,1.600000,0.000000,0.000000,8.000000,16.000000,1.200000,2.6,0.2
132,2000-11-18,Charlton,Chelsea,2.0,0.0,1.0,0.0,1,20043.0,Paul Durkin,10.0,13.0,6.0,3.0,0.0,1.0,4.0,5.0,18.0,22.0,5.0,1.0,2.0,3.0,0.0,0.0,20.0,30.0,1.0,3.0,0.0,11.0,3.0,5.0,1.0,10.0,119870.0,62.0,59.0,42.0,32.0,4.0,2.0,37.0,43.0,64.0,93.0,33.0,14.0,7.0,10.0,1.0,1.0,95.0,125.0,8.0,14.0,2.0,10.0,6.0,7.0,3.0,9.0,224497.0,71.0,68.0,36.0,27.0,3.0,1.0,38.0,31.0,87.0,97.0,20.0,21.0,7.0,10.0,1.0,1.0,95.0,125.0,9.0,12.0,3.0,1.5,0.0,0.5,0.0,1.5,20043.0,10.0,10.0,6.5,5.5,0.5,0.0,6.0,6.0,10.5,16.0,4.5,2.0,1.0,2.0,0.0,0.0,10.0,20.0,1.0,3.0,0.0,1.5,0.5,1.0,0.0,1.5,36067.0,11.5,11.0,4.5,4.5,0.5,0.0,6.5,5.0,14.5,17.0,3.0,4.0,0.0,1.5,0.0,0.0,12.5,20.0,1.5,2.0,0.5,1.833333,0.500000,0.833333,0.166667,1.666667,19978.333333,10.333333,9.833333,7.000000,5.333333,0.666667,0.333333,6.166667,7.166667,10.666667,15.500000,5.5,2.333333,1.166667,1.666667,0.166667,0.166667,15.833333,20.833333,1.333333,2.333333,0.333333,1.666667,1.000000,1.166667,0.5,1.500000,37416.166667,11.833333,11.333333,6.000000,4.5,0.500000,0.166667,6.333333,5.166667,14.5,16.166667,3.333333,3.500000,1.166667,1.666667,0.166667,0.166667,15.833333,20.833333,1.500000,2.0,0.5

In [45]:
df3= df2[['Date','AwayTeam','HomeTeam','Final_Away_goals','Final_Home_goals','Half_Time_Away_Goals','Half_Time_Home_Goals','Half_Time_Result','Crowd_Attendance','Referee','Away_Shots','Home_Shots','Away_Shots_Target','Home_Shots_Target','Away_Woodwork','Home_Woodwork','Away_Corners','Home_Corners','Away_Fouls','Home_Fouls','Away_Offsides','Home_Offsides','Away_Yellow_Cards','Home_Yellow_Cards','Away_Red_Cards','Home_Red_Cards','Away_Bookings_Points','Home_Bookings_Points', 'Final_result','Away_score','Home_score']]

In [46]:
df3.head(2)

,Date,AwayTeam,HomeTeam,Final_Away_goals,Final_Home_goals,Half_Time_Away_Goals,Half_Time_Home_Goals,Half_Time_Result,Crowd_Attendance,Referee,Away_Shots,Home_Shots,Away_Shots_Target,Home_Shots_Target,Away_Woodwork,Home_Woodwork,Away_Corners,Home_Corners,Away_Fouls,Home_Fouls,Away_Offsides,Home_Offsides,Away_Yellow_Cards,Home_Yellow_Cards,Away_Red_Cards,Home_Red_Cards,Away_Bookings_Points,Home_Bookings_Points,Final_result,Away_score,Home_score
0,2000-08-19,Man City,Charlton,0.0,4.0,0.0,2.0,1,20043.0,Rob Harris,8.0,17.0,4.0,14.0,1.0,2.0,6.0,6.0,12.0,13.0,6.0,8.0,2.0,1.0,0.0,0.0,20.0,10.0,1.0,0.0,3.0
1,2000-08-19,West Ham,Chelsea,2.0,4.0,0.0,1.0,1,34914.0,Graham Barber,12.0,17.0,5.0,10.0,0.0,1.0,7.0,7.0,14.0,19.0,3.0,2.0,2.0,1.0,0.0,0.0,20.0,10.0,1.0,0.0,3.0

In [47]:
df3.shape

(7508, 31)

In [48]:
df4= df3.rename(columns = {'AwayTeam':'HomeTeam','HomeTeam':'AwayTeam', 'Final_Away_goals':'Final_Home_goals', 'Final_Home_goals':'Final_Away_goals', 'Half_Time_Home_Goals':'Half_Time_Away_Goals','Home_Shots':'Away_Shots','Home_Shots_Target':'Away_Shots_Target','Home_Woodwork':'Away_Woodwork','Home_Corners':'Away_Corners','Home_Fouls':'Away_Fouls','Home_Offsides':'Away_Offsides','Home_Yellow_Cards':'Away_Yellow_Cards','Home_Red_Cards':'Away_Red_Cards','Home_Bookings_Points':'Away_Bookings_Points', 'Half_Time_Away_Goals':'Half_Time_Home_Goals','Away_Shots':'Home_Shots','Away_Shots_Target':'Home_Shots_Target','Away_Woodwork':'Home_Woodwork','Away_Corners':'Home_Corners','Away_Fouls':'Home_Fouls','Away_Offsides':'Home_Offsides','Away_Yellow_Cards':'Home_Yellow_Cards','Away_Red_Cards':'Home_Red_Cards','Away_Bookings_Points':'Home_Bookings_Points', 'Away_score':'Home_score', 'Home_score':'Away_score'})

In [49]:
df4.head(2)

,Date,HomeTeam,AwayTeam,Final_Home_goals,Final_Away_goals,Half_Time_Home_Goals,Half_Time_Away_Goals,Half_Time_Result,Crowd_Attendance,Referee,Home_Shots,Away_Shots,Home_Shots_Target,Away_Shots_Target,Home_Woodwork,Away_Woodwork,Home_Corners,Away_Corners,Home_Fouls,Away_Fouls,Home_Offsides,Away_Offsides,Home_Yellow_Cards,Away_Yellow_Cards,Home_Red_Cards,Away_Red_Cards,Home_Bookings_Points,Away_Bookings_Points,Final_result,Home_score,Away_score
0,2000-08-19,Man City,Charlton,0.0,4.0,0.0,2.0,1,20043.0,Rob Harris,8.0,17.0,4.0,14.0,1.0,2.0,6.0,6.0,12.0,13.0,6.0,8.0,2.0,1.0,0.0,0.0,20.0,10.0,1.0,0.0,3.0
1,2000-08-19,West Ham,Chelsea,2.0,4.0,0.0,1.0,1,34914.0,Graham Barber,12.0,17.0,5.0,10.0,0.0,1.0,7.0,7.0,14.0,19.0,3.0,2.0,2.0,1.0,0.0,0.0,20.0,10.0,1.0,0.0,3.0

In [50]:
filt1= df4['Final_result']==1
filt3= df4['Final_result']==3
df4.loc[filt1,'Final_result']= 3
df4.loc[filt3,'Final_result']= 1
filt2= df4['Half_Time_Result']==1
filt4= df4['Half_Time_Result']==3
df4.loc[filt2,'Half_Time_Result']= 3
df4.loc[filt4,'Half_Time_Result']= 1

In [51]:
df4.head(2)

,Date,HomeTeam,AwayTeam,Final_Home_goals,Final_Away_goals,Half_Time_Home_Goals,Half_Time_Away_Goals,Half_Time_Result,Crowd_Attendance,Referee,Home_Shots,Away_Shots,Home_Shots_Target,Away_Shots_Target,Home_Woodwork,Away_Woodwork,Home_Corners,Away_Corners,Home_Fouls,Away_Fouls,Home_Offsides,Away_Offsides,Home_Yellow_Cards,Away_Yellow_Cards,Home_Red_Cards,Away_Red_Cards,Home_Bookings_Points,Away_Bookings_Points,Final_result,Home_score,Away_score
0,2000-08-19,Man City,Charlton,0.0,4.0,0.0,2.0,3,20043.0,Rob Harris,8.0,17.0,4.0,14.0,1.0,2.0,6.0,6.0,12.0,13.0,6.0,8.0,2.0,1.0,0.0,0.0,20.0,10.0,3.0,0.0,3.0
1,2000-08-19,West Ham,Chelsea,2.0,4.0,0.0,1.0,3,34914.0,Graham Barber,12.0,17.0,5.0,10.0,0.0,1.0,7.0,7.0,14.0,19.0,3.0,2.0,2.0,1.0,0.0,0.0,20.0,10.0,3.0,0.0,3.0

In [52]:
df2.head(2)

,Date,HomeTeam,AwayTeam,Final_Home_goals,Final_Away_goals,Half_Time_Home_Goals,Half_Time_Away_Goals,Half_Time_Result,Crowd_Attendance,Referee,Home_Shots,Away_Shots,Home_Shots_Target,Away_Shots_Target,Home_Woodwork,Away_Woodwork,Home_Corners,Away_Corners,Home_Fouls,Away_Fouls,Home_Offsides,Away_Offsides,Home_Yellow_Cards,Away_Yellow_Cards,Home_Red_Cards,Away_Red_Cards,Home_Bookings_Points,Away_Bookings_Points,Final_result,Home_score,Away_score
0,2000-08-19,Charlton,Man City,4.0,0.0,2.0,0.0,1,20043.0,Rob Harris,17.0,8.0,14.0,4.0,2.0,1.0,6.0,6.0,13.0,12.0,8.0,6.0,1.0,2.0,0.0,0.0,10.0,20.0,1.0,3.0,0.0
1,2000-08-19,Chelsea,West Ham,4.0,2.0,1.0,0.0,1,34914.0,Graham Barber,17.0,12.0,10.0,5.0,1.0,0.0,7.0,7.0,19.0,14.0,2.0,3.0,1.0,2.0,0.0,0.0,10.0,20.0,1.0,3.0,0.0

In [53]:
df_cc= pd.concat([df2, df4])

In [54]:
df_cc.shape

(15016, 31)

In [55]:
df_cc.head(2)

,Date,HomeTeam,AwayTeam,Final_Home_goals,Final_Away_goals,Half_Time_Home_Goals,Half_Time_Away_Goals,Half_Time_Result,Crowd_Attendance,Referee,Home_Shots,Away_Shots,Home_Shots_Target,Away_Shots_Target,Home_Woodwork,Away_Woodwork,Home_Corners,Away_Corners,Home_Fouls,Away_Fouls,Home_Offsides,Away_Offsides,Home_Yellow_Cards,Away_Yellow_Cards,Home_Red_Cards,Away_Red_Cards,Home_Bookings_Points,Away_Bookings_Points,Final_result,Home_score,Away_score
0,2000-08-19,Charlton,Man City,4.0,0.0,2.0,0.0,1,20043.0,Rob Harris,17.0,8.0,14.0,4.0,2.0,1.0,6.0,6.0,13.0,12.0,8.0,6.0,1.0,2.0,0.0,0.0,10.0,20.0,1.0,3.0,0.0
1,2000-08-19,Chelsea,West Ham,4.0,2.0,1.0,0.0,1,34914.0,Graham Barber,17.0,12.0,10.0,5.0,1.0,0.0,7.0,7.0,19.0,14.0,2.0,3.0,1.0,2.0,0.0,0.0,10.0,20.0,1.0,3.0,0.0

In [56]:
df_cc = df_cc.reset_index()

In [57]:
df_cc

,index,Date,HomeTeam,AwayTeam,Final_Home_goals,Final_Away_goals,Half_Time_Home_Goals,Half_Time_Away_Goals,Half_Time_Result,Crowd_Attendance,Referee,Home_Shots,Away_Shots,Home_Shots_Target,Away_Shots_Target,Home_Woodwork,Away_Woodwork,Home_Corners,Away_Corners,Home_Fouls,Away_Fouls,Home_Offsides,Away_Offsides,Home_Yellow_Cards,Away_Yellow_Cards,Home_Red_Cards,Away_Red_Cards,Home_Bookings_Points,Away_Bookings_Points,Final_result,Home_score,Away_score
0,0,2000-08-19,Charlton,Man City,4.0,0.0,2.0,0.0,1,20043.0,Rob Harris,17.0,8.0,14.0,4.0,2.0,1.0,6.0,6.0,13.0,12.0,8.0,6.0,1.0,2.0,0.0,0.0,10.0,20.0,1.0,3.0,0.0
1,1,2000-08-19,Chelsea,West Ham,4.0,2.0,1.0,0.0,1,34914.0,Graham Barber,17.0,12.0,10.0,5.0,1.0,0.0,7.0,7.0,19.0,14.0,2.0,3.0,1.0,2.0,0.0,0.0,10.0,20.0,1.0,3.0,0.0
2,2,2000-08-19,Coventry,Middlesbrough,1.0,3.0,1.0,1.0,2,20624.0,Barry Knight,6.0,16.0,3.0,9.0,0.0,1.0,8.0,4.0,15.0,21.0,1.0,3.0,5.0,3.0,1.0,0.0,75.0,30.0,3.0,0.0,3.0
3,3,2000-08-19,Derby,Southampton,2.0,2.0,1.0,2.0,3,27223.0,Andy D'Urso,6.0,13.0,4.0,6.0,0.0,0.0,5.0,8.0,11.0,13.0,0.0,2.0,1.0,1.0,0.0,0.0,10.0,10.0,2.0,1.0,1.0
4,4,2000-08-19,Leeds,Everton,2.0,0.0,2.0,0.0,1,40010.0,Dermot Gallagher,17.0,12.0,8.0,6.0,0.0,0.0,6.0,4.0,21.0,20.0,6.0,1.0,1.0,3.0,0.0,0.0,10.0,30.0,1.0,3.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15011,7502,2020-03-07,Norwich,Sheffield United,0.0,1.0,0.0,1.0,3,NaN,S Hooper,12.0,10.0,5.0,4.0,NaN,NaN,5.0,10.0,8.0,12.0,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,3.0,0.0,3.0
15012,7504,2020-03-07,Tottenham,Burnley,1.0,1.0,0.0,1.0,3,NaN,J Moss,13.0,21.0,2.0,8.0,NaN,NaN,5.0,3.0,11.0,16.0,NaN,NaN,4.0,5.0,0.0,0.0,NaN,NaN,2.0,1.0,1.0
15013,7506,2020-03-08,Everton,Chelsea,0.0,4.0,0.0,2.0,3,NaN,K Friend,3.0,17.0,1.0,11.0,NaN,NaN,1.0,6.0,10.0,8.0,NaN,NaN,2.0,1.0,0.0,0.0,NaN,NaN,3.0,0.0,3.0
15014,7505,2020-03-08,Man City,Man United,0.0,2.0,0.0,1.0,3,NaN,M Dean,7.0,12.0,2.0,6.0,NaN,NaN,11.0,2.0,9.0,11.0,NaN,NaN,4.0,2.0,0.0,0.0,NaN,NaN,3.0,0.0,3.0
15015,7507,2020-03-09,Aston Villa,Leicester,0.0,4.0,0.0,1.0,3,NaN,M Oliver,4.0,15.0,1.0,7.0,NaN,NaN,0.0,9.0,12.0,15.0,NaN,NaN,1.0,2.0,0.0,0.0,NaN,NaN,3.0,0.0,3.0

In [58]:
del df_cc['index']

In [59]:
shh = df_cc.groupby(['HomeTeam']).shift()
del shh['Date']
sha = df_cc.groupby(['AwayTeam']).shift()
del sha['Date']
temp_H =pd.DataFrame(df_cc[['Date','HomeTeam']]).join(shh)
temp_A =pd.DataFrame(df_cc[['Date','AwayTeam']]).join(sha)

In [60]:
temp_H=temp_H.set_index('Date')
temp_A=temp_A.set_index('Date')

In [61]:
# rolling (sum) on the df_cc for the home column & merge with df_cc

#cc1_abol= pd.merge(df_cc, df_cc.set_index('Date').groupby(['HomeTeam']).rolling(6, min_periods=6).sum().reset_index(), suffixes=['','_Home_AllGames_sum_6'], on=['HomeTeam', 'Date'])

In [62]:
cc1= pd.merge(df_cc, temp_H.groupby(['HomeTeam']).rolling(6, min_periods=6).sum().reset_index(), suffixes=['','_Home_AllGames_sum_6'], on=['HomeTeam', 'Date'])

In [63]:
# df_cc_home= rolling (median) on the df_cc for the home column & merge with cc1
#cc2= pd.merge(cc1, df_cc.groupby(['HomeTeam']).rolling(6, min_periods=1).median().reset_index(), suffixes=['','_Home_AllGames_median_6'], on=['HomeTeam', 'Date'])

In [64]:
cc1= pd.merge(cc1, temp_H.groupby(['HomeTeam']).rolling(6, min_periods=1).median().reset_index(), suffixes=['','_Home_AllGames_median_6'], on=['HomeTeam', 'Date'])

In [65]:
# df_cc_home= rolling (average) on the df_cc for the home column & merge with cc2
cc1= pd.merge(cc1, temp_H.groupby(['HomeTeam']).rolling(6, min_periods=1).mean().reset_index(), suffixes=['','_Home_AllGames_Average_6'], on=['HomeTeam', 'Date'])

In [66]:
cols= set(cc1.columns.to_list()) - set(cc1.loc[:,'AwayTeam':'Away_score'].columns.to_list())

In [67]:
cols

{'Away_Bookings_Points_Home_AllGames_Average_6',
 'Away_Bookings_Points_Home_AllGames_median_6',
 'Away_Bookings_Points_Home_AllGames_sum_6',
 'Away_Corners_Home_AllGames_Average_6',
 'Away_Corners_Home_AllGames_median_6',
 'Away_Corners_Home_AllGames_sum_6',
 'Away_Fouls_Home_AllGames_Average_6',
 'Away_Fouls_Home_AllGames_median_6',
 'Away_Fouls_Home_AllGames_sum_6',
 'Away_Offsides_Home_AllGames_Average_6',
 'Away_Offsides_Home_AllGames_median_6',
 'Away_Offsides_Home_AllGames_sum_6',
 'Away_Red_Cards_Home_AllGames_Average_6',
 'Away_Red_Cards_Home_AllGames_median_6',
 'Away_Red_Cards_Home_AllGames_sum_6',
 'Away_Shots_Home_AllGames_Average_6',
 'Away_Shots_Home_AllGames_median_6',
 'Away_Shots_Home_AllGames_sum_6',
 'Away_Shots_Target_Home_AllGames_Average_6',
 'Away_Shots_Target_Home_AllGames_median_6',
 'Away_Shots_Target_Home_AllGames_sum_6',
 'Away_Woodwork_Home_AllGames_Average_6',
 'Away_Woodwork_Home_AllGames_median_6',
 'Away_Woodwork_Home_AllGames_sum_6',
 'Away_Yellow_Cards_Home_AllGames_Average_6',
 'Away_Yellow_Cards_Home_AllGames_median_6',
 'Away_Yellow_Cards_Home_AllGames_sum_6',
 'Away_score_Home_AllGames_Average_6',
 'Away_score_Home_AllGames_median_6',
 'Away_score_Home_AllGames_sum_6',
 'Crowd_Attendance_Home_AllGames_Average_6',
 'Crowd_Attendance_Home_AllGames_median_6',
 'Crowd_Attendance_Home_AllGames_sum_6',
 'Date',
 'Final_Away_goals_Home_AllGames_Average_6',
 'Final_Away_goals_Home_AllGames_median_6',
 'Final_Away_goals_Home_AllGames_sum_6',
 'Final_Home_goals_Home_AllGames_Average_6',
 'Final_Home_goals_Home_AllGames_median_6',
 'Final_Home_goals_Home_AllGames_sum_6',
 'Final_result_Home_AllGames_Average_6',
 'Final_result_Home_AllGames_median_6',
 'Final_result_Home_AllGames_sum_6',
 'Half_Time_Away_Goals_Home_AllGames_Average_6',
 'Half_Time_Away_Goals_Home_AllGames_median_6',
 'Half_Time_Away_Goals_Home_AllGames_sum_6',
 'Half_Time_Home_Goals_Home_AllGames_Average_6',
 'Half_Time_Home_Goals_Home_AllGames_median_6',
 'Half_Time_Home_Goals_Home_AllGames_sum_6',
 'Half_Time_Result_Home_AllGames_Average_6',
 'Half_Time_Result_Home_AllGames_median_6',
 'Half_Time_Result_Home_AllGames_sum_6',
 'HomeTeam',
 'Home_Bookings_Points_Home_AllGames_Average_6',
 'Home_Bookings_Points_Home_AllGames_median_6',
 'Home_Bookings_Points_Home_AllGames_sum_6',
 'Home_Corners_Home_AllGames_Average_6',
 'Home_Corners_Home_AllGames_median_6',
 'Home_Corners_Home_AllGames_sum_6',
 'Home_Fouls_Home_AllGames_Average_6',
 'Home_Fouls_Home_AllGames_median_6',
 'Home_Fouls_Home_AllGames_sum_6',
 'Home_Offsides_Home_AllGames_Average_6',
 'Home_Offsides_Home_AllGames_median_6',
 'Home_Offsides_Home_AllGames_sum_6',
 'Home_Red_Cards_Home_AllGames_Average_6',
 'Home_Red_Cards_Home_AllGames_median_6',
 'Home_Red_Cards_Home_AllGames_sum_6',
 'Home_Shots_Home_AllGames_Average_6',
 'Home_Shots_Home_AllGames_median_6',
 'Home_Shots_Home_AllGames_sum_6',
 'Home_Shots_Target_Home_AllGames_Average_6',
 'Home_Shots_Target_Home_AllGames_median_6',
 'Home_Shots_Target_Home_AllGames_sum_6',
 'Home_Woodwork_Home_AllGames_Average_6',
 'Home_Woodwork_Home_AllGames_median_6',
 'Home_Woodwork_Home_AllGames_sum_6',
 'Home_Yellow_Cards_Home_AllGames_Average_6',
 'Home_Yellow_Cards_Home_AllGames_median_6',
 'Home_Yellow_Cards_Home_AllGames_sum_6',
 'Home_score_Home_AllGames_Average_6',
 'Home_score_Home_AllGames_median_6',
 'Home_score_Home_AllGames_sum_6'}

In [68]:
df_home=cc1.loc[:,cols]

In [69]:
df_home.head(2)

,Home_Shots_Home_AllGames_sum_6,Half_Time_Home_Goals_Home_AllGames_Average_6,Home_Offsides_Home_AllGames_Average_6,Final_Away_goals_Home_AllGames_sum_6,Final_Home_goals_Home_AllGames_sum_6,Half_Time_Away_Goals_Home_AllGames_Average_6,Home_Yellow_Cards_Home_AllGames_median_6,Home_Shots_Home_AllGames_median_6,Away_Fouls_Home_AllGames_Average_6,Away_Woodwork_Home_AllGames_Average_6,Away_Shots_Target_Home_AllGames_Average_6,Crowd_Attendance_Home_AllGames_Average_6,Away_Corners_Home_AllGames_median_6,Away_Bookings_Points_Home_AllGames_median_6,Home_Offsides_Home_AllGames_sum_6,Half_Time_Away_Goals_Home_AllGames_median_6,Away_Shots_Target_Home_AllGames_median_6,Final_Away_goals_Home_AllGames_median_6,Away_Shots_Target_Home_AllGames_sum_6,Away_Corners_Home_AllGames_sum_6,Away_Fouls_Home_AllGames_sum_6,Home_Corners_Home_AllGames_Average_6,Away_Shots_Home_AllGames_median_6,Away_Yellow_Cards_Home_AllGames_Average_6,Home_Woodwork_Home_AllGames_sum_6,Away_Fouls_Home_AllGames_median_6,Away_Red_Cards_Home_AllGames_median_6,Home_Yellow_Cards_Home_AllGames_Average_6,Crowd_Attendance_Home_AllGames_median_6,Home_Red_Cards_Home_AllGames_sum_6,Away_score_Home_AllGames_Average_6,Away_Woodwork_Home_AllGames_median_6,Away_Shots_Home_AllGames_Average_6,Home_Yellow_Cards_Home_AllGames_sum_6,Final_result_Home_AllGames_median_6,Home_Bookings_Points_Home_AllGames_Average_6,Half_Time_Result_Home_AllGames_median_6,Away_Woodwork_Home_AllGames_sum_6,Home_Bookings_Points_Home_AllGames_sum_6,Final_Home_goals_Home_AllGames_Average_6,Away_Offsides_Home_AllGames_median_6,Half_Time_Away_Goals_Home_AllGames_sum_6,Home_Fouls_Home_AllGames_sum_6,Final_result_Home_AllGames_Average_6,Away_Corners_Home_AllGames_Average_6,Home_score_Home_AllGames_median_6,Home_Red_Cards_Home_AllGames_Average_6,Half_Time_Home_Goals_Home_AllGames_sum_6,Away_Yellow_Cards_Home_AllGames_median_6,Away_Bookings_Points_Home_AllGames_sum_6,Away_Offsides_Home_AllGames_Average_6,Away_score_Home_AllGames_sum_6,Final_Away_goals_Home_AllGames_Average_6,Home_Bookings_Points_Home_AllGames_median_6,Home_Shots_Target_Home_AllGames_Average_6,Home_Woodwork_Home_AllGames_median_6,Half_Time_Result_Home_AllGames_sum_6,Home_Woodwork_Home_AllGames_Average_6,Home_Red_Cards_Home_AllGames_median_6,Home_score_Home_AllGames_sum_6,Home_Fouls_Home_AllGames_Average_6,Half_Time_Result_Home_AllGames_Average_6,HomeTeam,Home_Shots_Target_Home_AllGames_median_6,Home_Corners_Home_AllGames_sum_6,Date,Away_Yellow_Cards_Home_AllGames_sum_6,Final_result_Home_AllGames_sum_6,Home_Shots_Home_AllGames_Average_6,Half_Time_Home_Goals_Home_AllGames_median_6,Home_Fouls_Home_AllGames_median_6,Away_Shots_Home_AllGames_sum_6,Home_Shots_Target_Home_AllGames_sum_6,Away_Offsides_Home_AllGames_sum_6,Away_Bookings_Points_Home_AllGames_Average_6,Crowd_Attendance_Home_AllGames_sum_6,Home_Offsides_Home_AllGames_median_6,Away_Red_Cards_Home_AllGames_Average_6,Home_Corners_Home_AllGames_median_6,Away_Red_Cards_Home_AllGames_sum_6,Final_Home_goals_Home_AllGames_median_6,Away_score_Home_AllGames_median_6,Home_score_Home_AllGames_Average_6
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Charlton,NaN,NaN,2000-08-19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Chelsea,NaN,NaN,2000-08-19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [70]:
res1.head(2)

,Date,HomeTeam,AwayTeam,Final_Home_goals,Final_Away_goals,Half_Time_Home_Goals,Half_Time_Away_Goals,Half_Time_Result,Crowd_Attendance,Referee,Home_Shots,Away_Shots,Home_Shots_Target,Away_Shots_Target,Home_Woodwork,Away_Woodwork,Home_Corners,Away_Corners,Home_Fouls,Away_Fouls,Home_Offsides,Away_Offsides,Home_Yellow_Cards,Away_Yellow_Cards,Home_Red_Cards,Away_Red_Cards,Home_Bookings_Points,Away_Bookings_Points,Final_result,Home_score,Away_score,Final_Home_goals_HomeTeam_sum_6,Final_Away_goals_HomeTeam_sum_6,Half_Time_Home_Goals_HomeTeam_sum_6,Half_Time_Away_Goals_HomeTeam_sum_6,Half_Time_Result_HomeTeam_sum_6,Crowd_Attendance_HomeTeam_sum_6,Home_Shots_HomeTeam_sum_6,Away_Shots_HomeTeam_sum_6,Home_Shots_Target_HomeTeam_sum_6,Away_Shots_Target_HomeTeam_sum_6,Home_Woodwork_HomeTeam_sum_6,Away_Woodwork_HomeTeam_sum_6,Home_Corners_HomeTeam_sum_6,Away_Corners_HomeTeam_sum_6,Home_Fouls_HomeTeam_sum_6,Away_Fouls_HomeTeam_sum_6,Home_Offsides_HomeTeam_sum_6,Away_Offsides_HomeTeam_sum_6,Home_Yellow_Cards_HomeTeam_sum_6,Away_Yellow_Cards_HomeTeam_sum_6,Home_Red_Cards_HomeTeam_sum_6,Away_Red_Cards_HomeTeam_sum_6,Home_Bookings_Points_HomeTeam_sum_6,Away_Bookings_Points_HomeTeam_sum_6,Final_result_HomeTeam_sum_6,Home_score_HomeTeam_sum_6,Away_score_HomeTeam_sum_6,Final_Home_goals_AwayTeam_sum_6,Final_Away_goals_AwayTeam_sum_6,Half_Time_Home_Goals_AwayTeam_sum_6,Half_Time_Away_Goals_AwayTeam_sum_6,Half_Time_Result_AwayTeam_sum_6,Crowd_Attendance_AwayTeam_sum_6,Home_Shots_AwayTeam_sum_6,Away_Shots_AwayTeam_sum_6,Home_Shots_Target_AwayTeam_sum_6,Away_Shots_Target_AwayTeam_sum_6,Home_Woodwork_AwayTeam_sum_6,Away_Woodwork_AwayTeam_sum_6,Home_Corners_AwayTeam_sum_6,Away_Corners_AwayTeam_sum_6,Home_Fouls_AwayTeam_sum_6,Away_Fouls_AwayTeam_sum_6,Home_Offsides_AwayTeam_sum_6,Away_Offsides_AwayTeam_sum_6,Home_Yellow_Cards_AwayTeam_sum_6,Away_Yellow_Cards_AwayTeam_sum_6,Home_Red_Cards_AwayTeam_sum_6,Away_Red_Cards_AwayTeam_sum_6,Home_Bookings_Points_AwayTeam_sum_6,Away_Bookings_Points_AwayTeam_sum_6,Final_result_AwayTeam_sum_6,Home_score_AwayTeam_sum_6,Away_score_AwayTeam_sum_6,Final_Home_goals_HomeTeam_median_6,Final_Away_goals_HomeTeam_median_6,Half_Time_Home_Goals_HomeTeam_median_6,Half_Time_Away_Goals_HomeTeam_median_6,Half_Time_Result_HomeTeam_median_6,Crowd_Attendance_HomeTeam_median_6,Home_Shots_HomeTeam_median_6,Away_Shots_HomeTeam_median_6,Home_Shots_Target_HomeTeam_median_6,Away_Shots_Target_HomeTeam_median_6,Home_Woodwork_HomeTeam_median_6,Away_Woodwork_HomeTeam_median_6,Home_Corners_HomeTeam_median_6,Away_Corners_HomeTeam_median_6,Home_Fouls_HomeTeam_median_6,Away_Fouls_HomeTeam_median_6,Home_Offsides_HomeTeam_median_6,Away_Offsides_HomeTeam_median_6,Home_Yellow_Cards_HomeTeam_median_6,Away_Yellow_Cards_HomeTeam_median_6,Home_Red_Cards_HomeTeam_median_6,Away_Red_Cards_HomeTeam_median_6,Home_Bookings_Points_HomeTeam_median_6,Away_Bookings_Points_HomeTeam_median_6,Final_result_HomeTeam_median_6,Home_score_HomeTeam_median_6,Away_score_HomeTeam_median_6,Final_Home_goals_AwayTeam_median_6,Final_Away_goals_AwayTeam_median_6,Half_Time_Home_Goals_AwayTeam_median_6,Half_Time_Away_Goals_AwayTeam_median_6,Half_Time_Result_AwayTeam_median_6,Crowd_Attendance_AwayTeam_median_6,Home_Shots_AwayTeam_median_6,Away_Shots_AwayTeam_median_6,Home_Shots_Target_AwayTeam_median_6,Away_Shots_Target_AwayTeam_median_6,Home_Woodwork_AwayTeam_median_6,Away_Woodwork_AwayTeam_median_6,Home_Corners_AwayTeam_median_6,Away_Corners_AwayTeam_median_6,Home_Fouls_AwayTeam_median_6,Away_Fouls_AwayTeam_median_6,Home_Offsides_AwayTeam_median_6,Away_Offsides_AwayTeam_median_6,Home_Yellow_Cards_AwayTeam_median_6,Away_Yellow_Cards_AwayTeam_median_6,Home_Red_Cards_AwayTeam_median_6,Away_Red_Cards_AwayTeam_median_6,Home_Bookings_Points_AwayTeam_median_6,Away_Bookings_Points_AwayTeam_median_6,Final_result_AwayTeam_median_6,Home_score_AwayTeam_median_6,Away_score_AwayTeam_median_6,Final_Home_goals_HomeTeam_average_6,Final_Away_goals_HomeTeam_average_6,Half_Time_Home_Goals_HomeTeam_average_6,Half_Time_Away_Goals_HomeTeam_average_6,Half_Time_Result_HomeTeam_average_6,Crowd_Attendance_HomeTeam_average_6,Home_Shots_HomeTeam_average_6,Away_Shots_HomeTeam_average_6,Home_Shots_Target_HomeTeam_average_6,Away_Shots_Target_HomeTeam_average_6,Home_Woodwork_HomeTeam_average_6,Away_Woodwork_HomeTeam_average_6,Home_Corners_HomeTeam_average_6,Away_Corners_HomeTeam_average_6,Home_Fouls_HomeTeam_average_6,Away_Fouls_HomeTeam_average_6,Home_Offsides_HomeTeam_average_6,Away_Offsides_HomeTeam_average_6,Home_Yellow_Cards_HomeTeam_average_6,Away_Yellow_Cards_HomeTeam_average_6,Home_Red_Cards_HomeTeam_average_6,Away_Red_Cards_HomeTeam_average_6,Home_Bookings_Points_HomeTeam_average_6,Away_Bookings_Points_HomeTeam_average_6,Final_result_HomeTeam_average_6,Home_score_HomeTeam_average_6,Away_score_HomeTeam_average_6,Final_Home_goals_AwayTeam_average_6,Final_Away_goals_AwayTeam_average_6,Half_Time_Home_Goals_AwayTeam_average_6,Half_Time_Away_Goals_AwayTeam_average_6,Half_Time_Result_AwayTeam_average_6,Crowd_Attendance_AwayTeam_average_6,Home_Shots_AwayTeam_average_6,Away_Shots_AwayTeam_average_6,Home_Shots_Target_AwayTeam_average_6,Away_Shots_Target_AwayTeam_average_6,Home_Woodwork_AwayTeam_average_6,Away_Woodwork_AwayTeam_average_6,Home_Corners_AwayTeam_average_6,Away_Corners_AwayTeam_average_6,Home_Fouls_AwayTeam_average_6,Away_Fouls_AwayTeam_average_6,Home_Offsides_AwayTeam_average_6,Away_Offsides_AwayTeam_average_6,Home_Yellow_Cards_AwayTeam_average_6,Away_Yellow_Cards_AwayTeam_average_6,Home_Red_Cards_AwayTeam_average_6,Away_Red_Cards_AwayTeam_average_6,Home_Bookings_Points_AwayTeam_average_6,Away_Bookings_Points_AwayTeam_average_6,Final_result_AwayTeam_average_6,Home_score_AwayTeam_average_6,Away_score_AwayTeam_average_6
0,2000-08-19,Charlton,Man City,4.0,0.0,2.0,0.0,1,20043.0,Rob Harris,17.0,8.0,14.0,4.0,2.0,1.0,6.0,6.0,13.0,12.0,8.0,6.0,1.0,2.0,0.0,0.0,10.0,20.0,1.0,3.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2000-08-19,Chelsea,West Ham,4.0,2.0,1.0,0.0,1,34914.0,Graham Barber,17.0,12.0,10.0,5.0,1.0,0.0,7.0,7.0,19.0,14.0,2.0,3.0,1.0,2.0,0.0,0.0,10.0,20.0,1.0,3.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [71]:
# res7 = merge res6 and df_home based on the df_cc_home.home=res6.home and date
res7= pd.merge(res1, df_home, on=['HomeTeam', 'Date'])

In [72]:
#res7.tail().to_csv('res7.csv')

In [73]:
res7.loc[res7['HomeTeam']=='Charlton', res7.columns.str.contains('Final_Home_goals')].head(7)

,Final_Home_goals,Final_Home_goals_HomeTeam_sum_6,Final_Home_goals_AwayTeam_sum_6,Final_Home_goals_HomeTeam_median_6,Final_Home_goals_AwayTeam_median_6,Final_Home_goals_HomeTeam_average_6,Final_Home_goals_AwayTeam_average_6,Final_Home_goals_Home_AllGames_sum_6,Final_Home_goals_Home_AllGames_Average_6,Final_Home_goals_Home_AllGames_median_6
0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,1.0,NaN,NaN,4.0,2.0,4.000000,2.000000,NaN,4.000000,4.0
50,1.0,NaN,NaN,2.5,1.5,2.500000,1.500000,NaN,2.500000,2.5
70,2.0,NaN,NaN,1.0,1.0,2.000000,1.333333,NaN,2.000000,1.0
90,1.0,NaN,NaN,1.5,1.0,2.000000,1.500000,NaN,2.000000,1.5
110,2.0,NaN,NaN,1.0,2.0,1.800000,2.400000,NaN,1.800000,1.0
132,2.0,11.0,10.0,1.5,1.5,1.833333,1.666667,11.0,1.833333,1.5

In [74]:
# rolling (sum) on the df_cc for the away column & merge with df_cc
aa1= pd.merge(df_cc, temp_A.groupby(['AwayTeam']).rolling(6, min_periods=6).sum().reset_index(), suffixes=['','_Away_AllGames_sum_6'], on=['AwayTeam', 'Date'])

In [75]:
# df_cc_home= rolling (median) on the df_cc for the away column & merge with aa1
aa1= pd.merge(aa1, temp_A.groupby(['AwayTeam']).rolling(6, min_periods=1).median().reset_index(), suffixes=['','_Away_AllGames_median_6'], on=['AwayTeam', 'Date'])

In [76]:
# df_cc_home= rolling (average) on the df_cc for the away column & merge with aa2
aa1= pd.merge(aa1, temp_A.groupby(['AwayTeam']).rolling(6, min_periods=1).mean().reset_index(), suffixes=['','_Away_AllGames_Average_6'], on=['AwayTeam', 'Date'])

In [77]:
aa1.shape

(15016, 112)

In [78]:
col= aa1.loc[:,'Final_Home_goals':'Away_score'].columns
col

Index(['Final_Home_goals', 'Final_Away_goals', 'Half_Time_Home_Goals',
       'Half_Time_Away_Goals', 'Half_Time_Result', 'Crowd_Attendance',
       'Referee', 'Home_Shots', 'Away_Shots', 'Home_Shots_Target',
       'Away_Shots_Target', 'Home_Woodwork', 'Away_Woodwork', 'Home_Corners',
       'Away_Corners', 'Home_Fouls', 'Away_Fouls', 'Home_Offsides',
       'Away_Offsides', 'Home_Yellow_Cards', 'Away_Yellow_Cards',
       'Home_Red_Cards', 'Away_Red_Cards', 'Home_Bookings_Points',
       'Away_Bookings_Points', 'Final_result', 'Home_score', 'Away_score'],
      dtype='object')

In [79]:
list(col)+['HomeTeam']

['Final_Home_goals',
 'Final_Away_goals',
 'Half_Time_Home_Goals',
 'Half_Time_Away_Goals',
 'Half_Time_Result',
 'Crowd_Attendance',
 'Referee',
 'Home_Shots',
 'Away_Shots',
 'Home_Shots_Target',
 'Away_Shots_Target',
 'Home_Woodwork',
 'Away_Woodwork',
 'Home_Corners',
 'Away_Corners',
 'Home_Fouls',
 'Away_Fouls',
 'Home_Offsides',
 'Away_Offsides',
 'Home_Yellow_Cards',
 'Away_Yellow_Cards',
 'Home_Red_Cards',
 'Away_Red_Cards',
 'Home_Bookings_Points',
 'Away_Bookings_Points',
 'Final_result',
 'Home_score',
 'Away_score',
 'HomeTeam']

In [80]:
cols= set(aa1.columns.to_list()) - set(aa1.loc[:,list(col)+['HomeTeam']].columns.to_list())

In [81]:
cols

{'AwayTeam',
 'Away_Bookings_Points_Away_AllGames_Average_6',
 'Away_Bookings_Points_Away_AllGames_median_6',
 'Away_Bookings_Points_Away_AllGames_sum_6',
 'Away_Corners_Away_AllGames_Average_6',
 'Away_Corners_Away_AllGames_median_6',
 'Away_Corners_Away_AllGames_sum_6',
 'Away_Fouls_Away_AllGames_Average_6',
 'Away_Fouls_Away_AllGames_median_6',
 'Away_Fouls_Away_AllGames_sum_6',
 'Away_Offsides_Away_AllGames_Average_6',
 'Away_Offsides_Away_AllGames_median_6',
 'Away_Offsides_Away_AllGames_sum_6',
 'Away_Red_Cards_Away_AllGames_Average_6',
 'Away_Red_Cards_Away_AllGames_median_6',
 'Away_Red_Cards_Away_AllGames_sum_6',
 'Away_Shots_Away_AllGames_Average_6',
 'Away_Shots_Away_AllGames_median_6',
 'Away_Shots_Away_AllGames_sum_6',
 'Away_Shots_Target_Away_AllGames_Average_6',
 'Away_Shots_Target_Away_AllGames_median_6',
 'Away_Shots_Target_Away_AllGames_sum_6',
 'Away_Woodwork_Away_AllGames_Average_6',
 'Away_Woodwork_Away_AllGames_median_6',
 'Away_Woodwork_Away_AllGames_sum_6',
 'Away_Yellow_Cards_Away_AllGames_Average_6',
 'Away_Yellow_Cards_Away_AllGames_median_6',
 'Away_Yellow_Cards_Away_AllGames_sum_6',
 'Away_score_Away_AllGames_Average_6',
 'Away_score_Away_AllGames_median_6',
 'Away_score_Away_AllGames_sum_6',
 'Crowd_Attendance_Away_AllGames_Average_6',
 'Crowd_Attendance_Away_AllGames_median_6',
 'Crowd_Attendance_Away_AllGames_sum_6',
 'Date',
 'Final_Away_goals_Away_AllGames_Average_6',
 'Final_Away_goals_Away_AllGames_median_6',
 'Final_Away_goals_Away_AllGames_sum_6',
 'Final_Home_goals_Away_AllGames_Average_6',
 'Final_Home_goals_Away_AllGames_median_6',
 'Final_Home_goals_Away_AllGames_sum_6',
 'Final_result_Away_AllGames_Average_6',
 'Final_result_Away_AllGames_median_6',
 'Final_result_Away_AllGames_sum_6',
 'Half_Time_Away_Goals_Away_AllGames_Average_6',
 'Half_Time_Away_Goals_Away_AllGames_median_6',
 'Half_Time_Away_Goals_Away_AllGames_sum_6',
 'Half_Time_Home_Goals_Away_AllGames_Average_6',
 'Half_Time_Home_Goals_Away_AllGames_median_6',
 'Half_Time_Home_Goals_Away_AllGames_sum_6',
 'Half_Time_Result_Away_AllGames_Average_6',
 'Half_Time_Result_Away_AllGames_median_6',
 'Half_Time_Result_Away_AllGames_sum_6',
 'Home_Bookings_Points_Away_AllGames_Average_6',
 'Home_Bookings_Points_Away_AllGames_median_6',
 'Home_Bookings_Points_Away_AllGames_sum_6',
 'Home_Corners_Away_AllGames_Average_6',
 'Home_Corners_Away_AllGames_median_6',
 'Home_Corners_Away_AllGames_sum_6',
 'Home_Fouls_Away_AllGames_Average_6',
 'Home_Fouls_Away_AllGames_median_6',
 'Home_Fouls_Away_AllGames_sum_6',
 'Home_Offsides_Away_AllGames_Average_6',
 'Home_Offsides_Away_AllGames_median_6',
 'Home_Offsides_Away_AllGames_sum_6',
 'Home_Red_Cards_Away_AllGames_Average_6',
 'Home_Red_Cards_Away_AllGames_median_6',
 'Home_Red_Cards_Away_AllGames_sum_6',
 'Home_Shots_Away_AllGames_Average_6',
 'Home_Shots_Away_AllGames_median_6',
 'Home_Shots_Away_AllGames_sum_6',
 'Home_Shots_Target_Away_AllGames_Average_6',
 'Home_Shots_Target_Away_AllGames_median_6',
 'Home_Shots_Target_Away_AllGames_sum_6',
 'Home_Woodwork_Away_AllGames_Average_6',
 'Home_Woodwork_Away_AllGames_median_6',
 'Home_Woodwork_Away_AllGames_sum_6',
 'Home_Yellow_Cards_Away_AllGames_Average_6',
 'Home_Yellow_Cards_Away_AllGames_median_6',
 'Home_Yellow_Cards_Away_AllGames_sum_6',
 'Home_score_Away_AllGames_Average_6',
 'Home_score_Away_AllGames_median_6',
 'Home_score_Away_AllGames_sum_6'}

In [82]:
df_away=aa1.loc[:,cols]

In [83]:
df_away.head(2)

,Away_Corners_Away_AllGames_Average_6,Away_Shots_Away_AllGames_Average_6,Home_Corners_Away_AllGames_sum_6,Crowd_Attendance_Away_AllGames_median_6,Home_Offsides_Away_AllGames_Average_6,Home_Woodwork_Away_AllGames_Average_6,Away_Yellow_Cards_Away_AllGames_sum_6,Away_Fouls_Away_AllGames_Average_6,Away_Bookings_Points_Away_AllGames_median_6,Final_Home_goals_Away_AllGames_Average_6,Away_Yellow_Cards_Away_AllGames_Average_6,Away_Red_Cards_Away_AllGames_sum_6,Away_Offsides_Away_AllGames_sum_6,Crowd_Attendance_Away_AllGames_Average_6,Final_Away_goals_Away_AllGames_median_6,Away_Red_Cards_Away_AllGames_Average_6,Home_Bookings_Points_Away_AllGames_sum_6,Half_Time_Result_Away_AllGames_median_6,Home_Bookings_Points_Away_AllGames_median_6,Away_Corners_Away_AllGames_median_6,Home_Shots_Target_Away_AllGames_median_6,Home_Shots_Away_AllGames_sum_6,Home_Corners_Away_AllGames_Average_6,Away_Red_Cards_Away_AllGames_median_6,Home_score_Away_AllGames_Average_6,Away_Shots_Away_AllGames_sum_6,Home_Woodwork_Away_AllGames_sum_6,Home_Fouls_Away_AllGames_median_6,Home_Red_Cards_Away_AllGames_median_6,Half_Time_Home_Goals_Away_AllGames_sum_6,Away_Shots_Target_Away_AllGames_Average_6,Home_Red_Cards_Away_AllGames_sum_6,Final_Away_goals_Away_AllGames_Average_6,Home_Shots_Target_Away_AllGames_Average_6,Half_Time_Away_Goals_Away_AllGames_sum_6,Home_Yellow_Cards_Away_AllGames_sum_6,Home_Shots_Away_AllGames_median_6,Home_Yellow_Cards_Away_AllGames_median_6,Away_Offsides_Away_AllGames_Average_6,Away_Bookings_Points_Away_AllGames_sum_6,Final_result_Away_AllGames_Average_6,Home_score_Away_AllGames_sum_6,Away_Corners_Away_AllGames_sum_6,Away_Shots_Away_AllGames_median_6,Away_Fouls_Away_AllGames_median_6,Half_Time_Result_Away_AllGames_Average_6,Away_Woodwork_Away_AllGames_median_6,Away_Offsides_Away_AllGames_median_6,Home_Shots_Away_AllGames_Average_6,Away_Yellow_Cards_Away_AllGames_median_6,Away_score_Away_AllGames_sum_6,Away_Fouls_Away_AllGames_sum_6,Home_Shots_Target_Away_AllGames_sum_6,Half_Time_Away_Goals_Away_AllGames_median_6,Home_Bookings_Points_Away_AllGames_Average_6,Half_Time_Away_Goals_Away_AllGames_Average_6,Home_Fouls_Away_AllGames_sum_6,Away_score_Away_AllGames_Average_6,Final_Home_goals_Away_AllGames_median_6,Away_Woodwork_Away_AllGames_Average_6,Half_Time_Home_Goals_Away_AllGames_median_6,Final_Home_goals_Away_AllGames_sum_6,Final_result_Away_AllGames_sum_6,Final_result_Away_AllGames_median_6,Half_Time_Home_Goals_Away_AllGames_Average_6,Final_Away_goals_Away_AllGames_sum_6,Crowd_Attendance_Away_AllGames_sum_6,Home_Offsides_Away_AllGames_median_6,Home_Fouls_Away_AllGames_Average_6,Home_Red_Cards_Away_AllGames_Average_6,AwayTeam,Home_Woodwork_Away_AllGames_median_6,Away_score_Away_AllGames_median_6,Half_Time_Result_Away_AllGames_sum_6,Date,Away_Woodwork_Away_AllGames_sum_6,Home_Corners_Away_AllGames_median_6,Away_Bookings_Points_Away_AllGames_Average_6,Away_Shots_Target_Away_AllGames_median_6,Away_Shots_Target_Away_AllGames_sum_6,Home_Offsides_Away_AllGames_sum_6,Home_Yellow_Cards_Away_AllGames_Average_6,Home_score_Away_AllGames_median_6
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Man City,NaN,NaN,NaN,2000-08-19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,West Ham,NaN,NaN,NaN,2000-08-19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [84]:
df_away['AwayTeam'].head()

0         Man City
1         West Ham
2    Middlesbrough
3      Southampton
4          Everton
Name: AwayTeam, dtype: object

In [85]:
#df_away.head(2).to_csv('away.csv')

In [86]:
# merge res7 and df_away based on the df_away.away=res7.away and date
df_final= pd.merge(res7, df_away, on=['AwayTeam','Date'])

In [87]:
df_final.shape

(7508, 355)

In [88]:
df_final.to_csv('final.csv')

In [89]:
df_final.shape

(7508, 355)

In [90]:
df_final.head(1)

,Date,HomeTeam,AwayTeam,Final_Home_goals,Final_Away_goals,Half_Time_Home_Goals,Half_Time_Away_Goals,Half_Time_Result,Crowd_Attendance,Referee,Home_Shots,Away_Shots,Home_Shots_Target,Away_Shots_Target,Home_Woodwork,Away_Woodwork,Home_Corners,Away_Corners,Home_Fouls,Away_Fouls,Home_Offsides,Away_Offsides,Home_Yellow_Cards,Away_Yellow_Cards,Home_Red_Cards,Away_Red_Cards,Home_Bookings_Points,Away_Bookings_Points,Final_result,Home_score,Away_score,Final_Home_goals_HomeTeam_sum_6,Final_Away_goals_HomeTeam_sum_6,Half_Time_Home_Goals_HomeTeam_sum_6,Half_Time_Away_Goals_HomeTeam_sum_6,Half_Time_Result_HomeTeam_sum_6,Crowd_Attendance_HomeTeam_sum_6,Home_Shots_HomeTeam_sum_6,Away_Shots_HomeTeam_sum_6,Home_Shots_Target_HomeTeam_sum_6,Away_Shots_Target_HomeTeam_sum_6,Home_Woodwork_HomeTeam_sum_6,Away_Woodwork_HomeTeam_sum_6,Home_Corners_HomeTeam_sum_6,Away_Corners_HomeTeam_sum_6,Home_Fouls_HomeTeam_sum_6,Away_Fouls_HomeTeam_sum_6,Home_Offsides_HomeTeam_sum_6,Away_Offsides_HomeTeam_sum_6,Home_Yellow_Cards_HomeTeam_sum_6,Away_Yellow_Cards_HomeTeam_sum_6,Home_Red_Cards_HomeTeam_sum_6,Away_Red_Cards_HomeTeam_sum_6,Home_Bookings_Points_HomeTeam_sum_6,Away_Bookings_Points_HomeTeam_sum_6,Final_result_HomeTeam_sum_6,Home_score_HomeTeam_sum_6,Away_score_HomeTeam_sum_6,Final_Home_goals_AwayTeam_sum_6,Final_Away_goals_AwayTeam_sum_6,Half_Time_Home_Goals_AwayTeam_sum_6,Half_Time_Away_Goals_AwayTeam_sum_6,Half_Time_Result_AwayTeam_sum_6,Crowd_Attendance_AwayTeam_sum_6,Home_Shots_AwayTeam_sum_6,Away_Shots_AwayTeam_sum_6,Home_Shots_Target_AwayTeam_sum_6,Away_Shots_Target_AwayTeam_sum_6,Home_Woodwork_AwayTeam_sum_6,Away_Woodwork_AwayTeam_sum_6,Home_Corners_AwayTeam_sum_6,Away_Corners_AwayTeam_sum_6,Home_Fouls_AwayTeam_sum_6,Away_Fouls_AwayTeam_sum_6,Home_Offsides_AwayTeam_sum_6,Away_Offsides_AwayTeam_sum_6,Home_Yellow_Cards_AwayTeam_sum_6,Away_Yellow_Cards_AwayTeam_sum_6,Home_Red_Cards_AwayTeam_sum_6,Away_Red_Cards_AwayTeam_sum_6,Home_Bookings_Points_AwayTeam_sum_6,Away_Bookings_Points_AwayTeam_sum_6,Final_result_AwayTeam_sum_6,Home_score_AwayTeam_sum_6,Away_score_AwayTeam_sum_6,Final_Home_goals_HomeTeam_median_6,Final_Away_goals_HomeTeam_median_6,Half_Time_Home_Goals_HomeTeam_median_6,Half_Time_Away_Goals_HomeTeam_median_6,Half_Time_Result_HomeTeam_median_6,Crowd_Attendance_HomeTeam_median_6,Home_Shots_HomeTeam_median_6,Away_Shots_HomeTeam_median_6,Home_Shots_Target_HomeTeam_median_6,Away_Shots_Target_HomeTeam_median_6,Home_Woodwork_HomeTeam_median_6,Away_Woodwork_HomeTeam_median_6,Home_Corners_HomeTeam_median_6,Away_Corners_HomeTeam_median_6,Home_Fouls_HomeTeam_median_6,Away_Fouls_HomeTeam_median_6,Home_Offsides_HomeTeam_median_6,Away_Offsides_HomeTeam_median_6,Home_Yellow_Cards_HomeTeam_median_6,Away_Yellow_Cards_HomeTeam_median_6,Home_Red_Cards_HomeTeam_median_6,Away_Red_Cards_HomeTeam_median_6,Home_Bookings_Points_HomeTeam_median_6,Away_Bookings_Points_HomeTeam_median_6,Final_result_HomeTeam_median_6,Home_score_HomeTeam_median_6,Away_score_HomeTeam_median_6,Final_Home_goals_AwayTeam_median_6,Final_Away_goals_AwayTeam_median_6,Half_Time_Home_Goals_AwayTeam_median_6,Half_Time_Away_Goals_AwayTeam_median_6,Half_Time_Result_AwayTeam_median_6,Crowd_Attendance_AwayTeam_median_6,Home_Shots_AwayTeam_median_6,Away_Shots_AwayTeam_median_6,Home_Shots_Target_AwayTeam_median_6,Away_Shots_Target_AwayTeam_median_6,Home_Woodwork_AwayTeam_median_6,Away_Woodwork_AwayTeam_median_6,Home_Corners_AwayTeam_median_6,Away_Corners_AwayTeam_median_6,Home_Fouls_AwayTeam_median_6,Away_Fouls_AwayTeam_median_6,Home_Offsides_AwayTeam_median_6,Away_Offsides_AwayTeam_median_6,Home_Yellow_Cards_AwayTeam_median_6,Away_Yellow_Cards_AwayTeam_median_6,Home_Red_Cards_AwayTeam_median_6,Away_Red_Cards_AwayTeam_median_6,Home_Bookings_Points_AwayTeam_median_6,Away_Bookings_Points_AwayTeam_median_6,Final_result_AwayTeam_median_6,Home_score_AwayTeam_median_6,Away_score_AwayTeam_median_6,Final_Home_goals_HomeTeam_average_6,Final_Away_goals_HomeTeam_average_6,Half_Time_Home_Goals_HomeTeam_average_6,Half_Time_Away_Goals_HomeTeam_average_6,Half_Time_Result_HomeTeam_average_6,Crowd_Attendance_HomeTeam_average_6,Home_Shots_HomeTeam_average_6,Away_Shots_HomeTeam_average_6,Home_Shots_Target_HomeTeam_average_6,Away_Shots_Target_HomeTeam_average_6,Home_Woodwork_HomeTeam_average_6,Away_Woodwork_HomeTeam_average_6,Home_Corners_HomeTeam_average_6,Away_Corners_HomeTeam_average_6,Home_Fouls_HomeTeam_average_6,Away_Fouls_HomeTeam_average_6,Home_Offsides_HomeTeam_average_6,Away_Offsides_HomeTeam_average_6,Home_Yellow_Cards_HomeTeam_average_6,Away_Yellow_Cards_HomeTeam_average_6,Home_Red_Cards_HomeTeam_average_6,Away_Red_Cards_HomeTeam_average_6,Home_Bookings_Points_HomeTeam_average_6,Away_Bookings_Points_HomeTeam_average_6,Final_result_HomeTeam_average_6,Home_score_HomeTeam_average_6,Away_score_HomeTeam_average_6,Final_Home_goals_AwayTeam_average_6,Final_Away_goals_AwayTeam_average_6,Half_Time_Home_Goals_AwayTeam_average_6,Half_Time_Away_Goals_AwayTeam_average_6,Half_Time_Result_AwayTeam_average_6,Crowd_Attendance_AwayTeam_average_6,Home_Shots_AwayTeam_average_6,Away_Shots_AwayTeam_average_6,Home_Shots_Target_AwayTeam_average_6,Away_Shots_Target_AwayTeam_average_6,Home_Woodwork_AwayTeam_average_6,Away_Woodwork_AwayTeam_average_6,Home_Corners_AwayTeam_average_6,Away_Corners_AwayTeam_average_6,Home_Fouls_AwayTeam_average_6,Away_Fouls_AwayTeam_average_6,Home_Offsides_AwayTeam_average_6,Away_Offsides_AwayTeam_average_6,Home_Yellow_Cards_AwayTeam_average_6,Away_Yellow_Cards_AwayTeam_average_6,Home_Red_Cards_AwayTeam_average_6,Away_Red_Cards_AwayTeam_average_6,Home_Bookings_Points_AwayTeam_average_6,Away_Bookings_Points_AwayTeam_average_6,Final_result_AwayTeam_average_6,Home_score_AwayTeam_average_6,Away_score_AwayTeam_average_6,Home_Shots_Home_AllGames_sum_6,Half_Time_Home_Goals_Home_AllGames_Average_6,Home_Offsides_Home_AllGames_Average_6,Final_Away_goals_Home_AllGames_sum_6,Final_Home_goals_Home_AllGames_sum_6,Half_Time_Away_Goals_Home_AllGames_Average_6,Home_Yellow_Cards_Home_AllGames_median_6,Home_Shots_Home_AllGames_median_6,Away_Fouls_Home_AllGames_Average_6,Away_Woodwork_Home_AllGames_Average_6,Away_Shots_Target_Home_AllGames_Average_6,Crowd_Attendance_Home_AllGames_Average_6,Away_Corners_Home_AllGames_median_6,Away_Bookings_Points_Home_AllGames_median_6,Home_Offsides_Home_AllGames_sum_6,Half_Time_Away_Goals_Home_AllGames_median_6,Away_Shots_Target_Home_AllGames_median_6,Final_Away_goals_Home_AllGames_median_6,Away_Shots_Target_Home_AllGames_sum_6,Away_Corners_Home_AllGames_sum_6,Away_Fouls_Home_AllGames_sum_6,Home_Corners_Home_AllGames_Average_6,Away_Shots_Home_AllGames_median_6,Away_Yellow_Cards_Home_AllGames_Average_6,Home_Woodwork_Home_AllGames_sum_6,Away_Fouls_Home_AllGames_median_6,Away_Red_Cards_Home_AllGames_median_6,Home_Yellow_Cards_Home_AllGames_Average_6,Crowd_Attendance_Home_AllGames_median_6,Home_Red_Cards_Home_AllGames_sum_6,Away_score_Home_AllGames_Average_6,Away_Woodwork_Home_AllGames_median_6,Away_Shots_Home_AllGames_Average_6,Home_Yellow_Cards_Home_AllGames_sum_6,Final_result_Home_AllGames_median_6,Home_Bookings_Points_Home_AllGames_Average_6,Half_Time_Result_Home_AllGames_median_6,Away_Woodwork_Home_AllGames_sum_6,Home_Bookings_Points_Home_AllGames_sum_6,Final_Home_goals_Home_AllGames_Average_6,Away_Offsides_Home_AllGames_median_6,Half_Time_Away_Goals_Home_AllGames_sum_6,Home_Fouls_Home_AllGames_sum_6,Final_result_Home_AllGames_Average_6,Away_Corners_Home_AllGames_Average_6,Home_score_Home_AllGames_median_6,Home_Red_Cards_Home_AllGames_Average_6,Half_Time_Home_Goals_Home_AllGames_sum_6,Away_Yellow_Cards_Home_AllGames_median_6,Away_Bookings_Points_Home_AllGames_sum_6,Away_Offsides_Home_AllGames_Average_6,Away_score_Home_AllGames_sum_6,Final_Away_goals_Home_AllGames_Average_6,Home_Bookings_Points_Home_AllGames_median_6,Home_Shots_Target_Home_AllGames_Average_6,Home_Woodwork_Home_AllGames_median_6,Half_Time_Result_Home_AllGames_sum_6,Home_Woodwork_Home_AllGames_Average_6,Home_Red_Cards_Home_AllGames_median_6,Home_score_Home_AllGames_sum_6,Home_Fouls_Home_AllGames_Average_6,Half_Time_Result_Home_AllGames_Average_6,Home_Shots_Target_Home_AllGames_median_6,Home_Corners_Home_AllGames_sum_6,Away_Yellow_Cards_Home_AllGames_sum_6,Final_result_Home_AllGames_sum_6,Home_Shots_Home_AllGames_Average_6,Half_Time_Home_Goals_Home_AllGames_median_6,Home_Fouls_Home_AllGames_median_6,Away_Shots_Home_AllGames_sum_6,Home_Shots_Target_Home_AllGames_sum_6,Away_Offsides_Home_AllGames_sum_6,Away_Bookings_Points_Home_AllGames_Average_6,Crowd_Attendance_Home_AllGames_sum_6,Home_Offsides_Home_AllGames_median_6,Away_Red_Cards_Home_AllGames_Average_6,Home_Corners_Home_AllGames_median_6,Away_Red_Cards_Home_AllGames_sum_6,Final_Home_goals_Home_AllGames_median_6,Away_score_Home_AllGames_median_6,Home_score_Home_AllGames_Average_6,Away_Corners_Away_AllGames_Average_6,Away_Shots_Away_AllGames_Average_6,Home_Corners_Away_AllGames_sum_6,Crowd_Attendance_Away_AllGames_median_6,Home_Offsides_Away_AllGames_Average_6,Home_Woodwork_Away_AllGames_Average_6,Away_Yellow_Cards_Away_AllGames_sum_6,Away_Fouls_Away_AllGames_Average_6,Away_Bookings_Points_Away_AllGames_median_6,Final_Home_goals_Away_AllGames_Average_6,Away_Yellow_Cards_Away_AllGames_Average_6,Away_Red_Cards_Away_AllGames_sum_6,Away_Offsides_Away_AllGames_sum_6,Crowd_Attendance_Away_AllGames_Average_6,Final_Away_goals_Away_AllGames_median_6,Away_Red_Cards_Away_AllGames_Average_6,Home_Bookings_Points_Away_AllGames_sum_6,Half_Time_Result_Away_AllGames_median_6,Home_Bookings_Points_Away_AllGames_median_6,Away_Corners_Away_AllGames_median_6,Home_Shots_Target_Away_AllGames_median_6,Home_Shots_Away_AllGames_sum_6,Home_Corners_Away_AllGames_Average_6,Away_Red_Cards_Away_AllGames_median_6,Home_score_Away_AllGames_Average_6,Away_Shots_Away_AllGames_sum_6,Home_Woodwork_Away_AllGames_sum_6,Home_Fouls_Away_AllGames_median_6,Home_Red_Cards_Away_AllGames_median_6,Half_Time_Home_Goals_Away_AllGames_sum_6,Away_Shots_Target_Away_AllGames_Average_6,Home_Red_Cards_Away_AllGames_sum_6,Final_Away_goals_Away_AllGames_Average_6,Home_Shots_Target_Away_AllGames_Average_6,Half_Time_Away_Goals_Away_AllGames_sum_6,Home_Yellow_Cards_Away_AllGames_sum_6,Home_Shots_Away_AllGames_median_6,Home_Yellow_Cards_Away_AllGames_median_6,Away_Offsides_Away_AllGames_Average_6,Away_Bookings_Points_Away_AllGames_sum_6,Final_result_Away_AllGames_Average_6,Home_score_Away_AllGames_sum_6,Away_Corners_Away_AllGames_sum_6,Away_Shots_Away_AllGames_median_6,Away_Fouls_Away_AllGames_median_6,Half_Time_Result_Away_AllGames_Average_6,Away_Woodwork_Away_AllGames_median_6,Away_Offsides_Away_AllGames_median_6,Home_Shots_Away_AllGames_Average_6,Away_Yellow_Cards_Away_AllGames_median_6,Away_score_Away_AllGames_sum_6,Away_Fouls_Away_AllGames_sum_6,Home_Shots_Target_Away_AllGames_sum_6,Half_Time_Away_Goals_Away_AllGames_median_6,Home_Bookings_Points_Away_AllGames_Average_6,Half_Time_Away_Goals_Away_AllGames_Average_6,Home_Fouls_Away_AllGames_sum_6,Away_score_Away_AllGames_Average_6,Final_Home_goals_Away_AllGames_median_6,Away_Woodwork_Away_AllGames_Average_6,Half_Time_Home_Goals_Away_AllGames_median_6,Final_Home_goals_Away_AllGames_sum_6,Final_result_Away_AllGames_sum_6,Final_result_Away_AllGames_median_6,Half_Time_Home_Goals_Away_AllGames_Average_6,Final_Away_goals_Away_AllGames_sum_6,Crowd_Attendance_Away_AllGames_sum_6,Home_Offsides_Away_AllGames_median_6,Home_Fouls_Away_AllGames_Average_6,Home_Red_Cards_Away_AllGames_Average_6,Home_Woodwork_Away_AllGames_median_6,Away_score_Away_AllGames_median_6,Half_Time_Result_Away_AllGames_sum_6,Away_Woodwork_Away_AllGames_sum_6,Home_Corners_Away_AllGames_median_6,Away_Bookings_Points_Away_AllGames_Average_6,Away_Shots_Target_Away_AllGames_median_6,Away_Shots_Target_Away_AllGames_sum_6,Home_Offsides_Away_AllGames_sum_6,Home_Yellow_Cards_Away_AllGames_Average_6,Home_score_Away_AllGames_median_6
0,2000-08-19,Charlton,Man City,4.0,0.0,2.0,0.0,1,20043.0,Rob Harris,17.0,8.0,14.0,4.0,2.0,1.0,6.0,6.0,13.0,12.0,8.0,6.0,1.0,2.0,0.0,0.0,10.0,20.0,1.0,3.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [91]:
df2.head(10)

,Date,HomeTeam,AwayTeam,Final_Home_goals,Final_Away_goals,Half_Time_Home_Goals,Half_Time_Away_Goals,Half_Time_Result,Crowd_Attendance,Referee,Home_Shots,Away_Shots,Home_Shots_Target,Away_Shots_Target,Home_Woodwork,Away_Woodwork,Home_Corners,Away_Corners,Home_Fouls,Away_Fouls,Home_Offsides,Away_Offsides,Home_Yellow_Cards,Away_Yellow_Cards,Home_Red_Cards,Away_Red_Cards,Home_Bookings_Points,Away_Bookings_Points,Final_result,Home_score,Away_score
0,2000-08-19,Charlton,Man City,4.0,0.0,2.0,0.0,1,20043.0,Rob Harris,17.0,8.0,14.0,4.0,2.0,1.0,6.0,6.0,13.0,12.0,8.0,6.0,1.0,2.0,0.0,0.0,10.0,20.0,1.0,3.0,0.0
1,2000-08-19,Chelsea,West Ham,4.0,2.0,1.0,0.0,1,34914.0,Graham Barber,17.0,12.0,10.0,5.0,1.0,0.0,7.0,7.0,19.0,14.0,2.0,3.0,1.0,2.0,0.0,0.0,10.0,20.0,1.0,3.0,0.0
2,2000-08-19,Coventry,Middlesbrough,1.0,3.0,1.0,1.0,2,20624.0,Barry Knight,6.0,16.0,3.0,9.0,0.0,1.0,8.0,4.0,15.0,21.0,1.0,3.0,5.0,3.0,1.0,0.0,75.0,30.0,3.0,0.0,3.0
3,2000-08-19,Derby,Southampton,2.0,2.0,1.0,2.0,3,27223.0,Andy D'Urso,6.0,13.0,4.0,6.0,0.0,0.0,5.0,8.0,11.0,13.0,0.0,2.0,1.0,1.0,0.0,0.0,10.0,10.0,2.0,1.0,1.0
4,2000-08-19,Leeds,Everton,2.0,0.0,2.0,0.0,1,40010.0,Dermot Gallagher,17.0,12.0,8.0,6.0,0.0,0.0,6.0,4.0,21.0,20.0,6.0,1.0,1.0,3.0,0.0,0.0,10.0,30.0,1.0,3.0,0.0
5,2000-08-19,Leicester,Aston Villa,0.0,0.0,0.0,0.0,2,21455.0,Mike Riley,5.0,5.0,4.0,3.0,0.0,0.0,5.0,4.0,12.0,12.0,1.0,4.0,2.0,3.0,0.0,0.0,20.0,30.0,2.0,1.0,1.0
6,2000-08-19,Liverpool,Bradford,1.0,0.0,0.0,0.0,2,44183.0,Paul Durkin,16.0,3.0,10.0,2.0,0.0,0.0,6.0,1.0,8.0,8.0,5.0,0.0,1.0,1.0,0.0,0.0,10.0,10.0,1.0,3.0,0.0
7,2000-08-19,Sunderland,Arsenal,1.0,0.0,0.0,0.0,2,46346.0,Steve Dunn,8.0,14.0,2.0,7.0,0.0,0.0,2.0,9.0,10.0,21.0,2.0,3.0,3.0,1.0,0.0,1.0,30.0,35.0,1.0,3.0,0.0
8,2000-08-19,Tottenham,Ipswich,3.0,1.0,2.0,1.0,1,36148.0,Alan Wiley,20.0,15.0,6.0,5.0,2.0,1.0,3.0,4.0,14.0,13.0,2.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,0.0
9,2000-08-20,Man United,Newcastle,2.0,0.0,1.0,0.0,1,67477.0,Steve Lodge,19.0,9.0,9.0,6.0,2.0,0.0,7.0,1.0,7.0,13.0,5.0,9.0,0.0,1.0,0.0,0.0,0.0,10.0,1.0,3.0,0.0

In [92]:
# Rolling (sum) df2 on 'AwayTeam' and merge with df2 only on "awayteam" without date
rex1= pd.merge(df2, df2.set_index('Date').groupby(['AwayTeam']).rolling(6, min_periods=6).sum().reset_index(),  how='left', suffixes=['','_6Away_of_home_sum'], left_on=['HomeTeam'],right_on=['AwayTeam'])

In [93]:
rex1['menha_date']= (pd.to_datetime(rex1['Date'])-pd.to_datetime(rex1['Date_6Away_of_home_sum'])).dt.days

In [94]:
filt= rex1['menha_date']>0
rex2 = rex1.loc[filt]

In [95]:
rex2.groupby(['Date','HomeTeam'])['menha_date'].min().reset_index()

            Date       HomeTeam  menha_date
0     2000-08-21        Arsenal           2
1     2000-08-22       Bradford           3
2     2000-08-22        Ipswich           3
3     2000-08-22  Middlesbrough           3
4     2000-08-23        Everton           4
...          ...            ...         ...
7484  2020-03-07    Southampton           7
7485  2020-03-07         Wolves           6
7486  2020-03-08        Chelsea           8
7487  2020-03-08     Man United           7
7488  2020-03-09      Leicester          10

[7489 rows x 3 columns]

In [96]:
rex3 = pd.merge(rex1,rex2.groupby(['Date','HomeTeam'])['menha_date'].min().reset_index(),on=['Date','HomeTeam'])

In [97]:
rex3 = rex3.loc[rex3['menha_date_x'] == rex3['menha_date_y']]

In [98]:
rex3[['Date','Date_6Away_of_home_sum','menha_date_y','menha_date_x']]

               Date Date_6Away_of_home_sum  menha_date_y  menha_date_x
0        2000-08-21             2000-08-19             2             2
374      2000-08-22             2000-08-19             3             3
412      2000-08-22             2000-08-19             3             3
602      2000-08-22             2000-08-19             3             3
621      2000-08-23             2000-08-19             4             4
...             ...                    ...           ...           ...
1929965  2020-03-07             2020-02-01            35            35
1930074  2020-03-07             2020-02-29             7             7
1930449  2020-03-08             2020-02-29             8             8
1930824  2020-03-08             2020-03-01             7             7
1930990  2020-03-09             2020-02-28            10            10

[7489 rows x 4 columns]

In [99]:
rex3.head(1)

,Date,HomeTeam,AwayTeam,Final_Home_goals,Final_Away_goals,Half_Time_Home_Goals,Half_Time_Away_Goals,Half_Time_Result,Crowd_Attendance,Referee,Home_Shots,Away_Shots,Home_Shots_Target,Away_Shots_Target,Home_Woodwork,Away_Woodwork,Home_Corners,Away_Corners,Home_Fouls,Away_Fouls,Home_Offsides,Away_Offsides,Home_Yellow_Cards,Away_Yellow_Cards,Home_Red_Cards,Away_Red_Cards,Home_Bookings_Points,Away_Bookings_Points,Final_result,Home_score,Away_score,AwayTeam_6Away_of_home_sum,Date_6Away_of_home_sum,Final_Home_goals_6Away_of_home_sum,Final_Away_goals_6Away_of_home_sum,Half_Time_Home_Goals_6Away_of_home_sum,Half_Time_Away_Goals_6Away_of_home_sum,Half_Time_Result_6Away_of_home_sum,Crowd_Attendance_6Away_of_home_sum,Home_Shots_6Away_of_home_sum,Away_Shots_6Away_of_home_sum,Home_Shots_Target_6Away_of_home_sum,Away_Shots_Target_6Away_of_home_sum,Home_Woodwork_6Away_of_home_sum,Away_Woodwork_6Away_of_home_sum,Home_Corners_6Away_of_home_sum,Away_Corners_6Away_of_home_sum,Home_Fouls_6Away_of_home_sum,Away_Fouls_6Away_of_home_sum,Home_Offsides_6Away_of_home_sum,Away_Offsides_6Away_of_home_sum,Home_Yellow_Cards_6Away_of_home_sum,Away_Yellow_Cards_6Away_of_home_sum,Home_Red_Cards_6Away_of_home_sum,Away_Red_Cards_6Away_of_home_sum,Home_Bookings_Points_6Away_of_home_sum,Away_Bookings_Points_6Away_of_home_sum,Final_result_6Away_of_home_sum,Home_score_6Away_of_home_sum,Away_score_6Away_of_home_sum,menha_date_x,menha_date_y
0,2000-08-21,Arsenal,Liverpool,2.0,0.0,1.0,0.0,1,38014.0,Graham Poll,17.0,7.0,12.0,4.0,0.0,0.0,10.0,11.0,25.0,20.0,5.0,4.0,2.0,4.0,1.0,2.0,45.0,90.0,1.0,3.0,0.0,Arsenal,2000-08-19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2

In [100]:
col= rex3.loc[:,'Date_6Away_of_home_sum':'menha_date_x'].columns

In [101]:
list(col)

['Date_6Away_of_home_sum',
 'Final_Home_goals_6Away_of_home_sum',
 'Final_Away_goals_6Away_of_home_sum',
 'Half_Time_Home_Goals_6Away_of_home_sum',
 'Half_Time_Away_Goals_6Away_of_home_sum',
 'Half_Time_Result_6Away_of_home_sum',
 'Crowd_Attendance_6Away_of_home_sum',
 'Home_Shots_6Away_of_home_sum',
 'Away_Shots_6Away_of_home_sum',
 'Home_Shots_Target_6Away_of_home_sum',
 'Away_Shots_Target_6Away_of_home_sum',
 'Home_Woodwork_6Away_of_home_sum',
 'Away_Woodwork_6Away_of_home_sum',
 'Home_Corners_6Away_of_home_sum',
 'Away_Corners_6Away_of_home_sum',
 'Home_Fouls_6Away_of_home_sum',
 'Away_Fouls_6Away_of_home_sum',
 'Home_Offsides_6Away_of_home_sum',
 'Away_Offsides_6Away_of_home_sum',
 'Home_Yellow_Cards_6Away_of_home_sum',
 'Away_Yellow_Cards_6Away_of_home_sum',
 'Home_Red_Cards_6Away_of_home_sum',
 'Away_Red_Cards_6Away_of_home_sum',
 'Home_Bookings_Points_6Away_of_home_sum',
 'Away_Bookings_Points_6Away_of_home_sum',
 'Final_result_6Away_of_home_sum',
 'Home_score_6Away_of_home_sum',
 'Away_score_6Away_of_home_sum',
 'menha_date_x']

In [102]:
list(col)+['Date','HomeTeam']

['Date_6Away_of_home_sum',
 'Final_Home_goals_6Away_of_home_sum',
 'Final_Away_goals_6Away_of_home_sum',
 'Half_Time_Home_Goals_6Away_of_home_sum',
 'Half_Time_Away_Goals_6Away_of_home_sum',
 'Half_Time_Result_6Away_of_home_sum',
 'Crowd_Attendance_6Away_of_home_sum',
 'Home_Shots_6Away_of_home_sum',
 'Away_Shots_6Away_of_home_sum',
 'Home_Shots_Target_6Away_of_home_sum',
 'Away_Shots_Target_6Away_of_home_sum',
 'Home_Woodwork_6Away_of_home_sum',
 'Away_Woodwork_6Away_of_home_sum',
 'Home_Corners_6Away_of_home_sum',
 'Away_Corners_6Away_of_home_sum',
 'Home_Fouls_6Away_of_home_sum',
 'Away_Fouls_6Away_of_home_sum',
 'Home_Offsides_6Away_of_home_sum',
 'Away_Offsides_6Away_of_home_sum',
 'Home_Yellow_Cards_6Away_of_home_sum',
 'Away_Yellow_Cards_6Away_of_home_sum',
 'Home_Red_Cards_6Away_of_home_sum',
 'Away_Red_Cards_6Away_of_home_sum',
 'Home_Bookings_Points_6Away_of_home_sum',
 'Away_Bookings_Points_6Away_of_home_sum',
 'Final_result_6Away_of_home_sum',
 'Home_score_6Away_of_home_sum',
 'Away_score_6Away_of_home_sum',
 'menha_date_x',
 'Date',
 'HomeTeam']

In [103]:
rex3= rex3.loc[:,list(col)+['Date','HomeTeam']]

In [104]:
rex3.head(1)

,Date_6Away_of_home_sum,Final_Home_goals_6Away_of_home_sum,Final_Away_goals_6Away_of_home_sum,Half_Time_Home_Goals_6Away_of_home_sum,Half_Time_Away_Goals_6Away_of_home_sum,Half_Time_Result_6Away_of_home_sum,Crowd_Attendance_6Away_of_home_sum,Home_Shots_6Away_of_home_sum,Away_Shots_6Away_of_home_sum,Home_Shots_Target_6Away_of_home_sum,Away_Shots_Target_6Away_of_home_sum,Home_Woodwork_6Away_of_home_sum,Away_Woodwork_6Away_of_home_sum,Home_Corners_6Away_of_home_sum,Away_Corners_6Away_of_home_sum,Home_Fouls_6Away_of_home_sum,Away_Fouls_6Away_of_home_sum,Home_Offsides_6Away_of_home_sum,Away_Offsides_6Away_of_home_sum,Home_Yellow_Cards_6Away_of_home_sum,Away_Yellow_Cards_6Away_of_home_sum,Home_Red_Cards_6Away_of_home_sum,Away_Red_Cards_6Away_of_home_sum,Home_Bookings_Points_6Away_of_home_sum,Away_Bookings_Points_6Away_of_home_sum,Final_result_6Away_of_home_sum,Home_score_6Away_of_home_sum,Away_score_6Away_of_home_sum,menha_date_x,Date,HomeTeam
0,2000-08-19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2000-08-21,Arsenal

In [105]:
rex3 = rex3.rename(columns = {'menha_date_x':'menha_date_6Away_of_home_sum'})

In [106]:
# Rolling (median) df2 on 'AwayTeam' and merge with df2 only on "awayteam" without date
nat1= pd.merge(df2, df2.set_index('Date').groupby(['AwayTeam']).rolling(6, min_periods=1).median().reset_index(),  how='left', suffixes=['','_6Away_of_home_median'], left_on=['HomeTeam'],right_on=['AwayTeam'])

In [107]:
nat1['menha_date']= (pd.to_datetime(nat1['Date'])-pd.to_datetime(nat1['Date_6Away_of_home_median'])).dt.days

In [108]:
filt= nat1['menha_date']>0
nat2 = nat1.loc[filt]

In [109]:
nat2.groupby(['Date','HomeTeam'])['menha_date'].min().reset_index()

            Date       HomeTeam  menha_date
0     2000-08-21        Arsenal           2
1     2000-08-22       Bradford           3
2     2000-08-22        Ipswich           3
3     2000-08-22  Middlesbrough           3
4     2000-08-23        Everton           4
...          ...            ...         ...
7484  2020-03-07    Southampton           7
7485  2020-03-07         Wolves           6
7486  2020-03-08        Chelsea           8
7487  2020-03-08     Man United           7
7488  2020-03-09      Leicester          10

[7489 rows x 3 columns]

In [110]:
nat3 = pd.merge(nat1,nat2.groupby(['Date','HomeTeam'])['menha_date'].min().reset_index(),on=['Date','HomeTeam'])

In [111]:
nat3= nat3.loc[nat3['menha_date_x']==nat3['menha_date_y']]
nat3.tail()

,Date,HomeTeam,AwayTeam,Final_Home_goals,Final_Away_goals,Half_Time_Home_Goals,Half_Time_Away_Goals,Half_Time_Result,Crowd_Attendance,Referee,Home_Shots,Away_Shots,Home_Shots_Target,Away_Shots_Target,Home_Woodwork,Away_Woodwork,Home_Corners,Away_Corners,Home_Fouls,Away_Fouls,Home_Offsides,Away_Offsides,Home_Yellow_Cards,Away_Yellow_Cards,Home_Red_Cards,Away_Red_Cards,Home_Bookings_Points,Away_Bookings_Points,Final_result,Home_score,Away_score,AwayTeam_6Away_of_home_median,Date_6Away_of_home_median,Final_Home_goals_6Away_of_home_median,Final_Away_goals_6Away_of_home_median,Half_Time_Home_Goals_6Away_of_home_median,Half_Time_Away_Goals_6Away_of_home_median,Half_Time_Result_6Away_of_home_median,Crowd_Attendance_6Away_of_home_median,Home_Shots_6Away_of_home_median,Away_Shots_6Away_of_home_median,Home_Shots_Target_6Away_of_home_median,Away_Shots_Target_6Away_of_home_median,Home_Woodwork_6Away_of_home_median,Away_Woodwork_6Away_of_home_median,Home_Corners_6Away_of_home_median,Away_Corners_6Away_of_home_median,Home_Fouls_6Away_of_home_median,Away_Fouls_6Away_of_home_median,Home_Offsides_6Away_of_home_median,Away_Offsides_6Away_of_home_median,Home_Yellow_Cards_6Away_of_home_median,Away_Yellow_Cards_6Away_of_home_median,Home_Red_Cards_6Away_of_home_median,Away_Red_Cards_6Away_of_home_median,Home_Bookings_Points_6Away_of_home_median,Away_Bookings_Points_6Away_of_home_median,Final_result_6Away_of_home_median,Home_score_6Away_of_home_median,Away_score_6Away_of_home_median,menha_date_x,menha_date_y
1929965,2020-03-07,Sheffield United,Norwich,1.0,0.0,1.0,0.0,1,NaN,S Hooper,10.0,12.0,4.0,5.0,NaN,NaN,10.0,5.0,12.0,8.0,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,1.0,3.0,0.0,Sheffield United,2020-02-01,1.0,1.0,0.5,0.0,1.5,NaN,13.5,8.5,4.0,2.5,NaN,NaN,8.0,4.5,6.0,11.5,NaN,NaN,1.0,2.0,0.0,0.0,NaN,NaN,2.5,0.5,2.0,35,35
1930074,2020-03-07,Burnley,Tottenham,1.0,1.0,1.0,0.0,1,NaN,J Moss,21.0,13.0,8.0,2.0,NaN,NaN,3.0,5.0,16.0,11.0,NaN,NaN,5.0,4.0,0.0,0.0,NaN,NaN,2.0,1.0,1.0,Burnley,2020-02-29,0.5,0.5,0.0,0.0,2.0,NaN,19.5,6.5,4.5,1.5,NaN,NaN,7.5,3.0,11.0,10.0,NaN,NaN,1.0,2.5,0.0,0.0,NaN,NaN,2.5,0.5,2.0,7,7
1930449,2020-03-08,Chelsea,Everton,4.0,0.0,2.0,0.0,1,NaN,K Friend,17.0,3.0,11.0,1.0,NaN,NaN,6.0,1.0,8.0,10.0,NaN,NaN,1.0,2.0,0.0,0.0,NaN,NaN,1.0,3.0,0.0,Chelsea,2020-02-29,1.0,2.0,0.0,0.5,2.5,NaN,8.0,14.5,3.0,4.0,NaN,NaN,3.5,5.5,9.0,14.0,NaN,NaN,2.0,2.5,0.0,0.0,NaN,NaN,2.0,1.0,1.0,8,8
1930824,2020-03-08,Man United,Man City,2.0,0.0,1.0,0.0,1,NaN,M Dean,12.0,7.0,6.0,2.0,NaN,NaN,2.0,11.0,11.0,9.0,NaN,NaN,2.0,4.0,0.0,0.0,NaN,NaN,1.0,3.0,0.0,Man United,2020-03-01,1.5,0.5,0.5,0.5,2.0,NaN,13.5,12.0,3.5,4.5,NaN,NaN,7.0,5.0,11.0,11.0,NaN,NaN,3.0,3.0,0.0,0.0,NaN,NaN,1.5,2.0,0.5,7,7
1930990,2020-03-09,Leicester,Aston Villa,4.0,0.0,1.0,0.0,1,NaN,M Oliver,15.0,4.0,7.0,1.0,NaN,NaN,9.0,0.0,15.0,12.0,NaN,NaN,2.0,1.0,0.0,0.0,NaN,NaN,1.0,3.0,0.0,Leicester,2020-02-28,1.0,1.0,0.0,1.0,2.0,NaN,12.5,15.0,4.5,6.0,NaN,NaN,5.5,5.0,13.5,9.5,NaN,NaN,1.5,1.5,0.0,0.0,NaN,NaN,1.5,2.0,0.5,10,10

In [112]:
col= nat3.loc[:,'Date_6Away_of_home_median':'menha_date_x'].columns

In [113]:
list(col)

['Date_6Away_of_home_median',
 'Final_Home_goals_6Away_of_home_median',
 'Final_Away_goals_6Away_of_home_median',
 'Half_Time_Home_Goals_6Away_of_home_median',
 'Half_Time_Away_Goals_6Away_of_home_median',
 'Half_Time_Result_6Away_of_home_median',
 'Crowd_Attendance_6Away_of_home_median',
 'Home_Shots_6Away_of_home_median',
 'Away_Shots_6Away_of_home_median',
 'Home_Shots_Target_6Away_of_home_median',
 'Away_Shots_Target_6Away_of_home_median',
 'Home_Woodwork_6Away_of_home_median',
 'Away_Woodwork_6Away_of_home_median',
 'Home_Corners_6Away_of_home_median',
 'Away_Corners_6Away_of_home_median',
 'Home_Fouls_6Away_of_home_median',
 'Away_Fouls_6Away_of_home_median',
 'Home_Offsides_6Away_of_home_median',
 'Away_Offsides_6Away_of_home_median',
 'Home_Yellow_Cards_6Away_of_home_median',
 'Away_Yellow_Cards_6Away_of_home_median',
 'Home_Red_Cards_6Away_of_home_median',
 'Away_Red_Cards_6Away_of_home_median',
 'Home_Bookings_Points_6Away_of_home_median',
 'Away_Bookings_Points_6Away_of_home_median',
 'Final_result_6Away_of_home_median',
 'Home_score_6Away_of_home_median',
 'Away_score_6Away_of_home_median',
 'menha_date_x']

In [114]:
['Date','HomeTeam']+ list(col)

['Date',
 'HomeTeam',
 'Date_6Away_of_home_median',
 'Final_Home_goals_6Away_of_home_median',
 'Final_Away_goals_6Away_of_home_median',
 'Half_Time_Home_Goals_6Away_of_home_median',
 'Half_Time_Away_Goals_6Away_of_home_median',
 'Half_Time_Result_6Away_of_home_median',
 'Crowd_Attendance_6Away_of_home_median',
 'Home_Shots_6Away_of_home_median',
 'Away_Shots_6Away_of_home_median',
 'Home_Shots_Target_6Away_of_home_median',
 'Away_Shots_Target_6Away_of_home_median',
 'Home_Woodwork_6Away_of_home_median',
 'Away_Woodwork_6Away_of_home_median',
 'Home_Corners_6Away_of_home_median',
 'Away_Corners_6Away_of_home_median',
 'Home_Fouls_6Away_of_home_median',
 'Away_Fouls_6Away_of_home_median',
 'Home_Offsides_6Away_of_home_median',
 'Away_Offsides_6Away_of_home_median',
 'Home_Yellow_Cards_6Away_of_home_median',
 'Away_Yellow_Cards_6Away_of_home_median',
 'Home_Red_Cards_6Away_of_home_median',
 'Away_Red_Cards_6Away_of_home_median',
 'Home_Bookings_Points_6Away_of_home_median',
 'Away_Bookings_Points_6Away_of_home_median',
 'Final_result_6Away_of_home_median',
 'Home_score_6Away_of_home_median',
 'Away_score_6Away_of_home_median',
 'menha_date_x']

In [115]:
nat3= nat3.loc[:,['Date','HomeTeam']+ list(col)]

In [116]:
nat3 = nat3.rename(columns = {'menha_date_x':'menha_date_6Away_of_home_median'})

In [117]:
# Rolling (mean) df2 on 'AwayTeam' and merge with df2 only on "awayteam" without date
jav1= pd.merge(df2, df2.set_index('Date').groupby(['AwayTeam']).rolling(6, min_periods=1).mean().reset_index(),  how='left', suffixes=['','_6Away_of_home_mean'], left_on=['HomeTeam'],right_on=['AwayTeam'])

In [118]:
jav1['menha_date']= (pd.to_datetime(jav1['Date'])-pd.to_datetime(jav1['Date_6Away_of_home_mean'])).dt.days

In [119]:
filt= jav1['menha_date']>0
jav2 = jav1.loc[filt]

In [120]:
jav2.groupby(['Date','HomeTeam'])['menha_date'].min().reset_index()

            Date       HomeTeam  menha_date
0     2000-08-21        Arsenal           2
1     2000-08-22       Bradford           3
2     2000-08-22        Ipswich           3
3     2000-08-22  Middlesbrough           3
4     2000-08-23        Everton           4
...          ...            ...         ...
7484  2020-03-07    Southampton           7
7485  2020-03-07         Wolves           6
7486  2020-03-08        Chelsea           8
7487  2020-03-08     Man United           7
7488  2020-03-09      Leicester          10

[7489 rows x 3 columns]

In [121]:
jav3 = pd.merge(jav1,jav2.groupby(['Date','HomeTeam'])['menha_date'].min().reset_index(),on=['Date','HomeTeam'])

In [122]:
jav3 = jav3.loc[jav3['menha_date_x'] == jav3['menha_date_y']]

In [123]:
jav3[['Date','Date_6Away_of_home_mean','menha_date_y','menha_date_x']]

               Date Date_6Away_of_home_mean  menha_date_y  menha_date_x
0        2000-08-21              2000-08-19             2             2
374      2000-08-22              2000-08-19             3             3
412      2000-08-22              2000-08-19             3             3
602      2000-08-22              2000-08-19             3             3
621      2000-08-23              2000-08-19             4             4
...             ...                     ...           ...           ...
1929965  2020-03-07              2020-02-01            35            35
1930074  2020-03-07              2020-02-29             7             7
1930449  2020-03-08              2020-02-29             8             8
1930824  2020-03-08              2020-03-01             7             7
1930990  2020-03-09              2020-02-28            10            10

[7489 rows x 4 columns]

In [124]:
col= jav3.loc[:,'Date_6Away_of_home_mean':'menha_date_x'].columns

In [125]:
list(col)

['Date_6Away_of_home_mean',
 'Final_Home_goals_6Away_of_home_mean',
 'Final_Away_goals_6Away_of_home_mean',
 'Half_Time_Home_Goals_6Away_of_home_mean',
 'Half_Time_Away_Goals_6Away_of_home_mean',
 'Half_Time_Result_6Away_of_home_mean',
 'Crowd_Attendance_6Away_of_home_mean',
 'Home_Shots_6Away_of_home_mean',
 'Away_Shots_6Away_of_home_mean',
 'Home_Shots_Target_6Away_of_home_mean',
 'Away_Shots_Target_6Away_of_home_mean',
 'Home_Woodwork_6Away_of_home_mean',
 'Away_Woodwork_6Away_of_home_mean',
 'Home_Corners_6Away_of_home_mean',
 'Away_Corners_6Away_of_home_mean',
 'Home_Fouls_6Away_of_home_mean',
 'Away_Fouls_6Away_of_home_mean',
 'Home_Offsides_6Away_of_home_mean',
 'Away_Offsides_6Away_of_home_mean',
 'Home_Yellow_Cards_6Away_of_home_mean',
 'Away_Yellow_Cards_6Away_of_home_mean',
 'Home_Red_Cards_6Away_of_home_mean',
 'Away_Red_Cards_6Away_of_home_mean',
 'Home_Bookings_Points_6Away_of_home_mean',
 'Away_Bookings_Points_6Away_of_home_mean',
 'Final_result_6Away_of_home_mean',
 'Home_score_6Away_of_home_mean',
 'Away_score_6Away_of_home_mean',
 'menha_date_x']

In [126]:
['Date','HomeTeam']+ list(col)

['Date',
 'HomeTeam',
 'Date_6Away_of_home_mean',
 'Final_Home_goals_6Away_of_home_mean',
 'Final_Away_goals_6Away_of_home_mean',
 'Half_Time_Home_Goals_6Away_of_home_mean',
 'Half_Time_Away_Goals_6Away_of_home_mean',
 'Half_Time_Result_6Away_of_home_mean',
 'Crowd_Attendance_6Away_of_home_mean',
 'Home_Shots_6Away_of_home_mean',
 'Away_Shots_6Away_of_home_mean',
 'Home_Shots_Target_6Away_of_home_mean',
 'Away_Shots_Target_6Away_of_home_mean',
 'Home_Woodwork_6Away_of_home_mean',
 'Away_Woodwork_6Away_of_home_mean',
 'Home_Corners_6Away_of_home_mean',
 'Away_Corners_6Away_of_home_mean',
 'Home_Fouls_6Away_of_home_mean',
 'Away_Fouls_6Away_of_home_mean',
 'Home_Offsides_6Away_of_home_mean',
 'Away_Offsides_6Away_of_home_mean',
 'Home_Yellow_Cards_6Away_of_home_mean',
 'Away_Yellow_Cards_6Away_of_home_mean',
 'Home_Red_Cards_6Away_of_home_mean',
 'Away_Red_Cards_6Away_of_home_mean',
 'Home_Bookings_Points_6Away_of_home_mean',
 'Away_Bookings_Points_6Away_of_home_mean',
 'Final_result_6Away_of_home_mean',
 'Home_score_6Away_of_home_mean',
 'Away_score_6Away_of_home_mean',
 'menha_date_x']

In [127]:
jav3= jav3.loc[:,['Date','HomeTeam']+ list(col)]

In [128]:
jav3.head(1)

,Date,HomeTeam,Date_6Away_of_home_mean,Final_Home_goals_6Away_of_home_mean,Final_Away_goals_6Away_of_home_mean,Half_Time_Home_Goals_6Away_of_home_mean,Half_Time_Away_Goals_6Away_of_home_mean,Half_Time_Result_6Away_of_home_mean,Crowd_Attendance_6Away_of_home_mean,Home_Shots_6Away_of_home_mean,Away_Shots_6Away_of_home_mean,Home_Shots_Target_6Away_of_home_mean,Away_Shots_Target_6Away_of_home_mean,Home_Woodwork_6Away_of_home_mean,Away_Woodwork_6Away_of_home_mean,Home_Corners_6Away_of_home_mean,Away_Corners_6Away_of_home_mean,Home_Fouls_6Away_of_home_mean,Away_Fouls_6Away_of_home_mean,Home_Offsides_6Away_of_home_mean,Away_Offsides_6Away_of_home_mean,Home_Yellow_Cards_6Away_of_home_mean,Away_Yellow_Cards_6Away_of_home_mean,Home_Red_Cards_6Away_of_home_mean,Away_Red_Cards_6Away_of_home_mean,Home_Bookings_Points_6Away_of_home_mean,Away_Bookings_Points_6Away_of_home_mean,Final_result_6Away_of_home_mean,Home_score_6Away_of_home_mean,Away_score_6Away_of_home_mean,menha_date_x
0,2000-08-21,Arsenal,2000-08-19,1.0,0.0,0.0,0.0,2.0,46346.0,8.0,14.0,2.0,7.0,0.0,0.0,2.0,9.0,10.0,21.0,2.0,3.0,3.0,1.0,0.0,1.0,30.0,35.0,1.0,3.0,0.0,2

In [129]:
jav3 = jav3.rename(columns = {'menha_date_x':'menha_date_6Away_of_home_mean'})

In [130]:
df_f= pd.merge(rex3, nat3, on=['HomeTeam','Date'])

In [131]:
df_6Away_of_home= pd.merge(df_f, jav3, on=['HomeTeam','Date'])

In [132]:
df_6Away_of_home.head(1)

,Date_6Away_of_home_sum,Final_Home_goals_6Away_of_home_sum,Final_Away_goals_6Away_of_home_sum,Half_Time_Home_Goals_6Away_of_home_sum,Half_Time_Away_Goals_6Away_of_home_sum,Half_Time_Result_6Away_of_home_sum,Crowd_Attendance_6Away_of_home_sum,Home_Shots_6Away_of_home_sum,Away_Shots_6Away_of_home_sum,Home_Shots_Target_6Away_of_home_sum,Away_Shots_Target_6Away_of_home_sum,Home_Woodwork_6Away_of_home_sum,Away_Woodwork_6Away_of_home_sum,Home_Corners_6Away_of_home_sum,Away_Corners_6Away_of_home_sum,Home_Fouls_6Away_of_home_sum,Away_Fouls_6Away_of_home_sum,Home_Offsides_6Away_of_home_sum,Away_Offsides_6Away_of_home_sum,Home_Yellow_Cards_6Away_of_home_sum,Away_Yellow_Cards_6Away_of_home_sum,Home_Red_Cards_6Away_of_home_sum,Away_Red_Cards_6Away_of_home_sum,Home_Bookings_Points_6Away_of_home_sum,Away_Bookings_Points_6Away_of_home_sum,Final_result_6Away_of_home_sum,Home_score_6Away_of_home_sum,Away_score_6Away_of_home_sum,menha_date_6Away_of_home_sum,Date,HomeTeam,Date_6Away_of_home_median,Final_Home_goals_6Away_of_home_median,Final_Away_goals_6Away_of_home_median,Half_Time_Home_Goals_6Away_of_home_median,Half_Time_Away_Goals_6Away_of_home_median,Half_Time_Result_6Away_of_home_median,Crowd_Attendance_6Away_of_home_median,Home_Shots_6Away_of_home_median,Away_Shots_6Away_of_home_median,Home_Shots_Target_6Away_of_home_median,Away_Shots_Target_6Away_of_home_median,Home_Woodwork_6Away_of_home_median,Away_Woodwork_6Away_of_home_median,Home_Corners_6Away_of_home_median,Away_Corners_6Away_of_home_median,Home_Fouls_6Away_of_home_median,Away_Fouls_6Away_of_home_median,Home_Offsides_6Away_of_home_median,Away_Offsides_6Away_of_home_median,Home_Yellow_Cards_6Away_of_home_median,Away_Yellow_Cards_6Away_of_home_median,Home_Red_Cards_6Away_of_home_median,Away_Red_Cards_6Away_of_home_median,Home_Bookings_Points_6Away_of_home_median,Away_Bookings_Points_6Away_of_home_median,Final_result_6Away_of_home_median,Home_score_6Away_of_home_median,Away_score_6Away_of_home_median,menha_date_6Away_of_home_median,Date_6Away_of_home_mean,Final_Home_goals_6Away_of_home_mean,Final_Away_goals_6Away_of_home_mean,Half_Time_Home_Goals_6Away_of_home_mean,Half_Time_Away_Goals_6Away_of_home_mean,Half_Time_Result_6Away_of_home_mean,Crowd_Attendance_6Away_of_home_mean,Home_Shots_6Away_of_home_mean,Away_Shots_6Away_of_home_mean,Home_Shots_Target_6Away_of_home_mean,Away_Shots_Target_6Away_of_home_mean,Home_Woodwork_6Away_of_home_mean,Away_Woodwork_6Away_of_home_mean,Home_Corners_6Away_of_home_mean,Away_Corners_6Away_of_home_mean,Home_Fouls_6Away_of_home_mean,Away_Fouls_6Away_of_home_mean,Home_Offsides_6Away_of_home_mean,Away_Offsides_6Away_of_home_mean,Home_Yellow_Cards_6Away_of_home_mean,Away_Yellow_Cards_6Away_of_home_mean,Home_Red_Cards_6Away_of_home_mean,Away_Red_Cards_6Away_of_home_mean,Home_Bookings_Points_6Away_of_home_mean,Away_Bookings_Points_6Away_of_home_mean,Final_result_6Away_of_home_mean,Home_score_6Away_of_home_mean,Away_score_6Away_of_home_mean,menha_date_6Away_of_home_mean
0,2000-08-19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2000-08-21,Arsenal,2000-08-19,1.0,0.0,0.0,0.0,2.0,46346.0,8.0,14.0,2.0,7.0,0.0,0.0,2.0,9.0,10.0,21.0,2.0,3.0,3.0,1.0,0.0,1.0,30.0,35.0,1.0,3.0,0.0,2,2000-08-19,1.0,0.0,0.0,0.0,2.0,46346.0,8.0,14.0,2.0,7.0,0.0,0.0,2.0,9.0,10.0,21.0,2.0,3.0,3.0,1.0,0.0,1.0,30.0,35.0,1.0,3.0,0.0,2

In [133]:
# Rolling (sum) df2 on 'HomeTeam' and merge with df2 only on "hometeam" without date
erf1= pd.merge(df2, df2.set_index('Date').groupby(['HomeTeam']).rolling(6, min_periods=6).sum().reset_index(),  how='left', suffixes=['','_6Home_of_away_sum'], left_on=['AwayTeam'],right_on=['HomeTeam'])

In [134]:
erf1['menha_date']= (pd.to_datetime(erf1['Date'])-pd.to_datetime(erf1['Date_6Home_of_away_sum'])).dt.days

In [135]:
filt= erf1['menha_date']>0
erf2 = erf1.loc[filt]

In [136]:
erf2.groupby(['Date','AwayTeam'])['menha_date'].min().reset_index()

            Date     AwayTeam  menha_date
0     2000-08-21    Liverpool           2
1     2000-08-22      Chelsea           3
2     2000-08-22   Man United           2
3     2000-08-22    Tottenham           3
4     2000-08-23     Charlton           4
...          ...          ...         ...
7478  2020-03-07      Watford           7
7479  2020-03-07     West Ham           7
7480  2020-03-08      Everton           7
7481  2020-03-08     Man City          18
7482  2020-03-09  Aston Villa          22

[7483 rows x 3 columns]

In [137]:
erf3 = pd.merge(erf1,erf2.groupby(['Date','AwayTeam'])['menha_date'].min().reset_index(),on=['Date','AwayTeam'])

In [138]:
erf3 = erf3.loc[erf3['menha_date_x'] == erf3['menha_date_y']]

In [139]:
erf3[['Date','Date_6Home_of_away_sum','menha_date_y','menha_date_x']]

               Date Date_6Home_of_away_sum  menha_date_y  menha_date_x
0        2000-08-21             2000-08-19             2             2
376      2000-08-22             2000-08-20             2             2
752      2000-08-22             2000-08-19             3             3
1127     2000-08-22             2000-08-19             3             3
1503     2000-08-23             2000-08-19             4             4
...             ...                    ...           ...           ...
1928039  2020-03-07             2020-02-28             8             8
1928414  2020-03-07             2020-03-01             6             6
1928789  2020-03-08             2020-03-01             7             7
1929144  2020-03-08             2020-02-19            18            18
1929461  2020-03-09             2020-02-16            22            22

[7483 rows x 4 columns]

In [140]:
col= erf3.loc[:,'Date_6Home_of_away_sum':'menha_date_x'].columns

In [141]:
list(col)

['Date_6Home_of_away_sum',
 'Final_Home_goals_6Home_of_away_sum',
 'Final_Away_goals_6Home_of_away_sum',
 'Half_Time_Home_Goals_6Home_of_away_sum',
 'Half_Time_Away_Goals_6Home_of_away_sum',
 'Half_Time_Result_6Home_of_away_sum',
 'Crowd_Attendance_6Home_of_away_sum',
 'Home_Shots_6Home_of_away_sum',
 'Away_Shots_6Home_of_away_sum',
 'Home_Shots_Target_6Home_of_away_sum',
 'Away_Shots_Target_6Home_of_away_sum',
 'Home_Woodwork_6Home_of_away_sum',
 'Away_Woodwork_6Home_of_away_sum',
 'Home_Corners_6Home_of_away_sum',
 'Away_Corners_6Home_of_away_sum',
 'Home_Fouls_6Home_of_away_sum',
 'Away_Fouls_6Home_of_away_sum',
 'Home_Offsides_6Home_of_away_sum',
 'Away_Offsides_6Home_of_away_sum',
 'Home_Yellow_Cards_6Home_of_away_sum',
 'Away_Yellow_Cards_6Home_of_away_sum',
 'Home_Red_Cards_6Home_of_away_sum',
 'Away_Red_Cards_6Home_of_away_sum',
 'Home_Bookings_Points_6Home_of_away_sum',
 'Away_Bookings_Points_6Home_of_away_sum',
 'Final_result_6Home_of_away_sum',
 'Home_score_6Home_of_away_sum',
 'Away_score_6Home_of_away_sum',
 'menha_date_x']

In [142]:
['Date','AwayTeam']+ list(col)

['Date',
 'AwayTeam',
 'Date_6Home_of_away_sum',
 'Final_Home_goals_6Home_of_away_sum',
 'Final_Away_goals_6Home_of_away_sum',
 'Half_Time_Home_Goals_6Home_of_away_sum',
 'Half_Time_Away_Goals_6Home_of_away_sum',
 'Half_Time_Result_6Home_of_away_sum',
 'Crowd_Attendance_6Home_of_away_sum',
 'Home_Shots_6Home_of_away_sum',
 'Away_Shots_6Home_of_away_sum',
 'Home_Shots_Target_6Home_of_away_sum',
 'Away_Shots_Target_6Home_of_away_sum',
 'Home_Woodwork_6Home_of_away_sum',
 'Away_Woodwork_6Home_of_away_sum',
 'Home_Corners_6Home_of_away_sum',
 'Away_Corners_6Home_of_away_sum',
 'Home_Fouls_6Home_of_away_sum',
 'Away_Fouls_6Home_of_away_sum',
 'Home_Offsides_6Home_of_away_sum',
 'Away_Offsides_6Home_of_away_sum',
 'Home_Yellow_Cards_6Home_of_away_sum',
 'Away_Yellow_Cards_6Home_of_away_sum',
 'Home_Red_Cards_6Home_of_away_sum',
 'Away_Red_Cards_6Home_of_away_sum',
 'Home_Bookings_Points_6Home_of_away_sum',
 'Away_Bookings_Points_6Home_of_away_sum',
 'Final_result_6Home_of_away_sum',
 'Home_score_6Home_of_away_sum',
 'Away_score_6Home_of_away_sum',
 'menha_date_x']

In [143]:
erf3= erf3.loc[:,['Date','AwayTeam']+ list(col)]

In [144]:
erf3 = erf3.rename(columns = {'menha_date_x':'menha_date_6Home_of_away_sum'})

In [145]:
# Rolling (median) df2 on 'HomeTeam' and merge with df2 only on "hometeam" without date
eli1= pd.merge(df2, df2.set_index('Date').groupby(['HomeTeam']).rolling(6, min_periods=1).median().reset_index(),  how='left', suffixes=['','_6Home_of_away_median'], left_on=['AwayTeam'],right_on=['HomeTeam'])

In [146]:
eli1['menha_date']= (pd.to_datetime(eli1['Date'])-pd.to_datetime(eli1['Date_6Home_of_away_median'])).dt.days

In [147]:
filt= eli1['menha_date']>0
eli2 = eli1.loc[filt]

In [148]:
eli2.groupby(['Date','AwayTeam'])['menha_date'].min().reset_index()

            Date     AwayTeam  menha_date
0     2000-08-21    Liverpool           2
1     2000-08-22      Chelsea           3
2     2000-08-22   Man United           2
3     2000-08-22    Tottenham           3
4     2000-08-23     Charlton           4
...          ...          ...         ...
7478  2020-03-07      Watford           7
7479  2020-03-07     West Ham           7
7480  2020-03-08      Everton           7
7481  2020-03-08     Man City          18
7482  2020-03-09  Aston Villa          22

[7483 rows x 3 columns]

In [149]:
eli3 = pd.merge(eli1,eli2.groupby(['Date','AwayTeam'])['menha_date'].min().reset_index(),on=['Date','AwayTeam'])

In [150]:
eli3= eli3.loc[eli3['menha_date_x']==eli3['menha_date_y']]
eli3.tail()

,Date,HomeTeam,AwayTeam,Final_Home_goals,Final_Away_goals,Half_Time_Home_Goals,Half_Time_Away_Goals,Half_Time_Result,Crowd_Attendance,Referee,Home_Shots,Away_Shots,Home_Shots_Target,Away_Shots_Target,Home_Woodwork,Away_Woodwork,Home_Corners,Away_Corners,Home_Fouls,Away_Fouls,Home_Offsides,Away_Offsides,Home_Yellow_Cards,Away_Yellow_Cards,Home_Red_Cards,Away_Red_Cards,Home_Bookings_Points,Away_Bookings_Points,Final_result,Home_score,Away_score,HomeTeam_6Home_of_away_median,Date_6Home_of_away_median,Final_Home_goals_6Home_of_away_median,Final_Away_goals_6Home_of_away_median,Half_Time_Home_Goals_6Home_of_away_median,Half_Time_Away_Goals_6Home_of_away_median,Half_Time_Result_6Home_of_away_median,Crowd_Attendance_6Home_of_away_median,Home_Shots_6Home_of_away_median,Away_Shots_6Home_of_away_median,Home_Shots_Target_6Home_of_away_median,Away_Shots_Target_6Home_of_away_median,Home_Woodwork_6Home_of_away_median,Away_Woodwork_6Home_of_away_median,Home_Corners_6Home_of_away_median,Away_Corners_6Home_of_away_median,Home_Fouls_6Home_of_away_median,Away_Fouls_6Home_of_away_median,Home_Offsides_6Home_of_away_median,Away_Offsides_6Home_of_away_median,Home_Yellow_Cards_6Home_of_away_median,Away_Yellow_Cards_6Home_of_away_median,Home_Red_Cards_6Home_of_away_median,Away_Red_Cards_6Home_of_away_median,Home_Bookings_Points_6Home_of_away_median,Away_Bookings_Points_6Home_of_away_median,Final_result_6Home_of_away_median,Home_score_6Home_of_away_median,Away_score_6Home_of_away_median,menha_date_x,menha_date_y
1928039,2020-03-07,Sheffield United,Norwich,1.0,0.0,1.0,0.0,1,NaN,S Hooper,10.0,12.0,4.0,5.0,NaN,NaN,10.0,5.0,12.0,8.0,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,1.0,3.0,0.0,Norwich,2020-02-28,1.0,1.0,1.0,0.0,1.0,NaN,12.0,14.5,4.5,4.0,NaN,NaN,3.5,6.5,11.0,10.5,NaN,NaN,2.0,2.0,0.0,0.0,NaN,NaN,2.0,1.0,1.0,8,8
1928414,2020-03-07,Burnley,Tottenham,1.0,1.0,1.0,0.0,1,NaN,J Moss,21.0,13.0,8.0,2.0,NaN,NaN,3.0,5.0,16.0,11.0,NaN,NaN,5.0,4.0,0.0,0.0,NaN,NaN,2.0,1.0,1.0,Tottenham,2020-03-01,2.0,1.0,0.0,1.0,2.5,NaN,12.0,13.0,3.5,4.5,NaN,NaN,4.0,4.0,9.5,10.0,NaN,NaN,2.5,2.0,0.0,0.0,NaN,NaN,2.0,1.5,1.5,6,6
1928789,2020-03-08,Chelsea,Everton,4.0,0.0,2.0,0.0,1,NaN,K Friend,17.0,3.0,11.0,1.0,NaN,NaN,6.0,1.0,8.0,10.0,NaN,NaN,1.0,2.0,0.0,0.0,NaN,NaN,1.0,3.0,0.0,Everton,2020-03-01,1.0,0.5,1.0,0.0,1.5,NaN,15.0,8.5,5.5,2.0,NaN,NaN,5.5,4.0,11.0,11.0,NaN,NaN,1.5,1.0,0.0,0.0,NaN,NaN,1.5,2.0,0.5,7,7
1929144,2020-03-08,Man United,Man City,2.0,0.0,1.0,0.0,1,NaN,M Dean,12.0,7.0,6.0,2.0,NaN,NaN,2.0,11.0,11.0,9.0,NaN,NaN,2.0,4.0,0.0,0.0,NaN,NaN,1.0,3.0,0.0,Man City,2020-02-19,2.0,1.0,0.0,0.5,2.0,NaN,21.0,6.0,6.5,2.0,NaN,NaN,7.0,2.5,9.5,8.0,NaN,NaN,1.0,2.0,0.0,0.0,NaN,NaN,1.0,3.0,0.0,18,18
1929461,2020-03-09,Leicester,Aston Villa,4.0,0.0,1.0,0.0,1,NaN,M Oliver,15.0,4.0,7.0,1.0,NaN,NaN,9.0,0.0,15.0,12.0,NaN,NaN,2.0,1.0,0.0,0.0,NaN,NaN,1.0,3.0,0.0,Aston Villa,2020-02-16,1.0,3.0,0.0,2.0,3.0,NaN,15.5,19.5,3.0,8.0,NaN,NaN,6.5,5.0,13.5,13.5,NaN,NaN,2.0,1.5,0.0,0.0,NaN,NaN,3.0,0.0,3.0,22,22

In [151]:
col= eli3.loc[:,'Date_6Home_of_away_median':'menha_date_x'].columns

In [152]:
list(col)

['Date_6Home_of_away_median',
 'Final_Home_goals_6Home_of_away_median',
 'Final_Away_goals_6Home_of_away_median',
 'Half_Time_Home_Goals_6Home_of_away_median',
 'Half_Time_Away_Goals_6Home_of_away_median',
 'Half_Time_Result_6Home_of_away_median',
 'Crowd_Attendance_6Home_of_away_median',
 'Home_Shots_6Home_of_away_median',
 'Away_Shots_6Home_of_away_median',
 'Home_Shots_Target_6Home_of_away_median',
 'Away_Shots_Target_6Home_of_away_median',
 'Home_Woodwork_6Home_of_away_median',
 'Away_Woodwork_6Home_of_away_median',
 'Home_Corners_6Home_of_away_median',
 'Away_Corners_6Home_of_away_median',
 'Home_Fouls_6Home_of_away_median',
 'Away_Fouls_6Home_of_away_median',
 'Home_Offsides_6Home_of_away_median',
 'Away_Offsides_6Home_of_away_median',
 'Home_Yellow_Cards_6Home_of_away_median',
 'Away_Yellow_Cards_6Home_of_away_median',
 'Home_Red_Cards_6Home_of_away_median',
 'Away_Red_Cards_6Home_of_away_median',
 'Home_Bookings_Points_6Home_of_away_median',
 'Away_Bookings_Points_6Home_of_away_median',
 'Final_result_6Home_of_away_median',
 'Home_score_6Home_of_away_median',
 'Away_score_6Home_of_away_median',
 'menha_date_x']

In [153]:
['Date','AwayTeam']+ list(col)

['Date',
 'AwayTeam',
 'Date_6Home_of_away_median',
 'Final_Home_goals_6Home_of_away_median',
 'Final_Away_goals_6Home_of_away_median',
 'Half_Time_Home_Goals_6Home_of_away_median',
 'Half_Time_Away_Goals_6Home_of_away_median',
 'Half_Time_Result_6Home_of_away_median',
 'Crowd_Attendance_6Home_of_away_median',
 'Home_Shots_6Home_of_away_median',
 'Away_Shots_6Home_of_away_median',
 'Home_Shots_Target_6Home_of_away_median',
 'Away_Shots_Target_6Home_of_away_median',
 'Home_Woodwork_6Home_of_away_median',
 'Away_Woodwork_6Home_of_away_median',
 'Home_Corners_6Home_of_away_median',
 'Away_Corners_6Home_of_away_median',
 'Home_Fouls_6Home_of_away_median',
 'Away_Fouls_6Home_of_away_median',
 'Home_Offsides_6Home_of_away_median',
 'Away_Offsides_6Home_of_away_median',
 'Home_Yellow_Cards_6Home_of_away_median',
 'Away_Yellow_Cards_6Home_of_away_median',
 'Home_Red_Cards_6Home_of_away_median',
 'Away_Red_Cards_6Home_of_away_median',
 'Home_Bookings_Points_6Home_of_away_median',
 'Away_Bookings_Points_6Home_of_away_median',
 'Final_result_6Home_of_away_median',
 'Home_score_6Home_of_away_median',
 'Away_score_6Home_of_away_median',
 'menha_date_x']

In [154]:
eli3= eli3.loc[:,['Date','AwayTeam']+ list(col)]

In [155]:
eli3.head(1)

,Date,AwayTeam,Date_6Home_of_away_median,Final_Home_goals_6Home_of_away_median,Final_Away_goals_6Home_of_away_median,Half_Time_Home_Goals_6Home_of_away_median,Half_Time_Away_Goals_6Home_of_away_median,Half_Time_Result_6Home_of_away_median,Crowd_Attendance_6Home_of_away_median,Home_Shots_6Home_of_away_median,Away_Shots_6Home_of_away_median,Home_Shots_Target_6Home_of_away_median,Away_Shots_Target_6Home_of_away_median,Home_Woodwork_6Home_of_away_median,Away_Woodwork_6Home_of_away_median,Home_Corners_6Home_of_away_median,Away_Corners_6Home_of_away_median,Home_Fouls_6Home_of_away_median,Away_Fouls_6Home_of_away_median,Home_Offsides_6Home_of_away_median,Away_Offsides_6Home_of_away_median,Home_Yellow_Cards_6Home_of_away_median,Away_Yellow_Cards_6Home_of_away_median,Home_Red_Cards_6Home_of_away_median,Away_Red_Cards_6Home_of_away_median,Home_Bookings_Points_6Home_of_away_median,Away_Bookings_Points_6Home_of_away_median,Final_result_6Home_of_away_median,Home_score_6Home_of_away_median,Away_score_6Home_of_away_median,menha_date_x
0,2000-08-21,Liverpool,2000-08-19,1.0,0.0,0.0,0.0,2.0,44183.0,16.0,3.0,10.0,2.0,0.0,0.0,6.0,1.0,8.0,8.0,5.0,0.0,1.0,1.0,0.0,0.0,10.0,10.0,1.0,3.0,0.0,2

In [156]:
eli3 = eli3.rename(columns = {'menha_date_x':'menha_date_6Home_of_away_median'})

In [157]:
# Rolling (mean) df2 on 'HomeTeam' and merge with df2 only on "hometeam" without date
bah1= pd.merge(df2, df2.set_index('Date').groupby(['HomeTeam']).rolling(6, min_periods=1).mean().reset_index(),  how='left', suffixes=['','_6Home_of_away_mean'], left_on=['AwayTeam'],right_on=['HomeTeam'])

In [158]:
bah1['menha_date']= (pd.to_datetime(bah1['Date'])-pd.to_datetime(bah1['Date_6Home_of_away_mean'])).dt.days

In [159]:
filt= bah1['menha_date']>0
bah2 = bah1.loc[filt]

In [160]:
bah2.groupby(['Date','AwayTeam'])['menha_date'].min().reset_index()

            Date     AwayTeam  menha_date
0     2000-08-21    Liverpool           2
1     2000-08-22      Chelsea           3
2     2000-08-22   Man United           2
3     2000-08-22    Tottenham           3
4     2000-08-23     Charlton           4
...          ...          ...         ...
7478  2020-03-07      Watford           7
7479  2020-03-07     West Ham           7
7480  2020-03-08      Everton           7
7481  2020-03-08     Man City          18
7482  2020-03-09  Aston Villa          22

[7483 rows x 3 columns]

In [161]:
bah3 = pd.merge(bah1,bah2.groupby(['Date','AwayTeam'])['menha_date'].min().reset_index(),on=['Date','AwayTeam'])

In [162]:
bah3 = bah3.loc[bah3['menha_date_x'] == bah3['menha_date_y']]

In [163]:
bah3[['Date','Date_6Home_of_away_mean','menha_date_y','menha_date_x']]

               Date Date_6Home_of_away_mean  menha_date_y  menha_date_x
0        2000-08-21              2000-08-19             2             2
376      2000-08-22              2000-08-20             2             2
752      2000-08-22              2000-08-19             3             3
1127     2000-08-22              2000-08-19             3             3
1503     2000-08-23              2000-08-19             4             4
...             ...                     ...           ...           ...
1928039  2020-03-07              2020-02-28             8             8
1928414  2020-03-07              2020-03-01             6             6
1928789  2020-03-08              2020-03-01             7             7
1929144  2020-03-08              2020-02-19            18            18
1929461  2020-03-09              2020-02-16            22            22

[7483 rows x 4 columns]

In [164]:
col= bah3.loc[:,'Date_6Home_of_away_mean':'menha_date_x'].columns

In [165]:
list(col)

['Date_6Home_of_away_mean',
 'Final_Home_goals_6Home_of_away_mean',
 'Final_Away_goals_6Home_of_away_mean',
 'Half_Time_Home_Goals_6Home_of_away_mean',
 'Half_Time_Away_Goals_6Home_of_away_mean',
 'Half_Time_Result_6Home_of_away_mean',
 'Crowd_Attendance_6Home_of_away_mean',
 'Home_Shots_6Home_of_away_mean',
 'Away_Shots_6Home_of_away_mean',
 'Home_Shots_Target_6Home_of_away_mean',
 'Away_Shots_Target_6Home_of_away_mean',
 'Home_Woodwork_6Home_of_away_mean',
 'Away_Woodwork_6Home_of_away_mean',
 'Home_Corners_6Home_of_away_mean',
 'Away_Corners_6Home_of_away_mean',
 'Home_Fouls_6Home_of_away_mean',
 'Away_Fouls_6Home_of_away_mean',
 'Home_Offsides_6Home_of_away_mean',
 'Away_Offsides_6Home_of_away_mean',
 'Home_Yellow_Cards_6Home_of_away_mean',
 'Away_Yellow_Cards_6Home_of_away_mean',
 'Home_Red_Cards_6Home_of_away_mean',
 'Away_Red_Cards_6Home_of_away_mean',
 'Home_Bookings_Points_6Home_of_away_mean',
 'Away_Bookings_Points_6Home_of_away_mean',
 'Final_result_6Home_of_away_mean',
 'Home_score_6Home_of_away_mean',
 'Away_score_6Home_of_away_mean',
 'menha_date_x']

In [166]:
['Date','AwayTeam']+ list(col)

['Date',
 'AwayTeam',
 'Date_6Home_of_away_mean',
 'Final_Home_goals_6Home_of_away_mean',
 'Final_Away_goals_6Home_of_away_mean',
 'Half_Time_Home_Goals_6Home_of_away_mean',
 'Half_Time_Away_Goals_6Home_of_away_mean',
 'Half_Time_Result_6Home_of_away_mean',
 'Crowd_Attendance_6Home_of_away_mean',
 'Home_Shots_6Home_of_away_mean',
 'Away_Shots_6Home_of_away_mean',
 'Home_Shots_Target_6Home_of_away_mean',
 'Away_Shots_Target_6Home_of_away_mean',
 'Home_Woodwork_6Home_of_away_mean',
 'Away_Woodwork_6Home_of_away_mean',
 'Home_Corners_6Home_of_away_mean',
 'Away_Corners_6Home_of_away_mean',
 'Home_Fouls_6Home_of_away_mean',
 'Away_Fouls_6Home_of_away_mean',
 'Home_Offsides_6Home_of_away_mean',
 'Away_Offsides_6Home_of_away_mean',
 'Home_Yellow_Cards_6Home_of_away_mean',
 'Away_Yellow_Cards_6Home_of_away_mean',
 'Home_Red_Cards_6Home_of_away_mean',
 'Away_Red_Cards_6Home_of_away_mean',
 'Home_Bookings_Points_6Home_of_away_mean',
 'Away_Bookings_Points_6Home_of_away_mean',
 'Final_result_6Home_of_away_mean',
 'Home_score_6Home_of_away_mean',
 'Away_score_6Home_of_away_mean',
 'menha_date_x']

In [167]:
bah3= bah3.loc[:,['Date','AwayTeam']+ list(col)]

In [168]:
bah3 = bah3.rename(columns = {'menha_date_x':'menha_date_6Home_of_away_mean'})

In [169]:
df_f_1= pd.merge(erf3, eli3, on=['AwayTeam','Date'])

In [170]:
df_6Home_of_away= pd.merge(df_f_1, bah3, on=['AwayTeam','Date'])

In [171]:
df_6Home_of_away.head(1)

,Date,AwayTeam,Date_6Home_of_away_sum,Final_Home_goals_6Home_of_away_sum,Final_Away_goals_6Home_of_away_sum,Half_Time_Home_Goals_6Home_of_away_sum,Half_Time_Away_Goals_6Home_of_away_sum,Half_Time_Result_6Home_of_away_sum,Crowd_Attendance_6Home_of_away_sum,Home_Shots_6Home_of_away_sum,Away_Shots_6Home_of_away_sum,Home_Shots_Target_6Home_of_away_sum,Away_Shots_Target_6Home_of_away_sum,Home_Woodwork_6Home_of_away_sum,Away_Woodwork_6Home_of_away_sum,Home_Corners_6Home_of_away_sum,Away_Corners_6Home_of_away_sum,Home_Fouls_6Home_of_away_sum,Away_Fouls_6Home_of_away_sum,Home_Offsides_6Home_of_away_sum,Away_Offsides_6Home_of_away_sum,Home_Yellow_Cards_6Home_of_away_sum,Away_Yellow_Cards_6Home_of_away_sum,Home_Red_Cards_6Home_of_away_sum,Away_Red_Cards_6Home_of_away_sum,Home_Bookings_Points_6Home_of_away_sum,Away_Bookings_Points_6Home_of_away_sum,Final_result_6Home_of_away_sum,Home_score_6Home_of_away_sum,Away_score_6Home_of_away_sum,menha_date_6Home_of_away_sum,Date_6Home_of_away_median,Final_Home_goals_6Home_of_away_median,Final_Away_goals_6Home_of_away_median,Half_Time_Home_Goals_6Home_of_away_median,Half_Time_Away_Goals_6Home_of_away_median,Half_Time_Result_6Home_of_away_median,Crowd_Attendance_6Home_of_away_median,Home_Shots_6Home_of_away_median,Away_Shots_6Home_of_away_median,Home_Shots_Target_6Home_of_away_median,Away_Shots_Target_6Home_of_away_median,Home_Woodwork_6Home_of_away_median,Away_Woodwork_6Home_of_away_median,Home_Corners_6Home_of_away_median,Away_Corners_6Home_of_away_median,Home_Fouls_6Home_of_away_median,Away_Fouls_6Home_of_away_median,Home_Offsides_6Home_of_away_median,Away_Offsides_6Home_of_away_median,Home_Yellow_Cards_6Home_of_away_median,Away_Yellow_Cards_6Home_of_away_median,Home_Red_Cards_6Home_of_away_median,Away_Red_Cards_6Home_of_away_median,Home_Bookings_Points_6Home_of_away_median,Away_Bookings_Points_6Home_of_away_median,Final_result_6Home_of_away_median,Home_score_6Home_of_away_median,Away_score_6Home_of_away_median,menha_date_6Home_of_away_median,Date_6Home_of_away_mean,Final_Home_goals_6Home_of_away_mean,Final_Away_goals_6Home_of_away_mean,Half_Time_Home_Goals_6Home_of_away_mean,Half_Time_Away_Goals_6Home_of_away_mean,Half_Time_Result_6Home_of_away_mean,Crowd_Attendance_6Home_of_away_mean,Home_Shots_6Home_of_away_mean,Away_Shots_6Home_of_away_mean,Home_Shots_Target_6Home_of_away_mean,Away_Shots_Target_6Home_of_away_mean,Home_Woodwork_6Home_of_away_mean,Away_Woodwork_6Home_of_away_mean,Home_Corners_6Home_of_away_mean,Away_Corners_6Home_of_away_mean,Home_Fouls_6Home_of_away_mean,Away_Fouls_6Home_of_away_mean,Home_Offsides_6Home_of_away_mean,Away_Offsides_6Home_of_away_mean,Home_Yellow_Cards_6Home_of_away_mean,Away_Yellow_Cards_6Home_of_away_mean,Home_Red_Cards_6Home_of_away_mean,Away_Red_Cards_6Home_of_away_mean,Home_Bookings_Points_6Home_of_away_mean,Away_Bookings_Points_6Home_of_away_mean,Final_result_6Home_of_away_mean,Home_score_6Home_of_away_mean,Away_score_6Home_of_away_mean,menha_date_6Home_of_away_mean
0,2000-08-21,Liverpool,2000-08-19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2000-08-19,1.0,0.0,0.0,0.0,2.0,44183.0,16.0,3.0,10.0,2.0,0.0,0.0,6.0,1.0,8.0,8.0,5.0,0.0,1.0,1.0,0.0,0.0,10.0,10.0,1.0,3.0,0.0,2,2000-08-19,1.0,0.0,0.0,0.0,2.0,44183.0,16.0,3.0,10.0,2.0,0.0,0.0,6.0,1.0,8.0,8.0,5.0,0.0,1.0,1.0,0.0,0.0,10.0,10.0,1.0,3.0,0.0,2

In [172]:
df_6Home_of_away.shape

(7483, 89)

In [173]:
df_6Away_of_home.head(1)

,Date_6Away_of_home_sum,Final_Home_goals_6Away_of_home_sum,Final_Away_goals_6Away_of_home_sum,Half_Time_Home_Goals_6Away_of_home_sum,Half_Time_Away_Goals_6Away_of_home_sum,Half_Time_Result_6Away_of_home_sum,Crowd_Attendance_6Away_of_home_sum,Home_Shots_6Away_of_home_sum,Away_Shots_6Away_of_home_sum,Home_Shots_Target_6Away_of_home_sum,Away_Shots_Target_6Away_of_home_sum,Home_Woodwork_6Away_of_home_sum,Away_Woodwork_6Away_of_home_sum,Home_Corners_6Away_of_home_sum,Away_Corners_6Away_of_home_sum,Home_Fouls_6Away_of_home_sum,Away_Fouls_6Away_of_home_sum,Home_Offsides_6Away_of_home_sum,Away_Offsides_6Away_of_home_sum,Home_Yellow_Cards_6Away_of_home_sum,Away_Yellow_Cards_6Away_of_home_sum,Home_Red_Cards_6Away_of_home_sum,Away_Red_Cards_6Away_of_home_sum,Home_Bookings_Points_6Away_of_home_sum,Away_Bookings_Points_6Away_of_home_sum,Final_result_6Away_of_home_sum,Home_score_6Away_of_home_sum,Away_score_6Away_of_home_sum,menha_date_6Away_of_home_sum,Date,HomeTeam,Date_6Away_of_home_median,Final_Home_goals_6Away_of_home_median,Final_Away_goals_6Away_of_home_median,Half_Time_Home_Goals_6Away_of_home_median,Half_Time_Away_Goals_6Away_of_home_median,Half_Time_Result_6Away_of_home_median,Crowd_Attendance_6Away_of_home_median,Home_Shots_6Away_of_home_median,Away_Shots_6Away_of_home_median,Home_Shots_Target_6Away_of_home_median,Away_Shots_Target_6Away_of_home_median,Home_Woodwork_6Away_of_home_median,Away_Woodwork_6Away_of_home_median,Home_Corners_6Away_of_home_median,Away_Corners_6Away_of_home_median,Home_Fouls_6Away_of_home_median,Away_Fouls_6Away_of_home_median,Home_Offsides_6Away_of_home_median,Away_Offsides_6Away_of_home_median,Home_Yellow_Cards_6Away_of_home_median,Away_Yellow_Cards_6Away_of_home_median,Home_Red_Cards_6Away_of_home_median,Away_Red_Cards_6Away_of_home_median,Home_Bookings_Points_6Away_of_home_median,Away_Bookings_Points_6Away_of_home_median,Final_result_6Away_of_home_median,Home_score_6Away_of_home_median,Away_score_6Away_of_home_median,menha_date_6Away_of_home_median,Date_6Away_of_home_mean,Final_Home_goals_6Away_of_home_mean,Final_Away_goals_6Away_of_home_mean,Half_Time_Home_Goals_6Away_of_home_mean,Half_Time_Away_Goals_6Away_of_home_mean,Half_Time_Result_6Away_of_home_mean,Crowd_Attendance_6Away_of_home_mean,Home_Shots_6Away_of_home_mean,Away_Shots_6Away_of_home_mean,Home_Shots_Target_6Away_of_home_mean,Away_Shots_Target_6Away_of_home_mean,Home_Woodwork_6Away_of_home_mean,Away_Woodwork_6Away_of_home_mean,Home_Corners_6Away_of_home_mean,Away_Corners_6Away_of_home_mean,Home_Fouls_6Away_of_home_mean,Away_Fouls_6Away_of_home_mean,Home_Offsides_6Away_of_home_mean,Away_Offsides_6Away_of_home_mean,Home_Yellow_Cards_6Away_of_home_mean,Away_Yellow_Cards_6Away_of_home_mean,Home_Red_Cards_6Away_of_home_mean,Away_Red_Cards_6Away_of_home_mean,Home_Bookings_Points_6Away_of_home_mean,Away_Bookings_Points_6Away_of_home_mean,Final_result_6Away_of_home_mean,Home_score_6Away_of_home_mean,Away_score_6Away_of_home_mean,menha_date_6Away_of_home_mean
0,2000-08-19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2000-08-21,Arsenal,2000-08-19,1.0,0.0,0.0,0.0,2.0,46346.0,8.0,14.0,2.0,7.0,0.0,0.0,2.0,9.0,10.0,21.0,2.0,3.0,3.0,1.0,0.0,1.0,30.0,35.0,1.0,3.0,0.0,2,2000-08-19,1.0,0.0,0.0,0.0,2.0,46346.0,8.0,14.0,2.0,7.0,0.0,0.0,2.0,9.0,10.0,21.0,2.0,3.0,3.0,1.0,0.0,1.0,30.0,35.0,1.0,3.0,0.0,2

In [174]:
df_final.head(1)

,Date,HomeTeam,AwayTeam,Final_Home_goals,Final_Away_goals,Half_Time_Home_Goals,Half_Time_Away_Goals,Half_Time_Result,Crowd_Attendance,Referee,Home_Shots,Away_Shots,Home_Shots_Target,Away_Shots_Target,Home_Woodwork,Away_Woodwork,Home_Corners,Away_Corners,Home_Fouls,Away_Fouls,Home_Offsides,Away_Offsides,Home_Yellow_Cards,Away_Yellow_Cards,Home_Red_Cards,Away_Red_Cards,Home_Bookings_Points,Away_Bookings_Points,Final_result,Home_score,Away_score,Final_Home_goals_HomeTeam_sum_6,Final_Away_goals_HomeTeam_sum_6,Half_Time_Home_Goals_HomeTeam_sum_6,Half_Time_Away_Goals_HomeTeam_sum_6,Half_Time_Result_HomeTeam_sum_6,Crowd_Attendance_HomeTeam_sum_6,Home_Shots_HomeTeam_sum_6,Away_Shots_HomeTeam_sum_6,Home_Shots_Target_HomeTeam_sum_6,Away_Shots_Target_HomeTeam_sum_6,Home_Woodwork_HomeTeam_sum_6,Away_Woodwork_HomeTeam_sum_6,Home_Corners_HomeTeam_sum_6,Away_Corners_HomeTeam_sum_6,Home_Fouls_HomeTeam_sum_6,Away_Fouls_HomeTeam_sum_6,Home_Offsides_HomeTeam_sum_6,Away_Offsides_HomeTeam_sum_6,Home_Yellow_Cards_HomeTeam_sum_6,Away_Yellow_Cards_HomeTeam_sum_6,Home_Red_Cards_HomeTeam_sum_6,Away_Red_Cards_HomeTeam_sum_6,Home_Bookings_Points_HomeTeam_sum_6,Away_Bookings_Points_HomeTeam_sum_6,Final_result_HomeTeam_sum_6,Home_score_HomeTeam_sum_6,Away_score_HomeTeam_sum_6,Final_Home_goals_AwayTeam_sum_6,Final_Away_goals_AwayTeam_sum_6,Half_Time_Home_Goals_AwayTeam_sum_6,Half_Time_Away_Goals_AwayTeam_sum_6,Half_Time_Result_AwayTeam_sum_6,Crowd_Attendance_AwayTeam_sum_6,Home_Shots_AwayTeam_sum_6,Away_Shots_AwayTeam_sum_6,Home_Shots_Target_AwayTeam_sum_6,Away_Shots_Target_AwayTeam_sum_6,Home_Woodwork_AwayTeam_sum_6,Away_Woodwork_AwayTeam_sum_6,Home_Corners_AwayTeam_sum_6,Away_Corners_AwayTeam_sum_6,Home_Fouls_AwayTeam_sum_6,Away_Fouls_AwayTeam_sum_6,Home_Offsides_AwayTeam_sum_6,Away_Offsides_AwayTeam_sum_6,Home_Yellow_Cards_AwayTeam_sum_6,Away_Yellow_Cards_AwayTeam_sum_6,Home_Red_Cards_AwayTeam_sum_6,Away_Red_Cards_AwayTeam_sum_6,Home_Bookings_Points_AwayTeam_sum_6,Away_Bookings_Points_AwayTeam_sum_6,Final_result_AwayTeam_sum_6,Home_score_AwayTeam_sum_6,Away_score_AwayTeam_sum_6,Final_Home_goals_HomeTeam_median_6,Final_Away_goals_HomeTeam_median_6,Half_Time_Home_Goals_HomeTeam_median_6,Half_Time_Away_Goals_HomeTeam_median_6,Half_Time_Result_HomeTeam_median_6,Crowd_Attendance_HomeTeam_median_6,Home_Shots_HomeTeam_median_6,Away_Shots_HomeTeam_median_6,Home_Shots_Target_HomeTeam_median_6,Away_Shots_Target_HomeTeam_median_6,Home_Woodwork_HomeTeam_median_6,Away_Woodwork_HomeTeam_median_6,Home_Corners_HomeTeam_median_6,Away_Corners_HomeTeam_median_6,Home_Fouls_HomeTeam_median_6,Away_Fouls_HomeTeam_median_6,Home_Offsides_HomeTeam_median_6,Away_Offsides_HomeTeam_median_6,Home_Yellow_Cards_HomeTeam_median_6,Away_Yellow_Cards_HomeTeam_median_6,Home_Red_Cards_HomeTeam_median_6,Away_Red_Cards_HomeTeam_median_6,Home_Bookings_Points_HomeTeam_median_6,Away_Bookings_Points_HomeTeam_median_6,Final_result_HomeTeam_median_6,Home_score_HomeTeam_median_6,Away_score_HomeTeam_median_6,Final_Home_goals_AwayTeam_median_6,Final_Away_goals_AwayTeam_median_6,Half_Time_Home_Goals_AwayTeam_median_6,Half_Time_Away_Goals_AwayTeam_median_6,Half_Time_Result_AwayTeam_median_6,Crowd_Attendance_AwayTeam_median_6,Home_Shots_AwayTeam_median_6,Away_Shots_AwayTeam_median_6,Home_Shots_Target_AwayTeam_median_6,Away_Shots_Target_AwayTeam_median_6,Home_Woodwork_AwayTeam_median_6,Away_Woodwork_AwayTeam_median_6,Home_Corners_AwayTeam_median_6,Away_Corners_AwayTeam_median_6,Home_Fouls_AwayTeam_median_6,Away_Fouls_AwayTeam_median_6,Home_Offsides_AwayTeam_median_6,Away_Offsides_AwayTeam_median_6,Home_Yellow_Cards_AwayTeam_median_6,Away_Yellow_Cards_AwayTeam_median_6,Home_Red_Cards_AwayTeam_median_6,Away_Red_Cards_AwayTeam_median_6,Home_Bookings_Points_AwayTeam_median_6,Away_Bookings_Points_AwayTeam_median_6,Final_result_AwayTeam_median_6,Home_score_AwayTeam_median_6,Away_score_AwayTeam_median_6,Final_Home_goals_HomeTeam_average_6,Final_Away_goals_HomeTeam_average_6,Half_Time_Home_Goals_HomeTeam_average_6,Half_Time_Away_Goals_HomeTeam_average_6,Half_Time_Result_HomeTeam_average_6,Crowd_Attendance_HomeTeam_average_6,Home_Shots_HomeTeam_average_6,Away_Shots_HomeTeam_average_6,Home_Shots_Target_HomeTeam_average_6,Away_Shots_Target_HomeTeam_average_6,Home_Woodwork_HomeTeam_average_6,Away_Woodwork_HomeTeam_average_6,Home_Corners_HomeTeam_average_6,Away_Corners_HomeTeam_average_6,Home_Fouls_HomeTeam_average_6,Away_Fouls_HomeTeam_average_6,Home_Offsides_HomeTeam_average_6,Away_Offsides_HomeTeam_average_6,Home_Yellow_Cards_HomeTeam_average_6,Away_Yellow_Cards_HomeTeam_average_6,Home_Red_Cards_HomeTeam_average_6,Away_Red_Cards_HomeTeam_average_6,Home_Bookings_Points_HomeTeam_average_6,Away_Bookings_Points_HomeTeam_average_6,Final_result_HomeTeam_average_6,Home_score_HomeTeam_average_6,Away_score_HomeTeam_average_6,Final_Home_goals_AwayTeam_average_6,Final_Away_goals_AwayTeam_average_6,Half_Time_Home_Goals_AwayTeam_average_6,Half_Time_Away_Goals_AwayTeam_average_6,Half_Time_Result_AwayTeam_average_6,Crowd_Attendance_AwayTeam_average_6,Home_Shots_AwayTeam_average_6,Away_Shots_AwayTeam_average_6,Home_Shots_Target_AwayTeam_average_6,Away_Shots_Target_AwayTeam_average_6,Home_Woodwork_AwayTeam_average_6,Away_Woodwork_AwayTeam_average_6,Home_Corners_AwayTeam_average_6,Away_Corners_AwayTeam_average_6,Home_Fouls_AwayTeam_average_6,Away_Fouls_AwayTeam_average_6,Home_Offsides_AwayTeam_average_6,Away_Offsides_AwayTeam_average_6,Home_Yellow_Cards_AwayTeam_average_6,Away_Yellow_Cards_AwayTeam_average_6,Home_Red_Cards_AwayTeam_average_6,Away_Red_Cards_AwayTeam_average_6,Home_Bookings_Points_AwayTeam_average_6,Away_Bookings_Points_AwayTeam_average_6,Final_result_AwayTeam_average_6,Home_score_AwayTeam_average_6,Away_score_AwayTeam_average_6,Home_Shots_Home_AllGames_sum_6,Half_Time_Home_Goals_Home_AllGames_Average_6,Home_Offsides_Home_AllGames_Average_6,Final_Away_goals_Home_AllGames_sum_6,Final_Home_goals_Home_AllGames_sum_6,Half_Time_Away_Goals_Home_AllGames_Average_6,Home_Yellow_Cards_Home_AllGames_median_6,Home_Shots_Home_AllGames_median_6,Away_Fouls_Home_AllGames_Average_6,Away_Woodwork_Home_AllGames_Average_6,Away_Shots_Target_Home_AllGames_Average_6,Crowd_Attendance_Home_AllGames_Average_6,Away_Corners_Home_AllGames_median_6,Away_Bookings_Points_Home_AllGames_median_6,Home_Offsides_Home_AllGames_sum_6,Half_Time_Away_Goals_Home_AllGames_median_6,Away_Shots_Target_Home_AllGames_median_6,Final_Away_goals_Home_AllGames_median_6,Away_Shots_Target_Home_AllGames_sum_6,Away_Corners_Home_AllGames_sum_6,Away_Fouls_Home_AllGames_sum_6,Home_Corners_Home_AllGames_Average_6,Away_Shots_Home_AllGames_median_6,Away_Yellow_Cards_Home_AllGames_Average_6,Home_Woodwork_Home_AllGames_sum_6,Away_Fouls_Home_AllGames_median_6,Away_Red_Cards_Home_AllGames_median_6,Home_Yellow_Cards_Home_AllGames_Average_6,Crowd_Attendance_Home_AllGames_median_6,Home_Red_Cards_Home_AllGames_sum_6,Away_score_Home_AllGames_Average_6,Away_Woodwork_Home_AllGames_median_6,Away_Shots_Home_AllGames_Average_6,Home_Yellow_Cards_Home_AllGames_sum_6,Final_result_Home_AllGames_median_6,Home_Bookings_Points_Home_AllGames_Average_6,Half_Time_Result_Home_AllGames_median_6,Away_Woodwork_Home_AllGames_sum_6,Home_Bookings_Points_Home_AllGames_sum_6,Final_Home_goals_Home_AllGames_Average_6,Away_Offsides_Home_AllGames_median_6,Half_Time_Away_Goals_Home_AllGames_sum_6,Home_Fouls_Home_AllGames_sum_6,Final_result_Home_AllGames_Average_6,Away_Corners_Home_AllGames_Average_6,Home_score_Home_AllGames_median_6,Home_Red_Cards_Home_AllGames_Average_6,Half_Time_Home_Goals_Home_AllGames_sum_6,Away_Yellow_Cards_Home_AllGames_median_6,Away_Bookings_Points_Home_AllGames_sum_6,Away_Offsides_Home_AllGames_Average_6,Away_score_Home_AllGames_sum_6,Final_Away_goals_Home_AllGames_Average_6,Home_Bookings_Points_Home_AllGames_median_6,Home_Shots_Target_Home_AllGames_Average_6,Home_Woodwork_Home_AllGames_median_6,Half_Time_Result_Home_AllGames_sum_6,Home_Woodwork_Home_AllGames_Average_6,Home_Red_Cards_Home_AllGames_median_6,Home_score_Home_AllGames_sum_6,Home_Fouls_Home_AllGames_Average_6,Half_Time_Result_Home_AllGames_Average_6,Home_Shots_Target_Home_AllGames_median_6,Home_Corners_Home_AllGames_sum_6,Away_Yellow_Cards_Home_AllGames_sum_6,Final_result_Home_AllGames_sum_6,Home_Shots_Home_AllGames_Average_6,Half_Time_Home_Goals_Home_AllGames_median_6,Home_Fouls_Home_AllGames_median_6,Away_Shots_Home_AllGames_sum_6,Home_Shots_Target_Home_AllGames_sum_6,Away_Offsides_Home_AllGames_sum_6,Away_Bookings_Points_Home_AllGames_Average_6,Crowd_Attendance_Home_AllGames_sum_6,Home_Offsides_Home_AllGames_median_6,Away_Red_Cards_Home_AllGames_Average_6,Home_Corners_Home_AllGames_median_6,Away_Red_Cards_Home_AllGames_sum_6,Final_Home_goals_Home_AllGames_median_6,Away_score_Home_AllGames_median_6,Home_score_Home_AllGames_Average_6,Away_Corners_Away_AllGames_Average_6,Away_Shots_Away_AllGames_Average_6,Home_Corners_Away_AllGames_sum_6,Crowd_Attendance_Away_AllGames_median_6,Home_Offsides_Away_AllGames_Average_6,Home_Woodwork_Away_AllGames_Average_6,Away_Yellow_Cards_Away_AllGames_sum_6,Away_Fouls_Away_AllGames_Average_6,Away_Bookings_Points_Away_AllGames_median_6,Final_Home_goals_Away_AllGames_Average_6,Away_Yellow_Cards_Away_AllGames_Average_6,Away_Red_Cards_Away_AllGames_sum_6,Away_Offsides_Away_AllGames_sum_6,Crowd_Attendance_Away_AllGames_Average_6,Final_Away_goals_Away_AllGames_median_6,Away_Red_Cards_Away_AllGames_Average_6,Home_Bookings_Points_Away_AllGames_sum_6,Half_Time_Result_Away_AllGames_median_6,Home_Bookings_Points_Away_AllGames_median_6,Away_Corners_Away_AllGames_median_6,Home_Shots_Target_Away_AllGames_median_6,Home_Shots_Away_AllGames_sum_6,Home_Corners_Away_AllGames_Average_6,Away_Red_Cards_Away_AllGames_median_6,Home_score_Away_AllGames_Average_6,Away_Shots_Away_AllGames_sum_6,Home_Woodwork_Away_AllGames_sum_6,Home_Fouls_Away_AllGames_median_6,Home_Red_Cards_Away_AllGames_median_6,Half_Time_Home_Goals_Away_AllGames_sum_6,Away_Shots_Target_Away_AllGames_Average_6,Home_Red_Cards_Away_AllGames_sum_6,Final_Away_goals_Away_AllGames_Average_6,Home_Shots_Target_Away_AllGames_Average_6,Half_Time_Away_Goals_Away_AllGames_sum_6,Home_Yellow_Cards_Away_AllGames_sum_6,Home_Shots_Away_AllGames_median_6,Home_Yellow_Cards_Away_AllGames_median_6,Away_Offsides_Away_AllGames_Average_6,Away_Bookings_Points_Away_AllGames_sum_6,Final_result_Away_AllGames_Average_6,Home_score_Away_AllGames_sum_6,Away_Corners_Away_AllGames_sum_6,Away_Shots_Away_AllGames_median_6,Away_Fouls_Away_AllGames_median_6,Half_Time_Result_Away_AllGames_Average_6,Away_Woodwork_Away_AllGames_median_6,Away_Offsides_Away_AllGames_median_6,Home_Shots_Away_AllGames_Average_6,Away_Yellow_Cards_Away_AllGames_median_6,Away_score_Away_AllGames_sum_6,Away_Fouls_Away_AllGames_sum_6,Home_Shots_Target_Away_AllGames_sum_6,Half_Time_Away_Goals_Away_AllGames_median_6,Home_Bookings_Points_Away_AllGames_Average_6,Half_Time_Away_Goals_Away_AllGames_Average_6,Home_Fouls_Away_AllGames_sum_6,Away_score_Away_AllGames_Average_6,Final_Home_goals_Away_AllGames_median_6,Away_Woodwork_Away_AllGames_Average_6,Half_Time_Home_Goals_Away_AllGames_median_6,Final_Home_goals_Away_AllGames_sum_6,Final_result_Away_AllGames_sum_6,Final_result_Away_AllGames_median_6,Half_Time_Home_Goals_Away_AllGames_Average_6,Final_Away_goals_Away_AllGames_sum_6,Crowd_Attendance_Away_AllGames_sum_6,Home_Offsides_Away_AllGames_median_6,Home_Fouls_Away_AllGames_Average_6,Home_Red_Cards_Away_AllGames_Average_6,Home_Woodwork_Away_AllGames_median_6,Away_score_Away_AllGames_median_6,Half_Time_Result_Away_AllGames_sum_6,Away_Woodwork_Away_AllGames_sum_6,Home_Corners_Away_AllGames_median_6,Away_Bookings_Points_Away_AllGames_Average_6,Away_Shots_Target_Away_AllGames_median_6,Away_Shots_Target_Away_AllGames_sum_6,Home_Offsides_Away_AllGames_sum_6,Home_Yellow_Cards_Away_AllGames_Average_6,Home_score_Away_AllGames_median_6
0,2000-08-19,Charlton,Man City,4.0,0.0,2.0,0.0,1,20043.0,Rob Harris,17.0,8.0,14.0,4.0,2.0,1.0,6.0,6.0,13.0,12.0,8.0,6.0,1.0,2.0,0.0,0.0,10.0,20.0,1.0,3.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [175]:
df_naha= pd.merge(df_final, df_6Away_of_home, how='left', on=['Date','HomeTeam'])
df_naha

,Date,HomeTeam,AwayTeam,Final_Home_goals,Final_Away_goals,Half_Time_Home_Goals,Half_Time_Away_Goals,Half_Time_Result,Crowd_Attendance,Referee,Home_Shots,Away_Shots,Home_Shots_Target,Away_Shots_Target,Home_Woodwork,Away_Woodwork,Home_Corners,Away_Corners,Home_Fouls,Away_Fouls,Home_Offsides,Away_Offsides,Home_Yellow_Cards,Away_Yellow_Cards,Home_Red_Cards,Away_Red_Cards,Home_Bookings_Points,Away_Bookings_Points,Final_result,Home_score,Away_score,Final_Home_goals_HomeTeam_sum_6,Final_Away_goals_HomeTeam_sum_6,Half_Time_Home_Goals_HomeTeam_sum_6,Half_Time_Away_Goals_HomeTeam_sum_6,Half_Time_Result_HomeTeam_sum_6,Crowd_Attendance_HomeTeam_sum_6,Home_Shots_HomeTeam_sum_6,Away_Shots_HomeTeam_sum_6,Home_Shots_Target_HomeTeam_sum_6,Away_Shots_Target_HomeTeam_sum_6,Home_Woodwork_HomeTeam_sum_6,Away_Woodwork_HomeTeam_sum_6,Home_Corners_HomeTeam_sum_6,Away_Corners_HomeTeam_sum_6,Home_Fouls_HomeTeam_sum_6,Away_Fouls_HomeTeam_sum_6,Home_Offsides_HomeTeam_sum_6,Away_Offsides_HomeTeam_sum_6,Home_Yellow_Cards_HomeTeam_sum_6,Away_Yellow_Cards_HomeTeam_sum_6,Home_Red_Cards_HomeTeam_sum_6,Away_Red_Cards_HomeTeam_sum_6,Home_Bookings_Points_HomeTeam_sum_6,Away_Bookings_Points_HomeTeam_sum_6,Final_result_HomeTeam_sum_6,Home_score_HomeTeam_sum_6,Away_score_HomeTeam_sum_6,Final_Home_goals_AwayTeam_sum_6,Final_Away_goals_AwayTeam_sum_6,Half_Time_Home_Goals_AwayTeam_sum_6,Half_Time_Away_Goals_AwayTeam_sum_6,Half_Time_Result_AwayTeam_sum_6,Crowd_Attendance_AwayTeam_sum_6,Home_Shots_AwayTeam_sum_6,Away_Shots_AwayTeam_sum_6,Home_Shots_Target_AwayTeam_sum_6,Away_Shots_Target_AwayTeam_sum_6,Home_Woodwork_AwayTeam_sum_6,Away_Woodwork_AwayTeam_sum_6,Home_Corners_AwayTeam_sum_6,Away_Corners_AwayTeam_sum_6,Home_Fouls_AwayTeam_sum_6,Away_Fouls_AwayTeam_sum_6,Home_Offsides_AwayTeam_sum_6,Away_Offsides_AwayTeam_sum_6,Home_Yellow_Cards_AwayTeam_sum_6,Away_Yellow_Cards_AwayTeam_sum_6,Home_Red_Cards_AwayTeam_sum_6,Away_Red_Cards_AwayTeam_sum_6,Home_Bookings_Points_AwayTeam_sum_6,Away_Bookings_Points_AwayTeam_sum_6,Final_result_AwayTeam_sum_6,Home_score_AwayTeam_sum_6,Away_score_AwayTeam_sum_6,Final_Home_goals_HomeTeam_median_6,Final_Away_goals_HomeTeam_median_6,Half_Time_Home_Goals_HomeTeam_median_6,Half_Time_Away_Goals_HomeTeam_median_6,Half_Time_Result_HomeTeam_median_6,Crowd_Attendance_HomeTeam_median_6,Home_Shots_HomeTeam_median_6,Away_Shots_HomeTeam_median_6,Home_Shots_Target_HomeTeam_median_6,Away_Shots_Target_HomeTeam_median_6,Home_Woodwork_HomeTeam_median_6,Away_Woodwork_HomeTeam_median_6,Home_Corners_HomeTeam_median_6,Away_Corners_HomeTeam_median_6,Home_Fouls_HomeTeam_median_6,Away_Fouls_HomeTeam_median_6,Home_Offsides_HomeTeam_median_6,Away_Offsides_HomeTeam_median_6,Home_Yellow_Cards_HomeTeam_median_6,Away_Yellow_Cards_HomeTeam_median_6,Home_Red_Cards_HomeTeam_median_6,Away_Red_Cards_HomeTeam_median_6,Home_Bookings_Points_HomeTeam_median_6,Away_Bookings_Points_HomeTeam_median_6,Final_result_HomeTeam_median_6,Home_score_HomeTeam_median_6,Away_score_HomeTeam_median_6,Final_Home_goals_AwayTeam_median_6,Final_Away_goals_AwayTeam_median_6,Half_Time_Home_Goals_AwayTeam_median_6,Half_Time_Away_Goals_AwayTeam_median_6,Half_Time_Result_AwayTeam_median_6,Crowd_Attendance_AwayTeam_median_6,Home_Shots_AwayTeam_median_6,Away_Shots_AwayTeam_median_6,Home_Shots_Target_AwayTeam_median_6,Away_Shots_Target_AwayTeam_median_6,Home_Woodwork_AwayTeam_median_6,Away_Woodwork_AwayTeam_median_6,Home_Corners_AwayTeam_median_6,Away_Corners_AwayTeam_median_6,Home_Fouls_AwayTeam_median_6,Away_Fouls_AwayTeam_median_6,Home_Offsides_AwayTeam_median_6,Away_Offsides_AwayTeam_median_6,Home_Yellow_Cards_AwayTeam_median_6,Away_Yellow_Cards_AwayTeam_median_6,Home_Red_Cards_AwayTeam_median_6,Away_Red_Cards_AwayTeam_median_6,Home_Bookings_Points_AwayTeam_median_6,Away_Bookings_Points_AwayTeam_median_6,Final_result_AwayTeam_median_6,Home_score_AwayTeam_median_6,Away_score_AwayTeam_median_6,Final_Home_goals_HomeTeam_average_6,Final_Away_goals_HomeTeam_average_6,Half_Time_Home_Goals_HomeTeam_average_6,Half_Time_Away_Goals_HomeTeam_average_6,Half_Time_Result_HomeTeam_average_6,Crowd_Attendance_HomeTeam_average_6,Home_Shots_HomeTeam_average_6,Away_Shots_HomeTeam_average_6,Home_Shots_Target_HomeTeam_average_6,Away_Shots_Target_HomeTeam_average_6,Home_Woodwork_HomeTeam_average_6,Away_Woodwork_HomeTeam_average_6,Home_Corners_HomeTeam_average_6,Away_Corners_HomeTeam_average_6,Home_Fouls_HomeTeam_average_6,Away_Fouls_HomeTeam_average_6,Home_Offsides_HomeTeam_average_6,Away_Offsides_HomeTeam_average_6,Home_Yellow_Cards_HomeTeam_average_6,Away_Yellow_Cards_HomeTeam_average_6,Home_Red_Cards_HomeTeam_average_6,Away_Red_Cards_HomeTeam_average_6,Home_Bookings_Points_HomeTeam_average_6,Away_Bookings_Points_HomeTeam_average_6,Final_result_HomeTeam_average_6,Home_score_HomeTeam_average_6,Away_score_HomeTeam_average_6,Final_Home_goals_AwayTeam_average_6,Final_Away_goals_AwayTeam_average_6,Half_Time_Home_Goals_AwayTeam_average_6,Half_Time_Away_Goals_AwayTeam_average_6,Half_Time_Result_AwayTeam_average_6,Crowd_Attendance_AwayTeam_average_6,Home_Shots_AwayTeam_average_6,Away_Shots_AwayTeam_average_6,Home_Shots_Target_AwayTeam_average_6,Away_Shots_Target_AwayTeam_average_6,Home_Woodwork_AwayTeam_average_6,Away_Woodwork_AwayTeam_average_6,Home_Corners_AwayTeam_average_6,Away_Corners_AwayTeam_average_6,Home_Fouls_AwayTeam_average_6,Away_Fouls_AwayTeam_average_6,Home_Offsides_AwayTeam_average_6,Away_Offsides_AwayTeam_average_6,Home_Yellow_Cards_AwayTeam_average_6,Away_Yellow_Cards_AwayTeam_average_6,Home_Red_Cards_AwayTeam_average_6,Away_Red_Cards_AwayTeam_average_6,Home_Bookings_Points_AwayTeam_average_6,Away_Bookings_Points_AwayTeam_average_6,Final_result_AwayTeam_average_6,Home_score_AwayTeam_average_6,Away_score_AwayTeam_average_6,Home_Shots_Home_AllGames_sum_6,Half_Time_Home_Goals_Home_AllGames_Average_6,Home_Offsides_Home_AllGames_Average_6,Final_Away_goals_Home_AllGames_sum_6,Final_Home_goals_Home_AllGames_sum_6,Half_Time_Away_Goals_Home_AllGames_Average_6,Home_Yellow_Cards_Home_AllGames_median_6,Home_Shots_Home_AllGames_median_6,Away_Fouls_Home_AllGames_Average_6,Away_Woodwork_Home_AllGames_Average_6,Away_Shots_Target_Home_AllGames_Average_6,Crowd_Attendance_Home_AllGames_Average_6,Away_Corners_Home_AllGames_median_6,Away_Bookings_Points_Home_AllGames_median_6,Home_Offsides_Home_AllGames_sum_6,Half_Time_Away_Goals_Home_AllGames_median_6,Away_Shots_Target_Home_AllGames_median_6,Final_Away_goals_Home_AllGames_median_6,Away_Shots_Target_Home_AllGames_sum_6,Away_Corners_Home_AllGames_sum_6,Away_Fouls_Home_AllGames_sum_6,Home_Corners_Home_AllGames_Average_6,Away_Shots_Home_AllGames_median_6,Away_Yellow_Cards_Home_AllGames_Average_6,Home_Woodwork_Home_AllGames_sum_6,Away_Fouls_Home_AllGames_median_6,Away_Red_Cards_Home_AllGames_median_6,Home_Yellow_Cards_Home_AllGames_Average_6,Crowd_Attendance_Home_AllGames_median_6,Home_Red_Cards_Home_AllGames_sum_6,Away_score_Home_AllGames_Average_6,Away_Woodwork_Home_AllGames_median_6,Away_Shots_Home_AllGames_Average_6,Home_Yellow_Cards_Home_AllGames_sum_6,Final_result_Home_AllGames_median_6,Home_Bookings_Points_Home_AllGames_Average_6,Half_Time_Result_Home_AllGames_median_6,Away_Woodwork_Home_AllGames_sum_6,Home_Bookings_Points_Home_AllGames_sum_6,Final_Home_goals_Home_AllGames_Average_6,Away_Offsides_Home_AllGames_median_6,Half_Time_Away_Goals_Home_AllGames_sum_6,Home_Fouls_Home_AllGames_sum_6,Final_result_Home_AllGames_Average_6,Away_Corners_Home_AllGames_Average_6,Home_score_Home_AllGames_median_6,Home_Red_Cards_Home_AllGames_Average_6,Half_Time_Home_Goals_Home_AllGames_sum_6,Away_Yellow_Cards_Home_AllGames_median_6,Away_Bookings_Points_Home_AllGames_sum_6,Away_Offsides_Home_AllGames_Average_6,Away_score_Home_AllGames_sum_6,Final_Away_goals_Home_AllGames_Average_6,Home_Bookings_Points_Home_AllGames_median_6,Home_Shots_Target_Home_AllGames_Average_6,Home_Woodwork_Home_AllGames_median_6,Half_Time_Result_Home_AllGames_sum_6,Home_Woodwork_Home_AllGames_Average_6,Home_Red_Cards_Home_AllGames_median_6,Home_score_Home_AllGames_sum_6,Home_Fouls_Home_AllGames_Average_6,Half_Time_Result_Home_AllGames_Average_6,Home_Shots_Target_Home_AllGames_median_6,Home_Corners_Home_AllGames_sum_6,Away_Yellow_Cards_Home_AllGames_sum_6,Final_result_Home_AllGames_sum_6,Home_Shots_Home_AllGames_Average_6,Half_Time_Home_Goals_Home_AllGames_median_6,Home_Fouls_Home_AllGames_median_6,Away_Shots_Home_AllGames_sum_6,Home_Shots_Target_Home_AllGames_sum_6,Away_Offsides_Home_AllGames_sum_6,Away_Bookings_Points_Home_AllGames_Average_6,Crowd_Attendance_Home_AllGames_sum_6,Home_Offsides_Home_AllGames_median_6,Away_Red_Cards_Home_AllGames_Average_6,Home_Corners_Home_AllGames_median_6,Away_Red_Cards_Home_AllGames_sum_6,Final_Home_goals_Home_AllGames_median_6,Away_score_Home_AllGames_median_6,Home_score_Home_AllGames_Average_6,Away_Corners_Away_AllGames_Average_6,Away_Shots_Away_AllGames_Average_6,Home_Corners_Away_AllGames_sum_6,Crowd_Attendance_Away_AllGames_median_6,Home_Offsides_Away_AllGames_Average_6,Home_Woodwork_Away_AllGames_Average_6,Away_Yellow_Cards_Away_AllGames_sum_6,Away_Fouls_Away_AllGames_Average_6,Away_Bookings_Points_Away_AllGames_median_6,Final_Home_goals_Away_AllGames_Average_6,Away_Yellow_Cards_Away_AllGames_Average_6,Away_Red_Cards_Away_AllGames_sum_6,Away_Offsides_Away_AllGames_sum_6,Crowd_Attendance_Away_AllGames_Average_6,Final_Away_goals_Away_AllGames_median_6,Away_Red_Cards_Away_AllGames_Average_6,Home_Bookings_Points_Away_AllGames_sum_6,Half_Time_Result_Away_AllGames_median_6,Home_Bookings_Points_Away_AllGames_median_6,Away_Corners_Away_AllGames_median_6,Home_Shots_Target_Away_AllGames_median_6,Home_Shots_Away_AllGames_sum_6,Home_Corners_Away_AllGames_Average_6,Away_Red_Cards_Away_AllGames_median_6,Home_score_Away_AllGames_Average_6,Away_Shots_Away_AllGames_sum_6,Home_Woodwork_Away_AllGames_sum_6,Home_Fouls_Away_AllGames_median_6,Home_Red_Cards_Away_AllGames_median_6,Half_Time_Home_Goals_Away_AllGames_sum_6,Away_Shots_Target_Away_AllGames_Average_6,Home_Red_Cards_Away_AllGames_sum_6,Final_Away_goals_Away_AllGames_Average_6,Home_Shots_Target_Away_AllGames_Average_6,Half_Time_Away_Goals_Away_AllGames_sum_6,Home_Yellow_Cards_Away_AllGames_sum_6,Home_Shots_Away_AllGames_median_6,Home_Yellow_Cards_Away_AllGames_median_6,Away_Offsides_Away_AllGames_Average_6,Away_Bookings_Points_Away_AllGames_sum_6,Final_result_Away_AllGames_Average_6,Home_score_Away_AllGames_sum_6,Away_Corners_Away_AllGames_sum_6,Away_Shots_Away_AllGames_median_6,Away_Fouls_Away_AllGames_median_6,Half_Time_Result_Away_AllGames_Average_6,Away_Woodwork_Away_AllGames_median_6,Away_Offsides_Away_AllGames_median_6,Home_Shots_Away_AllGames_Average_6,Away_Yellow_Cards_Away_AllGames_median_6,Away_score_Away_AllGames_sum_6,Away_Fouls_Away_AllGames_sum_6,Home_Shots_Target_Away_AllGames_sum_6,Half_Time_Away_Goals_Away_AllGames_median_6,Home_Bookings_Points_Away_AllGames_Average_6,Half_Time_Away_Goals_Away_AllGames_Average_6,Home_Fouls_Away_AllGames_sum_6,Away_score_Away_AllGames_Average_6,Final_Home_goals_Away_AllGames_median_6,Away_Woodwork_Away_AllGames_Average_6,Half_Time_Home_Goals_Away_AllGames_median_6,Final_Home_goals_Away_AllGames_sum_6,Final_result_Away_AllGames_sum_6,Final_result_Away_AllGames_median_6,Half_Time_Home_Goals_Away_AllGames_Average_6,Final_Away_goals_Away_AllGames_sum_6,Crowd_Attendance_Away_AllGames_sum_6,Home_Offsides_Away_AllGames_median_6,Home_Fouls_Away_AllGames_Average_6,Home_Red_Cards_Away_AllGames_Average_6,Home_Woodwork_Away_AllGames_median_6,Away_score_Away_AllGames_median_6,Half_Time_Result_Away_AllGames_sum_6,Away_Woodwork_Away_AllGames_sum_6,Home_Corners_Away_AllGames_median_6,Away_Bookings_Points_Away_AllGames_Average_6,Away_Shots_Target_Away_AllGames_median_6,Away_Shots_Target_Away_AllGames_sum_6,Home_Offsides_Away_AllGames_sum_6,Home_Yellow_Cards_Away_AllGames_Average_6,Home_score_Away_AllGames_median_6,Date_6Away_of_home_sum,Final_Home_goals_6Away_of_home_sum,Final_Away_goals_6Away_of_home_sum,Half_Time_Home_Goals_6Away_of_home_sum,Half_Time_Away_Goals_6Away_of_home_sum,Half_Time_Result_6Away_of_home_sum,Crowd_Attendance_6Away_of_home_sum,Home_Shots_6Away_of_home_sum,Away_Shots_6Away_of_home_sum,Home_Shots_Target_6Away_of_home_sum,Away_Shots_Target_6Away_of_home_sum,Home_Woodwork_6Away_of_home_sum,Away_Woodwork_6Away_of_home_sum,Home_Corners_6Away_of_home_sum,Away_Corners_6Away_of_home_sum,Home_Fouls_6Away_of_home_sum,Away_Fouls_6Away_of_home_sum,Home_Offsides_6Away_of_home_sum,Away_Offsides_6Away_of_home_sum,Home_Yellow_Cards_6Away_of_home_sum,Away_Yellow_Cards_6Away_of_home_sum,Home_Red_Cards_6Away_of_home_sum,Away_Red_Cards_6Away_of_home_sum,Home_Bookings_Points_6Away_of_home_sum,Away_Bookings_Points_6Away_of_home_sum,Final_result_6Away_of_home_sum,Home_score_6Away_of_home_sum,Away_score_6Away_of_home_sum,menha_date_6Away_of_home_sum,Date_6Away_of_home_median,Final_Home_goals_6Away_of_home_median,Final_Away_goals_6Away_of_home_median,Half_Time_Home_Goals_6Away_of_home_median,Half_Time_Away_Goals_6Away_of_home_median,Half_Time_Result_6Away_of_home_median,Crowd_Attendance_6Away_of_home_median,Home_Shots_6Away_of_home_median,Away_Shots_6Away_of_home_median,Home_Shots_Target_6Away_of_home_median,Away_Shots_Target_6Away_of_home_median,Home_Woodwork_6Away_of_home_median,Away_Woodwork_6Away_of_home_median,Home_Corners_6Away_of_home_median,Away_Corners_6Away_of_home_median,Home_Fouls_6Away_of_home_median,Away_Fouls_6Away_of_home_median,Home_Offsides_6Away_of_home_median,Away_Offsides_6Away_of_home_median,Home_Yellow_Cards_6Away_of_home_median,Away_Yellow_Cards_6Away_of_home_median,Home_Red_Cards_6Away_of_home_median,Away_Red_Cards_6Away_of_home_median,Home_Bookings_Points_6Away_of_home_median,Away_Bookings_Points_6Away_of_home_median,Final_result_6Away_of_home_median,Home_score_6Away_of_home_median,Away_score_6Away_of_home_median,menha_date_6Away_of_home_median,Date_6Away_of_home_mean,Final_Home_goals_6Away_of_home_mean,Final_Away_goals_6Away_of_home_mean,Half_Time_Home_Goals_6Away_of_home_mean,Half_Time_Away_Goals_6Away_of_home_mean,Half_Time_Result_6Away_of_home_mean,Crowd_Attendance_6Away_of_home_mean,Home_Shots_6Away_of_home_mean,Away_Shots_6Away_of_home_mean,Home_Shots_Target_6Away_of_home_mean,Away_Shots_Target_6Away_of_home_mean,Home_Woodwork_6Away_of_home_mean,Away_Woodwork_6Away_of_home_mean,Home_Corners_6Away_of_home_mean,Away_Corners_6Away_of_home_mean,Home_Fouls_6Away_of_home_mean,Away_Fouls_6Away_of_home_mean,Home_Offsides_6Away_of_home_mean,Away_Offsides_6Away_of_home_mean,Home_Yellow_Cards_6Away_of_home_mean,Away_Yellow_Cards_6Away_of_home_mean,Home_Red_Cards_6Away_of_home_mean,Away_Red_Cards_6Away_of_home_mean,Home_Bookings_Points_6Away_of_home_mean,Away_Bookings_Points_6Away_of_home_mean,Final_result_6Away_of_home_mean,Home_score_6Away_of_home_mean,Away_score_6Away_of_home_mean,menha_date_6Away_of_home_mean
0,2000-08-19,Charlton,Man City,4.0,0.0,2.0,0.0,1,20043.0,Rob Harris,17.0,8.0,14.0,4.0,2.0,1.0,6.0,6.0,13.0,12.0,8.0,6.0,1.0,2.0,0.0,0.0,10.0,20.0,1.0,3.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2000-08-19,Chelsea,West Ham,4.0,2.0,1.0,0.0,1,34914.0,Graham Barber,17.0,12.0,10.0,5.0,1.0,0.0,7.0,7.0,19.0,14.0,2.0,3.0,1.0,2.0,0.0,0.0,10.0,20.0,1.0,3.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [176]:
df_naha.loc[df_naha['HomeTeam']=='Charlton'].head(7)

,Date,HomeTeam,AwayTeam,Final_Home_goals,Final_Away_goals,Half_Time_Home_Goals,Half_Time_Away_Goals,Half_Time_Result,Crowd_Attendance,Referee,Home_Shots,Away_Shots,Home_Shots_Target,Away_Shots_Target,Home_Woodwork,Away_Woodwork,Home_Corners,Away_Corners,Home_Fouls,Away_Fouls,Home_Offsides,Away_Offsides,Home_Yellow_Cards,Away_Yellow_Cards,Home_Red_Cards,Away_Red_Cards,Home_Bookings_Points,Away_Bookings_Points,Final_result,Home_score,Away_score,Final_Home_goals_HomeTeam_sum_6,Final_Away_goals_HomeTeam_sum_6,Half_Time_Home_Goals_HomeTeam_sum_6,Half_Time_Away_Goals_HomeTeam_sum_6,Half_Time_Result_HomeTeam_sum_6,Crowd_Attendance_HomeTeam_sum_6,Home_Shots_HomeTeam_sum_6,Away_Shots_HomeTeam_sum_6,Home_Shots_Target_HomeTeam_sum_6,Away_Shots_Target_HomeTeam_sum_6,Home_Woodwork_HomeTeam_sum_6,Away_Woodwork_HomeTeam_sum_6,Home_Corners_HomeTeam_sum_6,Away_Corners_HomeTeam_sum_6,Home_Fouls_HomeTeam_sum_6,Away_Fouls_HomeTeam_sum_6,Home_Offsides_HomeTeam_sum_6,Away_Offsides_HomeTeam_sum_6,Home_Yellow_Cards_HomeTeam_sum_6,Away_Yellow_Cards_HomeTeam_sum_6,Home_Red_Cards_HomeTeam_sum_6,Away_Red_Cards_HomeTeam_sum_6,Home_Bookings_Points_HomeTeam_sum_6,Away_Bookings_Points_HomeTeam_sum_6,Final_result_HomeTeam_sum_6,Home_score_HomeTeam_sum_6,Away_score_HomeTeam_sum_6,Final_Home_goals_AwayTeam_sum_6,Final_Away_goals_AwayTeam_sum_6,Half_Time_Home_Goals_AwayTeam_sum_6,Half_Time_Away_Goals_AwayTeam_sum_6,Half_Time_Result_AwayTeam_sum_6,Crowd_Attendance_AwayTeam_sum_6,Home_Shots_AwayTeam_sum_6,Away_Shots_AwayTeam_sum_6,Home_Shots_Target_AwayTeam_sum_6,Away_Shots_Target_AwayTeam_sum_6,Home_Woodwork_AwayTeam_sum_6,Away_Woodwork_AwayTeam_sum_6,Home_Corners_AwayTeam_sum_6,Away_Corners_AwayTeam_sum_6,Home_Fouls_AwayTeam_sum_6,Away_Fouls_AwayTeam_sum_6,Home_Offsides_AwayTeam_sum_6,Away_Offsides_AwayTeam_sum_6,Home_Yellow_Cards_AwayTeam_sum_6,Away_Yellow_Cards_AwayTeam_sum_6,Home_Red_Cards_AwayTeam_sum_6,Away_Red_Cards_AwayTeam_sum_6,Home_Bookings_Points_AwayTeam_sum_6,Away_Bookings_Points_AwayTeam_sum_6,Final_result_AwayTeam_sum_6,Home_score_AwayTeam_sum_6,Away_score_AwayTeam_sum_6,Final_Home_goals_HomeTeam_median_6,Final_Away_goals_HomeTeam_median_6,Half_Time_Home_Goals_HomeTeam_median_6,Half_Time_Away_Goals_HomeTeam_median_6,Half_Time_Result_HomeTeam_median_6,Crowd_Attendance_HomeTeam_median_6,Home_Shots_HomeTeam_median_6,Away_Shots_HomeTeam_median_6,Home_Shots_Target_HomeTeam_median_6,Away_Shots_Target_HomeTeam_median_6,Home_Woodwork_HomeTeam_median_6,Away_Woodwork_HomeTeam_median_6,Home_Corners_HomeTeam_median_6,Away_Corners_HomeTeam_median_6,Home_Fouls_HomeTeam_median_6,Away_Fouls_HomeTeam_median_6,Home_Offsides_HomeTeam_median_6,Away_Offsides_HomeTeam_median_6,Home_Yellow_Cards_HomeTeam_median_6,Away_Yellow_Cards_HomeTeam_median_6,Home_Red_Cards_HomeTeam_median_6,Away_Red_Cards_HomeTeam_median_6,Home_Bookings_Points_HomeTeam_median_6,Away_Bookings_Points_HomeTeam_median_6,Final_result_HomeTeam_median_6,Home_score_HomeTeam_median_6,Away_score_HomeTeam_median_6,Final_Home_goals_AwayTeam_median_6,Final_Away_goals_AwayTeam_median_6,Half_Time_Home_Goals_AwayTeam_median_6,Half_Time_Away_Goals_AwayTeam_median_6,Half_Time_Result_AwayTeam_median_6,Crowd_Attendance_AwayTeam_median_6,Home_Shots_AwayTeam_median_6,Away_Shots_AwayTeam_median_6,Home_Shots_Target_AwayTeam_median_6,Away_Shots_Target_AwayTeam_median_6,Home_Woodwork_AwayTeam_median_6,Away_Woodwork_AwayTeam_median_6,Home_Corners_AwayTeam_median_6,Away_Corners_AwayTeam_median_6,Home_Fouls_AwayTeam_median_6,Away_Fouls_AwayTeam_median_6,Home_Offsides_AwayTeam_median_6,Away_Offsides_AwayTeam_median_6,Home_Yellow_Cards_AwayTeam_median_6,Away_Yellow_Cards_AwayTeam_median_6,Home_Red_Cards_AwayTeam_median_6,Away_Red_Cards_AwayTeam_median_6,Home_Bookings_Points_AwayTeam_median_6,Away_Bookings_Points_AwayTeam_median_6,Final_result_AwayTeam_median_6,Home_score_AwayTeam_median_6,Away_score_AwayTeam_median_6,Final_Home_goals_HomeTeam_average_6,Final_Away_goals_HomeTeam_average_6,Half_Time_Home_Goals_HomeTeam_average_6,Half_Time_Away_Goals_HomeTeam_average_6,Half_Time_Result_HomeTeam_average_6,Crowd_Attendance_HomeTeam_average_6,Home_Shots_HomeTeam_average_6,Away_Shots_HomeTeam_average_6,Home_Shots_Target_HomeTeam_average_6,Away_Shots_Target_HomeTeam_average_6,Home_Woodwork_HomeTeam_average_6,Away_Woodwork_HomeTeam_average_6,Home_Corners_HomeTeam_average_6,Away_Corners_HomeTeam_average_6,Home_Fouls_HomeTeam_average_6,Away_Fouls_HomeTeam_average_6,Home_Offsides_HomeTeam_average_6,Away_Offsides_HomeTeam_average_6,Home_Yellow_Cards_HomeTeam_average_6,Away_Yellow_Cards_HomeTeam_average_6,Home_Red_Cards_HomeTeam_average_6,Away_Red_Cards_HomeTeam_average_6,Home_Bookings_Points_HomeTeam_average_6,Away_Bookings_Points_HomeTeam_average_6,Final_result_HomeTeam_average_6,Home_score_HomeTeam_average_6,Away_score_HomeTeam_average_6,Final_Home_goals_AwayTeam_average_6,Final_Away_goals_AwayTeam_average_6,Half_Time_Home_Goals_AwayTeam_average_6,Half_Time_Away_Goals_AwayTeam_average_6,Half_Time_Result_AwayTeam_average_6,Crowd_Attendance_AwayTeam_average_6,Home_Shots_AwayTeam_average_6,Away_Shots_AwayTeam_average_6,Home_Shots_Target_AwayTeam_average_6,Away_Shots_Target_AwayTeam_average_6,Home_Woodwork_AwayTeam_average_6,Away_Woodwork_AwayTeam_average_6,Home_Corners_AwayTeam_average_6,Away_Corners_AwayTeam_average_6,Home_Fouls_AwayTeam_average_6,Away_Fouls_AwayTeam_average_6,Home_Offsides_AwayTeam_average_6,Away_Offsides_AwayTeam_average_6,Home_Yellow_Cards_AwayTeam_average_6,Away_Yellow_Cards_AwayTeam_average_6,Home_Red_Cards_AwayTeam_average_6,Away_Red_Cards_AwayTeam_average_6,Home_Bookings_Points_AwayTeam_average_6,Away_Bookings_Points_AwayTeam_average_6,Final_result_AwayTeam_average_6,Home_score_AwayTeam_average_6,Away_score_AwayTeam_average_6,Home_Shots_Home_AllGames_sum_6,Half_Time_Home_Goals_Home_AllGames_Average_6,Home_Offsides_Home_AllGames_Average_6,Final_Away_goals_Home_AllGames_sum_6,Final_Home_goals_Home_AllGames_sum_6,Half_Time_Away_Goals_Home_AllGames_Average_6,Home_Yellow_Cards_Home_AllGames_median_6,Home_Shots_Home_AllGames_median_6,Away_Fouls_Home_AllGames_Average_6,Away_Woodwork_Home_AllGames_Average_6,Away_Shots_Target_Home_AllGames_Average_6,Crowd_Attendance_Home_AllGames_Average_6,Away_Corners_Home_AllGames_median_6,Away_Bookings_Points_Home_AllGames_median_6,Home_Offsides_Home_AllGames_sum_6,Half_Time_Away_Goals_Home_AllGames_median_6,Away_Shots_Target_Home_AllGames_median_6,Final_Away_goals_Home_AllGames_median_6,Away_Shots_Target_Home_AllGames_sum_6,Away_Corners_Home_AllGames_sum_6,Away_Fouls_Home_AllGames_sum_6,Home_Corners_Home_AllGames_Average_6,Away_Shots_Home_AllGames_median_6,Away_Yellow_Cards_Home_AllGames_Average_6,Home_Woodwork_Home_AllGames_sum_6,Away_Fouls_Home_AllGames_median_6,Away_Red_Cards_Home_AllGames_median_6,Home_Yellow_Cards_Home_AllGames_Average_6,Crowd_Attendance_Home_AllGames_median_6,Home_Red_Cards_Home_AllGames_sum_6,Away_score_Home_AllGames_Average_6,Away_Woodwork_Home_AllGames_median_6,Away_Shots_Home_AllGames_Average_6,Home_Yellow_Cards_Home_AllGames_sum_6,Final_result_Home_AllGames_median_6,Home_Bookings_Points_Home_AllGames_Average_6,Half_Time_Result_Home_AllGames_median_6,Away_Woodwork_Home_AllGames_sum_6,Home_Bookings_Points_Home_AllGames_sum_6,Final_Home_goals_Home_AllGames_Average_6,Away_Offsides_Home_AllGames_median_6,Half_Time_Away_Goals_Home_AllGames_sum_6,Home_Fouls_Home_AllGames_sum_6,Final_result_Home_AllGames_Average_6,Away_Corners_Home_AllGames_Average_6,Home_score_Home_AllGames_median_6,Home_Red_Cards_Home_AllGames_Average_6,Half_Time_Home_Goals_Home_AllGames_sum_6,Away_Yellow_Cards_Home_AllGames_median_6,Away_Bookings_Points_Home_AllGames_sum_6,Away_Offsides_Home_AllGames_Average_6,Away_score_Home_AllGames_sum_6,Final_Away_goals_Home_AllGames_Average_6,Home_Bookings_Points_Home_AllGames_median_6,Home_Shots_Target_Home_AllGames_Average_6,Home_Woodwork_Home_AllGames_median_6,Half_Time_Result_Home_AllGames_sum_6,Home_Woodwork_Home_AllGames_Average_6,Home_Red_Cards_Home_AllGames_median_6,Home_score_Home_AllGames_sum_6,Home_Fouls_Home_AllGames_Average_6,Half_Time_Result_Home_AllGames_Average_6,Home_Shots_Target_Home_AllGames_median_6,Home_Corners_Home_AllGames_sum_6,Away_Yellow_Cards_Home_AllGames_sum_6,Final_result_Home_AllGames_sum_6,Home_Shots_Home_AllGames_Average_6,Half_Time_Home_Goals_Home_AllGames_median_6,Home_Fouls_Home_AllGames_median_6,Away_Shots_Home_AllGames_sum_6,Home_Shots_Target_Home_AllGames_sum_6,Away_Offsides_Home_AllGames_sum_6,Away_Bookings_Points_Home_AllGames_Average_6,Crowd_Attendance_Home_AllGames_sum_6,Home_Offsides_Home_AllGames_median_6,Away_Red_Cards_Home_AllGames_Average_6,Home_Corners_Home_AllGames_median_6,Away_Red_Cards_Home_AllGames_sum_6,Final_Home_goals_Home_AllGames_median_6,Away_score_Home_AllGames_median_6,Home_score_Home_AllGames_Average_6,Away_Corners_Away_AllGames_Average_6,Away_Shots_Away_AllGames_Average_6,Home_Corners_Away_AllGames_sum_6,Crowd_Attendance_Away_AllGames_median_6,Home_Offsides_Away_AllGames_Average_6,Home_Woodwork_Away_AllGames_Average_6,Away_Yellow_Cards_Away_AllGames_sum_6,Away_Fouls_Away_AllGames_Average_6,Away_Bookings_Points_Away_AllGames_median_6,Final_Home_goals_Away_AllGames_Average_6,Away_Yellow_Cards_Away_AllGames_Average_6,Away_Red_Cards_Away_AllGames_sum_6,Away_Offsides_Away_AllGames_sum_6,Crowd_Attendance_Away_AllGames_Average_6,Final_Away_goals_Away_AllGames_median_6,Away_Red_Cards_Away_AllGames_Average_6,Home_Bookings_Points_Away_AllGames_sum_6,Half_Time_Result_Away_AllGames_median_6,Home_Bookings_Points_Away_AllGames_median_6,Away_Corners_Away_AllGames_median_6,Home_Shots_Target_Away_AllGames_median_6,Home_Shots_Away_AllGames_sum_6,Home_Corners_Away_AllGames_Average_6,Away_Red_Cards_Away_AllGames_median_6,Home_score_Away_AllGames_Average_6,Away_Shots_Away_AllGames_sum_6,Home_Woodwork_Away_AllGames_sum_6,Home_Fouls_Away_AllGames_median_6,Home_Red_Cards_Away_AllGames_median_6,Half_Time_Home_Goals_Away_AllGames_sum_6,Away_Shots_Target_Away_AllGames_Average_6,Home_Red_Cards_Away_AllGames_sum_6,Final_Away_goals_Away_AllGames_Average_6,Home_Shots_Target_Away_AllGames_Average_6,Half_Time_Away_Goals_Away_AllGames_sum_6,Home_Yellow_Cards_Away_AllGames_sum_6,Home_Shots_Away_AllGames_median_6,Home_Yellow_Cards_Away_AllGames_median_6,Away_Offsides_Away_AllGames_Average_6,Away_Bookings_Points_Away_AllGames_sum_6,Final_result_Away_AllGames_Average_6,Home_score_Away_AllGames_sum_6,Away_Corners_Away_AllGames_sum_6,Away_Shots_Away_AllGames_median_6,Away_Fouls_Away_AllGames_median_6,Half_Time_Result_Away_AllGames_Average_6,Away_Woodwork_Away_AllGames_median_6,Away_Offsides_Away_AllGames_median_6,Home_Shots_Away_AllGames_Average_6,Away_Yellow_Cards_Away_AllGames_median_6,Away_score_Away_AllGames_sum_6,Away_Fouls_Away_AllGames_sum_6,Home_Shots_Target_Away_AllGames_sum_6,Half_Time_Away_Goals_Away_AllGames_median_6,Home_Bookings_Points_Away_AllGames_Average_6,Half_Time_Away_Goals_Away_AllGames_Average_6,Home_Fouls_Away_AllGames_sum_6,Away_score_Away_AllGames_Average_6,Final_Home_goals_Away_AllGames_median_6,Away_Woodwork_Away_AllGames_Average_6,Half_Time_Home_Goals_Away_AllGames_median_6,Final_Home_goals_Away_AllGames_sum_6,Final_result_Away_AllGames_sum_6,Final_result_Away_AllGames_median_6,Half_Time_Home_Goals_Away_AllGames_Average_6,Final_Away_goals_Away_AllGames_sum_6,Crowd_Attendance_Away_AllGames_sum_6,Home_Offsides_Away_AllGames_median_6,Home_Fouls_Away_AllGames_Average_6,Home_Red_Cards_Away_AllGames_Average_6,Home_Woodwork_Away_AllGames_median_6,Away_score_Away_AllGames_median_6,Half_Time_Result_Away_AllGames_sum_6,Away_Woodwork_Away_AllGames_sum_6,Home_Corners_Away_AllGames_median_6,Away_Bookings_Points_Away_AllGames_Average_6,Away_Shots_Target_Away_AllGames_median_6,Away_Shots_Target_Away_AllGames_sum_6,Home_Offsides_Away_AllGames_sum_6,Home_Yellow_Cards_Away_AllGames_Average_6,Home_score_Away_AllGames_median_6,Date_6Away_of_home_sum,Final_Home_goals_6Away_of_home_sum,Final_Away_goals_6Away_of_home_sum,Half_Time_Home_Goals_6Away_of_home_sum,Half_Time_Away_Goals_6Away_of_home_sum,Half_Time_Result_6Away_of_home_sum,Crowd_Attendance_6Away_of_home_sum,Home_Shots_6Away_of_home_sum,Away_Shots_6Away_of_home_sum,Home_Shots_Target_6Away_of_home_sum,Away_Shots_Target_6Away_of_home_sum,Home_Woodwork_6Away_of_home_sum,Away_Woodwork_6Away_of_home_sum,Home_Corners_6Away_of_home_sum,Away_Corners_6Away_of_home_sum,Home_Fouls_6Away_of_home_sum,Away_Fouls_6Away_of_home_sum,Home_Offsides_6Away_of_home_sum,Away_Offsides_6Away_of_home_sum,Home_Yellow_Cards_6Away_of_home_sum,Away_Yellow_Cards_6Away_of_home_sum,Home_Red_Cards_6Away_of_home_sum,Away_Red_Cards_6Away_of_home_sum,Home_Bookings_Points_6Away_of_home_sum,Away_Bookings_Points_6Away_of_home_sum,Final_result_6Away_of_home_sum,Home_score_6Away_of_home_sum,Away_score_6Away_of_home_sum,menha_date_6Away_of_home_sum,Date_6Away_of_home_median,Final_Home_goals_6Away_of_home_median,Final_Away_goals_6Away_of_home_median,Half_Time_Home_Goals_6Away_of_home_median,Half_Time_Away_Goals_6Away_of_home_median,Half_Time_Result_6Away_of_home_median,Crowd_Attendance_6Away_of_home_median,Home_Shots_6Away_of_home_median,Away_Shots_6Away_of_home_median,Home_Shots_Target_6Away_of_home_median,Away_Shots_Target_6Away_of_home_median,Home_Woodwork_6Away_of_home_median,Away_Woodwork_6Away_of_home_median,Home_Corners_6Away_of_home_median,Away_Corners_6Away_of_home_median,Home_Fouls_6Away_of_home_median,Away_Fouls_6Away_of_home_median,Home_Offsides_6Away_of_home_median,Away_Offsides_6Away_of_home_median,Home_Yellow_Cards_6Away_of_home_median,Away_Yellow_Cards_6Away_of_home_median,Home_Red_Cards_6Away_of_home_median,Away_Red_Cards_6Away_of_home_median,Home_Bookings_Points_6Away_of_home_median,Away_Bookings_Points_6Away_of_home_median,Final_result_6Away_of_home_median,Home_score_6Away_of_home_median,Away_score_6Away_of_home_median,menha_date_6Away_of_home_median,Date_6Away_of_home_mean,Final_Home_goals_6Away_of_home_mean,Final_Away_goals_6Away_of_home_mean,Half_Time_Home_Goals_6Away_of_home_mean,Half_Time_Away_Goals_6Away_of_home_mean,Half_Time_Result_6Away_of_home_mean,Crowd_Attendance_6Away_of_home_mean,Home_Shots_6Away_of_home_mean,Away_Shots_6Away_of_home_mean,Home_Shots_Target_6Away_of_home_mean,Away_Shots_Target_6Away_of_home_mean,Home_Woodwork_6Away_of_home_mean,Away_Woodwork_6Away_of_home_mean,Home_Corners_6Away_of_home_mean,Away_Corners_6Away_of_home_mean,Home_Fouls_6Away_of_home_mean,Away_Fouls_6Away_of_home_mean,Home_Offsides_6Away_of_home_mean,Away_Offsides_6Away_of_home_mean,Home_Yellow_Cards_6Away_of_home_mean,Away_Yellow_Cards_6Away_of_home_mean,Home_Red_Cards_6Away_of_home_mean,Away_Red_Cards_6Away_of_home_mean,Home_Bookings_Points_6Away_of_home_mean,Away_Bookings_Points_6Away_of_home_mean,Final_result_6Away_of_home_mean,Home_score_6Away_of_home_mean,Away_score_6Away_of_home_mean,menha_date_6Away_of_home_mean
0,2000-08-19,Charlton,Man City,4.0,0.0,2.0,0.0,1,20043.0,Rob Harris,17.0,8.0,14.0,4.0,2.0,1.0,6.0,6.0,13.0,12.0,8.0,6.0,1.0,2.0,0.0,0.0,10.0,20.0,1.0,3.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,2000-09-06,Charlton,Southampton,1.0,1.0,0.0,0.0,2,20043.0,Mark Halsey,8.0,11.0,6.0,3.0,0.0,0.0,10.0,14.0,14.0,16.0,4.0,3.0,3.0,3.0,1.0,0.0,55.0,30.0,2.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,0.0,2.0,0.0,1.0,20043.0,17.0,8.0,14.0,4.0,2.0,1.0,6.0,6.0,13.0,12.0,8.0,6.0,1.0,2.0,0.0,0.0,10.0,20.0,1.0,3.0,0.0,2.0,2.0,1.0,2.0,3.0,27223.0,6.0,13.0,4.0,6.0,0.0,0.0,5.0,8.0,11.0,13.0,0.0,2.0,1.0,1.0,0.0,0.0,10.0,10.0,2.0,1.0,1.0,4.000000,0.000000,2.000000,0.000000,1.000000,20043.000000,17.000000,8.000000,14.000000,4.000000,2.000000,1.000000,6.000000,6.000000,13.000000,12.000000,8.0,6.000000,1.000000,2.000000,0.000000,0.000000,10.000000,20.000000,1.000000,3.000000,0.000000,2.000000,2.000000,1.000000,2.0,3.000000,27223.000000,6.000000,13.000000,4.000000,6.0,0.000000,0.000000,5.000000,8.000000,11.0,13.000000,0.000000,2.000000,1.000000,1.000000,0.000000,0.000000,10.000000,10.000000,2.000000,1.0,1.0,NaN,2.000000,8.0,NaN,NaN,0.000000,1.0,17.0,12.000000,1.000000,4.000000,20043.000000,6.0,20.0,NaN,0.0,4.0,0.0,NaN,NaN,NaN,6.000000,8.0,2.000000,NaN,12.0,0.0,1.000000,20043.0,NaN,0.000000,1.0,8.000000,NaN,1.0,10.000000,1.0,NaN,NaN,4.000000,6.0,NaN,NaN,1.000000,6.000000,3.0,0.000000,NaN,2.0,NaN,6.000000,NaN,0.000000,10.0,14.000000,2.0,NaN,2.000000,0.0,NaN,13.000000,1.000000,14.0,NaN,NaN,NaN,17.000000,2.0,13.0,NaN,NaN,NaN,20.000000,NaN,8.0,0.000000,6.0,NaN,4.0,0.0,3.000000,8.000000,13.000000,NaN,27223.0,0.000000,0.000000,NaN,13.000000,10.0,2.000000,1.000000,NaN,NaN,27223.000000,2.0,0.000000,NaN,3.0,10.0,8.0,4.0,NaN,5.000000,0.0,1.0,NaN,NaN,11.0,0.0,NaN,6.0,NaN,2.000000,4.000000,NaN,NaN,6.0,1.0,2.000000,NaN,2.000000,NaN,NaN,13.0,13.0,3.000000,0.0,2.0,6.000000,1.0,NaN,NaN,NaN,2.0,10.000000,2.0,NaN,1.0,2.0,0.000000,1.0,NaN,NaN,2.0,1.000000,NaN,NaN,0.0,11.0,0.000000,0.0,1.0,NaN,NaN,5.0,10.000000,6.0,NaN,NaN,1.000000,1.0,2000-08-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.0,2000-08-26,4.0,1.5,0.5,1.0,2.5,37162.5,15.5,7.5,8.5,4.0,0.0,0.0,5.5,4.0,14.5,15.0,2.0,3.0,1.0,1.0,0.0,0.5,10.0,22.5,1.0,3.0,0.0,11.0,2000-08-26,4.000000,1.500000,0.50,1.000000,2.500000,37162.500000,15.500000,7.500000,8.500000,4.000000,0.000000,0.000000,5.500000,4.000000,14.500000,15.0,2.000000,3.000000,1.000000,1.000000,0.0,0.500000,10.000000,22.500000,1.000000,3.000000,0.000000,11.0

In [177]:
df_naha= pd.merge(df_naha, df_6Home_of_away, how='left', on=['Date','AwayTeam'])
df_naha

,Date,HomeTeam,AwayTeam,Final_Home_goals,Final_Away_goals,Half_Time_Home_Goals,Half_Time_Away_Goals,Half_Time_Result,Crowd_Attendance,Referee,Home_Shots,Away_Shots,Home_Shots_Target,Away_Shots_Target,Home_Woodwork,Away_Woodwork,Home_Corners,Away_Corners,Home_Fouls,Away_Fouls,Home_Offsides,Away_Offsides,Home_Yellow_Cards,Away_Yellow_Cards,Home_Red_Cards,Away_Red_Cards,Home_Bookings_Points,Away_Bookings_Points,Final_result,Home_score,Away_score,Final_Home_goals_HomeTeam_sum_6,Final_Away_goals_HomeTeam_sum_6,Half_Time_Home_Goals_HomeTeam_sum_6,Half_Time_Away_Goals_HomeTeam_sum_6,Half_Time_Result_HomeTeam_sum_6,Crowd_Attendance_HomeTeam_sum_6,Home_Shots_HomeTeam_sum_6,Away_Shots_HomeTeam_sum_6,Home_Shots_Target_HomeTeam_sum_6,Away_Shots_Target_HomeTeam_sum_6,Home_Woodwork_HomeTeam_sum_6,Away_Woodwork_HomeTeam_sum_6,Home_Corners_HomeTeam_sum_6,Away_Corners_HomeTeam_sum_6,Home_Fouls_HomeTeam_sum_6,Away_Fouls_HomeTeam_sum_6,Home_Offsides_HomeTeam_sum_6,Away_Offsides_HomeTeam_sum_6,Home_Yellow_Cards_HomeTeam_sum_6,Away_Yellow_Cards_HomeTeam_sum_6,Home_Red_Cards_HomeTeam_sum_6,Away_Red_Cards_HomeTeam_sum_6,Home_Bookings_Points_HomeTeam_sum_6,Away_Bookings_Points_HomeTeam_sum_6,Final_result_HomeTeam_sum_6,Home_score_HomeTeam_sum_6,Away_score_HomeTeam_sum_6,Final_Home_goals_AwayTeam_sum_6,Final_Away_goals_AwayTeam_sum_6,Half_Time_Home_Goals_AwayTeam_sum_6,Half_Time_Away_Goals_AwayTeam_sum_6,Half_Time_Result_AwayTeam_sum_6,Crowd_Attendance_AwayTeam_sum_6,Home_Shots_AwayTeam_sum_6,Away_Shots_AwayTeam_sum_6,Home_Shots_Target_AwayTeam_sum_6,Away_Shots_Target_AwayTeam_sum_6,Home_Woodwork_AwayTeam_sum_6,Away_Woodwork_AwayTeam_sum_6,Home_Corners_AwayTeam_sum_6,Away_Corners_AwayTeam_sum_6,Home_Fouls_AwayTeam_sum_6,Away_Fouls_AwayTeam_sum_6,Home_Offsides_AwayTeam_sum_6,Away_Offsides_AwayTeam_sum_6,Home_Yellow_Cards_AwayTeam_sum_6,Away_Yellow_Cards_AwayTeam_sum_6,Home_Red_Cards_AwayTeam_sum_6,Away_Red_Cards_AwayTeam_sum_6,Home_Bookings_Points_AwayTeam_sum_6,Away_Bookings_Points_AwayTeam_sum_6,Final_result_AwayTeam_sum_6,Home_score_AwayTeam_sum_6,Away_score_AwayTeam_sum_6,Final_Home_goals_HomeTeam_median_6,Final_Away_goals_HomeTeam_median_6,Half_Time_Home_Goals_HomeTeam_median_6,Half_Time_Away_Goals_HomeTeam_median_6,Half_Time_Result_HomeTeam_median_6,Crowd_Attendance_HomeTeam_median_6,Home_Shots_HomeTeam_median_6,Away_Shots_HomeTeam_median_6,Home_Shots_Target_HomeTeam_median_6,Away_Shots_Target_HomeTeam_median_6,Home_Woodwork_HomeTeam_median_6,Away_Woodwork_HomeTeam_median_6,Home_Corners_HomeTeam_median_6,Away_Corners_HomeTeam_median_6,Home_Fouls_HomeTeam_median_6,Away_Fouls_HomeTeam_median_6,Home_Offsides_HomeTeam_median_6,Away_Offsides_HomeTeam_median_6,Home_Yellow_Cards_HomeTeam_median_6,Away_Yellow_Cards_HomeTeam_median_6,Home_Red_Cards_HomeTeam_median_6,Away_Red_Cards_HomeTeam_median_6,Home_Bookings_Points_HomeTeam_median_6,Away_Bookings_Points_HomeTeam_median_6,Final_result_HomeTeam_median_6,Home_score_HomeTeam_median_6,Away_score_HomeTeam_median_6,Final_Home_goals_AwayTeam_median_6,Final_Away_goals_AwayTeam_median_6,Half_Time_Home_Goals_AwayTeam_median_6,Half_Time_Away_Goals_AwayTeam_median_6,Half_Time_Result_AwayTeam_median_6,Crowd_Attendance_AwayTeam_median_6,Home_Shots_AwayTeam_median_6,Away_Shots_AwayTeam_median_6,Home_Shots_Target_AwayTeam_median_6,Away_Shots_Target_AwayTeam_median_6,Home_Woodwork_AwayTeam_median_6,Away_Woodwork_AwayTeam_median_6,Home_Corners_AwayTeam_median_6,Away_Corners_AwayTeam_median_6,Home_Fouls_AwayTeam_median_6,Away_Fouls_AwayTeam_median_6,Home_Offsides_AwayTeam_median_6,Away_Offsides_AwayTeam_median_6,Home_Yellow_Cards_AwayTeam_median_6,Away_Yellow_Cards_AwayTeam_median_6,Home_Red_Cards_AwayTeam_median_6,Away_Red_Cards_AwayTeam_median_6,Home_Bookings_Points_AwayTeam_median_6,Away_Bookings_Points_AwayTeam_median_6,Final_result_AwayTeam_median_6,Home_score_AwayTeam_median_6,Away_score_AwayTeam_median_6,Final_Home_goals_HomeTeam_average_6,Final_Away_goals_HomeTeam_average_6,Half_Time_Home_Goals_HomeTeam_average_6,Half_Time_Away_Goals_HomeTeam_average_6,Half_Time_Result_HomeTeam_average_6,Crowd_Attendance_HomeTeam_average_6,Home_Shots_HomeTeam_average_6,Away_Shots_HomeTeam_average_6,Home_Shots_Target_HomeTeam_average_6,Away_Shots_Target_HomeTeam_average_6,Home_Woodwork_HomeTeam_average_6,Away_Woodwork_HomeTeam_average_6,Home_Corners_HomeTeam_average_6,Away_Corners_HomeTeam_average_6,Home_Fouls_HomeTeam_average_6,Away_Fouls_HomeTeam_average_6,Home_Offsides_HomeTeam_average_6,Away_Offsides_HomeTeam_average_6,Home_Yellow_Cards_HomeTeam_average_6,Away_Yellow_Cards_HomeTeam_average_6,Home_Red_Cards_HomeTeam_average_6,Away_Red_Cards_HomeTeam_average_6,Home_Bookings_Points_HomeTeam_average_6,Away_Bookings_Points_HomeTeam_average_6,Final_result_HomeTeam_average_6,Home_score_HomeTeam_average_6,Away_score_HomeTeam_average_6,Final_Home_goals_AwayTeam_average_6,Final_Away_goals_AwayTeam_average_6,Half_Time_Home_Goals_AwayTeam_average_6,Half_Time_Away_Goals_AwayTeam_average_6,Half_Time_Result_AwayTeam_average_6,Crowd_Attendance_AwayTeam_average_6,Home_Shots_AwayTeam_average_6,Away_Shots_AwayTeam_average_6,Home_Shots_Target_AwayTeam_average_6,Away_Shots_Target_AwayTeam_average_6,Home_Woodwork_AwayTeam_average_6,Away_Woodwork_AwayTeam_average_6,Home_Corners_AwayTeam_average_6,Away_Corners_AwayTeam_average_6,Home_Fouls_AwayTeam_average_6,Away_Fouls_AwayTeam_average_6,Home_Offsides_AwayTeam_average_6,Away_Offsides_AwayTeam_average_6,Home_Yellow_Cards_AwayTeam_average_6,Away_Yellow_Cards_AwayTeam_average_6,Home_Red_Cards_AwayTeam_average_6,Away_Red_Cards_AwayTeam_average_6,Home_Bookings_Points_AwayTeam_average_6,Away_Bookings_Points_AwayTeam_average_6,Final_result_AwayTeam_average_6,Home_score_AwayTeam_average_6,Away_score_AwayTeam_average_6,Home_Shots_Home_AllGames_sum_6,Half_Time_Home_Goals_Home_AllGames_Average_6,Home_Offsides_Home_AllGames_Average_6,Final_Away_goals_Home_AllGames_sum_6,Final_Home_goals_Home_AllGames_sum_6,Half_Time_Away_Goals_Home_AllGames_Average_6,Home_Yellow_Cards_Home_AllGames_median_6,Home_Shots_Home_AllGames_median_6,Away_Fouls_Home_AllGames_Average_6,Away_Woodwork_Home_AllGames_Average_6,Away_Shots_Target_Home_AllGames_Average_6,Crowd_Attendance_Home_AllGames_Average_6,Away_Corners_Home_AllGames_median_6,Away_Bookings_Points_Home_AllGames_median_6,Home_Offsides_Home_AllGames_sum_6,Half_Time_Away_Goals_Home_AllGames_median_6,Away_Shots_Target_Home_AllGames_median_6,Final_Away_goals_Home_AllGames_median_6,Away_Shots_Target_Home_AllGames_sum_6,Away_Corners_Home_AllGames_sum_6,Away_Fouls_Home_AllGames_sum_6,Home_Corners_Home_AllGames_Average_6,Away_Shots_Home_AllGames_median_6,Away_Yellow_Cards_Home_AllGames_Average_6,Home_Woodwork_Home_AllGames_sum_6,Away_Fouls_Home_AllGames_median_6,Away_Red_Cards_Home_AllGames_median_6,Home_Yellow_Cards_Home_AllGames_Average_6,Crowd_Attendance_Home_AllGames_median_6,Home_Red_Cards_Home_AllGames_sum_6,Away_score_Home_AllGames_Average_6,Away_Woodwork_Home_AllGames_median_6,Away_Shots_Home_AllGames_Average_6,Home_Yellow_Cards_Home_AllGames_sum_6,Final_result_Home_AllGames_median_6,Home_Bookings_Points_Home_AllGames_Average_6,Half_Time_Result_Home_AllGames_median_6,Away_Woodwork_Home_AllGames_sum_6,Home_Bookings_Points_Home_AllGames_sum_6,Final_Home_goals_Home_AllGames_Average_6,Away_Offsides_Home_AllGames_median_6,Half_Time_Away_Goals_Home_AllGames_sum_6,Home_Fouls_Home_AllGames_sum_6,Final_result_Home_AllGames_Average_6,Away_Corners_Home_AllGames_Average_6,Home_score_Home_AllGames_median_6,Home_Red_Cards_Home_AllGames_Average_6,Half_Time_Home_Goals_Home_AllGames_sum_6,Away_Yellow_Cards_Home_AllGames_median_6,Away_Bookings_Points_Home_AllGames_sum_6,Away_Offsides_Home_AllGames_Average_6,Away_score_Home_AllGames_sum_6,Final_Away_goals_Home_AllGames_Average_6,Home_Bookings_Points_Home_AllGames_median_6,Home_Shots_Target_Home_AllGames_Average_6,Home_Woodwork_Home_AllGames_median_6,Half_Time_Result_Home_AllGames_sum_6,Home_Woodwork_Home_AllGames_Average_6,Home_Red_Cards_Home_AllGames_median_6,Home_score_Home_AllGames_sum_6,Home_Fouls_Home_AllGames_Average_6,Half_Time_Result_Home_AllGames_Average_6,Home_Shots_Target_Home_AllGames_median_6,Home_Corners_Home_AllGames_sum_6,Away_Yellow_Cards_Home_AllGames_sum_6,Final_result_Home_AllGames_sum_6,Home_Shots_Home_AllGames_Average_6,Half_Time_Home_Goals_Home_AllGames_median_6,Home_Fouls_Home_AllGames_median_6,Away_Shots_Home_AllGames_sum_6,Home_Shots_Target_Home_AllGames_sum_6,Away_Offsides_Home_AllGames_sum_6,Away_Bookings_Points_Home_AllGames_Average_6,Crowd_Attendance_Home_AllGames_sum_6,Home_Offsides_Home_AllGames_median_6,Away_Red_Cards_Home_AllGames_Average_6,Home_Corners_Home_AllGames_median_6,Away_Red_Cards_Home_AllGames_sum_6,Final_Home_goals_Home_AllGames_median_6,Away_score_Home_AllGames_median_6,Home_score_Home_AllGames_Average_6,Away_Corners_Away_AllGames_Average_6,Away_Shots_Away_AllGames_Average_6,Home_Corners_Away_AllGames_sum_6,Crowd_Attendance_Away_AllGames_median_6,Home_Offsides_Away_AllGames_Average_6,Home_Woodwork_Away_AllGames_Average_6,Away_Yellow_Cards_Away_AllGames_sum_6,Away_Fouls_Away_AllGames_Average_6,Away_Bookings_Points_Away_AllGames_median_6,Final_Home_goals_Away_AllGames_Average_6,Away_Yellow_Cards_Away_AllGames_Average_6,Away_Red_Cards_Away_AllGames_sum_6,Away_Offsides_Away_AllGames_sum_6,Crowd_Attendance_Away_AllGames_Average_6,Final_Away_goals_Away_AllGames_median_6,Away_Red_Cards_Away_AllGames_Average_6,Home_Bookings_Points_Away_AllGames_sum_6,Half_Time_Result_Away_AllGames_median_6,Home_Bookings_Points_Away_AllGames_median_6,Away_Corners_Away_AllGames_median_6,Home_Shots_Target_Away_AllGames_median_6,Home_Shots_Away_AllGames_sum_6,Home_Corners_Away_AllGames_Average_6,Away_Red_Cards_Away_AllGames_median_6,Home_score_Away_AllGames_Average_6,Away_Shots_Away_AllGames_sum_6,Home_Woodwork_Away_AllGames_sum_6,Home_Fouls_Away_AllGames_median_6,Home_Red_Cards_Away_AllGames_median_6,Half_Time_Home_Goals_Away_AllGames_sum_6,Away_Shots_Target_Away_AllGames_Average_6,Home_Red_Cards_Away_AllGames_sum_6,Final_Away_goals_Away_AllGames_Average_6,Home_Shots_Target_Away_AllGames_Average_6,Half_Time_Away_Goals_Away_AllGames_sum_6,Home_Yellow_Cards_Away_AllGames_sum_6,Home_Shots_Away_AllGames_median_6,Home_Yellow_Cards_Away_AllGames_median_6,Away_Offsides_Away_AllGames_Average_6,Away_Bookings_Points_Away_AllGames_sum_6,Final_result_Away_AllGames_Average_6,Home_score_Away_AllGames_sum_6,Away_Corners_Away_AllGames_sum_6,Away_Shots_Away_AllGames_median_6,Away_Fouls_Away_AllGames_median_6,Half_Time_Result_Away_AllGames_Average_6,Away_Woodwork_Away_AllGames_median_6,Away_Offsides_Away_AllGames_median_6,Home_Shots_Away_AllGames_Average_6,Away_Yellow_Cards_Away_AllGames_median_6,Away_score_Away_AllGames_sum_6,Away_Fouls_Away_AllGames_sum_6,Home_Shots_Target_Away_AllGames_sum_6,Half_Time_Away_Goals_Away_AllGames_median_6,Home_Bookings_Points_Away_AllGames_Average_6,Half_Time_Away_Goals_Away_AllGames_Average_6,Home_Fouls_Away_AllGames_sum_6,Away_score_Away_AllGames_Average_6,Final_Home_goals_Away_AllGames_median_6,Away_Woodwork_Away_AllGames_Average_6,Half_Time_Home_Goals_Away_AllGames_median_6,Final_Home_goals_Away_AllGames_sum_6,Final_result_Away_AllGames_sum_6,Final_result_Away_AllGames_median_6,Half_Time_Home_Goals_Away_AllGames_Average_6,Final_Away_goals_Away_AllGames_sum_6,Crowd_Attendance_Away_AllGames_sum_6,Home_Offsides_Away_AllGames_median_6,Home_Fouls_Away_AllGames_Average_6,Home_Red_Cards_Away_AllGames_Average_6,Home_Woodwork_Away_AllGames_median_6,Away_score_Away_AllGames_median_6,Half_Time_Result_Away_AllGames_sum_6,Away_Woodwork_Away_AllGames_sum_6,Home_Corners_Away_AllGames_median_6,Away_Bookings_Points_Away_AllGames_Average_6,Away_Shots_Target_Away_AllGames_median_6,Away_Shots_Target_Away_AllGames_sum_6,Home_Offsides_Away_AllGames_sum_6,Home_Yellow_Cards_Away_AllGames_Average_6,Home_score_Away_AllGames_median_6,Date_6Away_of_home_sum,Final_Home_goals_6Away_of_home_sum,Final_Away_goals_6Away_of_home_sum,Half_Time_Home_Goals_6Away_of_home_sum,Half_Time_Away_Goals_6Away_of_home_sum,Half_Time_Result_6Away_of_home_sum,Crowd_Attendance_6Away_of_home_sum,Home_Shots_6Away_of_home_sum,Away_Shots_6Away_of_home_sum,Home_Shots_Target_6Away_of_home_sum,Away_Shots_Target_6Away_of_home_sum,Home_Woodwork_6Away_of_home_sum,Away_Woodwork_6Away_of_home_sum,Home_Corners_6Away_of_home_sum,Away_Corners_6Away_of_home_sum,Home_Fouls_6Away_of_home_sum,Away_Fouls_6Away_of_home_sum,Home_Offsides_6Away_of_home_sum,Away_Offsides_6Away_of_home_sum,Home_Yellow_Cards_6Away_of_home_sum,Away_Yellow_Cards_6Away_of_home_sum,Home_Red_Cards_6Away_of_home_sum,Away_Red_Cards_6Away_of_home_sum,Home_Bookings_Points_6Away_of_home_sum,Away_Bookings_Points_6Away_of_home_sum,Final_result_6Away_of_home_sum,Home_score_6Away_of_home_sum,Away_score_6Away_of_home_sum,menha_date_6Away_of_home_sum,Date_6Away_of_home_median,Final_Home_goals_6Away_of_home_median,Final_Away_goals_6Away_of_home_median,Half_Time_Home_Goals_6Away_of_home_median,Half_Time_Away_Goals_6Away_of_home_median,Half_Time_Result_6Away_of_home_median,Crowd_Attendance_6Away_of_home_median,Home_Shots_6Away_of_home_median,Away_Shots_6Away_of_home_median,Home_Shots_Target_6Away_of_home_median,Away_Shots_Target_6Away_of_home_median,Home_Woodwork_6Away_of_home_median,Away_Woodwork_6Away_of_home_median,Home_Corners_6Away_of_home_median,Away_Corners_6Away_of_home_median,Home_Fouls_6Away_of_home_median,Away_Fouls_6Away_of_home_median,Home_Offsides_6Away_of_home_median,Away_Offsides_6Away_of_home_median,Home_Yellow_Cards_6Away_of_home_median,Away_Yellow_Cards_6Away_of_home_median,Home_Red_Cards_6Away_of_home_median,Away_Red_Cards_6Away_of_home_median,Home_Bookings_Points_6Away_of_home_median,Away_Bookings_Points_6Away_of_home_median,Final_result_6Away_of_home_median,Home_score_6Away_of_home_median,Away_score_6Away_of_home_median,menha_date_6Away_of_home_median,Date_6Away_of_home_mean,Final_Home_goals_6Away_of_home_mean,Final_Away_goals_6Away_of_home_mean,Half_Time_Home_Goals_6Away_of_home_mean,Half_Time_Away_Goals_6Away_of_home_mean,Half_Time_Result_6Away_of_home_mean,Crowd_Attendance_6Away_of_home_mean,Home_Shots_6Away_of_home_mean,Away_Shots_6Away_of_home_mean,Home_Shots_Target_6Away_of_home_mean,Away_Shots_Target_6Away_of_home_mean,Home_Woodwork_6Away_of_home_mean,Away_Woodwork_6Away_of_home_mean,Home_Corners_6Away_of_home_mean,Away_Corners_6Away_of_home_mean,Home_Fouls_6Away_of_home_mean,Away_Fouls_6Away_of_home_mean,Home_Offsides_6Away_of_home_mean,Away_Offsides_6Away_of_home_mean,Home_Yellow_Cards_6Away_of_home_mean,Away_Yellow_Cards_6Away_of_home_mean,Home_Red_Cards_6Away_of_home_mean,Away_Red_Cards_6Away_of_home_mean,Home_Bookings_Points_6Away_of_home_mean,Away_Bookings_Points_6Away_of_home_mean,Final_result_6Away_of_home_mean,Home_score_6Away_of_home_mean,Away_score_6Away_of_home_mean,menha_date_6Away_of_home_mean,Date_6Home_of_away_sum,Final_Home_goals_6Home_of_away_sum,Final_Away_goals_6Home_of_away_sum,Half_Time_Home_Goals_6Home_of_away_sum,Half_Time_Away_Goals_6Home_of_away_sum,Half_Time_Result_6Home_of_away_sum,Crowd_Attendance_6Home_of_away_sum,Home_Shots_6Home_of_away_sum,Away_Shots_6Home_of_away_sum,Home_Shots_Target_6Home_of_away_sum,Away_Shots_Target_6Home_of_away_sum,Home_Woodwork_6Home_of_away_sum,Away_Woodwork_6Home_of_away_sum,Home_Corners_6Home_of_away_sum,Away_Corners_6Home_of_away_sum,Home_Fouls_6Home_of_away_sum,Away_Fouls_6Home_of_away_sum,Home_Offsides_6Home_of_away_sum,Away_Offsides_6Home_of_away_sum,Home_Yellow_Cards_6Home_of_away_sum,Away_Yellow_Cards_6Home_of_away_sum,Home_Red_Cards_6Home_of_away_sum,Away_Red_Cards_6Home_of_away_sum,Home_Bookings_Points_6Home_of_away_sum,Away_Bookings_Points_6Home_of_away_sum,Final_result_6Home_of_away_sum,Home_score_6Home_of_away_sum,Away_score_6Home_of_away_sum,menha_date_6Home_of_away_sum,Date_6Home_of_away_median,Final_Home_goals_6Home_of_away_median,Final_Away_goals_6Home_of_away_median,Half_Time_Home_Goals_6Home_of_away_median,Half_Time_Away_Goals_6Home_of_away_median,Half_Time_Result_6Home_of_away_median,Crowd_Attendance_6Home_of_away_median,Home_Shots_6Home_of_away_median,Away_Shots_6Home_of_away_median,Home_Shots_Target_6Home_of_away_median,Away_Shots_Target_6Home_of_away_median,Home_Woodwork_6Home_of_away_median,Away_Woodwork_6Home_of_away_median,Home_Corners_6Home_of_away_median,Away_Corners_6Home_of_away_median,Home_Fouls_6Home_of_away_median,Away_Fouls_6Home_of_away_median,Home_Offsides_6Home_of_away_median,Away_Offsides_6Home_of_away_median,Home_Yellow_Cards_6Home_of_away_median,Away_Yellow_Cards_6Home_of_away_median,Home_Red_Cards_6Home_of_away_median,Away_Red_Cards_6Home_of_away_median,Home_Bookings_Points_6Home_of_away_median,Away_Bookings_Points_6Home_of_away_median,Final_result_6Home_of_away_median,Home_score_6Home_of_away_median,Away_score_6Home_of_away_median,menha_date_6Home_of_away_median,Date_6Home_of_away_mean,Final_Home_goals_6Home_of_away_mean,Final_Away_goals_6Home_of_away_mean,Half_Time_Home_Goals_6Home_of_away_mean,Half_Time_Away_Goals_6Home_of_away_mean,Half_Time_Result_6Home_of_away_mean,Crowd_Attendance_6Home_of_away_mean,Home_Shots_6Home_of_away_mean,Away_Shots_6Home_of_away_mean,Home_Shots_Target_6Home_of_away_mean,Away_Shots_Target_6Home_of_away_mean,Home_Woodwork_6Home_of_away_mean,Away_Woodwork_6Home_of_away_mean,Home_Corners_6Home_of_away_mean,Away_Corners_6Home_of_away_mean,Home_Fouls_6Home_of_away_mean,Away_Fouls_6Home_of_away_mean,Home_Offsides_6Home_of_away_mean,Away_Offsides_6Home_of_away_mean,Home_Yellow_Cards_6Home_of_away_mean,Away_Yellow_Cards_6Home_of_away_mean,Home_Red_Cards_6Home_of_away_mean,Away_Red_Cards_6Home_of_away_mean,Home_Bookings_Points_6Home_of_away_mean,Away_Bookings_Points_6Home_of_away_mean,Final_result_6Home_of_away_mean,Home_score_6Home_of_away_mean,Away_score_6Home_of_away_mean,menha_date_6Home_of_away_mean
0,2000-08-19,Charlton,Man City,4.0,0.0,2.0,0.0,1,20043.0,Rob Harris,17.0,8.0,14.0,4.0,2.0,1.0,6.0,6.0,13.0,12.0,8.0,6.0,1.0,2.0,0.0,0.0,10.0,20.0,1.0,3.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [178]:
df_naha.loc[df_naha['HomeTeam']=='Charlton'].head(7)

,Date,HomeTeam,AwayTeam,Final_Home_goals,Final_Away_goals,Half_Time_Home_Goals,Half_Time_Away_Goals,Half_Time_Result,Crowd_Attendance,Referee,Home_Shots,Away_Shots,Home_Shots_Target,Away_Shots_Target,Home_Woodwork,Away_Woodwork,Home_Corners,Away_Corners,Home_Fouls,Away_Fouls,Home_Offsides,Away_Offsides,Home_Yellow_Cards,Away_Yellow_Cards,Home_Red_Cards,Away_Red_Cards,Home_Bookings_Points,Away_Bookings_Points,Final_result,Home_score,Away_score,Final_Home_goals_HomeTeam_sum_6,Final_Away_goals_HomeTeam_sum_6,Half_Time_Home_Goals_HomeTeam_sum_6,Half_Time_Away_Goals_HomeTeam_sum_6,Half_Time_Result_HomeTeam_sum_6,Crowd_Attendance_HomeTeam_sum_6,Home_Shots_HomeTeam_sum_6,Away_Shots_HomeTeam_sum_6,Home_Shots_Target_HomeTeam_sum_6,Away_Shots_Target_HomeTeam_sum_6,Home_Woodwork_HomeTeam_sum_6,Away_Woodwork_HomeTeam_sum_6,Home_Corners_HomeTeam_sum_6,Away_Corners_HomeTeam_sum_6,Home_Fouls_HomeTeam_sum_6,Away_Fouls_HomeTeam_sum_6,Home_Offsides_HomeTeam_sum_6,Away_Offsides_HomeTeam_sum_6,Home_Yellow_Cards_HomeTeam_sum_6,Away_Yellow_Cards_HomeTeam_sum_6,Home_Red_Cards_HomeTeam_sum_6,Away_Red_Cards_HomeTeam_sum_6,Home_Bookings_Points_HomeTeam_sum_6,Away_Bookings_Points_HomeTeam_sum_6,Final_result_HomeTeam_sum_6,Home_score_HomeTeam_sum_6,Away_score_HomeTeam_sum_6,Final_Home_goals_AwayTeam_sum_6,Final_Away_goals_AwayTeam_sum_6,Half_Time_Home_Goals_AwayTeam_sum_6,Half_Time_Away_Goals_AwayTeam_sum_6,Half_Time_Result_AwayTeam_sum_6,Crowd_Attendance_AwayTeam_sum_6,Home_Shots_AwayTeam_sum_6,Away_Shots_AwayTeam_sum_6,Home_Shots_Target_AwayTeam_sum_6,Away_Shots_Target_AwayTeam_sum_6,Home_Woodwork_AwayTeam_sum_6,Away_Woodwork_AwayTeam_sum_6,Home_Corners_AwayTeam_sum_6,Away_Corners_AwayTeam_sum_6,Home_Fouls_AwayTeam_sum_6,Away_Fouls_AwayTeam_sum_6,Home_Offsides_AwayTeam_sum_6,Away_Offsides_AwayTeam_sum_6,Home_Yellow_Cards_AwayTeam_sum_6,Away_Yellow_Cards_AwayTeam_sum_6,Home_Red_Cards_AwayTeam_sum_6,Away_Red_Cards_AwayTeam_sum_6,Home_Bookings_Points_AwayTeam_sum_6,Away_Bookings_Points_AwayTeam_sum_6,Final_result_AwayTeam_sum_6,Home_score_AwayTeam_sum_6,Away_score_AwayTeam_sum_6,Final_Home_goals_HomeTeam_median_6,Final_Away_goals_HomeTeam_median_6,Half_Time_Home_Goals_HomeTeam_median_6,Half_Time_Away_Goals_HomeTeam_median_6,Half_Time_Result_HomeTeam_median_6,Crowd_Attendance_HomeTeam_median_6,Home_Shots_HomeTeam_median_6,Away_Shots_HomeTeam_median_6,Home_Shots_Target_HomeTeam_median_6,Away_Shots_Target_HomeTeam_median_6,Home_Woodwork_HomeTeam_median_6,Away_Woodwork_HomeTeam_median_6,Home_Corners_HomeTeam_median_6,Away_Corners_HomeTeam_median_6,Home_Fouls_HomeTeam_median_6,Away_Fouls_HomeTeam_median_6,Home_Offsides_HomeTeam_median_6,Away_Offsides_HomeTeam_median_6,Home_Yellow_Cards_HomeTeam_median_6,Away_Yellow_Cards_HomeTeam_median_6,Home_Red_Cards_HomeTeam_median_6,Away_Red_Cards_HomeTeam_median_6,Home_Bookings_Points_HomeTeam_median_6,Away_Bookings_Points_HomeTeam_median_6,Final_result_HomeTeam_median_6,Home_score_HomeTeam_median_6,Away_score_HomeTeam_median_6,Final_Home_goals_AwayTeam_median_6,Final_Away_goals_AwayTeam_median_6,Half_Time_Home_Goals_AwayTeam_median_6,Half_Time_Away_Goals_AwayTeam_median_6,Half_Time_Result_AwayTeam_median_6,Crowd_Attendance_AwayTeam_median_6,Home_Shots_AwayTeam_median_6,Away_Shots_AwayTeam_median_6,Home_Shots_Target_AwayTeam_median_6,Away_Shots_Target_AwayTeam_median_6,Home_Woodwork_AwayTeam_median_6,Away_Woodwork_AwayTeam_median_6,Home_Corners_AwayTeam_median_6,Away_Corners_AwayTeam_median_6,Home_Fouls_AwayTeam_median_6,Away_Fouls_AwayTeam_median_6,Home_Offsides_AwayTeam_median_6,Away_Offsides_AwayTeam_median_6,Home_Yellow_Cards_AwayTeam_median_6,Away_Yellow_Cards_AwayTeam_median_6,Home_Red_Cards_AwayTeam_median_6,Away_Red_Cards_AwayTeam_median_6,Home_Bookings_Points_AwayTeam_median_6,Away_Bookings_Points_AwayTeam_median_6,Final_result_AwayTeam_median_6,Home_score_AwayTeam_median_6,Away_score_AwayTeam_median_6,Final_Home_goals_HomeTeam_average_6,Final_Away_goals_HomeTeam_average_6,Half_Time_Home_Goals_HomeTeam_average_6,Half_Time_Away_Goals_HomeTeam_average_6,Half_Time_Result_HomeTeam_average_6,Crowd_Attendance_HomeTeam_average_6,Home_Shots_HomeTeam_average_6,Away_Shots_HomeTeam_average_6,Home_Shots_Target_HomeTeam_average_6,Away_Shots_Target_HomeTeam_average_6,Home_Woodwork_HomeTeam_average_6,Away_Woodwork_HomeTeam_average_6,Home_Corners_HomeTeam_average_6,Away_Corners_HomeTeam_average_6,Home_Fouls_HomeTeam_average_6,Away_Fouls_HomeTeam_average_6,Home_Offsides_HomeTeam_average_6,Away_Offsides_HomeTeam_average_6,Home_Yellow_Cards_HomeTeam_average_6,Away_Yellow_Cards_HomeTeam_average_6,Home_Red_Cards_HomeTeam_average_6,Away_Red_Cards_HomeTeam_average_6,Home_Bookings_Points_HomeTeam_average_6,Away_Bookings_Points_HomeTeam_average_6,Final_result_HomeTeam_average_6,Home_score_HomeTeam_average_6,Away_score_HomeTeam_average_6,Final_Home_goals_AwayTeam_average_6,Final_Away_goals_AwayTeam_average_6,Half_Time_Home_Goals_AwayTeam_average_6,Half_Time_Away_Goals_AwayTeam_average_6,Half_Time_Result_AwayTeam_average_6,Crowd_Attendance_AwayTeam_average_6,Home_Shots_AwayTeam_average_6,Away_Shots_AwayTeam_average_6,Home_Shots_Target_AwayTeam_average_6,Away_Shots_Target_AwayTeam_average_6,Home_Woodwork_AwayTeam_average_6,Away_Woodwork_AwayTeam_average_6,Home_Corners_AwayTeam_average_6,Away_Corners_AwayTeam_average_6,Home_Fouls_AwayTeam_average_6,Away_Fouls_AwayTeam_average_6,Home_Offsides_AwayTeam_average_6,Away_Offsides_AwayTeam_average_6,Home_Yellow_Cards_AwayTeam_average_6,Away_Yellow_Cards_AwayTeam_average_6,Home_Red_Cards_AwayTeam_average_6,Away_Red_Cards_AwayTeam_average_6,Home_Bookings_Points_AwayTeam_average_6,Away_Bookings_Points_AwayTeam_average_6,Final_result_AwayTeam_average_6,Home_score_AwayTeam_average_6,Away_score_AwayTeam_average_6,Home_Shots_Home_AllGames_sum_6,Half_Time_Home_Goals_Home_AllGames_Average_6,Home_Offsides_Home_AllGames_Average_6,Final_Away_goals_Home_AllGames_sum_6,Final_Home_goals_Home_AllGames_sum_6,Half_Time_Away_Goals_Home_AllGames_Average_6,Home_Yellow_Cards_Home_AllGames_median_6,Home_Shots_Home_AllGames_median_6,Away_Fouls_Home_AllGames_Average_6,Away_Woodwork_Home_AllGames_Average_6,Away_Shots_Target_Home_AllGames_Average_6,Crowd_Attendance_Home_AllGames_Average_6,Away_Corners_Home_AllGames_median_6,Away_Bookings_Points_Home_AllGames_median_6,Home_Offsides_Home_AllGames_sum_6,Half_Time_Away_Goals_Home_AllGames_median_6,Away_Shots_Target_Home_AllGames_median_6,Final_Away_goals_Home_AllGames_median_6,Away_Shots_Target_Home_AllGames_sum_6,Away_Corners_Home_AllGames_sum_6,Away_Fouls_Home_AllGames_sum_6,Home_Corners_Home_AllGames_Average_6,Away_Shots_Home_AllGames_median_6,Away_Yellow_Cards_Home_AllGames_Average_6,Home_Woodwork_Home_AllGames_sum_6,Away_Fouls_Home_AllGames_median_6,Away_Red_Cards_Home_AllGames_median_6,Home_Yellow_Cards_Home_AllGames_Average_6,Crowd_Attendance_Home_AllGames_median_6,Home_Red_Cards_Home_AllGames_sum_6,Away_score_Home_AllGames_Average_6,Away_Woodwork_Home_AllGames_median_6,Away_Shots_Home_AllGames_Average_6,Home_Yellow_Cards_Home_AllGames_sum_6,Final_result_Home_AllGames_median_6,Home_Bookings_Points_Home_AllGames_Average_6,Half_Time_Result_Home_AllGames_median_6,Away_Woodwork_Home_AllGames_sum_6,Home_Bookings_Points_Home_AllGames_sum_6,Final_Home_goals_Home_AllGames_Average_6,Away_Offsides_Home_AllGames_median_6,Half_Time_Away_Goals_Home_AllGames_sum_6,Home_Fouls_Home_AllGames_sum_6,Final_result_Home_AllGames_Average_6,Away_Corners_Home_AllGames_Average_6,Home_score_Home_AllGames_median_6,Home_Red_Cards_Home_AllGames_Average_6,Half_Time_Home_Goals_Home_AllGames_sum_6,Away_Yellow_Cards_Home_AllGames_median_6,Away_Bookings_Points_Home_AllGames_sum_6,Away_Offsides_Home_AllGames_Average_6,Away_score_Home_AllGames_sum_6,Final_Away_goals_Home_AllGames_Average_6,Home_Bookings_Points_Home_AllGames_median_6,Home_Shots_Target_Home_AllGames_Average_6,Home_Woodwork_Home_AllGames_median_6,Half_Time_Result_Home_AllGames_sum_6,Home_Woodwork_Home_AllGames_Average_6,Home_Red_Cards_Home_AllGames_median_6,Home_score_Home_AllGames_sum_6,Home_Fouls_Home_AllGames_Average_6,Half_Time_Result_Home_AllGames_Average_6,Home_Shots_Target_Home_AllGames_median_6,Home_Corners_Home_AllGames_sum_6,Away_Yellow_Cards_Home_AllGames_sum_6,Final_result_Home_AllGames_sum_6,Home_Shots_Home_AllGames_Average_6,Half_Time_Home_Goals_Home_AllGames_median_6,Home_Fouls_Home_AllGames_median_6,Away_Shots_Home_AllGames_sum_6,Home_Shots_Target_Home_AllGames_sum_6,Away_Offsides_Home_AllGames_sum_6,Away_Bookings_Points_Home_AllGames_Average_6,Crowd_Attendance_Home_AllGames_sum_6,Home_Offsides_Home_AllGames_median_6,Away_Red_Cards_Home_AllGames_Average_6,Home_Corners_Home_AllGames_median_6,Away_Red_Cards_Home_AllGames_sum_6,Final_Home_goals_Home_AllGames_median_6,Away_score_Home_AllGames_median_6,Home_score_Home_AllGames_Average_6,Away_Corners_Away_AllGames_Average_6,Away_Shots_Away_AllGames_Average_6,Home_Corners_Away_AllGames_sum_6,Crowd_Attendance_Away_AllGames_median_6,Home_Offsides_Away_AllGames_Average_6,Home_Woodwork_Away_AllGames_Average_6,Away_Yellow_Cards_Away_AllGames_sum_6,Away_Fouls_Away_AllGames_Average_6,Away_Bookings_Points_Away_AllGames_median_6,Final_Home_goals_Away_AllGames_Average_6,Away_Yellow_Cards_Away_AllGames_Average_6,Away_Red_Cards_Away_AllGames_sum_6,Away_Offsides_Away_AllGames_sum_6,Crowd_Attendance_Away_AllGames_Average_6,Final_Away_goals_Away_AllGames_median_6,Away_Red_Cards_Away_AllGames_Average_6,Home_Bookings_Points_Away_AllGames_sum_6,Half_Time_Result_Away_AllGames_median_6,Home_Bookings_Points_Away_AllGames_median_6,Away_Corners_Away_AllGames_median_6,Home_Shots_Target_Away_AllGames_median_6,Home_Shots_Away_AllGames_sum_6,Home_Corners_Away_AllGames_Average_6,Away_Red_Cards_Away_AllGames_median_6,Home_score_Away_AllGames_Average_6,Away_Shots_Away_AllGames_sum_6,Home_Woodwork_Away_AllGames_sum_6,Home_Fouls_Away_AllGames_median_6,Home_Red_Cards_Away_AllGames_median_6,Half_Time_Home_Goals_Away_AllGames_sum_6,Away_Shots_Target_Away_AllGames_Average_6,Home_Red_Cards_Away_AllGames_sum_6,Final_Away_goals_Away_AllGames_Average_6,Home_Shots_Target_Away_AllGames_Average_6,Half_Time_Away_Goals_Away_AllGames_sum_6,Home_Yellow_Cards_Away_AllGames_sum_6,Home_Shots_Away_AllGames_median_6,Home_Yellow_Cards_Away_AllGames_median_6,Away_Offsides_Away_AllGames_Average_6,Away_Bookings_Points_Away_AllGames_sum_6,Final_result_Away_AllGames_Average_6,Home_score_Away_AllGames_sum_6,Away_Corners_Away_AllGames_sum_6,Away_Shots_Away_AllGames_median_6,Away_Fouls_Away_AllGames_median_6,Half_Time_Result_Away_AllGames_Average_6,Away_Woodwork_Away_AllGames_median_6,Away_Offsides_Away_AllGames_median_6,Home_Shots_Away_AllGames_Average_6,Away_Yellow_Cards_Away_AllGames_median_6,Away_score_Away_AllGames_sum_6,Away_Fouls_Away_AllGames_sum_6,Home_Shots_Target_Away_AllGames_sum_6,Half_Time_Away_Goals_Away_AllGames_median_6,Home_Bookings_Points_Away_AllGames_Average_6,Half_Time_Away_Goals_Away_AllGames_Average_6,Home_Fouls_Away_AllGames_sum_6,Away_score_Away_AllGames_Average_6,Final_Home_goals_Away_AllGames_median_6,Away_Woodwork_Away_AllGames_Average_6,Half_Time_Home_Goals_Away_AllGames_median_6,Final_Home_goals_Away_AllGames_sum_6,Final_result_Away_AllGames_sum_6,Final_result_Away_AllGames_median_6,Half_Time_Home_Goals_Away_AllGames_Average_6,Final_Away_goals_Away_AllGames_sum_6,Crowd_Attendance_Away_AllGames_sum_6,Home_Offsides_Away_AllGames_median_6,Home_Fouls_Away_AllGames_Average_6,Home_Red_Cards_Away_AllGames_Average_6,Home_Woodwork_Away_AllGames_median_6,Away_score_Away_AllGames_median_6,Half_Time_Result_Away_AllGames_sum_6,Away_Woodwork_Away_AllGames_sum_6,Home_Corners_Away_AllGames_median_6,Away_Bookings_Points_Away_AllGames_Average_6,Away_Shots_Target_Away_AllGames_median_6,Away_Shots_Target_Away_AllGames_sum_6,Home_Offsides_Away_AllGames_sum_6,Home_Yellow_Cards_Away_AllGames_Average_6,Home_score_Away_AllGames_median_6,Date_6Away_of_home_sum,Final_Home_goals_6Away_of_home_sum,Final_Away_goals_6Away_of_home_sum,Half_Time_Home_Goals_6Away_of_home_sum,Half_Time_Away_Goals_6Away_of_home_sum,Half_Time_Result_6Away_of_home_sum,Crowd_Attendance_6Away_of_home_sum,Home_Shots_6Away_of_home_sum,Away_Shots_6Away_of_home_sum,Home_Shots_Target_6Away_of_home_sum,Away_Shots_Target_6Away_of_home_sum,Home_Woodwork_6Away_of_home_sum,Away_Woodwork_6Away_of_home_sum,Home_Corners_6Away_of_home_sum,Away_Corners_6Away_of_home_sum,Home_Fouls_6Away_of_home_sum,Away_Fouls_6Away_of_home_sum,Home_Offsides_6Away_of_home_sum,Away_Offsides_6Away_of_home_sum,Home_Yellow_Cards_6Away_of_home_sum,Away_Yellow_Cards_6Away_of_home_sum,Home_Red_Cards_6Away_of_home_sum,Away_Red_Cards_6Away_of_home_sum,Home_Bookings_Points_6Away_of_home_sum,Away_Bookings_Points_6Away_of_home_sum,Final_result_6Away_of_home_sum,Home_score_6Away_of_home_sum,Away_score_6Away_of_home_sum,menha_date_6Away_of_home_sum,Date_6Away_of_home_median,Final_Home_goals_6Away_of_home_median,Final_Away_goals_6Away_of_home_median,Half_Time_Home_Goals_6Away_of_home_median,Half_Time_Away_Goals_6Away_of_home_median,Half_Time_Result_6Away_of_home_median,Crowd_Attendance_6Away_of_home_median,Home_Shots_6Away_of_home_median,Away_Shots_6Away_of_home_median,Home_Shots_Target_6Away_of_home_median,Away_Shots_Target_6Away_of_home_median,Home_Woodwork_6Away_of_home_median,Away_Woodwork_6Away_of_home_median,Home_Corners_6Away_of_home_median,Away_Corners_6Away_of_home_median,Home_Fouls_6Away_of_home_median,Away_Fouls_6Away_of_home_median,Home_Offsides_6Away_of_home_median,Away_Offsides_6Away_of_home_median,Home_Yellow_Cards_6Away_of_home_median,Away_Yellow_Cards_6Away_of_home_median,Home_Red_Cards_6Away_of_home_median,Away_Red_Cards_6Away_of_home_median,Home_Bookings_Points_6Away_of_home_median,Away_Bookings_Points_6Away_of_home_median,Final_result_6Away_of_home_median,Home_score_6Away_of_home_median,Away_score_6Away_of_home_median,menha_date_6Away_of_home_median,Date_6Away_of_home_mean,Final_Home_goals_6Away_of_home_mean,Final_Away_goals_6Away_of_home_mean,Half_Time_Home_Goals_6Away_of_home_mean,Half_Time_Away_Goals_6Away_of_home_mean,Half_Time_Result_6Away_of_home_mean,Crowd_Attendance_6Away_of_home_mean,Home_Shots_6Away_of_home_mean,Away_Shots_6Away_of_home_mean,Home_Shots_Target_6Away_of_home_mean,Away_Shots_Target_6Away_of_home_mean,Home_Woodwork_6Away_of_home_mean,Away_Woodwork_6Away_of_home_mean,Home_Corners_6Away_of_home_mean,Away_Corners_6Away_of_home_mean,Home_Fouls_6Away_of_home_mean,Away_Fouls_6Away_of_home_mean,Home_Offsides_6Away_of_home_mean,Away_Offsides_6Away_of_home_mean,Home_Yellow_Cards_6Away_of_home_mean,Away_Yellow_Cards_6Away_of_home_mean,Home_Red_Cards_6Away_of_home_mean,Away_Red_Cards_6Away_of_home_mean,Home_Bookings_Points_6Away_of_home_mean,Away_Bookings_Points_6Away_of_home_mean,Final_result_6Away_of_home_mean,Home_score_6Away_of_home_mean,Away_score_6Away_of_home_mean,menha_date_6Away_of_home_mean,Date_6Home_of_away_sum,Final_Home_goals_6Home_of_away_sum,Final_Away_goals_6Home_of_away_sum,Half_Time_Home_Goals_6Home_of_away_sum,Half_Time_Away_Goals_6Home_of_away_sum,Half_Time_Result_6Home_of_away_sum,Crowd_Attendance_6Home_of_away_sum,Home_Shots_6Home_of_away_sum,Away_Shots_6Home_of_away_sum,Home_Shots_Target_6Home_of_away_sum,Away_Shots_Target_6Home_of_away_sum,Home_Woodwork_6Home_of_away_sum,Away_Woodwork_6Home_of_away_sum,Home_Corners_6Home_of_away_sum,Away_Corners_6Home_of_away_sum,Home_Fouls_6Home_of_away_sum,Away_Fouls_6Home_of_away_sum,Home_Offsides_6Home_of_away_sum,Away_Offsides_6Home_of_away_sum,Home_Yellow_Cards_6Home_of_away_sum,Away_Yellow_Cards_6Home_of_away_sum,Home_Red_Cards_6Home_of_away_sum,Away_Red_Cards_6Home_of_away_sum,Home_Bookings_Points_6Home_of_away_sum,Away_Bookings_Points_6Home_of_away_sum,Final_result_6Home_of_away_sum,Home_score_6Home_of_away_sum,Away_score_6Home_of_away_sum,menha_date_6Home_of_away_sum,Date_6Home_of_away_median,Final_Home_goals_6Home_of_away_median,Final_Away_goals_6Home_of_away_median,Half_Time_Home_Goals_6Home_of_away_median,Half_Time_Away_Goals_6Home_of_away_median,Half_Time_Result_6Home_of_away_median,Crowd_Attendance_6Home_of_away_median,Home_Shots_6Home_of_away_median,Away_Shots_6Home_of_away_median,Home_Shots_Target_6Home_of_away_median,Away_Shots_Target_6Home_of_away_median,Home_Woodwork_6Home_of_away_median,Away_Woodwork_6Home_of_away_median,Home_Corners_6Home_of_away_median,Away_Corners_6Home_of_away_median,Home_Fouls_6Home_of_away_median,Away_Fouls_6Home_of_away_median,Home_Offsides_6Home_of_away_median,Away_Offsides_6Home_of_away_median,Home_Yellow_Cards_6Home_of_away_median,Away_Yellow_Cards_6Home_of_away_median,Home_Red_Cards_6Home_of_away_median,Away_Red_Cards_6Home_of_away_median,Home_Bookings_Points_6Home_of_away_median,Away_Bookings_Points_6Home_of_away_median,Final_result_6Home_of_away_median,Home_score_6Home_of_away_median,Away_score_6Home_of_away_median,menha_date_6Home_of_away_median,Date_6Home_of_away_mean,Final_Home_goals_6Home_of_away_mean,Final_Away_goals_6Home_of_away_mean,Half_Time_Home_Goals_6Home_of_away_mean,Half_Time_Away_Goals_6Home_of_away_mean,Half_Time_Result_6Home_of_away_mean,Crowd_Attendance_6Home_of_away_mean,Home_Shots_6Home_of_away_mean,Away_Shots_6Home_of_away_mean,Home_Shots_Target_6Home_of_away_mean,Away_Shots_Target_6Home_of_away_mean,Home_Woodwork_6Home_of_away_mean,Away_Woodwork_6Home_of_away_mean,Home_Corners_6Home_of_away_mean,Away_Corners_6Home_of_away_mean,Home_Fouls_6Home_of_away_mean,Away_Fouls_6Home_of_away_mean,Home_Offsides_6Home_of_away_mean,Away_Offsides_6Home_of_away_mean,Home_Yellow_Cards_6Home_of_away_mean,Away_Yellow_Cards_6Home_of_away_mean,Home_Red_Cards_6Home_of_away_mean,Away_Red_Cards_6Home_of_away_mean,Home_Bookings_Points_6Home_of_away_mean,Away_Bookings_Points_6Home_of_away_mean,Final_result_6Home_of_away_mean,Home_score_6Home_of_away_mean,Away_score_6Home_of_away_mean,menha_date_6Home_of_away_mean
0,2000-08-19,Charlton,Man City,4.0,0.0,2.0,0.0,1,20043.0,Rob Harris,17.0,8.0,14.0,4.0,2.0,1.0,6.0,6.0,13.0,12.0,8.0,6.0,1.0,2.0,0.0,0.0,10.0,20.0,1.0,3.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [179]:
df_naha.loc[:,df_naha.columns.str.contains('Final_Home_goals')].columns

Index(['Final_Home_goals', 'Final_Home_goals_HomeTeam_sum_6',
       'Final_Home_goals_AwayTeam_sum_6', 'Final_Home_goals_HomeTeam_median_6',
       'Final_Home_goals_AwayTeam_median_6',
       'Final_Home_goals_HomeTeam_average_6',
       'Final_Home_goals_AwayTeam_average_6',
       'Final_Home_goals_Home_AllGames_sum_6',
       'Final_Home_goals_Home_AllGames_Average_6',
       'Final_Home_goals_Home_AllGames_median_6',
       'Final_Home_goals_Away_AllGames_Average_6',
       'Final_Home_goals_Away_AllGames_median_6',
       'Final_Home_goals_Away_AllGames_sum_6',
       'Final_Home_goals_6Away_of_home_sum',
       'Final_Home_goals_6Away_of_home_median',
       'Final_Home_goals_6Away_of_home_mean',
       'Final_Home_goals_6Home_of_away_sum',
       'Final_Home_goals_6Home_of_away_median',
       'Final_Home_goals_6Home_of_away_mean'],
      dtype='object')

In [180]:
df_naha.loc[df_naha['HomeTeam']=='Leicester'].to_csv('Leicester.csv')

In [181]:
df_naha.loc[df_naha['AwayTeam']=='Leicester'].to_csv('LeicesterAway.csv')

In [182]:
cols= set(df_naha.columns.to_list()) - set(df_naha.loc[:,'AwayTeam':'Away_score'].columns.to_list())

In [183]:
df_naha=df_naha.loc[:,cols]

In [184]:
df.head(1)

,Date,HomeTeam,AwayTeam,Final_Home_goals,Final_Away_goals,Half_Time_Home_Goals,Half_Time_Away_Goals,Half_Time_Result,Crowd_Attendance,Referee,Home_Shots,Away_Shots,Home_Shots_Target,Away_Shots_Target,Home_Woodwork,Away_Woodwork,Home_Corners,Away_Corners,Home_Fouls,Away_Fouls,Home_Offsides,Away_Offsides,Home_Yellow_Cards,Away_Yellow_Cards,Home_Red_Cards,Away_Red_Cards,Home_Bookings_Points,Away_Bookings_Points,GBH,GBD,GBA,IWH,IWD,IWA,LBH,LBD,LBA,SBH,SBD,SBA,WHH,WHD,WHA,SYH,SYD,SYA,B365H,B365D,B365A,SOH,SOD,SOA,GB>2.5,GB<2.5,B365>2.5,B365<2.5,GBAHH,GBAHA,GBAH,LBAHH,LBAHA,LBAH,B365AHH,B365AHA,B365AH,BWH,BWD,BWA,SJH,SJD,SJA,VCH,VCD,VCA,Bb1X2,BbMxH,BbAvH,BbMxD,BbAvD,BbMxA,BbAvA,BbOU,BbMx>2.5,BbAv>2.5,BbMx<2.5,BbAv<2.5,BbAH,BbAHh,BbMxAHH,BbAvAHH,BbMxAHA,BbAvAHA,BSH,BSD,BSA,PSH,PSD,PSA,PSCH,PSCD,PSCA,Time,MaxH,MaxD,MaxA,AvgH,AvgD,AvgA,P>2.5,P<2.5,Max>2.5,Max<2.5,Avg>2.5,Avg<2.5,AHh,PAHH,PAHA,MaxAHH,MaxAHA,AvgAHH,AvgAHA,B365CH,B365CD,B365CA,BWCH,BWCD,BWCA,IWCH,IWCD,IWCA,WHCH,WHCD,WHCA,VCCH,VCCD,VCCA,MaxCH,MaxCD,MaxCA,AvgCH,AvgCD,AvgCA,B365C>2.5,B365C<2.5,PC>2.5,PC<2.5,MaxC>2.5,MaxC<2.5,AvgC>2.5,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,Season,Final_result,Winner,Home_score,Away_score,Corners_ratio
0,2000-08-19,Charlton,Man City,4.0,0.0,2.0,0.0,1,20043.0,Rob Harris,17.0,8.0,14.0,4.0,2.0,1.0,6.0,6.0,13.0,12.0,8.0,6.0,1.0,2.0,0.0,0.0,10.0,20.0,2.0,3.0,3.2,2.2,2.9,2.7,2.2,3.25,2.75,2.2,3.25,2.88,2.1,3.2,3.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,Charlton,3.0,0.0,0.5

In [185]:
df_ready= pd.merge(df, df_naha, how='left', on=['Date', 'HomeTeam'])

In [186]:
df_ready.head(1)

,Date,HomeTeam,AwayTeam,Final_Home_goals,Final_Away_goals,Half_Time_Home_Goals,Half_Time_Away_Goals,Half_Time_Result,Crowd_Attendance,Referee,Home_Shots,Away_Shots,Home_Shots_Target,Away_Shots_Target,Home_Woodwork,Away_Woodwork,Home_Corners,Away_Corners,Home_Fouls,Away_Fouls,Home_Offsides,Away_Offsides,Home_Yellow_Cards,Away_Yellow_Cards,Home_Red_Cards,Away_Red_Cards,Home_Bookings_Points,Away_Bookings_Points,GBH,GBD,GBA,IWH,IWD,IWA,LBH,LBD,LBA,SBH,SBD,SBA,WHH,WHD,WHA,SYH,SYD,SYA,B365H,B365D,B365A,SOH,SOD,SOA,GB>2.5,GB<2.5,B365>2.5,B365<2.5,GBAHH,GBAHA,GBAH,LBAHH,LBAHA,LBAH,B365AHH,B365AHA,B365AH,BWH,BWD,BWA,SJH,SJD,SJA,VCH,VCD,VCA,Bb1X2,BbMxH,BbAvH,BbMxD,BbAvD,BbMxA,BbAvA,BbOU,BbMx>2.5,BbAv>2.5,BbMx<2.5,BbAv<2.5,BbAH,BbAHh,BbMxAHH,BbAvAHH,BbMxAHA,BbAvAHA,BSH,BSD,BSA,PSH,PSD,PSA,PSCH,PSCD,PSCA,Time,MaxH,MaxD,MaxA,AvgH,AvgD,AvgA,P>2.5,P<2.5,Max>2.5,Max<2.5,Avg>2.5,Avg<2.5,AHh,PAHH,PAHA,MaxAHH,MaxAHA,AvgAHH,AvgAHA,B365CH,B365CD,B365CA,BWCH,BWCD,BWCA,IWCH,IWCD,IWCA,WHCH,WHCD,WHCA,VCCH,VCCD,VCCA,MaxCH,MaxCD,MaxCA,AvgCH,AvgCD,AvgCA,B365C>2.5,B365C<2.5,PC>2.5,PC<2.5,MaxC>2.5,MaxC<2.5,AvgC>2.5,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,Season,Final_result,Winner,Home_score,Away_score,Corners_ratio,Away_Corners_Away_AllGames_Average_6,Away_Corners_AwayTeam_median_6,Home_score_6Away_of_home_sum,Crowd_Attendance_6Home_of_away_mean,Date_6Home_of_away_sum,Home_Yellow_Cards_HomeTeam_median_6,Away_Shots_6Away_of_home_median,Away_Offsides_HomeTeam_average_6,Home_Corners_AwayTeam_average_6,Half_Time_Result_6Home_of_away_mean,Away_Offsides_6Home_of_away_mean,Away_Fouls_Away_AllGames_Average_6,Away_Bookings_Points_6Home_of_away_median,Away_score_HomeTeam_median_6,Away_Woodwork_Home_AllGames_Average_6,Away_Offsides_Away_AllGames_sum_6,Away_Offsides_6Home_of_away_sum,Home_Offsides_6Home_of_away_mean,Final_Away_goals_Away_AllGames_median_6,Home_Bookings_Points_Away_AllGames_sum_6,Away_score_AwayTeam_median_6,Home_Yellow_Cards_6Away_of_home_mean,Home_Bookings_Points_AwayTeam_average_6,Away_Shots_Target_6Away_of_home_mean,Date_6Home_of_away_mean,Half_Time_Away_Goals_Home_AllGames_median_6,Half_Time_Home_Goals_HomeTeam_median_6,Home_score_AwayTeam_sum_6,Final_Away_goals_Home_AllGames_median_6,Away_Shots_Target_Home_AllGames_sum_6,Home_score_Away_AllGames_Average_6,Away_Woodwork_6Home_of_away_mean,Away_Shots_Home_AllGames_median_6,Final_result_6Home_of_away_sum,Home_Woodwork_Home_AllGames_sum_6,Half_Time_Home_Goals_Away_AllGames_sum_6,Home_Offsides_AwayTeam_median_6,Away_Shots_Target_Away_AllGames_Average_6,Home_Yellow_Cards_Away_AllGames_sum_6,Home_Corners_6Home_of_away_median,Away_Fouls_6Away_of_home_mean,menha_date_6Home_of_away_sum,Home_Red_Cards_6Away_of_home_sum,Home_Woodwork_AwayTeam_median_6,Away_Shots_Away_AllGames_median_6,Away_Offsides_Away_AllGames_median_6,Home_Bookings_Points_6Away_of_home_mean,Home_Shots_AwayTeam_sum_6,Home_Shots_AwayTeam_median_6,Away_Woodwork_Home_AllGames_median_6,Half_Time_Away_Goals_AwayTeam_median_6,Away_Red_Cards_HomeTeam_sum_6,Away_Offsides_AwayTeam_median_6,Final_Home_goals_HomeTeam_average_6,Away_Red_Cards_6Away_of_home_mean,Crowd_Attendance_AwayTeam_sum_6,Home_Woodwork_6Home_of_away_sum,Home_Yellow_Cards_HomeTeam_average_6,Home_Woodwork_AwayTeam_sum_6,Half_Time_Away_Goals_Away_AllGames_Average_6,Final_result_HomeTeam_median_6,Final_Away_goals_AwayTeam_median_6,Home_Bookings_Points_6Home_of_away_sum,Home_Shots_Target_AwayTeam_sum_6,Half_Time_Away_Goals_Home_AllGames_sum_6,Home_Fouls_6Away_of_home_median,Final_Home_goals_Away_AllGames_median_6,Away_Woodwork_Away_AllGames_Average_6,Home_Fouls_Home_AllGames_sum_6,Final_result_Home_AllGames_Average_6,Final_result_HomeTeam_average_6,Away_Fouls_AwayTeam_sum_6,Away_score_6Away_of_home_sum,Final_Home_goals_AwayTeam_median_6,Final_Away_goals_6Away_of_home_median,Home_Offsides_6Away_of_home_sum,Home_score_HomeTeam_average_6,Away_Fouls_6Away_of_home_sum,Away_Red_Cards_6Away_of_home_median,Home_Yellow_Cards_6Home_of_away_sum,Away_Shots_HomeTeam_median_6,Date_6Away_of_home_sum,Away_Bookings_Points_Home_AllGames_sum_6,Home_Offsides_AwayTeam_average_6,Away_Bookings_Points_HomeTeam_median_6,Home_Yellow_Cards_AwayTeam_sum_6,Home_Corners_AwayTeam_median_6,Home_Offsides_Away_AllGames_median_6,Home_Woodwork_AwayTeam_average_6,Home_Red_Cards_Away_AllGames_Average_6,Away_Corners_6Away_of_home_median,Final_Away_goals_Home_AllGames_Average_6,Half_Time_Home_Goals_6Home_of_away_sum,Final_Home_goals_6Away_of_home_median,Home_Woodwork_Away_AllGames_median_6,Away_Offsides_6Home_of_away_median,Home_Red_Cards_Home_AllGames_median_6,Away_Corners_6Home_of_away_sum,Home_score_Home_AllGames_sum_6,Home_Fouls_Home_AllGames_Average_6,Half_Time_Result_Home_AllGames_Average_6,Half_Time_Result_Away_AllGames_sum_6,Half_Time_Away_Goals_HomeTeam_average_6,menha_date_6Away_of_home_median,Home_Corners_Home_AllGames_sum_6,Away_Yellow_Cards_Home_AllGames_sum_6,Final_Home_goals_AwayTeam_average_6,Half_Time_Home_Goals_Home_AllGames_median_6,Away_Shots_6Away_of_home_mean,Half_Time_Away_Goals_6Away_of_home_mean,Away_Fouls_6Home_of_away_sum,Half_Time_Result_HomeTeam_median_6,Home_Shots_Target_Home_AllGames_sum_6,Away_Shots_Target_Away_AllGames_median_6,Home_Red_Cards_6Away_of_home_mean,Away_Yellow_Cards_6Home_of_away_sum,Final_Home_goals_HomeTeam_median_6,Home_Woodwork_6Away_of_home_sum,Home_Offsides_Home_AllGames_median_6,Home_score_6Home_of_away_median,menha_date_6Away_of_home_mean,Away_Bookings_Points_6Home_of_away_sum,Final_result_AwayTeam_average_6,Home_score_Home_AllGames_Average_6,Away_Corners_6Away_of_home_mean,Home_Red_Cards_6Home_of_away_mean,Away_Shots_6Home_of_away_mean,Home_Shots_6Away_of_home_sum,Away_Woodwork_6Home_of_away_sum,Home_Offsides_Home_AllGames_Average_6,Final_Away_goals_Home_AllGames_sum_6,Home_Offsides_Away_AllGames_Average_6,Half_Time_Away_Goals_6Home_of_away_mean,Away_Red_Cards_HomeTeam_median_6,Half_Time_Away_Goals_Home_AllGames_Average_6,Home_Woodwork_Away_AllGames_Average_6,Away_Red_Cards_HomeTeam_average_6,Home_Yellow_Cards_Home_AllGames_median_6,Final_result_6Away_of_home_mean,Home_Fouls_6Home_of_away_mean,Away_Yellow_Cards_Away_AllGames_sum_6,Away_Red_Cards_6Home_of_away_mean,Away_Shots_Target_6Home_of_away_median,Home_Shots_HomeTeam_median_6,Crowd_Attendance_6Home_of_away_median,Home_Offsides_AwayTeam_sum_6,Away_score_6Away_of_home_mean,menha_date_6Home_of_away_mean,Home_Shots_Target_HomeTeam_sum_6,Half_Time_Result_AwayTeam_average_6,Away_Shots_Target_Home_AllGames_Average_6,Final_Away_goals_HomeTeam_sum_6,Away_Yellow_Cards_AwayTeam_average_6,Half_Time_Home_Goals_6Home_of_away_median,Home_Offsides_Home_AllGames_sum_6,Home_Corners_Away_AllGames_Average_6,Away_Red_Cards_Away_AllGames_median_6,Away_Shots_Target_Home_AllGames_median_6,Half_Time_Away_Goals_6Home_of_away_sum,Home_Fouls_HomeTeam_sum_6,Away_Corners_Home_AllGames_sum_6,Crowd_Attendance_AwayTeam_median_6,Home_Fouls_Away_AllGames_median_6,Home_Red_Cards_Away_AllGames_median_6,Away_Corners_AwayTeam_sum_6,Final_Away_goals_HomeTeam_average_6,Away_Shots_Target_HomeTeam_median_6,Crowd_Attendance_6Away_of_home_sum,Away_Yellow_Cards_6Away_of_home_mean,Away_Shots_Target_AwayTeam_sum_6,Home_Yellow_Cards_Away_AllGames_median_6,Home_Fouls_AwayTeam_sum_6,Away_Red_Cards_Home_AllGames_median_6,Away_Offsides_Away_AllGames_Average_6,Away_Yellow_Cards_6Home_of_away_median,Half_Time_Away_Goals_AwayTeam_sum_6,Final_result_Away_AllGames_Average_6,Away_Corners_HomeTeam_median_6,Away_Fouls_Away_AllGames_median_6,Home_Yellow_Cards_Home_AllGames_Average_6,Away_Bookings_Points_AwayTeam_average_6,Home_Fouls_6Home_of_away_median,Home_Red_Cards_HomeTeam_sum_6,Away_Yellow_Cards_Away_AllGames_median_6,Home_Red_Cards_Home_AllGames_sum_6,Home_Fouls_HomeTeam_average_6,Away_Corners_6Home_of_away_median,Home_Yellow_Cards_AwayTeam_median_6,Away_score_Away_AllGames_sum_6,Away_Fouls_Away_AllGames_sum_6,Away_Shots_Home_AllGames_Average_6,Final_result_Home_AllGames_median_6,Home_Shots_Target_Away_AllGames_sum_6,Away_Corners_AwayTeam_average_6,Away_Yellow_Cards_HomeTeam_average_6,Away_Shots_HomeTeam_average_6,Final_Away_goals_6Home_of_away_mean,Home_Fouls_Away_AllGames_sum_6,Away_score_Away_AllGames_Average_6,Final_Home_goals_6Home_of_away_mean,Home_Corners_6Home_of_away_sum,Home_Fouls_AwayTeam_median_6,Home_Corners_AwayTeam_sum_6,Home_Yellow_Cards_6Away_of_home_sum,Crowd_Attendance_6Home_of_away_sum,Away_Bookings_Points_AwayTeam_sum_6,Final_result_Away_AllGames_sum_6,Half_Time_Home_Goals_Away_AllGames_Average_6,Home_Shots_6Home_of_away_mean,Away_Yellow_Cards_Home_AllGames_median_6,Home_Shots_Target_AwayTeam_average_6,Away_Shots_Target_6Away_of_home_sum,Final_Away_goals_Away_AllGames_sum_6,Home_Bookings_Points_HomeTeam_average_6,Away_Woodwork_HomeTeam_average_6,Away_Offsides_Home_AllGames_Average_6,Home_Fouls_HomeTeam_median_6,Away_Corners_HomeTeam_sum_6,Home_Shots_Target_Home_AllGames_Average_6,Home_Woodwork_Home_AllGames_median_6,Home_Bookings_Points_6Away_of_home_median,Home_Shots_Target_Home_AllGames_median_6,Away_Yellow_Cards_AwayTeam_sum_6,Final_result_AwayTeam_sum_6,Home_Corners_Away_AllGames_median_6,Home_score_6Away_of_home_median,Home_Corners_6Away_of_home_mean,Away_Bookings_Points_Away_AllGames_Average_6,Away_Shots_Home_AllGames_sum_6,Home_Yellow_Cards_6Home_of_away_median,Home_Woodwork_6Home_of_away_mean,Crowd_Attendance_HomeTeam_sum_6,Away_Bookings_Points_Home_AllGames_Average_6,Home_Offsides_HomeTeam_sum_6,Home_Woodwork_HomeTeam_sum_6,Home_Offsides_6Home_of_away_sum,Away_Red_Cards_Home_AllGames_Average_6,Home_Corners_HomeTeam_sum_6,Home_Shots_Target_6Away_of_home_median,Away_score_6Home_of_away_mean,Home_Shots_6Away_of_home_median,Half_Time_Result_6Home_of_away_sum,Home_Shots_AwayTeam_average_6,Home_Shots_Target_6Home_of_away_sum,Away_score_Home_AllGames_median_6,Half_Time_Result_AwayTeam_median_6,Away_Red_Cards_AwayTeam_median_6,Home_score_Away_AllGames_median_6,Away_Corners_HomeTeam_average_6,Away_Shots_Away_AllGames_Average_6,Home_Bookings_Points_AwayTeam_sum_6,Half_Time_Home_Goals_Home_AllGames_Average_6,Home_Corners_Away_AllGames_sum_6,Home_Offsides_HomeTeam_median_6,Final_Away_goals_HomeTeam_median_6,Away_Woodwork_6Away_of_home_mean,Home_Red_Cards_AwayTeam_average_6,Home_Shots_Home_AllGames_median_6,Final_Home_goals_Away_AllGames_Average_6,Away_Corners_6Away_of_home_sum,Away_Fouls_Home_AllGames_Average_6,Away_Woodwork_AwayTeam_median_6,Away_Offsides_6Away_of_home_mean,Crowd_Attendance_Away_AllGames_Average_6,Half_Time_Home_Goals_6Home_of_away_mean,Away_Red_Cards_Away_AllGames_Average_6,Home_Bookings_Points_Away_AllGames_median_6,Date_6Away_of_home_mean,Home_Yellow_Cards_AwayTeam_average_6,Away_Corners_Home_AllGames_median_6,Away_Corners_Away_AllGames_median_6,Away_Bookings_Points_Home_AllGames_median_6,Home_Shots_Target_Away_AllGames_median_6,Half_Time_Home_Goals_6Away_of_home_mean,Away_Red_Cards_6Home_of_away_median,Home_Bookings_Points_6Home_of_away_median,Half_Time_Result_HomeTeam_sum_6,Final_Away_goals_6Away_of_home_sum,Away_score_6Away_of_home_median,Away_score_HomeTeam_average_6,Away_Shots_Away_AllGames_sum_6,Home_Woodwork_Away_AllGames_sum_6,Home_Yellow_Cards_6Home_of_away_mean,Away_score_HomeTeam_sum_6,Away_Fouls_6Away_of_home_median,Final_Away_goals_Away_AllGames_Average_6,Away_Fouls_6Home_of_away_mean,Half_Time_Home_Goals_6Away_of_home_median,Away_Bookings_Points_Away_AllGames_sum_6,Away_score_6Home_of_away_median,Away_Fouls_AwayTeam_average_6,Home_score_Away_AllGames_sum_6,menha_date_6Away_of_home_sum,Home_Red_Cards_6Home_of_away_sum,Home_Shots_Away_AllGames_Average_6,Home_score_AwayTeam_average_6,Away_score_6Home_of_away_sum,Home_Yellow_Cards_Home_AllGames_sum_6,Home_Bookings_Points_Home_AllGames_Average_6,Away_Woodwork_Home_AllGames_sum_6,Crowd_Attendance_HomeTeam_median_6,Final_result_6Away_of_home_sum,Away_Woodwork_6Home_of_away_median,Final_Home_goals_6Away_of_home_mean,Away_Offsides_6Away_of_home_sum,Final_Away_goals_6Away_of_home_mean,Final_Home_goals_Home_AllGames_Average_6,Home_score_HomeTeam_sum_6,Away_Offsides_Home_AllGames_median_6,Home_Shots_HomeTeam_sum_6,Home_Corners_6Home_of_away_mean,Half_Time_Home_Goals_Away_AllGames_median_6,Half_Time_Home_Goals_AwayTeam_average_6,Away_Yellow_Cards_6Home_of_away_mean,Final_Home_goals_Away_AllGames_sum_6,Away_score_AwayTeam_average_6,menha_date_6Home_of_away_median,Home_score_AwayTeam_median_6,Away_Shots_Target_HomeTeam_average_6,Home_Corners_HomeTeam_average_6,Half_Time_Home_Goals_AwayTeam_median_6,Away_score_Home_AllGames_sum_6,Home_Shots_6Away_of_home_mean,Away_Yellow_Cards_HomeTeam_median_6,Final_Away_goals_AwayTeam_sum_6,Home_Bookings_Points_Home_AllGames_median_6,Away_Corners_6Home_of_away_mean,Half_Time_Away_Goals_6Away_of_home_sum,Away_Shots_AwayTeam_median_6,Home_Woodwork_Home_AllGames_Average_6,Half_Time_Result_6Away_of_home_mean,Home_Fouls_6Away_of_home_sum,Home_score_6Home_of_away_sum,Home_Fouls_AwayTeam_average_6,Final_Away_goals_6Home_of_away_median,Away_Woodwork_HomeTeam_median_6,Away_Offsides_Home_AllGames_sum_6,Crowd_Attendance_Home_AllGames_sum_6,Home_Bookings_Points_HomeTeam_median_6,Home_Corners_Home_AllGames_median_6,Away_Red_Cards_Home_AllGames_sum_6,Final_Home_goals_Home_AllGames_median_6,Final_result_6Home_of_away_median,Crowd_Attendance_6Away_of_home_median,Home_score_6Home_of_away_mean,Half_Time_Away_Goals_AwayTeam_average_6,Home_Red_Cards_AwayTeam_median_6,Away_Bookings_Points_6Away_of_home_median,Half_Time_Result_6Home_of_away_median,Home_Shots_Target_6Home_of_away_mean,Away_Woodwork_HomeTeam_sum_6,Half_Time_Result_HomeTeam_average_6,Home_Fouls_6Home_of_away_sum,Away_Yellow_Cards_6Away_of_home_sum,Home_Corners_HomeTeam_median_6,Half_Time_Result_6Away_of_home_sum,Home_Shots_Home_AllGames_sum_6,Crowd_Attendance_HomeTeam_average_6,Away_Offsides_AwayTeam_average_6,Crowd_Attendance_Away_AllGames_median_6,Final_Home_goals_Home_AllGames_sum_6,Away_Woodwork_6Away_of_home_sum,Home_Bookings_Points_AwayTeam_median_6,Home_Red_Cards_6Home_of_away_median,Away_Offsides_HomeTeam_median_6,Half_Time_Away_Goals_6Away_of_home_median,Home_Shots_Target_6Away_of_home_mean,Away_Bookings_Points_HomeTeam_average_6,Away_Bookings_Points_Away_AllGames_median_6,Half_Time_Result_6Away_of_home_median,Away_Shots_Target_6Home_of_away_sum,Away_Yellow_Cards_Away_AllGames_Average_6,Away_Shots_Target_6Home_of_away_mean,Home_Shots_HomeTeam_average_6,Home_score_6Away_of_home_mean,Home_Woodwork_6Home_of_away_median,Half_Time_Home_Goals_HomeTeam_sum_6,Away_Shots_6Home_of_away_sum,Away_Red_Cards_Away_AllGames_sum_6,Away_Yellow_Cards_HomeTeam_sum_6,Away_Shots_HomeTeam_sum_6,Away_Offsides_HomeTeam_sum_6,Final_Away_goals_6Home_of_away_sum,Home_Yellow_Cards_HomeTeam_sum_6,Half_Time_Result_Away_AllGames_median_6,Crowd_Attendance_Home_AllGames_Average_6,Away_Shots_Target_AwayTeam_average_6,Home_Shots_Away_AllGames_sum_6,Home_Woodwork_HomeTeam_median_6,Away_Fouls_6Home_of_away_median,Home_Corners_6Away_of_home_sum,Away_Shots_6Away_of_home_sum,Final_result_AwayTeam_median_6,Away_Shots_AwayTeam_sum_6,Away_Fouls_Home_AllGames_sum_6,Away_Shots_AwayTeam_average_6,Home_Corners_Home_AllGames_Average_6,Away_Yellow_Cards_Home_AllGames_Average_6,Half_Time_Home_Goals_6Away_of_home_sum,Home_score_HomeTeam_median_6,Home_Red_Cards_Away_AllGames_sum_6,Away_Bookings_Points_AwayTeam_median_6,Home_Offsides_6Away_of_home_median,Away_Fouls_Home_AllGames_median_6,Home_Shots_Target_Away_AllGames_Average_6,Half_Time_Away_Goals_Away_AllGames_sum_6,Home_Shots_Away_AllGames_median_6,Away_Red_Cards_AwayTeam_sum_6,Half_Time_Home_Goals_AwayTeam_sum_6,Final_Home_goals_6Away_of_home_sum,Away_Corners_Away_AllGames_sum_6,Away_Fouls_HomeTeam_median_6,Final_Away_goals_AwayTeam_average_6,Away_Shots_Target_HomeTeam_sum_6,Half_Time_Result_Away_AllGames_Average_6,Away_Woodwork_Away_AllGames_median_6,Final_result_HomeTeam_sum_6,Away_Red_Cards_6Away_of_home_sum,Away_Red_Cards_AwayTeam_average_6,Half_Time_Away_Goals_HomeTeam_median_6,Away_Fouls_HomeTeam_sum_6,Home_Woodwork_HomeTeam_average_6,Crowd_Attendance_Home_AllGames_median_6,Away_Shots_Target_AwayTeam_median_6,Away_score_Home_AllGames_Average_6,Away_Woodwork_6Away_of_home_median,Home_Bookings_Points_6Away_of_home_sum,Final_Home_goals_6Home_of_away_median,Away_Woodwork_AwayTeam_average_6,Home_Offsides_HomeTeam_average_6,Final_Home_goals_AwayTeam_sum_6,Half_Time_Result_Home_AllGames_median_6,Away_Bookings_Points_6Away_of_home_sum,Away_score_AwayTeam_sum_6,Away_Bookings_Points_6Away_of_home_mean,Home_Bookings_Points_Home_AllGames_sum_6,Half_Time_Away_Goals_Away_AllGames_median_6,Home_Bookings_Points_Away_AllGames_Average_6,Home_Shots_6Home_of_away_median,Home_Shots_Target_6Away_of_home_sum,Home_Shots_6Home_of_away_sum,Away_Shots_Target_6Away_of_home_median,Home_Red_Cards_HomeTeam_average_6,Home_Bookings_Points_HomeTeam_sum_6,Final_Home_goals_HomeTeam_sum_6,Home_Fouls_6Away_of_home_mean,Away_Corners_Home_AllGames_Average_6,Away_Bookings_Points_6Home_of_away_mean,Home_score_Home_AllGames_median_6,Home_Red_Cards_Home_AllGames_Average_6,Final_result_Away_AllGames_median_6,Half_Time_Home_Goals_Home_AllGames_sum_6,Half_Time_Away_Goals_6Home_of_away_median,Half_Time_Home_Goals_HomeTeam_average_6,Crowd_Attendance_Away_AllGames_sum_6,Crowd_Attendance_6Away_of_home_mean,Date_6Home_of_away_median,Date_6Away_of_home_median,Home_Bookings_Points_6Home_of_away_mean,Home_Shots_Target_6Home_of_away_median,Home_Fouls_Away_AllGames_Average_6,Away_Woodwork_AwayTeam_sum_6,Home_Red_Cards_HomeTeam_median_6,Half_Time_Result_Home_AllGames_sum_6,Half_Time_Result_AwayTeam_sum_6,Away_score_Away_AllGames_median_6,Home_Woodwork_6Away_of_home_mean,Final_Home_goals_6Home_of_away_sum,Away_Woodwork_Away_AllGames_sum_6,Final_result_Home_AllGames_sum_6,Home_Shots_Home_AllGames_Average_6,Home_Red_Cards_AwayTeam_sum_6,Home_Shots_Target_HomeTeam_average_6,Home_Fouls_Home_AllGames_median_6,Away_Red_Cards_6Home_of_away_sum,Home_Shots_Target_HomeTeam_median_6,Away_Offsides_6Away_of_home_median,Away_Fouls_HomeTeam_average_6,Home_Corners_6Away_of_home_median,Away_Offsides_AwayTeam_sum_6,Final_result_6Away_of_home_median,Final_result_6Home_of_away_mean,Crowd_Attendance_AwayTeam_average_6,Half_Time_Away_Goals_HomeTeam_sum_6,Home_Woodwork_6Away_of_home_median,Away_Bookings_Points_HomeTeam_sum_6,Home_Red_Cards_6Away_of_home_median,Away_Fouls_AwayTeam_median_6,Away_Shots_6Home_of_away_median,Home_Yellow_Cards_6Away_of_home_median,Away_Shots_Target_Away_AllGames_sum_6,Away_Yellow_Cards_AwayTeam_median_6,Home_Offsides_Away_AllGames_sum_6,Home_Offsides_6Home_of_away_median,Home_Offsides_6Away_of_home_mean,Home_Shots_Target_AwayTeam_median_6,Away_Yellow_Cards_6Away_of_home_median,Home_Yellow_Cards_Away_AllGames_Average_6

In [187]:
df_ready.shape

(7508, 663)

In [188]:
a1=set(df_ready.loc[:,'Final_Home_goals':'Half_Time_Result'].columns.to_list())

In [189]:
a2=set(df_ready.loc[:,'Home_Shots':'Away_Bookings_Points'].columns.to_list())

In [190]:
a3=set(df_ready.loc[:,'Winner':'Corners_ratio'].columns.to_list())

In [191]:
cols= set(df_ready.columns.to_list()) - a1

In [192]:
cols= cols- a2

In [193]:
cols= cols- a3

In [194]:
df_ready=df_ready.loc[:,cols]

In [195]:
df_ready.head()

,Away_Corners_Away_AllGames_Average_6,Away_Corners_AwayTeam_median_6,Home_score_6Away_of_home_sum,Crowd_Attendance_6Home_of_away_mean,PSD,Date_6Home_of_away_sum,Home_Yellow_Cards_HomeTeam_median_6,Away_Shots_6Away_of_home_median,Away_Offsides_HomeTeam_average_6,Home_Corners_AwayTeam_average_6,Half_Time_Result_6Home_of_away_mean,WHH,Away_Offsides_6Home_of_away_mean,Away_Fouls_Away_AllGames_Average_6,Away_Bookings_Points_6Home_of_away_median,Away_score_HomeTeam_median_6,B365AHH,Away_Woodwork_Home_AllGames_Average_6,Away_Offsides_Away_AllGames_sum_6,Away_Offsides_6Home_of_away_sum,Home_Offsides_6Home_of_away_mean,Final_Away_goals_Away_AllGames_median_6,Home_Bookings_Points_Away_AllGames_sum_6,Away_score_AwayTeam_median_6,B365AHA,Home_Yellow_Cards_6Away_of_home_mean,Home_Bookings_Points_AwayTeam_average_6,Away_Shots_Target_6Away_of_home_mean,Date_6Home_of_away_mean,BSH,Half_Time_Away_Goals_Home_AllGames_median_6,Half_Time_Home_Goals_HomeTeam_median_6,Home_score_AwayTeam_sum_6,Final_Away_goals_Home_AllGames_median_6,Away_Shots_Target_Home_AllGames_sum_6,Home_score_Away_AllGames_Average_6,Away_Woodwork_6Home_of_away_mean,Away_Shots_Home_AllGames_median_6,Final_result_6Home_of_away_sum,Home_Woodwork_Home_AllGames_sum_6,PSCA,VCCA,Half_Time_Home_Goals_Away_AllGames_sum_6,Home_Offsides_AwayTeam_median_6,Away_Shots_Target_Away_AllGames_Average_6,Home_Yellow_Cards_Away_AllGames_sum_6,LBAH,Home_Corners_6Home_of_away_median,Away_Fouls_6Away_of_home_mean,menha_date_6Home_of_away_sum,AvgA,MaxCH,GBD,Home_Red_Cards_6Away_of_home_sum,Home_Woodwork_AwayTeam_median_6,Away_Shots_Away_AllGames_median_6,Bb1X2,SYD,Away_Offsides_Away_AllGames_median_6,Home_Bookings_Points_6Away_of_home_mean,Home_Shots_AwayTeam_sum_6,Home_Shots_AwayTeam_median_6,Away_Woodwork_Home_AllGames_median_6,BWA,Half_Time_Away_Goals_AwayTeam_median_6,Away_Red_Cards_HomeTeam_sum_6,Away_Offsides_AwayTeam_median_6,Final_Home_goals_HomeTeam_average_6,Away_Red_Cards_6Away_of_home_mean,Crowd_Attendance_AwayTeam_sum_6,AvgCD,B365C>2.5,Home_Woodwork_6Home_of_away_sum,Home_Yellow_Cards_HomeTeam_average_6,Home_Woodwork_AwayTeam_sum_6,Half_Time_Away_Goals_Away_AllGames_Average_6,Final_result_HomeTeam_median_6,IWCD,Final_Away_goals_AwayTeam_median_6,Home_Bookings_Points_6Home_of_away_sum,PSA,Home_Shots_Target_AwayTeam_sum_6,Half_Time_Away_Goals_Home_AllGames_sum_6,Home_Fouls_6Away_of_home_median,Final_Home_goals_Away_AllGames_median_6,Away_Woodwork_Away_AllGames_Average_6,Home_Fouls_Home_AllGames_sum_6,Final_result_Home_AllGames_Average_6,Final_result_HomeTeam_average_6,Away_Fouls_AwayTeam_sum_6,Away_score_6Away_of_home_sum,Final_Home_goals_AwayTeam_median_6,GBAHA,Final_Away_goals_6Away_of_home_median,Home_Offsides_6Away_of_home_sum,Home_score_HomeTeam_average_6,Away_Fouls_6Away_of_home_sum,Away_Red_Cards_6Away_of_home_median,Home_Yellow_Cards_6Home_of_away_sum,B365CH,Away_Shots_HomeTeam_median_6,Date_6Away_of_home_sum,Away_Bookings_Points_Home_AllGames_sum_6,Home_Offsides_AwayTeam_average_6,Away_Bookings_Points_HomeTeam_median_6,Home_Yellow_Cards_AwayTeam_sum_6,Home_Corners_AwayTeam_median_6,Home_Offsides_Away_AllGames_median_6,BbOU,Home_Woodwork_AwayTeam_average_6,Home_Red_Cards_Away_AllGames_Average_6,Away_Corners_6Away_of_home_median,Final_Away_goals_Home_AllGames_Average_6,AvgCAHA,Half_Time_Home_Goals_6Home_of_away_sum,AvgAHA,Season,Final_Home_goals_6Away_of_home_median,Home_Woodwork_Away_AllGames_median_6,Away_Offsides_6Home_of_away_median,Home_Red_Cards_Home_AllGames_median_6,Away_Corners_6Home_of_away_sum,SOH,Home_score_Home_AllGames_sum_6,Home_Fouls_Home_AllGames_Average_6,Half_Time_Result_Home_AllGames_Average_6,Half_Time_Result_Away_AllGames_sum_6,Referee,Half_Time_Away_Goals_HomeTeam_average_6,menha_date_6Away_of_home_median,Home_Corners_Home_AllGames_sum_6,PC<2.5,Away_Yellow_Cards_Home_AllGames_sum_6,Final_Home_goals_AwayTeam_average_6,Half_Time_Home_Goals_Home_AllGames_median_6,Away_Shots_6Away_of_home_mean,Half_Time_Away_Goals_6Away_of_home_mean,Away_Fouls_6Home_of_away_sum,Half_Time_Result_HomeTeam_median_6,AvgC<2.5,Home_Shots_Target_Home_AllGames_sum_6,SBH,Away_Shots_Target_Away_AllGames_median_6,Home_Red_Cards_6Away_of_home_mean,Away_Yellow_Cards_6Home_of_away_sum,Final_Home_goals_HomeTeam_median_6,Home_Woodwork_6Away_of_home_sum,VCCH,Home_Offsides_Home_AllGames_median_6,Home_score_6Home_of_away_median,menha_date_6Away_of_home_mean,Away_Bookings_Points_6Home_of_away_sum,Final_result_AwayTeam_average_6,Away_Corners_6Away_of_home_mean,Home_score_Home_AllGames_Average_6,Home_Red_Cards_6Home_of_away_mean,Away_Shots_6Home_of_away_mean,Home_Shots_6Away_of_home_sum,Away_Woodwork_6Home_of_away_sum,AvgD,Home_Offsides_Home_AllGames_Average_6,Final_Away_goals_Home_AllGames_sum_6,Home_Offsides_Away_AllGames_Average_6,Half_Time_Away_Goals_6Home_of_away_mean,GBAHH,Away_Red_Cards_HomeTeam_median_6,Half_Time_Away_Goals_Home_AllGames_Average_6,Home_Woodwork_Away_AllGames_Average_6,Away_Red_Cards_HomeTeam_average_6,Home_Yellow_Cards_Home_AllGames_median_6,Final_result_6Away_of_home_mean,Home_Fouls_6Home_of_away_mean,Away_Yellow_Cards_Away_AllGames_sum_6,BbAvAHA,Away_Red_Cards_6Home_of_away_mean,Away_Shots_Target_6Home_of_away_median,SJH,Home_Shots_HomeTeam_median_6,Crowd_Attendance_6Home_of_away_median,Home_Offsides_AwayTeam_sum_6,Away_score_6Away_of_home_mean,menha_date_6Home_of_away_mean,Home_Shots_Target_HomeTeam_sum_6,Half_Time_Result_AwayTeam_average_6,SYA,BSA,Away_Shots_Target_Home_AllGames_Average_6,Final_Away_goals_HomeTeam_sum_6,Away_Yellow_Cards_AwayTeam_average_6,Half_Time_Home_Goals_6Home_of_away_median,PSH,GBA,Home_Offsides_Home_AllGames_sum_6,Home_Corners_Away_AllGames_Average_6,Away_Red_Cards_Away_AllGames_median_6,Away_Shots_Target_Home_AllGames_median_6,Half_Time_Away_Goals_6Home_of_away_sum,MaxC>2.5,BbMxH,Home_Fouls_HomeTeam_sum_6,Away_Corners_Home_AllGames_sum_6,Crowd_Attendance_AwayTeam_median_6,SBA,Home_Fouls_Away_AllGames_median_6,Home_Red_Cards_Away_AllGames_median_6,Away_Corners_AwayTeam_sum_6,Final_Away_goals_HomeTeam_average_6,Away_Shots_Target_HomeTeam_median_6,AHCh,IWD,Crowd_Attendance_6Away_of_home_sum,Away_Yellow_Cards_6Away_of_home_mean,Away_Shots_Target_AwayTeam_sum_6,Home_Yellow_Cards_Away_AllGames_median_6,Home_Fouls_AwayTeam_sum_6,Away_Red_Cards_Home_AllGames_median_6,Away_Offsides_Away_AllGames_Average_6,Away_Yellow_Cards_6Home_of_away_median,Half_Time_Away_Goals_AwayTeam_sum_6,MaxCD,Final_result_Away_AllGames_Average_6,Away_Corners_HomeTeam_median_6,Away_Fouls_Away_AllGames_median_6,Home_Yellow_Cards_Home_AllGames_Average_6,Away_Bookings_Points_AwayTeam_average_6,Home_Fouls_6Home_of_away_median,Home_Red_Cards_HomeTeam_sum_6,Away_Yellow_Cards_Away_AllGames_median_6,Home_Red_Cards_Home_AllGames_sum_6,Home_Fouls_HomeTeam_average_6,Away_Corners_6Home_of_away_median,Home_Yellow_Cards_AwayTeam_median_6,Away_score_Away_AllGames_sum_6,Away_Fouls_Away_AllGames_sum_6,Away_Shots_Home_AllGames_Average_6,AHh,Final_result_Home_AllGames_median_6,Home_Shots_Target_Away_AllGames_sum_6,PAHA,Away_Corners_AwayTeam_average_6,Away_Yellow_Cards_HomeTeam_average_6,PSCD,PAHH,Away_Shots_HomeTeam_average_6,B365D,Final_Away_goals_6Home_of_away_mean,MaxAHH,Home_Fouls_Away_AllGames_sum_6,BbAvH,Away_score_Away_AllGames_Average_6,LBA,Final_Home_goals_6Home_of_away_mean,Home_Corners_6Home_of_away_sum,LBD,Home_Fouls_AwayTeam_median_6,Home_Corners_AwayTeam_sum_6,Home_Yellow_Cards_6Away_of_home_sum,Crowd_Attendance_6Home_of_away_sum,Away_Bookings_Points_AwayTeam_sum_6,BbMx<2.5,SOD,Final_result_Away_AllGames_sum_6,Half_Time_Home_Goals_Away_AllGames_Average_6,Home_Shots_6Home_of_away_mean,AvgCAHH,Away_Yellow_Cards_Home_AllGames_median_6,Home_Shots_Target_AwayTeam_average_6,Away_Shots_Target_6Away_of_home_sum,Final_Away_goals_Away_AllGames_sum_6,PCAHA,Home_Bookings_Points_HomeTeam_average_6,Away_Woodwork_HomeTeam_average_6,Away_Offsides_Home_AllGames_Average_6,Home_Fouls_HomeTeam_median_6,WHA,LBAHH,Away_Corners_HomeTeam_sum_6,Home_Shots_Target_Home_AllGames_Average_6,Home_Woodwork_Home_AllGames_median_6,Crowd_Attendance,Home_Bookings_Points_6Away_of_home_median,IWH,Home_Shots_Target_Home_AllGames_median_6,Away_Yellow_Cards_AwayTeam_sum_6,Date,Final_result_AwayTeam_sum_6,Home_Corners_Away_AllGames_median_6,Home_score_6Away_of_home_median,Home_Corners_6Away_of_home_mean,MaxC<2.5,Away_Bookings_Points_Away_AllGames_Average_6,AvgC>2.5,Away_Shots_Home_AllGames_sum_6,Home_Yellow_Cards_6Home_of_away_median,Home_Woodwork_6Home_of_away_mean,Crowd_Attendance_HomeTeam_sum_6,Away_Bookings_Points_Home_AllGames_Average_6,BWCH,Home_Offsides_HomeTeam_sum_6,MaxA,Home_Woodwork_HomeTeam_sum_6,Home_Offsides_6Home_of_away_sum,Away_Red_Cards_Home_AllGames_Average_6,BbAvD,Home_Corners_HomeTeam_sum_6,Home_Shots_Target_6Away_of_home_median,IWCH,Away_score_6Home_of_away_mean,SJA,Home_Shots_6Away_of_home_median,Half_Time_Result_6Home_of_away_sum,Max<2.5,Home_Shots_AwayTeam_average_6,Home_Shots_Target_6Home_of_away_sum,Away_score_Home_AllGames_median_6,Half_Time_Result_AwayTeam_median_6,Away_Red_Cards_AwayTeam_median_6,Home_score_Away_AllGames_median_6,Away_Corners_HomeTeam_average_6,Away_Shots_Away_AllGames_Average_6,P>2.5,Home_Bookings_Points_AwayTeam_sum_6,Half_Time_Home_Goals_Home_AllGames_Average_6,Home_Corners_Away_AllGames_sum_6,Home_Offsides_HomeTeam_median_6,Final_Away_goals_HomeTeam_median_6,Away_Woodwork_6Away_of_home_mean,Home_Red_Cards_AwayTeam_average_6,Home_Shots_Home_AllGames_median_6,Final_Home_goals_Away_AllGames_Average_6,Away_Corners_6Away_of_home_sum,Away_Fouls_Home_AllGames_Average_6,Away_Woodwork_AwayTeam_median_6,Away_Offsides_6Away_of_home_mean,Crowd_Attendance_Away_AllGames_Average_6,Half_Time_Home_Goals_6Home_of_away_mean,Away_Red_Cards_Away_AllGames_Average_6,VCH,Home_Bookings_Points_Away_AllGames_median_6,Date_6Away_of_home_mean,Home_Yellow_Cards_AwayTeam_average_6,Away_Corners_Home_AllGames_median_6,Away_Corners_Away_AllGames_median_6,Away_Bookings_Points_Home_AllGames_median_6,Home_Shots_Target_Away_AllGames_median_6,Max>2.5,Half_Time_Home_Goals_6Away_of_home_mean,Away_Red_Cards_6Home_of_away_median,Home_Bookings_Points_6Home_of_away_median,Half_Time_Result_HomeTeam_sum_6,BbMxA,Final_Away_goals_6Away_of_home_sum,Away_score_6Away_of_home_median,LBH,Away_score_HomeTeam_average_6,Away_Shots_Away_AllGames_sum_6,Home_Woodwork_Away_AllGames_sum_6,Home_Yellow_Cards_6Home_of_away_mean,GB<2.5,B365CD,Away_score_HomeTeam_sum_6,Away_Fouls_6Away_of_home_median,Final_Away_goals_Away_AllGames_Average_6,Away_Fouls_6Home_of_away_mean,Half_Time_Home_Goals_6Away_of_home_median,P<2.5,MaxCAHH,Away_Bookings_Points_Away_AllGames_sum_6,Away_score_6Home_of_away_median,Away_Fouls_AwayTeam_average_6,Home_score_Away_AllGames_sum_6,menha_date_6Away_of_home_sum,Home_Red_Cards_6Home_of_away_sum,B365AH,PSCH,Home_Shots_Away_AllGames_Average_6,BWH,Home_score_AwayTeam_average_6,Away_score_6Home_of_away_sum,Home_Yellow_Cards_Home_AllGames_sum_6,SOA,GBH,Home_Bookings_Points_Home_AllGames_Average_6,Away_Woodwork_Home_AllGames_sum_6,VCD,Crowd_Attendance_HomeTeam_median_6,Final_result_6Away_of_home_sum,Away_Woodwork_6Home_of_away_median,AvgCA,Final_Home_goals_6Away_of_home_mean,BbAv>2.5,B365C<2.5,MaxCA,B365>2.5,Away_Offsides_6Away_of_home_sum,Final_Away_goals_6Away_of_home_mean,Final_Home_goals_Home_AllGames_Average_6,Home_score_HomeTeam_sum_6,Away_Offsides_Home_AllGames_median_6,Home_Shots_HomeTeam_sum_6,Home_Corners_6Home_of_away_mean,Half_Time_Home_Goals_Away_AllGames_median_6,Half_Time_Home_Goals_AwayTeam_average_6,Away_Yellow_Cards_6Home_of_away_mean,Final_Home_goals_Away_AllGames_sum_6,LBAHA,Away_score_AwayTeam_average_6,menha_date_6Home_of_away_median,Home_score_AwayTeam_median_6,Away_Shots_Target_HomeTeam_average_6,B365CA,Home_Corners_HomeTeam_average_6,Half_Time_Home_Goals_AwayTeam_median_6,Away_score_Home_AllGames_sum_6,Home_Shots_6Away_of_home_mean,Away_Yellow_Cards_HomeTeam_median_6,Final_Away_goals_AwayTeam_sum_6,Home_Bookings_Points_Home_AllGames_median_6,Away_Corners_6Home_of_away_mean,Half_Time_Away_Goals_6Away_of_home_sum,Away_Shots_AwayTeam_median_6,Home_Woodwork_Home_AllGames_Average_6,B365A,WHD,Half_Time_Result_6Away_of_home_mean,SJD,HomeTeam,Home_Fouls_6Away_of_home_sum,Home_score_6Home_of_away_sum,Home_Fouls_AwayTeam_average_6,Final_Away_goals_6Home_of_away_median,BbAv<2.5,Away_Woodwork_HomeTeam_median_6,Away_Offsides_Home_AllGames_sum_6,BbMxD,Crowd_Attendance_Home_AllGames_sum_6,SYH,Home_Bookings_Points_HomeTeam_median_6,MaxD,Home_Corners_Home_AllGames_median_6,Away_Red_Cards_Home_AllGames_sum_6,Final_Home_goals_Home_AllGames_median_6,Final_result_6Home_of_away_median,MaxAHA,Avg<2.5,Crowd_Attendance_6Away_of_home_median,Home_score_6Home_of_away_mean,Half_Time_Away_Goals_AwayTeam_average_6,Home_Red_Cards_AwayTeam_median_6,Away_Bookings_Points_6Away_of_home_median,Half_Time_Result_6Home_of_away_median,Home_Shots_Target_6Home_of_away_mean,Away_Woodwork_HomeTeam_sum_6,Half_Time_Result_HomeTeam_average_6,Home_Fouls_6Home_of_away_sum,Away_Yellow_Cards_6Away_of_home_sum,Home_Corners_HomeTeam_median_6,Half_Time_Result_6Away_of_home_sum,Home_Shots_Home_AllGames_sum_6,Crowd_Attendance_HomeTeam_average_6,Away_Offsides_AwayTeam_average_6,BbMx>2.5,B365CAHA,Crowd_Attendance_Away_AllGames_median_6,Final_Home_goals_Home_AllGames_sum_6,Away_Woodwork_6Away_of_home_sum,Home_Bookings_Points_AwayTeam_median_6,Home_Red_Cards_6Home_of_away_median,Away_Offsides_HomeTeam_median_6,Half_Time_Away_Goals_6Away_of_home_median,Home_Shots_Target_6Away_of_home_mean,GB>2.5,Away_Bookings_Points_HomeTeam_average_6,Away_Bookings_Points_Away_AllGames_median_6,Half_Time_Result_6Away_of_home_median,AvgCH,Away_Shots_Target_6Home_of_away_sum,Away_Yellow_Cards_Away_AllGames_Average_6,Away_Shots_Target_6Home_of_away_mean,SBD,Home_Shots_HomeTeam_average_6,Home_score_6Away_of_home_mean,Home_Woodwork_6Home_of_away_median,Half_Time_Home_Goals_HomeTeam_sum_6,Away_Shots_6Home_of_away_sum,Away_Red_Cards_Away_AllGames_sum_6,Away_Yellow_Cards_HomeTeam_sum_6,Away_Shots_HomeTeam_sum_6,Away_Offsides_HomeTeam_sum_6,Final_Away_goals_6Home_of_away_sum,BSD,Home_Yellow_Cards_HomeTeam_sum_6,Half_Time_Result_Away_AllGames_median_6,Avg>2.5,Crowd_Attendance_Home_AllGames_Average_6,WHCA,Away_Shots_Target_AwayTeam_average_6,Home_Shots_Away_AllGames_sum_6,Home_Woodwork_HomeTeam_median_6,Away_Fouls_6Home_of_away_median,Home_Corners_6Away_of_home_sum,Away_Shots_6Away_of_home_sum,Final_result_AwayTeam_median_6,Time,Away_Shots_AwayTeam_sum_6,Away_Fouls_Home_AllGames_sum_6,Away_Shots_AwayTeam_average_6,Home_Corners_Home_AllGames_Average_6,Away_Yellow_Cards_Home_AllGames_Average_6,Half_Time_Home_Goals_6Away_of_home_sum,Home_score_HomeTeam_median_6,Home_Red_Cards_Away_AllGames_sum_6,WHCD,Away_Bookings_Points_AwayTeam_median_6,Home_Offsides_6Away_of_home_median,Away_Fouls_Home_AllGames_median_6,Home_Shots_Target_Away_AllGames_Average_6,Half_Time_Away_Goals_Away_AllGames_sum_6,Home_Shots_Away_AllGames_median_6,Away_Red_Cards_AwayTeam_sum_6,Half_Time_Home_Goals_AwayTeam_sum_6,Final_Home_goals_6Away_of_home_sum,Away_Corners_Away_AllGames_sum_6,Away_Fouls_HomeTeam_median_6,Final_Away_goals_AwayTeam_average_6,Away_Shots_Target_HomeTeam_sum_6,Half_Time_Result_Away_AllGames_Average_6,Away_Woodwork_Away_AllGames_median_6,Final_result_HomeTeam_sum_6,B365H,Away_Red_Cards_6Away_of_home_sum,Away_Red_Cards_AwayTeam_average_6,Half_Time_Away_Goals_HomeTeam_median_6,Away_Fouls_HomeTeam_sum_6,BbMxAHH,Home_Woodwork_HomeTeam_average_6,Crowd_Attendance_Home_AllGames_median_6,Away_Shots_Target_AwayTeam_median_6,Away_score_Home_AllGames_Average_6,Away_Woodwork_6Away_of_home_median,B365CAHH,Home_Bookings_Points_6Away_of_home_sum,Final_Home_goals_6Home_of_away_median,Away_Woodwork_AwayTeam_average_6,Home_Offsides_HomeTeam_average_6,Final_Home_goals_AwayTeam_sum_6,Half_Time_Result_Home_AllGames_median_6,BbAH,MaxCAHA,Away_Bookings_Points_6Away_of_home_sum,BbAvA,Away_score_AwayTeam_sum_6,Away_Bookings_Points_6Away_of_home_mean,Home_Bookings_Points_Home_AllGames_sum_6,Half_Time_Away_Goals_Away_AllGames_median_6,Home_Bookings_Points_Away_AllGames_Average_6,Home_Shots_6Home_of_away_median,Home_Shots_Target_6Away_of_home_sum,Home_Shots_6Home_of_away_sum,BWCD,Away_Shots_Target_6Away_of_home_median,Home_Red_Cards_HomeTeam_average_6,BWD,Home_Bookings_Points_HomeTeam_sum_6,Final_Home_goals_HomeTeam_sum_6,Home_Fouls_6Away_of_home_mean,IWCA,Away_Corners_Home_AllGames_Average_6,Away_Bookings_Points_6Home_of_away_mean,Home_score_Home_AllGames_median_6,BbAvAHH,Home_Red_Cards_Home_AllGames_Average_6,PC>2.5,Final_result_Away_AllGames_median_6,Half_Time_Home_Goals_Home_AllGames_sum_6,Half_Time_Away_Goals_6Home_of_away_median,Half_Time_Home_Goals_HomeTeam_average_6,GBAH,Crowd_Attendance_Away_AllGames_sum_6,Crowd_Attendance_6Away_of_home_mean,Date_6Home_of_away_median,Date_6Away_of_home_median,BWCA,PCAHH,Home_Bookings_Points_6Home_of_away_mean,Home_Shots_Target_6Home_of_away_median,Home_Fouls_Away_AllGames_Average_6,Away_Woodwork_AwayTeam_sum_6,AwayTeam,MaxH,Home_Red_Cards_HomeTeam_median_6,Half_Time_Result_Home_AllGames_sum_6,AvgH,Final_result,Half_Time_Result_AwayTeam_sum_6,Away_score_Away_AllGames_median_6,Home_Woodwork_6Away_of_home_mean,BbAHh,Final_Home_goals_6Home_of_away_sum,Away_Woodwork_Away_AllGames_sum_6,Final_result_Home_AllGames_sum_6,Home_Shots_Home_AllGames_Average_6,Home_Red_Cards_AwayTeam_sum_6,Home_Shots_Target_HomeTeam_average_6,Home_Fouls_Home_AllGames_median_6,Away_Red_Cards_6Home_of_away_sum,Home_Shots_Target_HomeTeam_median_6,Away_Offsides_6Away_of_home_median,Away_Fouls_HomeTeam_average_6,Home_Corners_6Away_of_home_median,Away_Offsides_AwayTeam_sum_6,Final_result_6Away_of_home_median,Final_result_6Home_of_away_mean,Crowd_Attendance_AwayTeam_average_6,WHCH,Half_Time_Away_Goals_HomeTeam_sum_6,Home_Woodwork_6Away_of_home_median,AvgAHH,Away_Bookings_Points_HomeTeam_sum_6,Home_Red_Cards_6Away_of_home_median,Away_Fouls_AwayTeam_median_6,BbMxAHA,Away_Shots_6Home_of_away_median,Home_Yellow_Cards_6Away_of_home_median,Away_Shots_Target_Away_AllGames_sum_6,VCA,B365<2.5,VCCD,Away_Yellow_Cards_AwayTeam_median_6,Home_Offsides_Away_AllGames_sum_6,Home_Offsides_6Home_of_away_median,Home_Offsides_6Away_of_home_mean,Home_Shots_Target_AwayTeam_median_6,Away_Yellow_Cards_6Away_of_home_median,Home_Yellow_Cards_Away_AllGames_Average_6,IWA

In [196]:
#OR: 
#col= set(df_ready.columns.to_list()) - (a1 | a2 | a3)
#df_ready11=df_ready.loc[:,col]

In [197]:
L= ['Date_6Home_of_away_sum', 'Date_6Away_of_home_mean', 'Date_6Home_of_away_median', 'Date_6Away_of_home_sum', 'Date_6Home_of_away_mean',
    'Date_6Away_of_home_median', 'menha_date_6Home_of_away_mean', 'menha_date_6Away_of_home_mean', 'menha_date_6Home_of_away_sum',
    'menha_date_6Away_of_home_sum', 'menha_date_6Away_of_home_median', 'menha_date_6Home_of_away_median']

In [198]:
cols= set(df_ready.columns.to_list()) - set(L)

In [200]:
df_ready=df_ready.loc[:,cols]

In [201]:
df_ready.shape

(7508, 624)

In [202]:
df_ready.to_csv('df_ready_No_dummy.csv')

In [203]:
df_ready= pd.read_csv('df_ready_No_dummy.csv')

C:\Users\enabi\miniconda3\envs\Projects\lib\site-packages\IPython\core\interactiveshell.py:3071: DtypeWarning: Columns (494) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [204]:
del df_ready['Unnamed: 0']

In [205]:
#HOME
# _HomeTeam_sum_6
# _HomeTeam_median_6
# _HomeTeam_average_6
# _Home_AllGames_sum_6
# _Home_AllGames_median_6
# _Home_AllGames_Average_6
#_6Away_of_home_sum
# _6Away_of_home_median
# _6Away_of_home_mean

filt1 = df_ready.columns[df_ready.columns.str.contains(pat = '_HomeTeam_sum_6|_HomeTeam_median_6|_HomeTeam_average_6|_Home_AllGames_sum_6|_Home_AllGames_median_6|_Home_AllGames_Average_6|_6Away_of_home_sum|_6Away_of_home_median|_6Away_of_home_mean')]
#print(filt1, len(filt1))

In [199]:
#AWAY
# _AwayTeam_sum_6
# _AwayTeam_median_6
# _AwayTeam_average_6
# _Away_AllGames_sum_6
# _Away_AllGames_median_6
# _Away_AllGames_Average_6
# _6Home_of_away_sum
# _6Home_of_away_median
# _6Home_of_away_mean

filt2 = df_ready.columns[df_ready.columns.str.contains(pat = '_AwayTeam_sum_6|_AwayTeam_median_6|_AwayTeam_average_6|_Away_AllGames_sum_6|_Away_AllGames_median_6|_Away_AllGames_Average_6|_6Home_of_away_sum|_6Home_of_away_median|_6Home_of_away_mean')]
#print(filt2, len(filt2))
#list(filt2)+['HomeTeam']
#print(set(filt2))

In [200]:
df_N= df_ready.copy()

In [201]:
df_N.loc[:,list(filt1)]= df_N.loc[:,list(filt1)+['HomeTeam']].fillna(df_N.groupby(['HomeTeam'])[filt1].transform('mean'))

In [202]:
df_ready.loc[df_ready['HomeTeam']=='Arsenal','Crowd_Attendance_Home_AllGames_sum_6'].value_counts(dropna=False)

NaN         343
228277.0      2
228142.0      1
227849.0      1
228236.0      1
227476.0      1
228245.0      1
227485.0      1
228249.0      1
227739.0      1
227869.0      1
227871.0      1
228258.0      1
227750.0      1
227623.0      1
228008.0      1
228222.0      1
228392.0      1
227509.0      1
227510.0      1
228289.0      1
228035.0      1
228038.0      1
227434.0      1
228296.0      1
228309.0      1
228264.0      1
228070.0      1
228457.0      1
228074.0      1
228204.0      1
228461.0      1
228399.0      1
Name: Crowd_Attendance_Home_AllGames_sum_6, dtype: int64

In [203]:
df_N.loc[df_N['HomeTeam']=='Arsenal','Crowd_Attendance_Home_AllGames_sum_6'].value_counts(dropna=False)

228039.909091    343
228277.000000      2
228222.000000      1
228008.000000      1
227623.000000      1
227750.000000      1
228258.000000      1
227871.000000      1
227869.000000      1
227739.000000      1
228399.000000      1
228249.000000      1
227485.000000      1
228245.000000      1
227476.000000      1
228236.000000      1
228142.000000      1
227509.000000      1
228392.000000      1
227510.000000      1
228289.000000      1
228035.000000      1
228038.000000      1
227434.000000      1
228296.000000      1
228309.000000      1
228264.000000      1
228070.000000      1
228457.000000      1
228074.000000      1
228204.000000      1
228461.000000      1
227849.000000      1
Name: Crowd_Attendance_Home_AllGames_sum_6, dtype: int64

In [204]:
df_N.loc[:,list(filt2)]= df_N.loc[:,list(filt2)+['AwayTeam']].fillna(df_N.groupby(['AwayTeam'])[filt2].transform('mean'))

In [205]:
df_ready.loc[df_ready['AwayTeam']=='Arsenal','Crowd_Attendance_6Home_of_away_median'].value_counts(dropna=False)

NaN        332
38035.5      3
38052.5      3
38031.0      3
38026.5      3
38076.5      3
38045.5      3
38042.5      2
38058.0      2
38018.5      2
38019.5      2
38021.5      2
38044.0      2
38038.0      2
38047.5      2
38014.0      1
38025.0      1
38122.0      1
38254.0      1
38020.0      1
38146.0      1
38049.0      1
38048.5      1
Name: Crowd_Attendance_6Home_of_away_median, dtype: int64

In [206]:
df_N.loc[df_N['AwayTeam']=='Arsenal','Crowd_Attendance_6Home_of_away_median'].value_counts(dropna=False)

38049.047619    332
38052.500000      3
38031.000000      3
38045.500000      3
38076.500000      3
38026.500000      3
38035.500000      3
38021.500000      2
38018.500000      2
38058.000000      2
38047.500000      2
38019.500000      2
38042.500000      2
38044.000000      2
38038.000000      2
38146.000000      1
38049.000000      1
38254.000000      1
38020.000000      1
38025.000000      1
38014.000000      1
38122.000000      1
38048.500000      1
Name: Crowd_Attendance_6Home_of_away_median, dtype: int64

In [207]:
df_ready['Crowd_Attendance_6Home_of_away_median'].value_counts(dropna=False)

NaN        6650
20043.0      20
26041.0       7
28274.5       7
67595.5       6
           ...
33542.5       1
35592.0       1
22121.5       1
26346.5       1
31616.0       1
Name: Crowd_Attendance_6Home_of_away_median, Length: 496, dtype: int64

In [208]:
df_N['Crowd_Attendance_6Home_of_away_median'].value_counts(dropna=False)

NaN             2034
43956.244186     332
35884.795455     332
67555.779070     332
33879.840909     332
                ...
35011.500000       1
17250.500000       1
51889.000000       1
35017.500000       1
28686.000000       1
Name: Crowd_Attendance_6Home_of_away_median, Length: 518, dtype: int64

In [209]:
df_N.groupby(['AwayTeam'])['Crowd_Attendance_6Home_of_away_median'].value_counts(dropna=False)

AwayTeam  Crowd_Attendance_6Home_of_away_median
Arsenal   38049.047619                             332
          38026.500000                               3
          38031.000000                               3
          38035.500000                               3
          38045.500000                               3
                                                  ...
West Ham  34610.500000                               1
          34900.500000                               1
          34989.500000                               1
Wigan     NaN                                      152
Wolves    NaN                                      109
Name: Crowd_Attendance_6Home_of_away_median, Length: 538, dtype: int64

In [210]:
df_N.loc[df_N['AwayTeam']=='Wigan', 'Crowd_Attendance_6Home_of_away_median'].value_counts(dropna=False)

NaN    152
Name: Crowd_Attendance_6Home_of_away_median, dtype: int64

In [211]:
#OR
df_N.loc[df_N['AwayTeam']=='Wigan', 'Crowd_Attendance_6Home_of_away_median'].isnull().all()

True

In [212]:
pd.set_option("max_rows", None)

In [213]:
df_N.loc[df_N['AwayTeam']=='Wigan'].isnull().count()

Away_Corners_Away_AllGames_median_6             152
B365H                                           152
Final_Home_goals_Away_AllGames_median_6         152
Home_Offsides_6Home_of_away_mean                152
SYH                                             152
Home_Bookings_Points_6Home_of_away_mean         152
B365D                                           152
Home_Corners_Home_AllGames_Average_6            152
Away_Yellow_Cards_HomeTeam_sum_6                152
Away_score_6Away_of_home_mean                   152
Home_Corners_HomeTeam_average_6                 152
BWD                                             152
Final_Away_goals_AwayTeam_sum_6                 152
Home_Yellow_Cards_AwayTeam_sum_6                152
Home_Woodwork_6Home_of_away_sum                 152
Home_Corners_HomeTeam_median_6                  152
Away_Offsides_6Away_of_home_mean                152
Home_Woodwork_6Home_of_away_mean                152
GBH                                             152
AvgCD                                           152
Home_score_6Home_of_away_mean                   152
BbAvD                                           152
Home_Offsides_6Away_of_home_mean                152
Half_Time_Home_Goals_HomeTeam_average_6         152
Home_Bookings_Points_6Away_of_home_sum          152
Crowd_Attendance_6Away_of_home_mean             152
AvgCAHH                                         152
B365A                                           152
SOA                                             152
Away_Red_Cards_Away_AllGames_median_6           152
Away_Corners_HomeTeam_sum_6                     152
Home_Bookings_Points_HomeTeam_average_6         152
MaxCAHA                                         152
Half_Time_Home_Goals_Home_AllGames_median_6     152
BbMxA                                           152
BbAvA                                           152
Away_Fouls_HomeTeam_average_6                   152
MaxH                                            152
Home_Shots_HomeTeam_median_6                    152
BbAH                                            152
Home_Fouls_Away_AllGames_sum_6                  152
Home_Red_Cards_HomeTeam_median_6                152
Final_Home_goals_AwayTeam_average_6             152
Away_Red_Cards_Home_AllGames_median_6           152
BbMxH                                           152
PSH                                             152
P>2.5                                           152
MaxCD                                           152
Half_Time_Result_HomeTeam_median_6              152
Home_Yellow_Cards_AwayTeam_average_6            152
Away_Bookings_Points_Away_AllGames_Average_6    152
Final_result_6Home_of_away_sum                  152
Away_Corners_HomeTeam_median_6                  152
Crowd_Attendance_Home_AllGames_Average_6        152
P<2.5                                           152
Away_Offsides_AwayTeam_sum_6                    152
Away_Corners_Home_AllGames_median_6             152
AvgAHH                                          152
Home_Bookings_Points_6Away_of_home_median       152
BbAvAHH                                         152
Half_Time_Away_Goals_Home_AllGames_sum_6        152
Home_Fouls_AwayTeam_average_6                   152
Away_Fouls_6Away_of_home_sum                    152
Away_Fouls_Away_AllGames_sum_6                  152
Away_score_Away_AllGames_median_6               152
Away_Offsides_6Away_of_home_median              152
GB>2.5                                          152
Away_Red_Cards_Home_AllGames_Average_6          152
Away_score_6Home_of_away_mean                   152
Away_Red_Cards_6Away_of_home_mean               152
Away_Shots_Target_6Away_of_home_sum             152
Final_Home_goals_6Away_of_home_sum              152
Home_Corners_6Away_of_home_median               152
Home_Woodwork_Away_AllGames_sum_6               152
SOH                                             152
Away_Woodwork_Home_AllGames_Average_6           152
Home_score_6Away_of_home_mean                   152
Home_Fouls_Home_AllGames_sum_6                  152
Home_Yellow_Cards_6Away_of_home_sum             152
Away_Red_Cards_6Home_of_away_sum                152
BbMx<2.5                                        152
Home_Shots_AwayTeam_median_6                    152
Home_Shots_HomeTeam_average_6                   152
Away_Shots_Home_AllGames_median_6               152
Home_score_6Away_of_home_sum                    152
LBH                                             152
Half_Time_Result_Home_AllGames_median_6         152
Home_Shots_Target_HomeTeam_average_6            152
Away_Red_Cards_6Away_of_home_sum                152
Away_Shots_Target_AwayTeam_average_6            152
IWCA                                            152
Away_Offsides_Home_AllGames_median_6            152
Away_Woodwork_Home_AllGames_sum_6               152
Home_Corners_AwayTeam_average_6                 152
Home_Yellow_Cards_HomeTeam_median_6             152
Away_score_Away_AllGames_Average_6              152
Away_Bookings_Points_6Home_of_away_median       152
Final_Away_goals_HomeTeam_sum_6                 152
Final_Away_goals_Home_AllGames_Average_6        152
SBD                                             152
SBA                                             152
Away_Woodwork_Away_AllGames_median_6            152
Home_score_6Home_of_away_median                 152
Crowd_Attendance_HomeTeam_average_6             152
Home_score_Home_AllGames_median_6               152
Crowd_Attendance_AwayTeam_sum_6                 152
IWH                                             152
AwayTeam                                        152
Away_Red_Cards_HomeTeam_sum_6                   152
Away_score_HomeTeam_median_6                    152
Home_Yellow_Cards_6Home_of_away_median          152
WHCH                                            152
Away_Woodwork_6Home_of_away_mean                152
Half_Time_Home_Goals_Away_AllGames_median_6     152
Home_score_Away_AllGames_median_6               152
Bb1X2                                           152
Home_Shots_AwayTeam_sum_6                       152
BWA                                             152
PAHH                                            152
Half_Time_Result_Home_AllGames_sum_6            152
Away_Red_Cards_6Home_of_away_median             152
Away_Shots_Target_Home_AllGames_Average_6       152
AvgCH                                           152
VCCD                                            152
Away_Woodwork_HomeTeam_average_6                152
Half_Time_Away_Goals_Away_AllGames_median_6     152
Half_Time_Away_Goals_HomeTeam_sum_6             152
Avg>2.5                                         152
B365<2.5                                        152
PC>2.5                                          152
Away_Red_Cards_AwayTeam_sum_6                   152
Away_Woodwork_6Away_of_home_sum                 152
Away_Bookings_Points_6Away_of_home_mean         152
Half_Time_Away_Goals_6Home_of_away_sum          152
Away_Shots_Away_AllGames_sum_6                  152
Home_Corners_6Home_of_away_median               152
Home_Shots_HomeTeam_sum_6                       152
Home_Shots_Target_HomeTeam_sum_6                152
Half_Time_Result_6Away_of_home_sum              152
AvgCA                                           152
Home_Fouls_6Home_of_away_sum                    152
Home_Corners_Away_AllGames_median_6             152
Home_Woodwork_6Away_of_home_median              152
Half_Time_Away_Goals_AwayTeam_sum_6             152
Home_Shots_Target_6Away_of_home_mean            152
Away_Bookings_Points_HomeTeam_average_6         152
AvgC<2.5                                        152
Home_Woodwork_6Away_of_home_sum                 152
Away_score_HomeTeam_sum_6                       152
BSD                                             152
Away_Woodwork_HomeTeam_median_6                 152
Final_Home_goals_AwayTeam_sum_6                 152
Home_score_AwayTeam_sum_6                       152
Home_Red_Cards_Away_AllGames_median_6           152
Home_Shots_6Home_of_away_mean                   152
Final_Home_goals_Home_AllGames_Average_6        152
GBAH                                            152
Away_Bookings_Points_Away_AllGames_sum_6        152
Away_Shots_6Away_of_home_mean                   152
Away_Offsides_AwayTeam_median_6                 152
Home_Bookings_Points_HomeTeam_sum_6             152
B365CAHH                                        152
Crowd_Attendance_6Home_of_away_mean             152
Away_Corners_Home_AllGames_sum_6                152
Final_Away_goals_6Away_of_home_mean             152
VCCH                                            152
Home_Fouls_Home_AllGames_median_6               152
Away_Bookings_Points_AwayTeam_average_6         152
Away_Bookings_Points_6Home_of_away_mean         152
Home_Corners_Away_AllGames_sum_6                152
Home_Yellow_Cards_Away_AllGames_Average_6       152
Half_Time_Home_Goals_HomeTeam_sum_6             152
GBAHA                                           152
Away_Shots_Target_Away_AllGames_median_6        152
BbMxAHA                                         152
Crowd_Attendance_6Home_of_away_sum              152
Away_Woodwork_Home_AllGames_median_6            152
Half_Time_Away_Goals_6Away_of_home_median       152
Home_Red_Cards_6Home_of_away_mean               152
Half_Time_Result_Away_AllGames_sum_6            152
Away_Shots_Home_AllGames_sum_6                  152
Home_Shots_Target_AwayTeam_sum_6                152
IWA                                             152
Half_Time_Away_Goals_Home_AllGames_Average_6    152
Final_result_6Away_of_home_sum                  152
BWH                                             152
Away_Fouls_AwayTeam_average_6                   152
Final_Away_goals_Away_AllGames_median_6         152
Away_Red_Cards_Home_AllGames_sum_6              152
Referee                                         152
Away_Yellow_Cards_6Away_of_home_median          152
Home_Yellow_Cards_6Away_of_home_mean            152
Away_score_6Home_of_away_median                 152
Home_Shots_Target_6Home_of_away_mean            152
Half_Time_Result_AwayTeam_median_6              152
Home_Shots_Home_AllGames_sum_6                  152
Final_Away_goals_AwayTeam_median_6              152
Home_Offsides_6Away_of_home_sum                 152
Final_result_Home_AllGames_sum_6                152
PSCA                                            152
Home_Yellow_Cards_6Home_of_away_sum             152
Home_Woodwork_6Home_of_away_median              152
LBAHA                                           152
Home_Offsides_Away_AllGames_sum_6               152
BWCA                                            152
Home_score_Home_AllGames_Average_6              152
Home_Corners_6Away_of_home_sum                  152
Home_Shots_Away_AllGames_Average_6              152
Away_Fouls_AwayTeam_median_6                    152
Away_Corners_6Away_of_home_median               152
Final_result_AwayTeam_average_6                 152
Away_Shots_Target_6Home_of_away_median          152
Home_Offsides_6Away_of_home_median              152
GB<2.5                                          152
Crowd_Attendance_HomeTeam_sum_6                 152
Home_Shots_Target_6Away_of_home_sum             152
Home_Woodwork_HomeTeam_median_6                 152
Away_Shots_Target_AwayTeam_median_6             152
Final_Home_goals_Home_AllGames_median_6         152
Home_Offsides_AwayTeam_sum_6                    152
Away_Shots_6Home_of_away_sum                    152
Away_Corners_6Home_of_away_sum                  152
Away_Shots_Target_HomeTeam_average_6            152
Home_Shots_Target_6Away_of_home_median          152
Home_Woodwork_6Away_of_home_mean                152
Away_Bookings_Points_HomeTeam_sum_6             152
Home_Fouls_6Home_of_away_median                 152
Final_result_Home_AllGames_median_6             152
Home_Bookings_Points_6Home_of_away_sum          152
Home_Shots_AwayTeam_average_6                   152
Crowd_Attendance_HomeTeam_median_6              152
Away_Shots_Target_Home_AllGames_sum_6           152
Away_Red_Cards_Away_AllGames_sum_6              152
Away_Offsides_Home_AllGames_sum_6               152
Away_Yellow_Cards_6Home_of_away_sum             152
Home_Offsides_Home_AllGames_median_6            152
BWCD                                            152
Home_Bookings_Points_Away_AllGames_sum_6        152
Half_Time_Home_Goals_AwayTeam_median_6          152
Away_Yellow_Cards_HomeTeam_median_6             152
Half_Time_Result_6Home_of_away_sum              152
Half_Time_Home_Goals_Home_AllGames_sum_6        152
Home_Offsides_Home_AllGames_sum_6               152
Home_Bookings_Points_Away_AllGames_Average_6    152
Away_Shots_HomeTeam_sum_6                       152
Half_Time_Home_Goals_6Home_of_away_mean         152
Half_Time_Home_Goals_6Home_of_away_sum          152
Away_Woodwork_6Home_of_away_sum                 152
Away_Shots_Target_Away_AllGames_sum_6           152
HomeTeam                                        152
Away_Fouls_6Away_of_home_mean                   152
Away_score_6Home_of_away_sum                    152
Home_Offsides_AwayTeam_average_6                152
Away_score_AwayTeam_median_6                    152
Away_Shots_Target_6Away_of_home_median          152
Away_Shots_Target_6Away_of_home_mean            152
Home_Red_Cards_Away_AllGames_sum_6              152
Away_Shots_Target_Away_AllGames_Average_6       152
Home_Bookings_Points_Home_AllGames_median_6     152
Final_Away_goals_6Home_of_away_sum              152
Home_Yellow_Cards_6Home_of_away_mean            152
Half_Time_Result_6Away_of_home_mean             152
B365AHA                                         152
Home_Red_Cards_HomeTeam_average_6               152
Home_Offsides_Home_AllGames_Average_6           152
Home_Corners_HomeTeam_sum_6                     152
Final_Away_goals_AwayTeam_average_6             152
Half_Time_Result_6Away_of_home_median           152
Final_Away_goals_Away_AllGames_Average_6        152
Home_Bookings_Points_Home_AllGames_Average_6    152
Away_Offsides_6Home_of_away_sum                 152
Home_Yellow_Cards_Home_AllGames_median_6        152
Away_Woodwork_AwayTeam_average_6                152
Away_Fouls_6Away_of_home_median                 152
Home_Offsides_HomeTeam_average_6                152
Crowd_Attendance_Away_AllGames_median_6         152
AvgA                                            152
Final_Away_goals_6Home_of_away_median           152
Away_Shots_HomeTeam_median_6                    152
Crowd_Attendance_Away_AllGames_Average_6        152
Home_Woodwork_AwayTeam_median_6                 152
Away_Woodwork_6Home_of_away_median              152
Away_Shots_6Home_of_away_mean                   152
Half_Time_Result_AwayTeam_sum_6                 152
Home_Red_Cards_6Away_of_home_mean               152
Home_score_6Away_of_home_median                 152
AHCh                                            152
Home_Yellow_Cards_HomeTeam_average_6            152
Away_Yellow_Cards_Away_AllGames_median_6        152
Crowd_Attendance_6Away_of_home_sum              152
Away_Bookings_Points_Home_AllGames_median_6     152
MaxAHA                                          152
VCCA                                            152
Half_Time_Home_Goals_Home_AllGames_Average_6    152
WHD                                             152
MaxC<2.5                                        152
Half_Time_Away_Goals_HomeTeam_average_6         152
Home_Fouls_AwayTeam_sum_6                       152
Final_Away_goals_HomeTeam_average_6             152
Half_Time_Away_Goals_6Home_of_away_mean         152
Home_Yellow_Cards_Home_AllGames_sum_6           152
Home_score_HomeTeam_median_6                    152
MaxC>2.5                                        152
Final_Away_goals_6Away_of_home_median           152
Away_Corners_HomeTeam_average_6                 152
BbAHh                                           152
BbMx>2.5                                        152
Away_score_HomeTeam_average_6                   152
PAHA                                            152
Away_Red_Cards_6Home_of_away_mean               152
Away_Shots_Target_HomeTeam_sum_6                152
Away_Fouls_HomeTeam_sum_6                       152
IWCD                                            152
Home_Red_Cards_Home_AllGames_sum_6              152
Away_Shots_Target_6Home_of_away_sum             152
Home_Yellow_Cards_Away_AllGames_sum_6           152
B365CA                                          152
GBD                                             152
Away_Offsides_HomeTeam_median_6                 152
Home_Yellow_Cards_HomeTeam_sum_6                152
B365>2.5                                        152
PCAHA                                           152
Half_Time_Result_6Home_of_away_median           152
Half_Time_Home_Goals_Away_AllGames_sum_6        152
Final_Home_goals_HomeTeam_median_6              152
SYA                                             152
Half_Time_Home_Goals_AwayTeam_sum_6             152
Home_score_6Home_of_away_sum                    152
PSD                                             152
B365AH                                          152
Away_Corners_AwayTeam_median_6                  152
Half_Time_Home_Goals_AwayTeam_average_6         152
Home_Offsides_HomeTeam_median_6                 152
Away_Shots_Target_Home_AllGames_median_6        152
Away_Woodwork_AwayTeam_median_6                 152
MaxA                                            152
Avg<2.5                                         152
Away_Yellow_Cards_6Away_of_home_sum             152
Away_Shots_Target_HomeTeam_median_6             152
BbAv>2.5                                        152
B365C>2.5                                       152
Away_Yellow_Cards_AwayTeam_average_6            152
Home_Shots_Target_Home_AllGames_Average_6       152
Away_Shots_Target_6Home_of_away_mean            152
Home_Fouls_Away_AllGames_median_6               152
Away_Fouls_HomeTeam_median_6                    152
Away_Offsides_Away_AllGames_median_6            152
Home_Shots_Away_AllGames_sum_6                  152
Final_result_AwayTeam_median_6                  152
Final_Away_goals_Away_AllGames_sum_6            152
Final_Home_goals_Away_AllGames_sum_6            152
Away_Woodwork_6Away_of_home_median              152
Home_Red_Cards_HomeTeam_sum_6                   152
Final_result_Away_AllGames_Average_6            152
Home_Shots_Target_AwayTeam_average_6            152
Half_Time_Away_Goals_HomeTeam_median_6          152
Home_Shots_6Home_of_away_sum                    152
Away_Red_Cards_Away_AllGames_Average_6          152
Home_Corners_6Away_of_home_mean                 152
Away_score_AwayTeam_sum_6                       152
Home_Fouls_6Away_of_home_median                 152
Home_Woodwork_Away_AllGames_median_6            152
Away_Woodwork_6Away_of_home_mean                152
Time                                            152
Away_score_Home_AllGames_median_6               152
Away_Shots_6Away_of_home_median                 152
Home_Shots_Target_6Home_of_away_sum             152
Home_Fouls_6Home_of_away_mean                   152
Home_Red_Cards_AwayTeam_sum_6                   152
Away_Yellow_Cards_Away_AllGames_Average_6       152
Home_Offsides_AwayTeam_median_6                 152
Away_Yellow_Cards_Away_AllGames_sum_6           152
Final_result_6Away_of_home_median               152
Away_Bookings_Points_6Away_of_home_sum          152
GBAHH                                           152
Half_Time_Away_Goals_6Away_of_home_sum          152
PCAHH                                           152
Home_Shots_Away_AllGames_median_6               152
Final_result_Away_AllGames_median_6             152
Home_Shots_6Away_of_home_sum                    152
Away_Corners_6Home_of_away_median               152
Home_Fouls_6Away_of_home_sum                    152
Home_score_Away_AllGames_Average_6              152
Away_Fouls_Home_AllGames_sum_6                  152

In [214]:
df_N.loc[df_N['HomeTeam']=='Wigan'].isnull().count()

Away_Corners_Away_AllGames_median_6             152
B365H                                           152
Final_Home_goals_Away_AllGames_median_6         152
Home_Offsides_6Home_of_away_mean                152
SYH                                             152
Home_Bookings_Points_6Home_of_away_mean         152
B365D                                           152
Home_Corners_Home_AllGames_Average_6            152
Away_Yellow_Cards_HomeTeam_sum_6                152
Away_score_6Away_of_home_mean                   152
Home_Corners_HomeTeam_average_6                 152
BWD                                             152
Final_Away_goals_AwayTeam_sum_6                 152
Home_Yellow_Cards_AwayTeam_sum_6                152
Home_Woodwork_6Home_of_away_sum                 152
Home_Corners_HomeTeam_median_6                  152
Away_Offsides_6Away_of_home_mean                152
Home_Woodwork_6Home_of_away_mean                152
GBH                                             152
AvgCD                                           152
Home_score_6Home_of_away_mean                   152
BbAvD                                           152
Home_Offsides_6Away_of_home_mean                152
Half_Time_Home_Goals_HomeTeam_average_6         152
Home_Bookings_Points_6Away_of_home_sum          152
Crowd_Attendance_6Away_of_home_mean             152
AvgCAHH                                         152
B365A                                           152
SOA                                             152
Away_Red_Cards_Away_AllGames_median_6           152
Away_Corners_HomeTeam_sum_6                     152
Home_Bookings_Points_HomeTeam_average_6         152
MaxCAHA                                         152
Half_Time_Home_Goals_Home_AllGames_median_6     152
BbMxA                                           152
BbAvA                                           152
Away_Fouls_HomeTeam_average_6                   152
MaxH                                            152
Home_Shots_HomeTeam_median_6                    152
BbAH                                            152
Home_Fouls_Away_AllGames_sum_6                  152
Home_Red_Cards_HomeTeam_median_6                152
Final_Home_goals_AwayTeam_average_6             152
Away_Red_Cards_Home_AllGames_median_6           152
BbMxH                                           152
PSH                                             152
P>2.5                                           152
MaxCD                                           152
Half_Time_Result_HomeTeam_median_6              152
Home_Yellow_Cards_AwayTeam_average_6            152
Away_Bookings_Points_Away_AllGames_Average_6    152
Final_result_6Home_of_away_sum                  152
Away_Corners_HomeTeam_median_6                  152
Crowd_Attendance_Home_AllGames_Average_6        152
P<2.5                                           152
Away_Offsides_AwayTeam_sum_6                    152
Away_Corners_Home_AllGames_median_6             152
AvgAHH                                          152
Home_Bookings_Points_6Away_of_home_median       152
BbAvAHH                                         152
Half_Time_Away_Goals_Home_AllGames_sum_6        152
Home_Fouls_AwayTeam_average_6                   152
Away_Fouls_6Away_of_home_sum                    152
Away_Fouls_Away_AllGames_sum_6                  152
Away_score_Away_AllGames_median_6               152
Away_Offsides_6Away_of_home_median              152
GB>2.5                                          152
Away_Red_Cards_Home_AllGames_Average_6          152
Away_score_6Home_of_away_mean                   152
Away_Red_Cards_6Away_of_home_mean               152
Away_Shots_Target_6Away_of_home_sum             152
Final_Home_goals_6Away_of_home_sum              152
Home_Corners_6Away_of_home_median               152
Home_Woodwork_Away_AllGames_sum_6               152
SOH                                             152
Away_Woodwork_Home_AllGames_Average_6           152
Home_score_6Away_of_home_mean                   152
Home_Fouls_Home_AllGames_sum_6                  152
Home_Yellow_Cards_6Away_of_home_sum             152
Away_Red_Cards_6Home_of_away_sum                152
BbMx<2.5                                        152
Home_Shots_AwayTeam_median_6                    152
Home_Shots_HomeTeam_average_6                   152
Away_Shots_Home_AllGames_median_6               152
Home_score_6Away_of_home_sum                    152
LBH                                             152
Half_Time_Result_Home_AllGames_median_6         152
Home_Shots_Target_HomeTeam_average_6            152
Away_Red_Cards_6Away_of_home_sum                152
Away_Shots_Target_AwayTeam_average_6            152
IWCA                                            152
Away_Offsides_Home_AllGames_median_6            152
Away_Woodwork_Home_AllGames_sum_6               152
Home_Corners_AwayTeam_average_6                 152
Home_Yellow_Cards_HomeTeam_median_6             152
Away_score_Away_AllGames_Average_6              152
Away_Bookings_Points_6Home_of_away_median       152
Final_Away_goals_HomeTeam_sum_6                 152
Final_Away_goals_Home_AllGames_Average_6        152
SBD                                             152
SBA                                             152
Away_Woodwork_Away_AllGames_median_6            152
Home_score_6Home_of_away_median                 152
Crowd_Attendance_HomeTeam_average_6             152
Home_score_Home_AllGames_median_6               152
Crowd_Attendance_AwayTeam_sum_6                 152
IWH                                             152
AwayTeam                                        152
Away_Red_Cards_HomeTeam_sum_6                   152
Away_score_HomeTeam_median_6                    152
Home_Yellow_Cards_6Home_of_away_median          152
WHCH                                            152
Away_Woodwork_6Home_of_away_mean                152
Half_Time_Home_Goals_Away_AllGames_median_6     152
Home_score_Away_AllGames_median_6               152
Bb1X2                                           152
Home_Shots_AwayTeam_sum_6                       152
BWA                                             152
PAHH                                            152
Half_Time_Result_Home_AllGames_sum_6            152
Away_Red_Cards_6Home_of_away_median             152
Away_Shots_Target_Home_AllGames_Average_6       152
AvgCH                                           152
VCCD                                            152
Away_Woodwork_HomeTeam_average_6                152
Half_Time_Away_Goals_Away_AllGames_median_6     152
Half_Time_Away_Goals_HomeTeam_sum_6             152
Avg>2.5                                         152
B365<2.5                                        152
PC>2.5                                          152
Away_Red_Cards_AwayTeam_sum_6                   152
Away_Woodwork_6Away_of_home_sum                 152
Away_Bookings_Points_6Away_of_home_mean         152
Half_Time_Away_Goals_6Home_of_away_sum          152
Away_Shots_Away_AllGames_sum_6                  152
Home_Corners_6Home_of_away_median               152
Home_Shots_HomeTeam_sum_6                       152
Home_Shots_Target_HomeTeam_sum_6                152
Half_Time_Result_6Away_of_home_sum              152
AvgCA                                           152
Home_Fouls_6Home_of_away_sum                    152
Home_Corners_Away_AllGames_median_6             152
Home_Woodwork_6Away_of_home_median              152
Half_Time_Away_Goals_AwayTeam_sum_6             152
Home_Shots_Target_6Away_of_home_mean            152
Away_Bookings_Points_HomeTeam_average_6         152
AvgC<2.5                                        152
Home_Woodwork_6Away_of_home_sum                 152
Away_score_HomeTeam_sum_6                       152
BSD                                             152
Away_Woodwork_HomeTeam_median_6                 152
Final_Home_goals_AwayTeam_sum_6                 152
Home_score_AwayTeam_sum_6                       152
Home_Red_Cards_Away_AllGames_median_6           152
Home_Shots_6Home_of_away_mean                   152
Final_Home_goals_Home_AllGames_Average_6        152
GBAH                                            152
Away_Bookings_Points_Away_AllGames_sum_6        152
Away_Shots_6Away_of_home_mean                   152
Away_Offsides_AwayTeam_median_6                 152
Home_Bookings_Points_HomeTeam_sum_6             152
B365CAHH                                        152
Crowd_Attendance_6Home_of_away_mean             152
Away_Corners_Home_AllGames_sum_6                152
Final_Away_goals_6Away_of_home_mean             152
VCCH                                            152
Home_Fouls_Home_AllGames_median_6               152
Away_Bookings_Points_AwayTeam_average_6         152
Away_Bookings_Points_6Home_of_away_mean         152
Home_Corners_Away_AllGames_sum_6                152
Home_Yellow_Cards_Away_AllGames_Average_6       152
Half_Time_Home_Goals_HomeTeam_sum_6             152
GBAHA                                           152
Away_Shots_Target_Away_AllGames_median_6        152
BbMxAHA                                         152
Crowd_Attendance_6Home_of_away_sum              152
Away_Woodwork_Home_AllGames_median_6            152
Half_Time_Away_Goals_6Away_of_home_median       152
Home_Red_Cards_6Home_of_away_mean               152
Half_Time_Result_Away_AllGames_sum_6            152
Away_Shots_Home_AllGames_sum_6                  152
Home_Shots_Target_AwayTeam_sum_6                152
IWA                                             152
Half_Time_Away_Goals_Home_AllGames_Average_6    152
Final_result_6Away_of_home_sum                  152
BWH                                             152
Away_Fouls_AwayTeam_average_6                   152
Final_Away_goals_Away_AllGames_median_6         152
Away_Red_Cards_Home_AllGames_sum_6              152
Referee                                         152
Away_Yellow_Cards_6Away_of_home_median          152
Home_Yellow_Cards_6Away_of_home_mean            152
Away_score_6Home_of_away_median                 152
Home_Shots_Target_6Home_of_away_mean            152
Half_Time_Result_AwayTeam_median_6              152
Home_Shots_Home_AllGames_sum_6                  152
Final_Away_goals_AwayTeam_median_6              152
Home_Offsides_6Away_of_home_sum                 152
Final_result_Home_AllGames_sum_6                152
PSCA                                            152
Home_Yellow_Cards_6Home_of_away_sum             152
Home_Woodwork_6Home_of_away_median              152
LBAHA                                           152
Home_Offsides_Away_AllGames_sum_6               152
BWCA                                            152
Home_score_Home_AllGames_Average_6              152
Home_Corners_6Away_of_home_sum                  152
Home_Shots_Away_AllGames_Average_6              152
Away_Fouls_AwayTeam_median_6                    152
Away_Corners_6Away_of_home_median               152
Final_result_AwayTeam_average_6                 152
Away_Shots_Target_6Home_of_away_median          152
Home_Offsides_6Away_of_home_median              152
GB<2.5                                          152
Crowd_Attendance_HomeTeam_sum_6                 152
Home_Shots_Target_6Away_of_home_sum             152
Home_Woodwork_HomeTeam_median_6                 152
Away_Shots_Target_AwayTeam_median_6             152
Final_Home_goals_Home_AllGames_median_6         152
Home_Offsides_AwayTeam_sum_6                    152
Away_Shots_6Home_of_away_sum                    152
Away_Corners_6Home_of_away_sum                  152
Away_Shots_Target_HomeTeam_average_6            152
Home_Shots_Target_6Away_of_home_median          152
Home_Woodwork_6Away_of_home_mean                152
Away_Bookings_Points_HomeTeam_sum_6             152
Home_Fouls_6Home_of_away_median                 152
Final_result_Home_AllGames_median_6             152
Home_Bookings_Points_6Home_of_away_sum          152
Home_Shots_AwayTeam_average_6                   152
Crowd_Attendance_HomeTeam_median_6              152
Away_Shots_Target_Home_AllGames_sum_6           152
Away_Red_Cards_Away_AllGames_sum_6              152
Away_Offsides_Home_AllGames_sum_6               152
Away_Yellow_Cards_6Home_of_away_sum             152
Home_Offsides_Home_AllGames_median_6            152
BWCD                                            152
Home_Bookings_Points_Away_AllGames_sum_6        152
Half_Time_Home_Goals_AwayTeam_median_6          152
Away_Yellow_Cards_HomeTeam_median_6             152
Half_Time_Result_6Home_of_away_sum              152
Half_Time_Home_Goals_Home_AllGames_sum_6        152
Home_Offsides_Home_AllGames_sum_6               152
Home_Bookings_Points_Away_AllGames_Average_6    152
Away_Shots_HomeTeam_sum_6                       152
Half_Time_Home_Goals_6Home_of_away_mean         152
Half_Time_Home_Goals_6Home_of_away_sum          152
Away_Woodwork_6Home_of_away_sum                 152
Away_Shots_Target_Away_AllGames_sum_6           152
HomeTeam                                        152
Away_Fouls_6Away_of_home_mean                   152
Away_score_6Home_of_away_sum                    152
Home_Offsides_AwayTeam_average_6                152
Away_score_AwayTeam_median_6                    152
Away_Shots_Target_6Away_of_home_median          152
Away_Shots_Target_6Away_of_home_mean            152
Home_Red_Cards_Away_AllGames_sum_6              152
Away_Shots_Target_Away_AllGames_Average_6       152
Home_Bookings_Points_Home_AllGames_median_6     152
Final_Away_goals_6Home_of_away_sum              152
Home_Yellow_Cards_6Home_of_away_mean            152
Half_Time_Result_6Away_of_home_mean             152
B365AHA                                         152
Home_Red_Cards_HomeTeam_average_6               152
Home_Offsides_Home_AllGames_Average_6           152
Home_Corners_HomeTeam_sum_6                     152
Final_Away_goals_AwayTeam_average_6             152
Half_Time_Result_6Away_of_home_median           152
Final_Away_goals_Away_AllGames_Average_6        152
Home_Bookings_Points_Home_AllGames_Average_6    152
Away_Offsides_6Home_of_away_sum                 152
Home_Yellow_Cards_Home_AllGames_median_6        152
Away_Woodwork_AwayTeam_average_6                152
Away_Fouls_6Away_of_home_median                 152
Home_Offsides_HomeTeam_average_6                152
Crowd_Attendance_Away_AllGames_median_6         152
AvgA                                            152
Final_Away_goals_6Home_of_away_median           152
Away_Shots_HomeTeam_median_6                    152
Crowd_Attendance_Away_AllGames_Average_6        152
Home_Woodwork_AwayTeam_median_6                 152
Away_Woodwork_6Home_of_away_median              152
Away_Shots_6Home_of_away_mean                   152
Half_Time_Result_AwayTeam_sum_6                 152
Home_Red_Cards_6Away_of_home_mean               152
Home_score_6Away_of_home_median                 152
AHCh                                            152
Home_Yellow_Cards_HomeTeam_average_6            152
Away_Yellow_Cards_Away_AllGames_median_6        152
Crowd_Attendance_6Away_of_home_sum              152
Away_Bookings_Points_Home_AllGames_median_6     152
MaxAHA                                          152
VCCA                                            152
Half_Time_Home_Goals_Home_AllGames_Average_6    152
WHD                                             152
MaxC<2.5                                        152
Half_Time_Away_Goals_HomeTeam_average_6         152
Home_Fouls_AwayTeam_sum_6                       152
Final_Away_goals_HomeTeam_average_6             152
Half_Time_Away_Goals_6Home_of_away_mean         152
Home_Yellow_Cards_Home_AllGames_sum_6           152
Home_score_HomeTeam_median_6                    152
MaxC>2.5                                        152
Final_Away_goals_6Away_of_home_median           152
Away_Corners_HomeTeam_average_6                 152
BbAHh                                           152
BbMx>2.5                                        152
Away_score_HomeTeam_average_6                   152
PAHA                                            152
Away_Red_Cards_6Home_of_away_mean               152
Away_Shots_Target_HomeTeam_sum_6                152
Away_Fouls_HomeTeam_sum_6                       152
IWCD                                            152
Home_Red_Cards_Home_AllGames_sum_6              152
Away_Shots_Target_6Home_of_away_sum             152
Home_Yellow_Cards_Away_AllGames_sum_6           152
B365CA                                          152
GBD                                             152
Away_Offsides_HomeTeam_median_6                 152
Home_Yellow_Cards_HomeTeam_sum_6                152
B365>2.5                                        152
PCAHA                                           152
Half_Time_Result_6Home_of_away_median           152
Half_Time_Home_Goals_Away_AllGames_sum_6        152
Final_Home_goals_HomeTeam_median_6              152
SYA                                             152
Half_Time_Home_Goals_AwayTeam_sum_6             152
Home_score_6Home_of_away_sum                    152
PSD                                             152
B365AH                                          152
Away_Corners_AwayTeam_median_6                  152
Half_Time_Home_Goals_AwayTeam_average_6         152
Home_Offsides_HomeTeam_median_6                 152
Away_Shots_Target_Home_AllGames_median_6        152
Away_Woodwork_AwayTeam_median_6                 152
MaxA                                            152
Avg<2.5                                         152
Away_Yellow_Cards_6Away_of_home_sum             152
Away_Shots_Target_HomeTeam_median_6             152
BbAv>2.5                                        152
B365C>2.5                                       152
Away_Yellow_Cards_AwayTeam_average_6            152
Home_Shots_Target_Home_AllGames_Average_6       152
Away_Shots_Target_6Home_of_away_mean            152
Home_Fouls_Away_AllGames_median_6               152
Away_Fouls_HomeTeam_median_6                    152
Away_Offsides_Away_AllGames_median_6            152
Home_Shots_Away_AllGames_sum_6                  152
Final_result_AwayTeam_median_6                  152
Final_Away_goals_Away_AllGames_sum_6            152
Final_Home_goals_Away_AllGames_sum_6            152
Away_Woodwork_6Away_of_home_median              152
Home_Red_Cards_HomeTeam_sum_6                   152
Final_result_Away_AllGames_Average_6            152
Home_Shots_Target_AwayTeam_average_6            152
Half_Time_Away_Goals_HomeTeam_median_6          152
Home_Shots_6Home_of_away_sum                    152
Away_Red_Cards_Away_AllGames_Average_6          152
Home_Corners_6Away_of_home_mean                 152
Away_score_AwayTeam_sum_6                       152
Home_Fouls_6Away_of_home_median                 152
Home_Woodwork_Away_AllGames_median_6            152
Away_Woodwork_6Away_of_home_mean                152
Time                                            152
Away_score_Home_AllGames_median_6               152
Away_Shots_6Away_of_home_median                 152
Home_Shots_Target_6Home_of_away_sum             152
Home_Fouls_6Home_of_away_mean                   152
Home_Red_Cards_AwayTeam_sum_6                   152
Away_Yellow_Cards_Away_AllGames_Average_6       152
Home_Offsides_AwayTeam_median_6                 152
Away_Yellow_Cards_Away_AllGames_sum_6           152
Final_result_6Away_of_home_median               152
Away_Bookings_Points_6Away_of_home_sum          152
GBAHH                                           152
Half_Time_Away_Goals_6Away_of_home_sum          152
PCAHH                                           152
Home_Shots_Away_AllGames_median_6               152
Final_result_Away_AllGames_median_6             152
Home_Shots_6Away_of_home_sum                    152
Away_Corners_6Home_of_away_median               152
Home_Fouls_6Away_of_home_sum                    152
Home_score_Away_AllGames_Average_6              152
Away_Fouls_Home_AllGames_sum_6                  152

In [215]:
df_N.groupby(['AwayTeam'])['Crowd_Attendance_6Home_of_away_median'].value_counts(dropna=False)

AwayTeam          Crowd_Attendance_6Home_of_away_median
Arsenal           38049.047619                             332
                  38026.500000                               3
                  38031.000000                               3
                  38035.500000                               3
                  38045.500000                               3
                  38052.500000                               3
                  38076.500000                               3
                  38018.500000                               2
                  38019.500000                               2
                  38021.500000                               2
                  38038.000000                               2
                  38042.500000                               2
                  38044.000000                               2
                  38047.500000                               2
                  38058.000000                               2
                  38014.000000                               1
                  38020.000000                               1
                  38025.000000                               1
                  38048.500000                               1
                  38049.000000                               1
                  38122.000000                               1
                  38146.000000                               1
                  38254.000000                               1
Aston Villa       32402.048780                             278
                  31352.000000                               3
                  39237.500000                               3
                  27056.000000                               2
                  27655.000000                               2
                  29667.000000                               2
                  30155.500000                               2
                  31795.000000                               2
                  33931.500000                               2
                  38690.000000                               2
                  27452.500000                               1
                  27461.000000                               1
                  27849.000000                               1
                  27895.000000                               1
                  28611.000000                               1
                  30015.500000                               1
                  30157.500000                               1
                  30304.000000                               1
                  30512.000000                               1
                  31444.500000                               1
                  31560.000000                               1
                  31585.500000                               1
                  32723.000000                               1
                  33066.000000                               1
                  34510.000000                               1
                  36597.000000                               1
                  36797.000000                               1
                  36969.000000                               1
                  37341.000000                               1
                  37647.000000                               1
                  38318.000000                               1
Birmingham        NaN                                      133
Blackburn         25883.250000                             187
                  24916.000000                               3
                  23447.000000                               2
                  25435.500000                               2
                  25712.000000                               2
                  25790.500000                               2
                  26079.000000                               2
                  26712.000000                               2
                  27379.000000                               2
                  24403.000000                               1
                  25949.000000                               1
                  26840.500000                               1
                  27781.500000                               1
                  28599.500000                               1
Blackpool         NaN                                       19
Bolton            25157.812500                             185
                  25075.500000                               3
                  25817.000000                               3
                  23869.500000                               2
                  24378.000000                               2
                  24520.000000                               2
                  25855.000000                               2
                  26584.000000                               2
                  23976.000000                               1
                  24116.500000                               1
                  24449.000000                               1
                  24739.500000                               1
                  25117.500000                               1
                  25246.500000                               1
                  25701.000000                               1
                  27351.000000                               1
Bournemouth       NaN                                       91
Bradford          17102.500000                               3
                  16963.000000                               2
                  17135.000000                               2
                  17320.000000                               2
                  19638.500000                               2
                  17160.000000                               1
                  17250.500000                               1
                  17319.000000                               1
                  17954.611111                               1
                  18433.500000                               1
                  19354.000000                               1
                  19980.500000                               1
                  20265.000000                               1
Brighton          NaN                                       53
Burnley           NaN                                      109
Cardiff           NaN                                       38
Charlton          22430.329545                              89
                  20043.000000                              20
                  20451.000000                               4
                  23674.500000                               2
                  25875.000000                               2
                  26457.500000                               2
                  20247.000000                               1
                  21669.000000                               1
                  23042.500000                               1
                  24638.000000                               1
                  25534.000000                               1
                  25769.000000                               1
                  26123.500000                               1
                  26346.500000                               1
                  26356.000000                               1
                  26358.000000                               1
                  26416.500000                               1
                  26557.000000                               1
                  26585.500000                               1
                  26614.000000                               1
Chelsea           37258.388889                             330
                  34632.500000                               3
                  34914.000000                               3
                  34918.500000                               3
                  34982.000000                               3
                  37595.500000                               3
                  38445.500000                               3
                  39174.000000                               3
                  34944.500000                               2
                  39889.500000                               2
                  39981.000000                               2
                  40247.000000                               2
                  40709.000000                               2
                  41217.000000                               2
                  34641.500000                               1
                  34806.000000                               1
                  34954.000000                               1
                  34966.000000                               1
                  34970.500000                               1
                  35059.500000                               1
                  35166.000000                               1
                  35981.500000                               1
                  36567.000000                               1
                  40381.500000                               1
                  40545.000000                               1
                  40627.000000                               1
Coventry          20624.000000                               5
                  20200.500000                               3
                  20631.500000                               2
                  19248.000000                               1
                  20300.000000                               1
                  20319.000000                               1
                  20500.500000                               1
                  20544.500000                               1
                  20599.500000                               1
                  20728.000000                               1
                  20851.500000                               1
                  21277.500000                               1
Crystal Palace    NaN                                      147
Derby             29123.333333                              12
                  28911.500000                               3
                  29224.500000                               3
                  26248.000000                               2
                  27223.000000                               2
                  28300.000000                               2
                  29269.500000                               2
                  29365.000000                               2
                  29565.500000                               2
                  29710.500000                               2
                  30165.000000                               2
                  30883.000000                               2
                  31031.000000                               2
                  31401.000000                               2
                  24290.000000                               1
                  25269.000000                               1
                  25434.500000                               1
                  28083.000000                               1
                  28311.500000                               1
                  28537.500000                               1
                  28573.000000                               1
                  28718.000000                               1
                  28923.500000                               1
                  29055.000000                               1
                  29553.500000                               1
                  30576.000000                               1
                  30714.500000                               1
                  30735.000000                               1
                  30822.000000                               1
                  30926.500000                               1
                  31296.500000                               1
Everton           33879.840909                             332
                  32100.000000                               4
                  32700.500000                               3
                  34234.000000                               3
                  34976.000000                               3
                  35278.000000                               3
                  30933.500000                               2
                  32851.500000                               2
                  33090.500000                               2
                  34840.000000                               2
                  35570.000000                               2
                  31921.500000                               1
                  32176.000000                               1
                  32698.000000                               1
                  33147.500000                               1
                  33257.000000                               1
                  33310.500000                               1
                  33542.500000                               1
                  33718.500000                               1
                  33932.500000                               1
                  34327.500000                               1
                  34807.500000                               1
                  35011.500000                               1
                  35017.500000                               1
                  35408.500000                               1
                  35580.000000                               1
                  35850.000000                               1
                  36170.000000                               1
                  36300.000000                               1
Fulham            19863.545455                             244
                  20128.000000                               5
                  19416.000000                               3
                  19498.000000                               3
                  19810.500000                               3
                  19459.000000                               2
                  20197.000000                               2
                  20805.000000                               2
                  18761.500000                               1
                  20501.000000                               1
Huddersfield      NaN                                       38
Hull              NaN                                       95
Ipswich           22117.500000                               4
                  22723.500000                               4
                  22047.500000                               3
                  23766.000000                               3
                  25081.500000                               3
                  22018.500000                               2
                  22231.000000                               2
                  22827.000000                               2
                  25343.500000                               2
                  21918.500000                               1
                  22007.000000                               1
                  22030.000000                               1
                  22121.500000                               1
                  22129.000000                               1
                  22862.000000                               1
                  23192.608108                               1
                  23416.000000                               1
                  24460.000000                               1
                  24591.500000                               1
                  24707.000000                               1
                  25201.500000                               1
                  25793.500000                               1
Leeds             39683.852273                              32
                  39482.500000                               5
                  39491.000000                               3
                  39859.500000                               3
                  38460.500000                               2
                  38837.000000                               2
                  39259.000000                               2
                  39484.000000                               2
                  39635.500000                               2
                  39934.500000                               2
                  40010.000000                               2
                  40156.000000                               2
                  40172.000000                               2
                  40186.000000                               2
                  39260.000000                               1
                  39423.500000                               1
                  39612.500000                               1
                  39810.000000                               1
                  39811.000000                               1
                  39857.000000                               1
                  39957.500000                               1
                  40014.500000                               1
                  40029.000000                               1
                  40032.500000                               1
                  40151.000000                               1
                  40180.000000                               1
                  40218.000000                               1
Leicester         20336.441860                             123
                  20447.000000                               4
                  18846.000000                               3
                  20061.500000                               3
                  21513.000000                               3
                  19452.500000                               2
                  19463.000000                               2
                  19598.000000                               2
                  20832.500000                               2
                  20965.500000                               2
                  21446.000000                               2
                  21455.000000                               2
                  18769.000000                               1
                  18976.000000                               1
                  18982.000000                               1
                  19745.500000                               1
                  19766.000000                               1
                  19786.000000                               1
                  19920.500000                               1
                  20105.500000                               1
                  20640.000000                               1
                  20655.000000                               1
                  20737.500000                               1
                  20958.500000                               1
                  21294.000000                               1
                  21447.000000                               1
                  21494.000000                               1
                  21716.000000                               1
Liverpool         43956.244186                             332
                  43692.000000                               5
                  43512.000000                               3
                  44109.000000                               3
                  44183.000000                               3

In [216]:
s = pd.DataFrame(df_N.groupby(['AwayTeam'])['Crowd_Attendance_6Home_of_away_median'].value_counts(dropna=False))

In [217]:
s.head()

                                                Crowd_Attendance_6Home_of_away_median
AwayTeam Crowd_Attendance_6Home_of_away_median
Arsenal  38049.047619                                                             332
         38026.500000                                                               3
         38031.000000                                                               3
         38035.500000                                                               3
         38045.500000                                                               3

In [218]:
df_N.groupby(['AwayTeam'])['Crowd_Attendance_6Home_of_away_median'].value_counts(dropna=False).count()

538

In [219]:
del s['Crowd_Attendance_6Home_of_away_median']
s = s.reset_index()
s.tail(20)

     AwayTeam  Crowd_Attendance_6Home_of_away_median
518  West Ham                                26010.0
519  West Ham                                26018.0
520  West Ham                                26030.0
521  West Ham                                27448.5
522  West Ham                                33651.5
523  West Ham                                35546.0
524  West Ham                                25702.5
525  West Ham                                26028.0
526  West Ham                                26028.5
527  West Ham                                26129.0
528  West Ham                                26368.5
529  West Ham                                32088.5
530  West Ham                                33319.0
531  West Ham                                34432.5
532  West Ham                                34576.0
533  West Ham                                34610.5
534  West Ham                                34900.5
535  West Ham                                34989.5
536     Wigan                                    NaN
537    Wolves                                    NaN

In [220]:
(s.groupby('AwayTeam')['Crowd_Attendance_6Home_of_away_median'].count()==0).sort_values()

AwayTeam
Arsenal             False
West Ham            False
Tottenham           False
Sunderland          False
Southampton         False
Newcastle           False
Middlesbrough       False
Man United          False
Man City            False
Liverpool           False
Leicester           False
Ipswich             False
Fulham              False
Everton             False
Derby               False
Leeds               False
Coventry            False
Chelsea             False
Aston Villa         False
Charlton            False
Blackburn           False
Bradford            False
Bolton              False
West Brom            True
Watford              True
Birmingham           True
Swansea              True
Stoke                True
Blackpool            True
Sheffield United     True
Reading              True
Portsmouth           True
Crystal Palace       True
Norwich              True
Bournemouth          True
Brighton             True
Burnley              True
Cardiff              True
Wigan                True
Hull                 True
Huddersfield         True
QPR                  True
Wolves               True
Name: Crowd_Attendance_6Home_of_away_median, dtype: bool

In [221]:
df_N.loc[df_N['AwayTeam']=='Wolves'].isnull().sum()== df_N.loc[df_N['AwayTeam']=='Wolves','Date'].count()

Away_Corners_Away_AllGames_median_6             False
B365H                                           False
Final_Home_goals_Away_AllGames_median_6         False
Home_Offsides_6Home_of_away_mean                 True
SYH                                              True
Home_Bookings_Points_6Home_of_away_mean          True
B365D                                           False
Home_Corners_Home_AllGames_Average_6            False
Away_Yellow_Cards_HomeTeam_sum_6                False
Away_score_6Away_of_home_mean                   False
Home_Corners_HomeTeam_average_6                 False
BWD                                             False
Final_Away_goals_AwayTeam_sum_6                 False
Home_Yellow_Cards_AwayTeam_sum_6                False
Home_Woodwork_6Home_of_away_sum                  True
Home_Corners_HomeTeam_median_6                  False
Away_Offsides_6Away_of_home_mean                False
Home_Woodwork_6Home_of_away_mean                 True
GBH                                             False
AvgCD                                           False
Home_score_6Home_of_away_mean                   False
BbAvD                                           False
Home_Offsides_6Away_of_home_mean                False
Half_Time_Home_Goals_HomeTeam_average_6         False
Home_Bookings_Points_6Away_of_home_sum          False
Crowd_Attendance_6Away_of_home_mean             False
AvgCAHH                                         False
B365A                                           False
SOA                                             False
Away_Red_Cards_Away_AllGames_median_6           False
Away_Corners_HomeTeam_sum_6                     False
Home_Bookings_Points_HomeTeam_average_6         False
MaxCAHA                                         False
Half_Time_Home_Goals_Home_AllGames_median_6     False
BbMxA                                           False
BbAvA                                           False
Away_Fouls_HomeTeam_average_6                   False
MaxH                                            False
Home_Shots_HomeTeam_median_6                    False
BbAH                                            False
Home_Fouls_Away_AllGames_sum_6                  False
Home_Red_Cards_HomeTeam_median_6                False
Final_Home_goals_AwayTeam_average_6             False
Away_Red_Cards_Home_AllGames_median_6           False
BbMxH                                           False
PSH                                             False
P>2.5                                           False
MaxCD                                           False
Half_Time_Result_HomeTeam_median_6              False
Home_Yellow_Cards_AwayTeam_average_6            False
Away_Bookings_Points_Away_AllGames_Average_6     True
Final_result_6Home_of_away_sum                  False
Away_Corners_HomeTeam_median_6                  False
Crowd_Attendance_Home_AllGames_Average_6        False
P<2.5                                           False
Away_Offsides_AwayTeam_sum_6                     True
Away_Corners_Home_AllGames_median_6             False
AvgAHH                                          False
Home_Bookings_Points_6Away_of_home_median       False
BbAvAHH                                         False
Half_Time_Away_Goals_Home_AllGames_sum_6        False
Home_Fouls_AwayTeam_average_6                   False
Away_Fouls_6Away_of_home_sum                    False
Away_Fouls_Away_AllGames_sum_6                  False
Away_score_Away_AllGames_median_6               False
Away_Offsides_6Away_of_home_median              False
GB>2.5                                          False
Away_Red_Cards_Home_AllGames_Average_6          False
Away_score_6Home_of_away_mean                   False
Away_Red_Cards_6Away_of_home_mean               False
Away_Shots_Target_6Away_of_home_sum             False
Final_Home_goals_6Away_of_home_sum              False
Home_Corners_6Away_of_home_median               False
Home_Woodwork_Away_AllGames_sum_6                True
SOH                                             False
Away_Woodwork_Home_AllGames_Average_6           False
Home_score_6Away_of_home_mean                   False
Home_Fouls_Home_AllGames_sum_6                  False
Home_Yellow_Cards_6Away_of_home_sum             False
Away_Red_Cards_6Home_of_away_sum                False
BbMx<2.5                                        False
Home_Shots_AwayTeam_median_6                    False
Home_Shots_HomeTeam_average_6                   False
Away_Shots_Home_AllGames_median_6               False
Home_score_6Away_of_home_sum                    False
LBH                                             False
Half_Time_Result_Home_AllGames_median_6         False
Home_Shots_Target_HomeTeam_average_6            False
Away_Red_Cards_6Away_of_home_sum                False
Away_Shots_Target_AwayTeam_average_6            False
IWCA                                            False
Away_Offsides_Home_AllGames_median_6            False
Away_Woodwork_Home_AllGames_sum_6               False
Home_Corners_AwayTeam_average_6                 False
Home_Yellow_Cards_HomeTeam_median_6             False
Away_score_Away_AllGames_Average_6              False
Away_Bookings_Points_6Home_of_away_median        True
Final_Away_goals_HomeTeam_sum_6                 False
Final_Away_goals_Home_AllGames_Average_6        False
SBD                                             False
SBA                                             False
Away_Woodwork_Away_AllGames_median_6             True
Home_score_6Home_of_away_median                 False
Crowd_Attendance_HomeTeam_average_6             False
Home_score_Home_AllGames_median_6               False
Crowd_Attendance_AwayTeam_sum_6                  True
IWH                                             False
AwayTeam                                        False
Away_Red_Cards_HomeTeam_sum_6                   False
Away_score_HomeTeam_median_6                    False
Home_Yellow_Cards_6Home_of_away_median          False
WHCH                                            False
Away_Woodwork_6Home_of_away_mean                 True
Half_Time_Home_Goals_Away_AllGames_median_6     False
Home_score_Away_AllGames_median_6               False
Bb1X2                                           False
Home_Shots_AwayTeam_sum_6                       False
BWA                                             False
PAHH                                            False
Half_Time_Result_Home_AllGames_sum_6            False
Away_Red_Cards_6Home_of_away_median             False
Away_Shots_Target_Home_AllGames_Average_6       False
AvgCH                                           False
VCCD                                            False
Away_Woodwork_HomeTeam_average_6                False
Half_Time_Away_Goals_Away_AllGames_median_6     False
Half_Time_Away_Goals_HomeTeam_sum_6             False
Avg>2.5                                         False
B365<2.5                                        False
PC>2.5                                          False
Away_Red_Cards_AwayTeam_sum_6                   False
Away_Woodwork_6Away_of_home_sum                 False
Away_Bookings_Points_6Away_of_home_mean         False
Half_Time_Away_Goals_6Home_of_away_sum          False
Away_Shots_Away_AllGames_sum_6                  False
Home_Corners_6Home_of_away_median               False
Home_Shots_HomeTeam_sum_6                       False
Home_Shots_Target_HomeTeam_sum_6                False
Half_Time_Result_6Away_of_home_sum              False
AvgCA                                           False
Home_Fouls_6Home_of_away_sum                    False
Home_Corners_Away_AllGames_median_6             False
Home_Woodwork_6Away_of_home_median              False
Half_Time_Away_Goals_AwayTeam_sum_6             False
Home_Shots_Target_6Away_of_home_mean            False
Away_Bookings_Points_HomeTeam_average_6         False
AvgC<2.5                                        False
Home_Woodwork_6Away_of_home_sum                 False
Away_score_HomeTeam_sum_6                       False
BSD                                             False
Away_Woodwork_HomeTeam_median_6                 False
Final_Home_goals_AwayTeam_sum_6                 False
Home_score_AwayTeam_sum_6                       False
Home_Red_Cards_Away_AllGames_median_6           False
Home_Shots_6Home_of_away_mean                   False
Final_Home_goals_Home_AllGames_Average_6        False
GBAH                                            False
Away_Bookings_Points_Away_AllGames_sum_6         True
Away_Shots_6Away_of_home_mean                   False
Away_Offsides_AwayTeam_median_6                  True
Home_Bookings_Points_HomeTeam_sum_6             False
B365CAHH                                        False
Crowd_Attendance_6Home_of_away_mean              True
Away_Corners_Home_AllGames_sum_6                False
Final_Away_goals_6Away_of_home_mean             False
VCCH                                            False
Home_Fouls_Home_AllGames_median_6               False
Away_Bookings_Points_AwayTeam_average_6          True
Away_Bookings_Points_6Home_of_away_mean          True
Home_Corners_Away_AllGames_sum_6                False
Home_Yellow_Cards_Away_AllGames_Average_6       False
Half_Time_Home_Goals_HomeTeam_sum_6             False
GBAHA                                           False
Away_Shots_Target_Away_AllGames_median_6        False
BbMxAHA                                         False
Crowd_Attendance_6Home_of_away_sum               True
Away_Woodwork_Home_AllGames_median_6            False
Half_Time_Away_Goals_6Away_of_home_median       False
Home_Red_Cards_6Home_of_away_mean               False
Half_Time_Result_Away_AllGames_sum_6            False
Away_Shots_Home_AllGames_sum_6                  False
Home_Shots_Target_AwayTeam_sum_6                False
IWA                                             False
Half_Time_Away_Goals_Home_AllGames_Average_6    False
Final_result_6Away_of_home_sum                  False
BWH                                             False
Away_Fouls_AwayTeam_average_6                   False
Final_Away_goals_Away_AllGames_median_6         False
Away_Red_Cards_Home_AllGames_sum_6              False
Referee                                         False
Away_Yellow_Cards_6Away_of_home_median          False
Home_Yellow_Cards_6Away_of_home_mean            False
Away_score_6Home_of_away_median                 False
Home_Shots_Target_6Home_of_away_mean            False
Half_Time_Result_AwayTeam_median_6              False
Home_Shots_Home_AllGames_sum_6                  False
Final_Away_goals_AwayTeam_median_6              False
Home_Offsides_6Away_of_home_sum                 False
Final_result_Home_AllGames_sum_6                False
PSCA                                            False
Home_Yellow_Cards_6Home_of_away_sum             False
Home_Woodwork_6Home_of_away_median               True
LBAHA                                           False
Home_Offsides_Away_AllGames_sum_6                True
BWCA                                            False
Home_score_Home_AllGames_Average_6              False
Home_Corners_6Away_of_home_sum                  False
Home_Shots_Away_AllGames_Average_6              False
Away_Fouls_AwayTeam_median_6                    False
Away_Corners_6Away_of_home_median               False
Final_result_AwayTeam_average_6                 False
Away_Shots_Target_6Home_of_away_median          False
Home_Offsides_6Away_of_home_median              False
GB<2.5                                          False
Crowd_Attendance_HomeTeam_sum_6                 False
Home_Shots_Target_6Away_of_home_sum             False
Home_Woodwork_HomeTeam_median_6                 False
Away_Shots_Target_AwayTeam_median_6             False
Final_Home_goals_Home_AllGames_median_6         False
Home_Offsides_AwayTeam_sum_6                     True
Away_Shots_6Home_of_away_sum                    False
Away_Corners_6Home_of_away_sum                  False
Away_Shots_Target_HomeTeam_average_6            False
Home_Shots_Target_6Away_of_home_median          False
Home_Woodwork_6Away_of_home_mean                False
Away_Bookings_Points_HomeTeam_sum_6             False
Home_Fouls_6Home_of_away_median                 False
Final_result_Home_AllGames_median_6             False
Home_Bookings_Points_6Home_of_away_sum           True
Home_Shots_AwayTeam_average_6                   False
Crowd_Attendance_HomeTeam_median_6              False
Away_Shots_Target_Home_AllGames_sum_6           False
Away_Red_Cards_Away_AllGames_sum_6              False
Away_Offsides_Home_AllGames_sum_6               False
Away_Yellow_Cards_6Home_of_away_sum             False
Home_Offsides_Home_AllGames_median_6            False
BWCD                                            False
Home_Bookings_Points_Away_AllGames_sum_6         True
Half_Time_Home_Goals_AwayTeam_median_6          False
Away_Yellow_Cards_HomeTeam_median_6             False
Half_Time_Result_6Home_of_away_sum              False
Half_Time_Home_Goals_Home_AllGames_sum_6        False
Home_Offsides_Home_AllGames_sum_6               False
Home_Bookings_Points_Away_AllGames_Average_6     True
Away_Shots_HomeTeam_sum_6                       False
Half_Time_Home_Goals_6Home_of_away_mean         False
Half_Time_Home_Goals_6Home_of_away_sum          False
Away_Woodwork_6Home_of_away_sum                  True
Away_Shots_Target_Away_AllGames_sum_6           False
HomeTeam                                        False
Away_Fouls_6Away_of_home_mean                   False
Away_score_6Home_of_away_sum                    False
Home_Offsides_AwayTeam_average_6                 True
Away_score_AwayTeam_median_6                    False
Away_Shots_Target_6Away_of_home_median          False
Away_Shots_Target_6Away_of_home_mean            False
Home_Red_Cards_Away_AllGames_sum_6              False
Away_Shots_Target_Away_AllGames_Average_6       False
Home_Bookings_Points_Home_AllGames_median_6     False
Final_Away_goals_6Home_of_away_sum              False
Home_Yellow_Cards_6Home_of_away_mean            False
Half_Time_Result_6Away_of_home_mean             False
B365AHA                                         False
Home_Red_Cards_HomeTeam_average_6               False
Home_Offsides_Home_AllGames_Average_6           False
Home_Corners_HomeTeam_sum_6                     False
Final_Away_goals_AwayTeam_average_6             False
Half_Time_Result_6Away_of_home_median           False
Final_Away_goals_Away_AllGames_Average_6        False
Home_Bookings_Points_Home_AllGames_Average_6    False
Away_Offsides_6Home_of_away_sum                  True
Home_Yellow_Cards_Home_AllGames_median_6        False
Away_Woodwork_AwayTeam_average_6                 True
Away_Fouls_6Away_of_home_median                 False
Home_Offsides_HomeTeam_average_6                False
Crowd_Attendance_Away_AllGames_median_6          True
AvgA                                            False
Final_Away_goals_6Home_of_away_median           False
Away_Shots_HomeTeam_median_6                    False
Crowd_Attendance_Away_AllGames_Average_6         True
Home_Woodwork_AwayTeam_median_6                  True
Away_Woodwork_6Home_of_away_median               True
Away_Shots_6Home_of_away_mean                   False
Half_Time_Result_AwayTeam_sum_6                 False
Home_Red_Cards_6Away_of_home_mean               False
Home_score_6Away_of_home_median                 False
AHCh                                            False
Home_Yellow_Cards_HomeTeam_average_6            False
Away_Yellow_Cards_Away_AllGames_median_6        False
Crowd_Attendance_6Away_of_home_sum              False
Away_Bookings_Points_Home_AllGames_median_6     False
MaxAHA                                          False
VCCA                                            False
Half_Time_Home_Goals_Home_AllGames_Average_6    False
WHD                                             False
MaxC<2.5                                        False
Half_Time_Away_Goals_HomeTeam_average_6         False
Home_Fouls_AwayTeam_sum_6                       False
Final_Away_goals_HomeTeam_average_6             False
Half_Time_Away_Goals_6Home_of_away_mean         False
Home_Yellow_Cards_Home_AllGames_sum_6           False
Home_score_HomeTeam_median_6                    False
MaxC>2.5                                        False
Final_Away_goals_6Away_of_home_median           False
Away_Corners_HomeTeam_average_6                 False
BbAHh                                           False
BbMx>2.5                                        False
Away_score_HomeTeam_average_6                   False
PAHA                                            False
Away_Red_Cards_6Home_of_away_mean               False
Away_Shots_Target_HomeTeam_sum_6                False
Away_Fouls_HomeTeam_sum_6                       False
IWCD                                            False
Home_Red_Cards_Home_AllGames_sum_6              False
Away_Shots_Target_6Home_of_away_sum             False
Home_Yellow_Cards_Away_AllGames_sum_6           False
B365CA                                          False
GBD                                             False
Away_Offsides_HomeTeam_median_6                 False
Home_Yellow_Cards_HomeTeam_sum_6                False
B365>2.5                                        False
PCAHA                                           False
Half_Time_Result_6Home_of_away_median           False
Half_Time_Home_Goals_Away_AllGames_sum_6        False
Final_Home_goals_HomeTeam_median_6              False
SYA                                              True
Half_Time_Home_Goals_AwayTeam_sum_6             False
Home_score_6Home_of_away_sum                    False
PSD                                             False
B365AH                                          False
Away_Corners_AwayTeam_median_6                  False
Half_Time_Home_Goals_AwayTeam_average_6         False
Home_Offsides_HomeTeam_median_6                 False
Away_Shots_Target_Home_AllGames_median_6        False
Away_Woodwork_AwayTeam_median_6                  True
MaxA                                            False
Avg<2.5                                         False
Away_Yellow_Cards_6Away_of_home_sum             False
Away_Shots_Target_HomeTeam_median_6             False
BbAv>2.5                                        False
B365C>2.5                                       False
Away_Yellow_Cards_AwayTeam_average_6            False
Home_Shots_Target_Home_AllGames_Average_6       False
Away_Shots_Target_6Home_of_away_mean            False
Home_Fouls_Away_AllGames_median_6               False
Away_Fouls_HomeTeam_median_6                    False
Away_Offsides_Away_AllGames_median_6             True
Home_Shots_Away_AllGames_sum_6                  False
Final_result_AwayTeam_median_6                  False
Final_Away_goals_Away_AllGames_sum_6            False
Final_Home_goals_Away_AllGames_sum_6            False
Away_Woodwork_6Away_of_home_median              False
Home_Red_Cards_HomeTeam_sum_6                   False
Final_result_Away_AllGames_Average_6            False
Home_Shots_Target_AwayTeam_average_6            False
Half_Time_Away_Goals_HomeTeam_median_6          False
Home_Shots_6Home_of_away_sum                    False
Away_Red_Cards_Away_AllGames_Average_6          False
Home_Corners_6Away_of_home_mean                 False
Away_score_AwayTeam_sum_6                       False
Home_Fouls_6Away_of_home_median                 False
Home_Woodwork_Away_AllGames_median_6             True
Away_Woodwork_6Away_of_home_mean                False
Time                                            False
Away_score_Home_AllGames_median_6               False
Away_Shots_6Away_of_home_median                 False
Home_Shots_Target_6Home_of_away_sum             False
Home_Fouls_6Home_of_away_mean                   False
Home_Red_Cards_AwayTeam_sum_6                   False
Away_Yellow_Cards_Away_AllGames_Average_6       False

In [222]:
df_N['Final_result'].value_counts(dropna=False)

1.0    3486
3.0    2128
2.0    1894
Name: Final_result, dtype: int64

In [223]:
df_N.loc[df_N['HomeTeam']=='Wolves'].isnull().sum()== df_N.loc[df_N['HomeTeam']=='Wolves','Date'].count()

Away_Corners_Away_AllGames_median_6             False
B365H                                           False
Final_Home_goals_Away_AllGames_median_6         False
Home_Offsides_6Home_of_away_mean                False
SYH                                              True
Home_Bookings_Points_6Home_of_away_mean         False
B365D                                           False
Home_Corners_Home_AllGames_Average_6            False
Away_Yellow_Cards_HomeTeam_sum_6                False
Away_score_6Away_of_home_mean                   False
Home_Corners_HomeTeam_average_6                 False
BWD                                             False
Final_Away_goals_AwayTeam_sum_6                 False
Home_Yellow_Cards_AwayTeam_sum_6                False
Home_Woodwork_6Home_of_away_sum                 False
Home_Corners_HomeTeam_median_6                  False
Away_Offsides_6Away_of_home_mean                 True
Home_Woodwork_6Home_of_away_mean                False
GBH                                             False
AvgCD                                           False
Home_score_6Home_of_away_mean                   False
BbAvD                                           False
Home_Offsides_6Away_of_home_mean                 True
Half_Time_Home_Goals_HomeTeam_average_6         False
Home_Bookings_Points_6Away_of_home_sum           True
Crowd_Attendance_6Away_of_home_mean              True
AvgCAHH                                         False
B365A                                           False
SOA                                             False
Away_Red_Cards_Away_AllGames_median_6           False
Away_Corners_HomeTeam_sum_6                     False
Home_Bookings_Points_HomeTeam_average_6          True
MaxCAHA                                         False
Half_Time_Home_Goals_Home_AllGames_median_6     False
BbMxA                                           False
BbAvA                                           False
Away_Fouls_HomeTeam_average_6                   False
MaxH                                            False
Home_Shots_HomeTeam_median_6                    False
BbAH                                            False
Home_Fouls_Away_AllGames_sum_6                  False
Home_Red_Cards_HomeTeam_median_6                False
Final_Home_goals_AwayTeam_average_6             False
Away_Red_Cards_Home_AllGames_median_6           False
BbMxH                                           False
PSH                                             False
P>2.5                                           False
MaxCD                                           False
Half_Time_Result_HomeTeam_median_6              False
Home_Yellow_Cards_AwayTeam_average_6            False
Away_Bookings_Points_Away_AllGames_Average_6    False
Final_result_6Home_of_away_sum                  False
Away_Corners_HomeTeam_median_6                  False
Crowd_Attendance_Home_AllGames_Average_6         True
P<2.5                                           False
Away_Offsides_AwayTeam_sum_6                    False
Away_Corners_Home_AllGames_median_6             False
AvgAHH                                          False
Home_Bookings_Points_6Away_of_home_median        True
BbAvAHH                                         False
Half_Time_Away_Goals_Home_AllGames_sum_6        False
Home_Fouls_AwayTeam_average_6                   False
Away_Fouls_6Away_of_home_sum                    False
Away_Fouls_Away_AllGames_sum_6                  False
Away_score_Away_AllGames_median_6               False
Away_Offsides_6Away_of_home_median               True
GB>2.5                                          False
Away_Red_Cards_Home_AllGames_Average_6          False
Away_score_6Home_of_away_mean                   False
Away_Red_Cards_6Away_of_home_mean               False
Away_Shots_Target_6Away_of_home_sum             False
Final_Home_goals_6Away_of_home_sum              False
Home_Corners_6Away_of_home_median               False
Home_Woodwork_Away_AllGames_sum_6               False
SOH                                             False
Away_Woodwork_Home_AllGames_Average_6            True
Home_score_6Away_of_home_mean                   False
Home_Fouls_Home_AllGames_sum_6                  False
Home_Yellow_Cards_6Away_of_home_sum             False
Away_Red_Cards_6Home_of_away_sum                False
BbMx<2.5                                        False
Home_Shots_AwayTeam_median_6                    False
Home_Shots_HomeTeam_average_6                   False
Away_Shots_Home_AllGames_median_6               False
Home_score_6Away_of_home_sum                    False
LBH                                             False
Half_Time_Result_Home_AllGames_median_6         False
Home_Shots_Target_HomeTeam_average_6            False
Away_Red_Cards_6Away_of_home_sum                False
Away_Shots_Target_AwayTeam_average_6            False
IWCA                                            False
Away_Offsides_Home_AllGames_median_6             True
Away_Woodwork_Home_AllGames_sum_6                True
Home_Corners_AwayTeam_average_6                 False
Home_Yellow_Cards_HomeTeam_median_6             False
Away_score_Away_AllGames_Average_6              False
Away_Bookings_Points_6Home_of_away_median       False
Final_Away_goals_HomeTeam_sum_6                 False
Final_Away_goals_Home_AllGames_Average_6        False
SBD                                             False
SBA                                             False
Away_Woodwork_Away_AllGames_median_6            False
Home_score_6Home_of_away_median                 False
Crowd_Attendance_HomeTeam_average_6              True
Home_score_Home_AllGames_median_6               False
Crowd_Attendance_AwayTeam_sum_6                 False
IWH                                             False
AwayTeam                                        False
Away_Red_Cards_HomeTeam_sum_6                   False
Away_score_HomeTeam_median_6                    False
Home_Yellow_Cards_6Home_of_away_median          False
WHCH                                            False
Away_Woodwork_6Home_of_away_mean                False
Half_Time_Home_Goals_Away_AllGames_median_6     False
Home_score_Away_AllGames_median_6               False
Bb1X2                                           False
Home_Shots_AwayTeam_sum_6                       False
BWA                                             False
PAHH                                            False
Half_Time_Result_Home_AllGames_sum_6            False
Away_Red_Cards_6Home_of_away_median             False
Away_Shots_Target_Home_AllGames_Average_6       False
AvgCH                                           False
VCCD                                            False
Away_Woodwork_HomeTeam_average_6                 True
Half_Time_Away_Goals_Away_AllGames_median_6     False
Half_Time_Away_Goals_HomeTeam_sum_6             False
Avg>2.5                                         False
B365<2.5                                        False
PC>2.5                                          False
Away_Red_Cards_AwayTeam_sum_6                   False
Away_Woodwork_6Away_of_home_sum                  True
Away_Bookings_Points_6Away_of_home_mean          True
Half_Time_Away_Goals_6Home_of_away_sum          False
Away_Shots_Away_AllGames_sum_6                  False
Home_Corners_6Home_of_away_median               False
Home_Shots_HomeTeam_sum_6                       False
Home_Shots_Target_HomeTeam_sum_6                False
Half_Time_Result_6Away_of_home_sum              False
AvgCA                                           False
Home_Fouls_6Home_of_away_sum                    False
Home_Corners_Away_AllGames_median_6             False
Home_Woodwork_6Away_of_home_median               True
Half_Time_Away_Goals_AwayTeam_sum_6             False
Home_Shots_Target_6Away_of_home_mean            False
Away_Bookings_Points_HomeTeam_average_6          True
AvgC<2.5                                        False
Home_Woodwork_6Away_of_home_sum                  True
Away_score_HomeTeam_sum_6                       False
BSD                                             False
Away_Woodwork_HomeTeam_median_6                  True
Final_Home_goals_AwayTeam_sum_6                 False
Home_score_AwayTeam_sum_6                       False
Home_Red_Cards_Away_AllGames_median_6           False
Home_Shots_6Home_of_away_mean                   False
Final_Home_goals_Home_AllGames_Average_6        False
GBAH                                            False
Away_Bookings_Points_Away_AllGames_sum_6        False
Away_Shots_6Away_of_home_mean                   False
Away_Offsides_AwayTeam_median_6                 False
Home_Bookings_Points_HomeTeam_sum_6              True
B365CAHH                                        False
Crowd_Attendance_6Home_of_away_mean             False
Away_Corners_Home_AllGames_sum_6                False
Final_Away_goals_6Away_of_home_mean             False
VCCH                                            False
Home_Fouls_Home_AllGames_median_6               False
Away_Bookings_Points_AwayTeam_average_6         False
Away_Bookings_Points_6Home_of_away_mean         False
Home_Corners_Away_AllGames_sum_6                False
Home_Yellow_Cards_Away_AllGames_Average_6       False
Half_Time_Home_Goals_HomeTeam_sum_6             False
GBAHA                                           False
Away_Shots_Target_Away_AllGames_median_6        False
BbMxAHA                                         False
Crowd_Attendance_6Home_of_away_sum              False
Away_Woodwork_Home_AllGames_median_6             True
Half_Time_Away_Goals_6Away_of_home_median       False
Home_Red_Cards_6Home_of_away_mean               False
Half_Time_Result_Away_AllGames_sum_6            False
Away_Shots_Home_AllGames_sum_6                  False
Home_Shots_Target_AwayTeam_sum_6                False
IWA                                             False
Half_Time_Away_Goals_Home_AllGames_Average_6    False
Final_result_6Away_of_home_sum                  False
BWH                                             False
Away_Fouls_AwayTeam_average_6                   False
Final_Away_goals_Away_AllGames_median_6         False
Away_Red_Cards_Home_AllGames_sum_6              False
Referee                                         False
Away_Yellow_Cards_6Away_of_home_median          False
Home_Yellow_Cards_6Away_of_home_mean            False
Away_score_6Home_of_away_median                 False
Home_Shots_Target_6Home_of_away_mean            False
Half_Time_Result_AwayTeam_median_6              False
Home_Shots_Home_AllGames_sum_6                  False
Final_Away_goals_AwayTeam_median_6              False
Home_Offsides_6Away_of_home_sum                  True
Final_result_Home_AllGames_sum_6                False
PSCA                                            False
Home_Yellow_Cards_6Home_of_away_sum             False
Home_Woodwork_6Home_of_away_median              False
LBAHA                                           False
Home_Offsides_Away_AllGames_sum_6               False
BWCA                                            False
Home_score_Home_AllGames_Average_6              False
Home_Corners_6Away_of_home_sum                  False
Home_Shots_Away_AllGames_Average_6              False
Away_Fouls_AwayTeam_median_6                    False
Away_Corners_6Away_of_home_median               False
Final_result_AwayTeam_average_6                 False
Away_Shots_Target_6Home_of_away_median          False
Home_Offsides_6Away_of_home_median               True
GB<2.5                                          False
Crowd_Attendance_HomeTeam_sum_6                  True
Home_Shots_Target_6Away_of_home_sum             False
Home_Woodwork_HomeTeam_median_6                  True
Away_Shots_Target_AwayTeam_median_6             False
Final_Home_goals_Home_AllGames_median_6         False
Home_Offsides_AwayTeam_sum_6                    False
Away_Shots_6Home_of_away_sum                    False
Away_Corners_6Home_of_away_sum                  False
Away_Shots_Target_HomeTeam_average_6            False
Home_Shots_Target_6Away_of_home_median          False
Home_Woodwork_6Away_of_home_mean                 True
Away_Bookings_Points_HomeTeam_sum_6              True
Home_Fouls_6Home_of_away_median                 False
Final_result_Home_AllGames_median_6             False
Home_Bookings_Points_6Home_of_away_sum          False
Home_Shots_AwayTeam_average_6                   False
Crowd_Attendance_HomeTeam_median_6               True
Away_Shots_Target_Home_AllGames_sum_6           False
Away_Red_Cards_Away_AllGames_sum_6              False
Away_Offsides_Home_AllGames_sum_6                True
Away_Yellow_Cards_6Home_of_away_sum             False
Home_Offsides_Home_AllGames_median_6             True
BWCD                                            False
Home_Bookings_Points_Away_AllGames_sum_6        False
Half_Time_Home_Goals_AwayTeam_median_6          False
Away_Yellow_Cards_HomeTeam_median_6             False
Half_Time_Result_6Home_of_away_sum              False
Half_Time_Home_Goals_Home_AllGames_sum_6        False
Home_Offsides_Home_AllGames_sum_6                True
Home_Bookings_Points_Away_AllGames_Average_6    False
Away_Shots_HomeTeam_sum_6                       False
Half_Time_Home_Goals_6Home_of_away_mean         False
Half_Time_Home_Goals_6Home_of_away_sum          False
Away_Woodwork_6Home_of_away_sum                 False
Away_Shots_Target_Away_AllGames_sum_6           False
HomeTeam                                        False
Away_Fouls_6Away_of_home_mean                   False
Away_score_6Home_of_away_sum                    False
Home_Offsides_AwayTeam_average_6                False
Away_score_AwayTeam_median_6                    False
Away_Shots_Target_6Away_of_home_median          False
Away_Shots_Target_6Away_of_home_mean            False
Home_Red_Cards_Away_AllGames_sum_6              False
Away_Shots_Target_Away_AllGames_Average_6       False
Home_Bookings_Points_Home_AllGames_median_6      True
Final_Away_goals_6Home_of_away_sum              False
Home_Yellow_Cards_6Home_of_away_mean            False
Half_Time_Result_6Away_of_home_mean             False
B365AHA                                         False
Home_Red_Cards_HomeTeam_average_6               False
Home_Offsides_Home_AllGames_Average_6            True
Home_Corners_HomeTeam_sum_6                     False
Final_Away_goals_AwayTeam_average_6             False
Half_Time_Result_6Away_of_home_median           False
Final_Away_goals_Away_AllGames_Average_6        False
Home_Bookings_Points_Home_AllGames_Average_6     True
Away_Offsides_6Home_of_away_sum                 False
Home_Yellow_Cards_Home_AllGames_median_6        False
Away_Woodwork_AwayTeam_average_6                False
Away_Fouls_6Away_of_home_median                 False
Home_Offsides_HomeTeam_average_6                 True
Crowd_Attendance_Away_AllGames_median_6         False
AvgA                                            False
Final_Away_goals_6Home_of_away_median           False
Away_Shots_HomeTeam_median_6                    False
Crowd_Attendance_Away_AllGames_Average_6        False
Home_Woodwork_AwayTeam_median_6                 False
Away_Woodwork_6Home_of_away_median              False
Away_Shots_6Home_of_away_mean                   False
Half_Time_Result_AwayTeam_sum_6                 False
Home_Red_Cards_6Away_of_home_mean               False
Home_score_6Away_of_home_median                 False
AHCh                                            False
Home_Yellow_Cards_HomeTeam_average_6            False
Away_Yellow_Cards_Away_AllGames_median_6        False
Crowd_Attendance_6Away_of_home_sum               True
Away_Bookings_Points_Home_AllGames_median_6      True
MaxAHA                                          False
VCCA                                            False
Half_Time_Home_Goals_Home_AllGames_Average_6    False
WHD                                             False
MaxC<2.5                                        False
Half_Time_Away_Goals_HomeTeam_average_6         False
Home_Fouls_AwayTeam_sum_6                       False
Final_Away_goals_HomeTeam_average_6             False
Half_Time_Away_Goals_6Home_of_away_mean         False
Home_Yellow_Cards_Home_AllGames_sum_6           False
Home_score_HomeTeam_median_6                    False
MaxC>2.5                                        False
Final_Away_goals_6Away_of_home_median           False
Away_Corners_HomeTeam_average_6                 False
BbAHh                                           False
BbMx>2.5                                        False
Away_score_HomeTeam_average_6                   False
PAHA                                            False
Away_Red_Cards_6Home_of_away_mean               False
Away_Shots_Target_HomeTeam_sum_6                False
Away_Fouls_HomeTeam_sum_6                       False
IWCD                                            False
Home_Red_Cards_Home_AllGames_sum_6              False
Away_Shots_Target_6Home_of_away_sum             False
Home_Yellow_Cards_Away_AllGames_sum_6           False
B365CA                                          False
GBD                                             False
Away_Offsides_HomeTeam_median_6                  True
Home_Yellow_Cards_HomeTeam_sum_6                False
B365>2.5                                        False
PCAHA                                           False
Half_Time_Result_6Home_of_away_median           False
Half_Time_Home_Goals_Away_AllGames_sum_6        False
Final_Home_goals_HomeTeam_median_6              False
SYA                                              True
Half_Time_Home_Goals_AwayTeam_sum_6             False
Home_score_6Home_of_away_sum                    False
PSD                                             False
B365AH                                          False
Away_Corners_AwayTeam_median_6                  False
Half_Time_Home_Goals_AwayTeam_average_6         False
Home_Offsides_HomeTeam_median_6                  True
Away_Shots_Target_Home_AllGames_median_6        False
Away_Woodwork_AwayTeam_median_6                 False
MaxA                                            False
Avg<2.5                                         False
Away_Yellow_Cards_6Away_of_home_sum             False
Away_Shots_Target_HomeTeam_median_6             False
BbAv>2.5                                        False
B365C>2.5                                       False
Away_Yellow_Cards_AwayTeam_average_6            False
Home_Shots_Target_Home_AllGames_Average_6       False
Away_Shots_Target_6Home_of_away_mean            False
Home_Fouls_Away_AllGames_median_6               False
Away_Fouls_HomeTeam_median_6                    False
Away_Offsides_Away_AllGames_median_6            False
Home_Shots_Away_AllGames_sum_6                  False
Final_result_AwayTeam_median_6                  False
Final_Away_goals_Away_AllGames_sum_6            False
Final_Home_goals_Away_AllGames_sum_6            False
Away_Woodwork_6Away_of_home_median               True
Home_Red_Cards_HomeTeam_sum_6                   False
Final_result_Away_AllGames_Average_6            False
Home_Shots_Target_AwayTeam_average_6            False
Half_Time_Away_Goals_HomeTeam_median_6          False
Home_Shots_6Home_of_away_sum                    False
Away_Red_Cards_Away_AllGames_Average_6          False
Home_Corners_6Away_of_home_mean                 False
Away_score_AwayTeam_sum_6                       False
Home_Fouls_6Away_of_home_median                 False
Home_Woodwork_Away_AllGames_median_6            False
Away_Woodwork_6Away_of_home_mean                 True
Time                                            False
Away_score_Home_AllGames_median_6               False
Away_Shots_6Away_of_home_median                 False
Home_Shots_Target_6Home_of_away_sum             False
Home_Fouls_6Home_of_away_mean                   False
Home_Red_Cards_AwayTeam_sum_6                   False
Away_Yellow_Cards_Away_AllGames_Average_6       False

In [224]:
# Odds fillna

In [225]:
filt1 = df_N.columns[df_N.columns.str.contains(pat = '_HomeTeam_sum_6|_HomeTeam_median_6|_HomeTeam_average_6|_Home_AllGames_sum_6|_Home_AllGames_median_6|_Home_AllGames_Average_6|_6Away_of_home_sum|_6Away_of_home_median|_6Away_of_home_mean')]
filt2 = df_N.columns[df_N.columns.str.contains(pat = '_AwayTeam_sum_6|_AwayTeam_median_6|_AwayTeam_average_6|_Away_AllGames_sum_6|_Away_AllGames_median_6|_Away_AllGames_Average_6|_6Home_of_away_sum|_6Home_of_away_median|_6Home_of_away_mean')]

In [226]:
a1=set(list(filt1))

In [227]:
a2=set(list(filt2))

In [228]:
col= set(df_N.columns.to_list()) - (a1 | a2)
LH=[c for c in col if c[-1] in ('H','h')]
LA=[c for c in col if c[-1] in ('A','a')]
LD=[c for c in col if c[-1] in ('D','d')]
print(LA)

['PAHA', 'B365CAHA', 'GBAHA', 'BbMxAHA', 'B365CA', 'PCAHA', 'IWA', 'SYA', 'PSA', 'MaxA', 'PSCA', 'B365A', 'AvgCAHA', 'SOA', 'LBAHA', 'MaxCAHA', 'BbMxA', 'BbAvA', 'AvgAHA', 'BWCA', 'LBA', 'MaxCA', 'SJA', 'GBA', 'IWCA', 'VCA', 'SBA', 'B365AHA', 'WHCA', 'BbAvAHA', 'BWA', 'AvgA', 'WHA', 'AvgCA', 'MaxAHA', 'VCCA', 'BSA']

In [229]:
df_N.loc[:,LH].head(1)

,SBH,B365H,B365CAHH,BbAHh,WHH,SYH,VCCH,AHh,SJH,IWCH,VCH,GBH,BWH,B365AH,BSH,AvgCAHH,MaxH,BbAH,AvgH,BbMxH,PSH,AvgAHH,BbAvAHH,GBAHH,PCAHH,SOH,LBAH,PSCH,LBH,B365AHH,IWH,WHCH,BbMxAHH,MaxCH,PAHH,AvgCH,B365CH,BWCH,AHCh,LBAHH,MaxAHH,BbAvH,MaxCAHH,GBAH
0,2.2,NaN,NaN,NaN,2.1,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.2,NaN,2.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [478]:
df_N.loc[:,LA].head(1)

,BbMxAHA,GBA,MaxA,SJA,PSCA,IWA,PAHA,MaxAHA,AvgAHA,GBAHA,B365CA,B365AHA,SOA,BWCA,SBA,WHCA,B365CAHA,BbMxA,MaxCAHA,PSA,LBA,VCA,AvgA,BWA,MaxCA,B365A,WHA,AvgCAHA,PCAHA,LBAHA,IWCA,VCCA,AvgCA,SYA,BSA,BbAvA,BbAvAHA
0,NaN,3.2,NaN,NaN,NaN,2.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.88,NaN,NaN,NaN,NaN,NaN,2.75,NaN,NaN,NaN,NaN,NaN,3.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [479]:
df_N.loc[:,LD].head(1)

,IWD,LBD,SJD,BWCD,WHD,BbMxD,VCD,BSD,AvgD,VCCD,IWCD,PSD,WHCD,PSCD,SYD,GBD,BbAvD,SOD,MaxD,MaxCD,BWD,SBD,AvgCD,B365CD,B365D
0,2.9,3.25,NaN,NaN,3.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,3.25,NaN,NaN,NaN

In [480]:
df_O= df_N.copy()

In [481]:
df_O.loc[:,LH]= df_O.loc[:,LH+['HomeTeam']].fillna(df_O.groupby(['HomeTeam'])[LH].transform('mean'))

In [482]:
df_O.loc[:,LA]= df_O.loc[:,LA+['AwayTeam']].fillna(df_O.groupby(['AwayTeam'])[LA].transform('mean'))

In [505]:
df_O.loc[:,LD]= df_O.loc[:,LD+['HomeTeam']+['AwayTeam']].fillna( ((df_O.groupby(['HomeTeam'])[LD].transform('mean'))+(df_O.groupby(['AwayTeam'])[LD].transform('mean')))/2 )

In [489]:
df_N['BSD'].value_counts(dropna=False)

NaN     5228
3.25     501
3.40     312
3.20     300
3.50     189
3.30     142
3.60     122
4.00     113
3.75     108
5.00      74
4.50      72
6.00      62
4.33      60
5.50      57
3.80      44
4.75      24
6.50      18
7.00      18
4.20      17
3.10      15
3.90       8
7.50       7
8.00       4
3.00       4
5.25       3
5.75       2
3.70       2
6.75       1
8.50       1
Name: BSD, dtype: int64

In [490]:
df_O['BSD'].value_counts(dropna=False)

NaN         1739
3.250000     501
3.400000     312
3.200000     300
3.500000     189
3.300000     142
3.600000     122
4.000000     113
3.750000     108
5.000000      74
4.500000      72
6.000000      62
4.330000      60
5.500000      57
3.800000      44
4.750000      24
7.000000      18
6.500000      18
4.200000      17
3.100000      15
8.580789      14
8.568772      14
7.697456      14
8.447807      14
8.584474      14
7.267719      14
7.578947      14
7.007193      14
8.325614      14
7.279298      14
7.141404      14
7.563246      14
7.893772      14
8.233246      14
7.918421      14
7.902719      14
7.527807      14
8.644123      14
7.337719      14
8.163246      14
8.829298      14
8.702982      14
8.329298      14
8.313596      14
7.966404      13
7.896404      13
7.597807      13
7.635877      13
8.796772      13
7.178421      13
7.651579      13
7.823772      13
7.791246      13
8.541596      13
7.368596      13
7.282982      13
7.914737      13
7.495281      13
7.401491      13
7.108509      13
6.863596      13
7.108421      13
8.670088      13
8.130719      13
7.019211      13
6.982105      13
7.235193      13
7.664561      13
8.004035      13
9.038333      12
6.859912      12
7.770088      12
6.966228      12
6.969912      12
6.847895      12
8.672439      12
7.214737      12
6.954211      12
6.942632      12
6.824123      12
7.992018      12
7.366035      12
8.414912      12
8.627456      12
7.284737      12
6.949211      12
7.647895      12
8.261561      12
7.138947      12
8.287982      12
7.922088      12
6.820439      12
6.808421      12
7.110281      11
7.182211      11
7.068947      11
7.863877      11
7.572632      11
7.444035      11
6.909737      11
8.360614      11
6.882281      11
9.293509      11
8.490351      11
6.894298      11
8.745526      11
7.626123      11
6.897982      11
7.088421      11
7.731930      11
7.036421      11
8.079474      11
8.927614      11
7.994719      11
7.533158      10
7.313053      10
7.142807      10
7.206737      10
7.812632      10
7.212807      10
7.055526      10
7.740000      10
6.983596      10
7.016491      10
7.183947      10
7.024649      10
7.241123       9
7.607018       9
7.130965       9
6.985175       8
8.269825       8
8.590088       8
8.544912       8
7.839737       8
6.792544       8
6.822807       8
7.715307       8
7.124386       8
6.820175       8
8.083904       8
7.930351       8
6.810789       8
7.141316       8
6.914737       8
6.816491       8
7.543772       8
6.895175       8
7.283684       8
6.945000       8
7.135000       8
7.111053       8
7.175526       8
7.498596       8
7.634386       8
7.041053       8
8.134035       8
8.011272       8
7.163316       8
8.761623       8
6.796228       8
7.455219       8
7.238509       8
8.680702       8
7.213684       8
9.016798       8
8.935877       8
8.350746       8
8.845263       8
7.038789       8
7.143684       8
7.374298       8
6.938684       8
7.794561       8
6.780526       8
6.898860       8
7.071316       8
3.900000       8
7.017368       8
6.883158       8
6.826491       8
6.804474       8
7.065000       8
6.984474       8
8.800088       8
8.179211       8
7.008526       7
6.981228       7
7.867193       7
7.079211       7
7.500000       7
6.987544       7
6.881842       7
7.158772       7
7.032474       7
7.249386       7
7.912368       7
8.002982       7
7.402237       7
7.242000       7
6.905789       7
6.912105       7
6.957281       7
7.113596       7
7.215000       7
7.256447       7
7.529211       7
7.607895       7
7.321316       7
7.111158       7
7.295921       7
6.825491       6
7.198175       6
8.884667       6
7.140526       6
7.163789       6
7.057018       6
8.218614       6
7.038000       6
6.825702       6
7.044789       6
8.689491       6
7.096421       6
8.944667       6
7.330307       6
7.186684       6
7.383088       6
6.986754       6
6.947684       6
7.169632       6
7.643175       6
7.185526       6
7.074000       6
7.189368       6
7.505263       6
7.250263       6
7.089965       6
7.126684       6
6.829175       6
6.822018       6
7.252500       6
7.258175       6
7.879140       6
6.813474       6
7.323088       6
7.041316       6
8.629491       6
8.278614       6
7.070526       6
7.223789       6
7.039737       6
7.084912       6
7.086491       6
6.990228       6
7.583175       6
7.144000       6
7.059912       6
6.944211       6
7.139368       6
6.810000       6
7.535526       6
7.939140       6
7.042105       6
7.230702       6
7.125895       6
7.041474       6
7.156421       6
7.188737       5
7.147632       5
6.872807       5
6.841912       5
7.951772       5
7.908246       5
7.333316       5
7.299105       5
6.964105       5
7.160421       5
7.311842       5
7.042368       5
8.011772       5
7.219632       5
6.914789       5
9.007088       5
7.271579       5
7.191316       5
7.457632       5
9.072193       5
7.035789       5
6.953070       5
7.445509       5
7.855263       5
6.845596       5
8.139298       5
8.406140       5
8.066667       5
6.860789       5
6.876491       5
9.469825       5
7.554632       5
8.751912       5
8.817018       5
7.246737       5
7.392526       5
8.074193       5
7.299895       5
7.321474       5
9.214649       5
7.308816       5
7.585526       5
6.911316       5
7.510614       5
6.829895       5
8.341035       5
7.075263       5
7.386579       5
7.705596       5
8.001561       5
6.956754       5
6.995000       5
6.962105       5
7.201579       5
7.090421       5
6.941053       5
7.121316       5
7.277921       5
8.168333       5
8.803772       5
7.665789       5
7.770702       5
6.931211       5
7.187018       4
7.231579       4
7.286211       4
7.330105       4
6.919561       4
7.258816       4
7.254386       4
7.162772       4
7.159298       4
6.742807       4
8.252018       4
3.000000       4
6.838684       4
7.534737       4
7.202561       4
7.351316       4
7.019298       4
7.114474       4
7.080965       4
7.985175       4
6.960877       4
7.748947       4
7.057982       4
6.970807       4
6.877018       4
7.124316       4
8.662895       4
7.307895       4
7.159649       4
6.844123       4
8.918070       4
7.606491       4
7.073333       4
7.172316       4
7.678421       4
7.228553       4
7.184316       4
6.754825       4
6.826667       4
7.133000       4
7.270105       4
7.103158       4
7.003333       4
6.974123       4
7.216491       4
6.917018       4
7.142561       4
7.057895       4
7.288772       4
7.356491       4
8.287456       4
8.000000       4
8.464298       4
7.572105       4
7.219965       4
7.003421       4
7.058702       4
7.197000       4
7.217281       4
8.536930       4
7.006316       4
6.842368       4
8.975263       4
7.039211       4
7.157193       4
7.160088       4
7.054667       4
7.242789       4
7.165526       4
6.927982       4
7.538211       4
7.673772       4
7.169053       4
7.709474       4
7.081754       4
7.129825       4
6.905000       4
7.168842       4
7.912544       4
9.292982       4
8.309211       4
7.177895       4
8.042368       4
7.088789       4
7.197193       4
7.118702       4
7.087193       4
7.227895       4
7.731404       4
6.758509       4
7.969737       4
7.991491       4
7.616579       4
8.720088       4
7.235526       4
7.541842       4
7.413684       4
7.159298       3
7.523842       3
7.590789       3
7.037544       3
7.360702       3
9.299825       3
7.701140       3
6.866053       3
7.177105       3
8.633772       3
6.898772       3
7.467544       3
7.304368       3
7.314079       3
7.385702       3
6.878070       3
7.730947       3
7.607368       3
7.629737       3
6.881754       3
7.532632       3
7.180368       3
6.910789       3
7.000263       3
7.196579       3
7.233158       3
7.126772       3
8.257193       3
7.577105       3
7.784211       3
6.967368       3
7.685263       3
7.444474       3
7.961228       3
7.229298       3
9.007544       3
7.369474       3
7.190833       3
7.259053       3
8.626930       3
7.738246       3
7.180579       3
7.224895       3
7.092105       3
7.120368       3
7.261500       3
7.554737       3
7.006649       3
7.998333       3
7.320596       3
5.250000       3
7.233158       3
9.262719       3
8.329825       3
7.761842       3
7.578947       3
7.389079       3
7.258026       3
8.294298       3
8.366930       3
7.502368       3
7.000088       3
7.648158       3
7.199053       3
7.126579       3
6.920702       3
8.596667       3
7.623509       3
7.379368       3
7.498421       3
8.360088       3
9.037807       3
7.353026       3
7.289649       3
7.585000       2
7.138421       2
7.320526       2
7.257614       2
7.247965       2
7.468947       2
7.343316       2
8.825702       2
9.044649       2
3.700000       2
7.804211       2
7.799825       2
7.505526       2
7.149649       2
7.272105       2
7.094053       2
8.075351       2
6.914474       2
7.863158       2
7.181491       2
7.779386       2
7.265018       2
6.889123       2
7.205018       2
7.910526       2
6.990439       2
9.525088       2
7.101649       2
7.175263       2
7.576228       2
7.065877       2
7.210965       2
7.497263       2
7.117123       2
7.764737       2
7.165614       2
7.838596       2
8.519561       2
9.080877       2
7.042807       2
7.360000       2
7.736842       2
7.308158       2
7.398947       2
6.904825       2
7.154123       2
7.322895       2
7.157719       2
7.023333       2
7.292632       2
7.185509       2
7.232456       2
7.150439       2
7.109912       2
7.369737       2
7.272632       2
7.338772       2
7.554105       2
6.901140       2
7.394386       2
7.032982       2
7.274693       2
7.117807       2
7.075526       2
7.705526       2
7.263842       2
7.528684       2
7.963509       2
7.519298       2
7.325579       2
7.760789       2
7.219649       2
7.535000       2
7.120439       2
7.303509       2
7.366421       2
7.214912       2
7.635000       2
9.269912       2
8.223596       2
7.315175       2
7.322105       2
7.238421       2
5.750000       2
8.859035       2
8.147982       2
7.783333       2
8.414825       2
7.767105       2
7.408421       2
7.551404       2
7.106386       1
7.336053       1
7.467018       1
7.003684       1
9.310088       1
7.545789       1
7.185368       1
7.473860       1
7.676667       1
6.968947       1
8.232719       1
7.254298       1
7.416974       1
7.248070       1
7.172368       1
7.767105       1
7.607368       1
6.984649       1
7.504737       1
7.153772       1
7.145702       1
8.500000       1
8.572193       1
6.750000       1
7.695526       1
7.636053       1
7.100789       1
7.662895       1
7.496140       1
6.881491       1
7.314211       1
8.304561       1
7.305263       1
7.327789       1
7.239737       1
7.558596       1
8.305351       1
7.283947       1
7.407263       1
7.544526       1
7.557719       1
7.479474       1
7.589211       1
7.550877       1
7.229474       1
7.217544       1
7.295614       1
7.280895       1
6.980965       1
7.299474       1
7.482947       1
7.602105       1
8.377193       1
7.672105       1
7.450000       1
7.541053       1
7.092105       1
7.624474       1
7.472368       1
7.537684       1
7.070263       1
7.130088       1
6.869474       1
7.571211       1
7.622982       1
7.228316       1
6.970789       1
9.054912       1
7.936754       1
7.274667       1
7.613333       1
9.238246       1
7.103158       1
7.517368       1
7.511579       1
7.474474       1
7.769789       1
7.549737       1
7.337149       1
7.539474       1
8.983070       1
7.218842       1
7.061211       1
7.137281       1
6.885175       1
7.682368       1
7.681579       1
7.477895       1
7.097368       1
7.196947       1
7.097474       1
7.316579       1
7.145965       1
8.592193       1
7.870000       1
7.693684       1
8.008596       1
7.254912       1
7.480263       1
7.249105       1
7.256228       1
7.214667       1
7.711842       1
7.200000       1
7.454316       1
7.766316       1
7.311491       1
7.381579       1
7.514316       1
7.193772       1
7.136316       1
7.748509       1
7.598947       1
7.395263       1
7.130000       1
7.220895       1
7.623596       1
7.504737       1
7.245368       1
7.046228       1
8.644035       1
7.218772       1
7.665263       1
7.551754       1
7.142544       1
7.590263       1
7.534211       1
7.414912       1
Name: BSD, dtype: int64

In [510]:
baghi= set(list(col))- set(LH+LA+LD) -set(['AwayTeam', 'Crowd_Attendance', 'Final_result', 'HomeTeam', 'Referee', 'Season', 'Time','Date'])

In [511]:
bagh=list(baghi)
bagh

['P<2.5',
 'BbAv>2.5',
 'BbMx<2.5',
 'MaxC<2.5',
 'PC>2.5',
 'Max<2.5',
 'GB<2.5',
 'GB>2.5',
 'MaxC>2.5',
 'Max>2.5',
 'B365C>2.5',
 'Bb1X2',
 'P>2.5',
 'AvgC>2.5',
 'B365<2.5',
 'AvgC<2.5',
 'BbAv<2.5',
 'BbOU',
 'Avg<2.5',
 'BbMx>2.5',
 'B365C<2.5',
 'Avg>2.5',
 'B365>2.5',
 'PC<2.5']

In [512]:
df_O.loc[:,bagh]= df_O.loc[:,bagh+['HomeTeam']+['AwayTeam']].fillna( ((df_O.groupby(['HomeTeam'])[bagh].transform('mean'))+(df_O.groupby(['AwayTeam'])[bagh].transform('mean')))/2 )

In [513]:
df_O= df_O.fillna(-1)

In [230]:
df_p= df_N.fillna(-1)

In [231]:
df_p.loc[df_p['AwayTeam']=='Wolves'].isnull().sum()== df_p.loc[df_p['AwayTeam']=='Wolves','Date'].count()

Away_Corners_Away_AllGames_median_6             False
B365H                                           False
Final_Home_goals_Away_AllGames_median_6         False
Home_Offsides_6Home_of_away_mean                False
SYH                                             False
Home_Bookings_Points_6Home_of_away_mean         False
B365D                                           False
Home_Corners_Home_AllGames_Average_6            False
Away_Yellow_Cards_HomeTeam_sum_6                False
Away_score_6Away_of_home_mean                   False
Home_Corners_HomeTeam_average_6                 False
BWD                                             False
Final_Away_goals_AwayTeam_sum_6                 False
Home_Yellow_Cards_AwayTeam_sum_6                False
Home_Woodwork_6Home_of_away_sum                 False
Home_Corners_HomeTeam_median_6                  False
Away_Offsides_6Away_of_home_mean                False
Home_Woodwork_6Home_of_away_mean                False
GBH                                             False
AvgCD                                           False
Home_score_6Home_of_away_mean                   False
BbAvD                                           False
Home_Offsides_6Away_of_home_mean                False
Half_Time_Home_Goals_HomeTeam_average_6         False
Home_Bookings_Points_6Away_of_home_sum          False
Crowd_Attendance_6Away_of_home_mean             False
AvgCAHH                                         False
B365A                                           False
SOA                                             False
Away_Red_Cards_Away_AllGames_median_6           False
Away_Corners_HomeTeam_sum_6                     False
Home_Bookings_Points_HomeTeam_average_6         False
MaxCAHA                                         False
Half_Time_Home_Goals_Home_AllGames_median_6     False
BbMxA                                           False
BbAvA                                           False
Away_Fouls_HomeTeam_average_6                   False
MaxH                                            False
Home_Shots_HomeTeam_median_6                    False
BbAH                                            False
Home_Fouls_Away_AllGames_sum_6                  False
Home_Red_Cards_HomeTeam_median_6                False
Final_Home_goals_AwayTeam_average_6             False
Away_Red_Cards_Home_AllGames_median_6           False
BbMxH                                           False
PSH                                             False
P>2.5                                           False
MaxCD                                           False
Half_Time_Result_HomeTeam_median_6              False
Home_Yellow_Cards_AwayTeam_average_6            False
Away_Bookings_Points_Away_AllGames_Average_6    False
Final_result_6Home_of_away_sum                  False
Away_Corners_HomeTeam_median_6                  False
Crowd_Attendance_Home_AllGames_Average_6        False
P<2.5                                           False
Away_Offsides_AwayTeam_sum_6                    False
Away_Corners_Home_AllGames_median_6             False
AvgAHH                                          False
Home_Bookings_Points_6Away_of_home_median       False
BbAvAHH                                         False
Half_Time_Away_Goals_Home_AllGames_sum_6        False
Home_Fouls_AwayTeam_average_6                   False
Away_Fouls_6Away_of_home_sum                    False
Away_Fouls_Away_AllGames_sum_6                  False
Away_score_Away_AllGames_median_6               False
Away_Offsides_6Away_of_home_median              False
GB>2.5                                          False
Away_Red_Cards_Home_AllGames_Average_6          False
Away_score_6Home_of_away_mean                   False
Away_Red_Cards_6Away_of_home_mean               False
Away_Shots_Target_6Away_of_home_sum             False
Final_Home_goals_6Away_of_home_sum              False
Home_Corners_6Away_of_home_median               False
Home_Woodwork_Away_AllGames_sum_6               False
SOH                                             False
Away_Woodwork_Home_AllGames_Average_6           False
Home_score_6Away_of_home_mean                   False
Home_Fouls_Home_AllGames_sum_6                  False
Home_Yellow_Cards_6Away_of_home_sum             False
Away_Red_Cards_6Home_of_away_sum                False
BbMx<2.5                                        False
Home_Shots_AwayTeam_median_6                    False
Home_Shots_HomeTeam_average_6                   False
Away_Shots_Home_AllGames_median_6               False
Home_score_6Away_of_home_sum                    False
LBH                                             False
Half_Time_Result_Home_AllGames_median_6         False
Home_Shots_Target_HomeTeam_average_6            False
Away_Red_Cards_6Away_of_home_sum                False
Away_Shots_Target_AwayTeam_average_6            False
IWCA                                            False
Away_Offsides_Home_AllGames_median_6            False
Away_Woodwork_Home_AllGames_sum_6               False
Home_Corners_AwayTeam_average_6                 False
Home_Yellow_Cards_HomeTeam_median_6             False
Away_score_Away_AllGames_Average_6              False
Away_Bookings_Points_6Home_of_away_median       False
Final_Away_goals_HomeTeam_sum_6                 False
Final_Away_goals_Home_AllGames_Average_6        False
SBD                                             False
SBA                                             False
Away_Woodwork_Away_AllGames_median_6            False
Home_score_6Home_of_away_median                 False
Crowd_Attendance_HomeTeam_average_6             False
Home_score_Home_AllGames_median_6               False
Crowd_Attendance_AwayTeam_sum_6                 False
IWH                                             False
AwayTeam                                        False
Away_Red_Cards_HomeTeam_sum_6                   False
Away_score_HomeTeam_median_6                    False
Home_Yellow_Cards_6Home_of_away_median          False
WHCH                                            False
Away_Woodwork_6Home_of_away_mean                False
Half_Time_Home_Goals_Away_AllGames_median_6     False
Home_score_Away_AllGames_median_6               False
Bb1X2                                           False
Home_Shots_AwayTeam_sum_6                       False
BWA                                             False
PAHH                                            False
Half_Time_Result_Home_AllGames_sum_6            False
Away_Red_Cards_6Home_of_away_median             False
Away_Shots_Target_Home_AllGames_Average_6       False
AvgCH                                           False
VCCD                                            False
Away_Woodwork_HomeTeam_average_6                False
Half_Time_Away_Goals_Away_AllGames_median_6     False
Half_Time_Away_Goals_HomeTeam_sum_6             False
Avg>2.5                                         False
B365<2.5                                        False
PC>2.5                                          False
Away_Red_Cards_AwayTeam_sum_6                   False
Away_Woodwork_6Away_of_home_sum                 False
Away_Bookings_Points_6Away_of_home_mean         False
Half_Time_Away_Goals_6Home_of_away_sum          False
Away_Shots_Away_AllGames_sum_6                  False
Home_Corners_6Home_of_away_median               False
Home_Shots_HomeTeam_sum_6                       False
Home_Shots_Target_HomeTeam_sum_6                False
Half_Time_Result_6Away_of_home_sum              False
AvgCA                                           False
Home_Fouls_6Home_of_away_sum                    False
Home_Corners_Away_AllGames_median_6             False
Home_Woodwork_6Away_of_home_median              False
Half_Time_Away_Goals_AwayTeam_sum_6             False
Home_Shots_Target_6Away_of_home_mean            False
Away_Bookings_Points_HomeTeam_average_6         False
AvgC<2.5                                        False
Home_Woodwork_6Away_of_home_sum                 False
Away_score_HomeTeam_sum_6                       False
BSD                                             False
Away_Woodwork_HomeTeam_median_6                 False
Final_Home_goals_AwayTeam_sum_6                 False
Home_score_AwayTeam_sum_6                       False
Home_Red_Cards_Away_AllGames_median_6           False
Home_Shots_6Home_of_away_mean                   False
Final_Home_goals_Home_AllGames_Average_6        False
GBAH                                            False
Away_Bookings_Points_Away_AllGames_sum_6        False
Away_Shots_6Away_of_home_mean                   False
Away_Offsides_AwayTeam_median_6                 False
Home_Bookings_Points_HomeTeam_sum_6             False
B365CAHH                                        False
Crowd_Attendance_6Home_of_away_mean             False
Away_Corners_Home_AllGames_sum_6                False
Final_Away_goals_6Away_of_home_mean             False
VCCH                                            False
Home_Fouls_Home_AllGames_median_6               False
Away_Bookings_Points_AwayTeam_average_6         False
Away_Bookings_Points_6Home_of_away_mean         False
Home_Corners_Away_AllGames_sum_6                False
Home_Yellow_Cards_Away_AllGames_Average_6       False
Half_Time_Home_Goals_HomeTeam_sum_6             False
GBAHA                                           False
Away_Shots_Target_Away_AllGames_median_6        False
BbMxAHA                                         False
Crowd_Attendance_6Home_of_away_sum              False
Away_Woodwork_Home_AllGames_median_6            False
Half_Time_Away_Goals_6Away_of_home_median       False
Home_Red_Cards_6Home_of_away_mean               False
Half_Time_Result_Away_AllGames_sum_6            False
Away_Shots_Home_AllGames_sum_6                  False
Home_Shots_Target_AwayTeam_sum_6                False
IWA                                             False
Half_Time_Away_Goals_Home_AllGames_Average_6    False
Final_result_6Away_of_home_sum                  False
BWH                                             False
Away_Fouls_AwayTeam_average_6                   False
Final_Away_goals_Away_AllGames_median_6         False
Away_Red_Cards_Home_AllGames_sum_6              False
Referee                                         False
Away_Yellow_Cards_6Away_of_home_median          False
Home_Yellow_Cards_6Away_of_home_mean            False
Away_score_6Home_of_away_median                 False
Home_Shots_Target_6Home_of_away_mean            False
Half_Time_Result_AwayTeam_median_6              False
Home_Shots_Home_AllGames_sum_6                  False
Final_Away_goals_AwayTeam_median_6              False
Home_Offsides_6Away_of_home_sum                 False
Final_result_Home_AllGames_sum_6                False
PSCA                                            False
Home_Yellow_Cards_6Home_of_away_sum             False
Home_Woodwork_6Home_of_away_median              False
LBAHA                                           False
Home_Offsides_Away_AllGames_sum_6               False
BWCA                                            False
Home_score_Home_AllGames_Average_6              False
Home_Corners_6Away_of_home_sum                  False
Home_Shots_Away_AllGames_Average_6              False
Away_Fouls_AwayTeam_median_6                    False
Away_Corners_6Away_of_home_median               False
Final_result_AwayTeam_average_6                 False
Away_Shots_Target_6Home_of_away_median          False
Home_Offsides_6Away_of_home_median              False
GB<2.5                                          False
Crowd_Attendance_HomeTeam_sum_6                 False
Home_Shots_Target_6Away_of_home_sum             False
Home_Woodwork_HomeTeam_median_6                 False
Away_Shots_Target_AwayTeam_median_6             False
Final_Home_goals_Home_AllGames_median_6         False
Home_Offsides_AwayTeam_sum_6                    False
Away_Shots_6Home_of_away_sum                    False
Away_Corners_6Home_of_away_sum                  False
Away_Shots_Target_HomeTeam_average_6            False
Home_Shots_Target_6Away_of_home_median          False
Home_Woodwork_6Away_of_home_mean                False
Away_Bookings_Points_HomeTeam_sum_6             False
Home_Fouls_6Home_of_away_median                 False
Final_result_Home_AllGames_median_6             False
Home_Bookings_Points_6Home_of_away_sum          False
Home_Shots_AwayTeam_average_6                   False
Crowd_Attendance_HomeTeam_median_6              False
Away_Shots_Target_Home_AllGames_sum_6           False
Away_Red_Cards_Away_AllGames_sum_6              False
Away_Offsides_Home_AllGames_sum_6               False
Away_Yellow_Cards_6Home_of_away_sum             False
Home_Offsides_Home_AllGames_median_6            False
BWCD                                            False
Home_Bookings_Points_Away_AllGames_sum_6        False
Half_Time_Home_Goals_AwayTeam_median_6          False
Away_Yellow_Cards_HomeTeam_median_6             False
Half_Time_Result_6Home_of_away_sum              False
Half_Time_Home_Goals_Home_AllGames_sum_6        False
Home_Offsides_Home_AllGames_sum_6               False
Home_Bookings_Points_Away_AllGames_Average_6    False
Away_Shots_HomeTeam_sum_6                       False
Half_Time_Home_Goals_6Home_of_away_mean         False
Half_Time_Home_Goals_6Home_of_away_sum          False
Away_Woodwork_6Home_of_away_sum                 False
Away_Shots_Target_Away_AllGames_sum_6           False
HomeTeam                                        False
Away_Fouls_6Away_of_home_mean                   False
Away_score_6Home_of_away_sum                    False
Home_Offsides_AwayTeam_average_6                False
Away_score_AwayTeam_median_6                    False
Away_Shots_Target_6Away_of_home_median          False
Away_Shots_Target_6Away_of_home_mean            False
Home_Red_Cards_Away_AllGames_sum_6              False
Away_Shots_Target_Away_AllGames_Average_6       False
Home_Bookings_Points_Home_AllGames_median_6     False
Final_Away_goals_6Home_of_away_sum              False
Home_Yellow_Cards_6Home_of_away_mean            False
Half_Time_Result_6Away_of_home_mean             False
B365AHA                                         False
Home_Red_Cards_HomeTeam_average_6               False
Home_Offsides_Home_AllGames_Average_6           False
Home_Corners_HomeTeam_sum_6                     False
Final_Away_goals_AwayTeam_average_6             False
Half_Time_Result_6Away_of_home_median           False
Final_Away_goals_Away_AllGames_Average_6        False
Home_Bookings_Points_Home_AllGames_Average_6    False
Away_Offsides_6Home_of_away_sum                 False
Home_Yellow_Cards_Home_AllGames_median_6        False
Away_Woodwork_AwayTeam_average_6                False
Away_Fouls_6Away_of_home_median                 False
Home_Offsides_HomeTeam_average_6                False
Crowd_Attendance_Away_AllGames_median_6         False
AvgA                                            False
Final_Away_goals_6Home_of_away_median           False
Away_Shots_HomeTeam_median_6                    False
Crowd_Attendance_Away_AllGames_Average_6        False
Home_Woodwork_AwayTeam_median_6                 False
Away_Woodwork_6Home_of_away_median              False
Away_Shots_6Home_of_away_mean                   False
Half_Time_Result_AwayTeam_sum_6                 False
Home_Red_Cards_6Away_of_home_mean               False
Home_score_6Away_of_home_median                 False
AHCh                                            False
Home_Yellow_Cards_HomeTeam_average_6            False
Away_Yellow_Cards_Away_AllGames_median_6        False
Crowd_Attendance_6Away_of_home_sum              False
Away_Bookings_Points_Home_AllGames_median_6     False
MaxAHA                                          False
VCCA                                            False
Half_Time_Home_Goals_Home_AllGames_Average_6    False
WHD                                             False
MaxC<2.5                                        False
Half_Time_Away_Goals_HomeTeam_average_6         False
Home_Fouls_AwayTeam_sum_6                       False
Final_Away_goals_HomeTeam_average_6             False
Half_Time_Away_Goals_6Home_of_away_mean         False
Home_Yellow_Cards_Home_AllGames_sum_6           False
Home_score_HomeTeam_median_6                    False
MaxC>2.5                                        False
Final_Away_goals_6Away_of_home_median           False
Away_Corners_HomeTeam_average_6                 False
BbAHh                                           False
BbMx>2.5                                        False
Away_score_HomeTeam_average_6                   False
PAHA                                            False
Away_Red_Cards_6Home_of_away_mean               False
Away_Shots_Target_HomeTeam_sum_6                False
Away_Fouls_HomeTeam_sum_6                       False
IWCD                                            False
Home_Red_Cards_Home_AllGames_sum_6              False
Away_Shots_Target_6Home_of_away_sum             False
Home_Yellow_Cards_Away_AllGames_sum_6           False
B365CA                                          False
GBD                                             False
Away_Offsides_HomeTeam_median_6                 False
Home_Yellow_Cards_HomeTeam_sum_6                False
B365>2.5                                        False
PCAHA                                           False
Half_Time_Result_6Home_of_away_median           False
Half_Time_Home_Goals_Away_AllGames_sum_6        False
Final_Home_goals_HomeTeam_median_6              False
SYA                                             False
Half_Time_Home_Goals_AwayTeam_sum_6             False
Home_score_6Home_of_away_sum                    False
PSD                                             False
B365AH                                          False
Away_Corners_AwayTeam_median_6                  False
Half_Time_Home_Goals_AwayTeam_average_6         False
Home_Offsides_HomeTeam_median_6                 False
Away_Shots_Target_Home_AllGames_median_6        False
Away_Woodwork_AwayTeam_median_6                 False
MaxA                                            False
Avg<2.5                                         False
Away_Yellow_Cards_6Away_of_home_sum             False
Away_Shots_Target_HomeTeam_median_6             False
BbAv>2.5                                        False
B365C>2.5                                       False
Away_Yellow_Cards_AwayTeam_average_6            False
Home_Shots_Target_Home_AllGames_Average_6       False
Away_Shots_Target_6Home_of_away_mean            False
Home_Fouls_Away_AllGames_median_6               False
Away_Fouls_HomeTeam_median_6                    False
Away_Offsides_Away_AllGames_median_6            False
Home_Shots_Away_AllGames_sum_6                  False
Final_result_AwayTeam_median_6                  False
Final_Away_goals_Away_AllGames_sum_6            False
Final_Home_goals_Away_AllGames_sum_6            False
Away_Woodwork_6Away_of_home_median              False
Home_Red_Cards_HomeTeam_sum_6                   False
Final_result_Away_AllGames_Average_6            False
Home_Shots_Target_AwayTeam_average_6            False
Half_Time_Away_Goals_HomeTeam_median_6          False
Home_Shots_6Home_of_away_sum                    False
Away_Red_Cards_Away_AllGames_Average_6          False
Home_Corners_6Away_of_home_mean                 False
Away_score_AwayTeam_sum_6                       False
Home_Fouls_6Away_of_home_median                 False
Home_Woodwork_Away_AllGames_median_6            False
Away_Woodwork_6Away_of_home_mean                False
Time                                            False
Away_score_Home_AllGames_median_6               False
Away_Shots_6Away_of_home_median                 False
Home_Shots_Target_6Home_of_away_sum             False
Home_Fouls_6Home_of_away_mean                   False
Home_Red_Cards_AwayTeam_sum_6                   False
Away_Yellow_Cards_Away_AllGames_Average_6       False

In [232]:
(df_p.loc[df_p['HomeTeam']=='Hull']==-1).sum()

Away_Corners_Away_AllGames_median_6              0
B365H                                            0
Final_Home_goals_Away_AllGames_median_6          0
Home_Offsides_6Home_of_away_mean                29
SYH                                             95
Home_Bookings_Points_6Home_of_away_mean         29
B365D                                            0
Home_Corners_Home_AllGames_Average_6             0
Away_Yellow_Cards_HomeTeam_sum_6                 0
Away_score_6Away_of_home_mean                    0
Home_Corners_HomeTeam_average_6                  0
BWD                                              0
Final_Away_goals_AwayTeam_sum_6                  0
Home_Yellow_Cards_AwayTeam_sum_6                 0
Home_Woodwork_6Home_of_away_sum                 29
Home_Corners_HomeTeam_median_6                   0
Away_Offsides_6Away_of_home_mean                95
Home_Woodwork_6Home_of_away_mean                29
GBH                                             57
AvgCD                                           95
Home_score_6Home_of_away_mean                    0
BbAvD                                            0
Home_Offsides_6Away_of_home_mean                95
Half_Time_Home_Goals_HomeTeam_average_6          0
Home_Bookings_Points_6Away_of_home_sum          95
Crowd_Attendance_6Away_of_home_mean             95
AvgCAHH                                         95
B365A                                            0
SOA                                             95
Away_Red_Cards_Away_AllGames_median_6            0
Away_Corners_HomeTeam_sum_6                      0
Home_Bookings_Points_HomeTeam_average_6         95
MaxCAHA                                         95
Half_Time_Home_Goals_Home_AllGames_median_6      0
BbMxA                                            0
BbAvA                                            0
Away_Fouls_HomeTeam_average_6                    0
MaxH                                            95
Home_Shots_HomeTeam_median_6                     0
BbAH                                             0
Home_Fouls_Away_AllGames_sum_6                   0
Home_Red_Cards_HomeTeam_median_6                 0
Final_Home_goals_AwayTeam_average_6              0
Away_Red_Cards_Home_AllGames_median_6            0
BbMxH                                            0
PSH                                             38
P>2.5                                           95
MaxCD                                           95
Half_Time_Result_HomeTeam_median_6               0
Home_Yellow_Cards_AwayTeam_average_6             0
Away_Bookings_Points_Away_AllGames_Average_6    29
Final_result_6Home_of_away_sum                   0
Away_Corners_HomeTeam_median_6                   0
Crowd_Attendance_Home_AllGames_Average_6        95
P<2.5                                           95
Away_Offsides_AwayTeam_sum_6                    29
Away_Corners_Home_AllGames_median_6              0
AvgAHH                                          95
Home_Bookings_Points_6Away_of_home_median       95
BbAvAHH                                          0
Half_Time_Away_Goals_Home_AllGames_sum_6         0
Home_Fouls_AwayTeam_average_6                    0
Away_Fouls_6Away_of_home_sum                     0
Away_Fouls_Away_AllGames_sum_6                   0
Away_score_Away_AllGames_median_6                0
Away_Offsides_6Away_of_home_median              95
GB>2.5                                          95
Away_Red_Cards_Home_AllGames_Average_6           0
Away_score_6Home_of_away_mean                    0
Away_Red_Cards_6Away_of_home_mean                0
Away_Shots_Target_6Away_of_home_sum              0
Final_Home_goals_6Away_of_home_sum               0
Home_Corners_6Away_of_home_median                0
Home_Woodwork_Away_AllGames_sum_6               29
SOH                                             95
Away_Woodwork_Home_AllGames_Average_6           95
Home_score_6Away_of_home_mean                    0
Home_Fouls_Home_AllGames_sum_6                   0
Home_Yellow_Cards_6Away_of_home_sum              0
Away_Red_Cards_6Home_of_away_sum                 0
BbMx<2.5                                         0
Home_Shots_AwayTeam_median_6                     0
Home_Shots_HomeTeam_average_6                    0
Away_Shots_Home_AllGames_median_6                0
Home_score_6Away_of_home_sum                     0
LBH                                              0
Half_Time_Result_Home_AllGames_median_6          0
Home_Shots_Target_HomeTeam_average_6             0
Away_Red_Cards_6Away_of_home_sum                 0
Away_Shots_Target_AwayTeam_average_6             0
IWCA                                            95
Away_Offsides_Home_AllGames_median_6            95
Away_Woodwork_Home_AllGames_sum_6               95
Home_Corners_AwayTeam_average_6                  0
Home_Yellow_Cards_HomeTeam_median_6              0
Away_score_Away_AllGames_Average_6               0
Away_Bookings_Points_6Home_of_away_median       29
Final_Away_goals_HomeTeam_sum_6                  0
Final_Away_goals_Home_AllGames_Average_6         0
SBD                                             57
SBA                                             57
Away_Woodwork_Away_AllGames_median_6            29
Home_score_6Home_of_away_median                  0
Crowd_Attendance_HomeTeam_average_6             95
Home_score_Home_AllGames_median_6                0
Crowd_Attendance_AwayTeam_sum_6                 29
IWH                                              1
AwayTeam                                         0
Away_Red_Cards_HomeTeam_sum_6                    0
Away_score_HomeTeam_median_6                     0
Home_Yellow_Cards_6Home_of_away_median           0
WHCH                                            95
Away_Woodwork_6Home_of_away_mean                29
Half_Time_Home_Goals_Away_AllGames_median_6      0
Home_score_Away_AllGames_median_6                0
Bb1X2                                            0
Home_Shots_AwayTeam_sum_6                        0
BWA                                              0
PAHH                                            95
Half_Time_Result_Home_AllGames_sum_6             0
Away_Red_Cards_6Home_of_away_median              0
Away_Shots_Target_Home_AllGames_Average_6        0
AvgCH                                           95
VCCD                                            95
Away_Woodwork_HomeTeam_average_6                95
Half_Time_Away_Goals_Away_AllGames_median_6      0
Half_Time_Away_Goals_HomeTeam_sum_6              0
Avg>2.5                                         95
B365<2.5                                        95
PC>2.5                                          95
Away_Red_Cards_AwayTeam_sum_6                    0
Away_Woodwork_6Away_of_home_sum                 95
Away_Bookings_Points_6Away_of_home_mean         95
Half_Time_Away_Goals_6Home_of_away_sum           0
Away_Shots_Away_AllGames_sum_6                   0
Home_Corners_6Home_of_away_median                0
Home_Shots_HomeTeam_sum_6                        0
Home_Shots_Target_HomeTeam_sum_6                 0
Half_Time_Result_6Away_of_home_sum               0
AvgCA                                           95
Home_Fouls_6Home_of_away_sum                     0
Home_Corners_Away_AllGames_median_6              0
Home_Woodwork_6Away_of_home_median              95
Half_Time_Away_Goals_AwayTeam_sum_6              0
Home_Shots_Target_6Away_of_home_mean             0
Away_Bookings_Points_HomeTeam_average_6         95
AvgC<2.5                                        95
Home_Woodwork_6Away_of_home_sum                 95
Away_score_HomeTeam_sum_6                        0
BSD                                             57
Away_Woodwork_HomeTeam_median_6                 95
Final_Home_goals_AwayTeam_sum_6                  0
Home_score_AwayTeam_sum_6                        0
Home_Red_Cards_Away_AllGames_median_6            0
Home_Shots_6Home_of_away_mean                    0
Final_Home_goals_Home_AllGames_Average_6         0
GBAH                                            95
Away_Bookings_Points_Away_AllGames_sum_6        29
Away_Shots_6Away_of_home_mean                    0
Away_Offsides_AwayTeam_median_6                 29
Home_Bookings_Points_HomeTeam_sum_6             95
B365CAHH                                        95
Crowd_Attendance_6Home_of_away_mean             29
Away_Corners_Home_AllGames_sum_6                 0
Final_Away_goals_6Away_of_home_mean              0
VCCH                                            95
Home_Fouls_Home_AllGames_median_6                0
Away_Bookings_Points_AwayTeam_average_6         29
Away_Bookings_Points_6Home_of_away_mean         29
Home_Corners_Away_AllGames_sum_6                 0
Home_Yellow_Cards_Away_AllGames_Average_6        0
Half_Time_Home_Goals_HomeTeam_sum_6              0
GBAHA                                           95
Away_Shots_Target_Away_AllGames_median_6         0
BbMxAHA                                          0
Crowd_Attendance_6Home_of_away_sum              29
Away_Woodwork_Home_AllGames_median_6            95
Half_Time_Away_Goals_6Away_of_home_median        0
Home_Red_Cards_6Home_of_away_mean                0
Half_Time_Result_Away_AllGames_sum_6             0
Away_Shots_Home_AllGames_sum_6                   0
Home_Shots_Target_AwayTeam_sum_6                 0
IWA                                              1
Half_Time_Away_Goals_Home_AllGames_Average_6     0
Final_result_6Away_of_home_sum                   0
BWH                                              0
Away_Fouls_AwayTeam_average_6                    0
Final_Away_goals_Away_AllGames_median_6          0
Away_Red_Cards_Home_AllGames_sum_6               0
Referee                                          0
Away_Yellow_Cards_6Away_of_home_median           0
Home_Yellow_Cards_6Away_of_home_mean             0
Away_score_6Home_of_away_median                  0
Home_Shots_Target_6Home_of_away_mean             0
Half_Time_Result_AwayTeam_median_6               0
Home_Shots_Home_AllGames_sum_6                   0
Final_Away_goals_AwayTeam_median_6               0
Home_Offsides_6Away_of_home_sum                 95
Final_result_Home_AllGames_sum_6                 0
PSCA                                            38
Home_Yellow_Cards_6Home_of_away_sum              0
Home_Woodwork_6Home_of_away_median              29
LBAHA                                           95
Home_Offsides_Away_AllGames_sum_6               29
BWCA                                            95
Home_score_Home_AllGames_Average_6               0
Home_Corners_6Away_of_home_sum                   0
Home_Shots_Away_AllGames_Average_6               0
Away_Fouls_AwayTeam_median_6                     0
Away_Corners_6Away_of_home_median                0
Final_result_AwayTeam_average_6                  0
Away_Shots_Target_6Home_of_away_median           0
Home_Offsides_6Away_of_home_median              95
GB<2.5                                          95
Crowd_Attendance_HomeTeam_sum_6                 95
Home_Shots_Target_6Away_of_home_sum              0
Home_Woodwork_HomeTeam_median_6                 95
Away_Shots_Target_AwayTeam_median_6              0
Final_Home_goals_Home_AllGames_median_6          0
Home_Offsides_AwayTeam_sum_6                    29
Away_Shots_6Home_of_away_sum                     0
Away_Corners_6Home_of_away_sum                   0
Away_Shots_Target_HomeTeam_average_6             0
Home_Shots_Target_6Away_of_home_median           0
Home_Woodwork_6Away_of_home_mean                95
Away_Bookings_Points_HomeTeam_sum_6             95
Home_Fouls_6Home_of_away_median                  0
Final_result_Home_AllGames_median_6              0
Home_Bookings_Points_6Home_of_away_sum          29
Home_Shots_AwayTeam_average_6                    0
Crowd_Attendance_HomeTeam_median_6              95
Away_Shots_Target_Home_AllGames_sum_6            0
Away_Red_Cards_Away_AllGames_sum_6               0
Away_Offsides_Home_AllGames_sum_6               95
Away_Yellow_Cards_6Home_of_away_sum              0
Home_Offsides_Home_AllGames_median_6            95
BWCD                                            95
Home_Bookings_Points_Away_AllGames_sum_6        29
Half_Time_Home_Goals_AwayTeam_median_6           0
Away_Yellow_Cards_HomeTeam_median_6              0
Half_Time_Result_6Home_of_away_sum               0
Half_Time_Home_Goals_Home_AllGames_sum_6         0
Home_Offsides_Home_AllGames_sum_6               95
Home_Bookings_Points_Away_AllGames_Average_6    29
Away_Shots_HomeTeam_sum_6                        0
Half_Time_Home_Goals_6Home_of_away_mean          0
Half_Time_Home_Goals_6Home_of_away_sum           0
Away_Woodwork_6Home_of_away_sum                 29
Away_Shots_Target_Away_AllGames_sum_6            0
HomeTeam                                         0
Away_Fouls_6Away_of_home_mean                    0
Away_score_6Home_of_away_sum                     0
Home_Offsides_AwayTeam_average_6                29
Away_score_AwayTeam_median_6                     0
Away_Shots_Target_6Away_of_home_median           0
Away_Shots_Target_6Away_of_home_mean             0
Home_Red_Cards_Away_AllGames_sum_6               0
Away_Shots_Target_Away_AllGames_Average_6        0
Home_Bookings_Points_Home_AllGames_median_6     95
Final_Away_goals_6Home_of_away_sum               0
Home_Yellow_Cards_6Home_of_away_mean             0
Half_Time_Result_6Away_of_home_mean              0
B365AHA                                         95
Home_Red_Cards_HomeTeam_average_6                0
Home_Offsides_Home_AllGames_Average_6           95
Home_Corners_HomeTeam_sum_6                      0
Final_Away_goals_AwayTeam_average_6              0
Half_Time_Result_6Away_of_home_median            0
Final_Away_goals_Away_AllGames_Average_6         0
Home_Bookings_Points_Home_AllGames_Average_6    95
Away_Offsides_6Home_of_away_sum                 29
Home_Yellow_Cards_Home_AllGames_median_6         0
Away_Woodwork_AwayTeam_average_6                29
Away_Fouls_6Away_of_home_median                  0
Home_Offsides_HomeTeam_average_6                95
Crowd_Attendance_Away_AllGames_median_6         29
AvgA                                            95
Final_Away_goals_6Home_of_away_median            0
Away_Shots_HomeTeam_median_6                     0
Crowd_Attendance_Away_AllGames_Average_6        29
Home_Woodwork_AwayTeam_median_6                 29
Away_Woodwork_6Home_of_away_median              29
Away_Shots_6Home_of_away_mean                    0
Half_Time_Result_AwayTeam_sum_6                  0
Home_Red_Cards_6Away_of_home_mean                0
Home_score_6Away_of_home_median                  0
AHCh                                            95
Home_Yellow_Cards_HomeTeam_average_6             0
Away_Yellow_Cards_Away_AllGames_median_6         0
Crowd_Attendance_6Away_of_home_sum              95
Away_Bookings_Points_Home_AllGames_median_6     95
MaxAHA                                          95
VCCA                                            95
Half_Time_Home_Goals_Home_AllGames_Average_6     0
WHD                                              0
MaxC<2.5                                        95
Half_Time_Away_Goals_HomeTeam_average_6          0
Home_Fouls_AwayTeam_sum_6                        0
Final_Away_goals_HomeTeam_average_6              0
Half_Time_Away_Goals_6Home_of_away_mean          0
Home_Yellow_Cards_Home_AllGames_sum_6            0
Home_score_HomeTeam_median_6                     0
MaxC>2.5                                        95
Final_Away_goals_6Away_of_home_median            0
Away_Corners_HomeTeam_average_6                  0
BbAHh                                            1
BbMx>2.5                                         0
Away_score_HomeTeam_average_6                    0
PAHA                                            95
Away_Red_Cards_6Home_of_away_mean                0
Away_Shots_Target_HomeTeam_sum_6                 0
Away_Fouls_HomeTeam_sum_6                        0
IWCD                                            95
Home_Red_Cards_Home_AllGames_sum_6               0
Away_Shots_Target_6Home_of_away_sum              0
Home_Yellow_Cards_Away_AllGames_sum_6            0
B365CA                                          95
GBD                                             57
Away_Offsides_HomeTeam_median_6                 95
Home_Yellow_Cards_HomeTeam_sum_6                 0
B365>2.5                                        95
PCAHA                                           95
Half_Time_Result_6Home_of_away_median            0
Half_Time_Home_Goals_Away_AllGames_sum_6         0
Final_Home_goals_HomeTeam_median_6               0
SYA                                             95
Half_Time_Home_Goals_AwayTeam_sum_6              0
Home_score_6Home_of_away_sum                     0
PSD                                             38
B365AH                                          95
Away_Corners_AwayTeam_median_6                   0
Half_Time_Home_Goals_AwayTeam_average_6          0
Home_Offsides_HomeTeam_median_6                 95
Away_Shots_Target_Home_AllGames_median_6         0
Away_Woodwork_AwayTeam_median_6                 29
MaxA                                            95
Avg<2.5                                         95
Away_Yellow_Cards_6Away_of_home_sum              0
Away_Shots_Target_HomeTeam_median_6              0
BbAv>2.5                                         0
B365C>2.5                                       95
Away_Yellow_Cards_AwayTeam_average_6             0
Home_Shots_Target_Home_AllGames_Average_6        0
Away_Shots_Target_6Home_of_away_mean             0
Home_Fouls_Away_AllGames_median_6                0
Away_Fouls_HomeTeam_median_6                     0
Away_Offsides_Away_AllGames_median_6            29
Home_Shots_Away_AllGames_sum_6                   0
Final_result_AwayTeam_median_6                   0
Final_Away_goals_Away_AllGames_sum_6             0
Final_Home_goals_Away_AllGames_sum_6             0
Away_Woodwork_6Away_of_home_median              95
Home_Red_Cards_HomeTeam_sum_6                    0
Final_result_Away_AllGames_Average_6             0
Home_Shots_Target_AwayTeam_average_6             0
Half_Time_Away_Goals_HomeTeam_median_6           0
Home_Shots_6Home_of_away_sum                     0
Away_Red_Cards_Away_AllGames_Average_6           0
Home_Corners_6Away_of_home_mean                  0
Away_score_AwayTeam_sum_6                        0
Home_Fouls_6Away_of_home_median                  0
Home_Woodwork_Away_AllGames_median_6            29
Away_Woodwork_6Away_of_home_mean                95
Time                                            95
Away_score_Home_AllGames_median_6                0
Away_Shots_6Away_of_home_median                  0
Home_Shots_Target_6Home_of_away_sum              0
Home_Fouls_6Home_of_away_mean                    0
Home_Red_Cards_AwayTeam_sum_6                    0
Away_Yellow_Cards_Away_AllGames_Average_6        0
Home_Offsides_AwayTeam_median_6                 29
Away_Yellow_Cards_Away_AllGames_sum_6            0
Final_result_6Away_of_home_median                0
Away_Bookings_Points_6Away_of_home_sum          95
GBAHH                                           95
Half_Time_Away_Goals_6Away_of_home_sum           0
PCAHH                                           95
Home_Shots_Away_AllGames_median_6                0
Final_result_Away_AllGames_median_6              0
Home_Shots_6Away_of_home_sum                     0
Away_Corners_6Home_of_away_median                0
Home_Fouls_6Away_of_home_sum                     0
Home_score_Away_AllGames_Average_6               0
Away_Fouls_Home_AllGames_sum_6                   0
PSCD                                            38
Away_Corners_AwayTeam_average_6                  0
Away_Red_Cards_6Away_of_home_median              0
Final_result_HomeTeam_average_6                  0
Final_Away_goals_Home_AllGames_median_6          0
Home_Shots_6Away_of_home_mean                    0
Final_Home_goals_AwayTeam_median_6               0
Away_Shots_HomeTeam_average_6                    0

In [233]:
#dummies:

mylist = list(['HomeTeam','AwayTeam','Referee'])
dummies = pd.get_dummies(df_p[mylist], prefix= mylist)
df_p.drop(mylist, axis=1, inplace = True)
df_p = pd.concat([df_p,dummies], axis =1 )

In [234]:
df_p.shape

(7508, 851)

In [235]:
df_p.head(1)

,Away_Corners_Away_AllGames_median_6,B365H,Final_Home_goals_Away_AllGames_median_6,Home_Offsides_6Home_of_away_mean,SYH,Home_Bookings_Points_6Home_of_away_mean,B365D,Home_Corners_Home_AllGames_Average_6,Away_Yellow_Cards_HomeTeam_sum_6,Away_score_6Away_of_home_mean,Home_Corners_HomeTeam_average_6,BWD,Final_Away_goals_AwayTeam_sum_6,Home_Yellow_Cards_AwayTeam_sum_6,Home_Woodwork_6Home_of_away_sum,Home_Corners_HomeTeam_median_6,Away_Offsides_6Away_of_home_mean,Home_Woodwork_6Home_of_away_mean,GBH,AvgCD,Home_score_6Home_of_away_mean,BbAvD,Home_Offsides_6Away_of_home_mean,Half_Time_Home_Goals_HomeTeam_average_6,Home_Bookings_Points_6Away_of_home_sum,Crowd_Attendance_6Away_of_home_mean,AvgCAHH,B365A,SOA,Away_Red_Cards_Away_AllGames_median_6,Away_Corners_HomeTeam_sum_6,Home_Bookings_Points_HomeTeam_average_6,MaxCAHA,Half_Time_Home_Goals_Home_AllGames_median_6,BbMxA,BbAvA,Away_Fouls_HomeTeam_average_6,MaxH,Home_Shots_HomeTeam_median_6,BbAH,Home_Fouls_Away_AllGames_sum_6,Home_Red_Cards_HomeTeam_median_6,Final_Home_goals_AwayTeam_average_6,Away_Red_Cards_Home_AllGames_median_6,BbMxH,PSH,P>2.5,MaxCD,Half_Time_Result_HomeTeam_median_6,Home_Yellow_Cards_AwayTeam_average_6,Away_Bookings_Points_Away_AllGames_Average_6,Final_result_6Home_of_away_sum,Away_Corners_HomeTeam_median_6,Crowd_Attendance_Home_AllGames_Average_6,P<2.5,Away_Offsides_AwayTeam_sum_6,Away_Corners_Home_AllGames_median_6,AvgAHH,Home_Bookings_Points_6Away_of_home_median,BbAvAHH,Half_Time_Away_Goals_Home_AllGames_sum_6,Home_Fouls_AwayTeam_average_6,Away_Fouls_6Away_of_home_sum,Away_Fouls_Away_AllGames_sum_6,Away_score_Away_AllGames_median_6,Away_Offsides_6Away_of_home_median,GB>2.5,Away_Red_Cards_Home_AllGames_Average_6,Away_score_6Home_of_away_mean,Away_Red_Cards_6Away_of_home_mean,Away_Shots_Target_6Away_of_home_sum,Final_Home_goals_6Away_of_home_sum,Home_Corners_6Away_of_home_median,Home_Woodwork_Away_AllGames_sum_6,SOH,Away_Woodwork_Home_AllGames_Average_6,Home_score_6Away_of_home_mean,Home_Fouls_Home_AllGames_sum_6,Home_Yellow_Cards_6Away_of_home_sum,Away_Red_Cards_6Home_of_away_sum,BbMx<2.5,Home_Shots_AwayTeam_median_6,Home_Shots_HomeTeam_average_6,Away_Shots_Home_AllGames_median_6,Home_score_6Away_of_home_sum,LBH,Half_Time_Result_Home_AllGames_median_6,Home_Shots_Target_HomeTeam_average_6,Away_Red_Cards_6Away_of_home_sum,Away_Shots_Target_AwayTeam_average_6,IWCA,Away_Offsides_Home_AllGames_median_6,Away_Woodwork_Home_AllGames_sum_6,Home_Corners_AwayTeam_average_6,Home_Yellow_Cards_HomeTeam_median_6,Away_score_Away_AllGames_Average_6,Away_Bookings_Points_6Home_of_away_median,Final_Away_goals_HomeTeam_sum_6,Final_Away_goals_Home_AllGames_Average_6,SBD,SBA,Away_Woodwork_Away_AllGames_median_6,Home_score_6Home_of_away_median,Crowd_Attendance_HomeTeam_average_6,Home_score_Home_AllGames_median_6,Crowd_Attendance_AwayTeam_sum_6,IWH,Away_Red_Cards_HomeTeam_sum_6,Away_score_HomeTeam_median_6,Home_Yellow_Cards_6Home_of_away_median,WHCH,Away_Woodwork_6Home_of_away_mean,Half_Time_Home_Goals_Away_AllGames_median_6,Home_score_Away_AllGames_median_6,Bb1X2,Home_Shots_AwayTeam_sum_6,BWA,PAHH,Half_Time_Result_Home_AllGames_sum_6,Away_Red_Cards_6Home_of_away_median,Away_Shots_Target_Home_AllGames_Average_6,AvgCH,VCCD,Away_Woodwork_HomeTeam_average_6,Half_Time_Away_Goals_Away_AllGames_median_6,Half_Time_Away_Goals_HomeTeam_sum_6,Avg>2.5,B365<2.5,PC>2.5,Away_Red_Cards_AwayTeam_sum_6,Away_Woodwork_6Away_of_home_sum,Away_Bookings_Points_6Away_of_home_mean,Half_Time_Away_Goals_6Home_of_away_sum,Away_Shots_Away_AllGames_sum_6,Home_Corners_6Home_of_away_median,Home_Shots_HomeTeam_sum_6,Home_Shots_Target_HomeTeam_sum_6,Half_Time_Result_6Away_of_home_sum,AvgCA,Home_Fouls_6Home_of_away_sum,Home_Corners_Away_AllGames_median_6,Home_Woodwork_6Away_of_home_median,Half_Time_Away_Goals_AwayTeam_sum_6,Home_Shots_Target_6Away_of_home_mean,Away_Bookings_Points_HomeTeam_average_6,AvgC<2.5,Home_Woodwork_6Away_of_home_sum,Away_score_HomeTeam_sum_6,BSD,Away_Woodwork_HomeTeam_median_6,Final_Home_goals_AwayTeam_sum_6,Home_score_AwayTeam_sum_6,Home_Red_Cards_Away_AllGames_median_6,Home_Shots_6Home_of_away_mean,Final_Home_goals_Home_AllGames_Average_6,GBAH,Away_Bookings_Points_Away_AllGames_sum_6,Away_Shots_6Away_of_home_mean,Away_Offsides_AwayTeam_median_6,Home_Bookings_Points_HomeTeam_sum_6,B365CAHH,Crowd_Attendance_6Home_of_away_mean,Away_Corners_Home_AllGames_sum_6,Final_Away_goals_6Away_of_home_mean,VCCH,Home_Fouls_Home_AllGames_median_6,Away_Bookings_Points_AwayTeam_average_6,Away_Bookings_Points_6Home_of_away_mean,Home_Corners_Away_AllGames_sum_6,Home_Yellow_Cards_Away_AllGames_Average_6,Half_Time_Home_Goals_HomeTeam_sum_6,GBAHA,Away_Shots_Target_Away_AllGames_median_6,BbMxAHA,Crowd_Attendance_6Home_of_away_sum,Away_Woodwork_Home_AllGames_median_6,Half_Time_Away_Goals_6Away_of_home_median,Home_Red_Cards_6Home_of_away_mean,Half_Time_Result_Away_AllGames_sum_6,Away_Shots_Home_AllGames_sum_6,Home_Shots_Target_AwayTeam_sum_6,IWA,Half_Time_Away_Goals_Home_AllGames_Average_6,Final_result_6Away_of_home_sum,BWH,Away_Fouls_AwayTeam_average_6,Final_Away_goals_Away_AllGames_median_6,Away_Red_Cards_Home_AllGames_sum_6,Away_Yellow_Cards_6Away_of_home_median,Home_Yellow_Cards_6Away_of_home_mean,Away_score_6Home_of_away_median,Home_Shots_Target_6Home_of_away_mean,Half_Time_Result_AwayTeam_median_6,Home_Shots_Home_AllGames_sum_6,Final_Away_goals_AwayTeam_median_6,Home_Offsides_6Away_of_home_sum,Final_result_Home_AllGames_sum_6,PSCA,Home_Yellow_Cards_6Home_of_away_sum,Home_Woodwork_6Home_of_away_median,LBAHA,Home_Offsides_Away_AllGames_sum_6,BWCA,Home_score_Home_AllGames_Average_6,Home_Corners_6Away_of_home_sum,Home_Shots_Away_AllGames_Average_6,Away_Fouls_AwayTeam_median_6,Away_Corners_6Away_of_home_median,Final_result_AwayTeam_average_6,Away_Shots_Target_6Home_of_away_median,Home_Offsides_6Away_of_home_median,GB<2.5,Crowd_Attendance_HomeTeam_sum_6,Home_Shots_Target_6Away_of_home_sum,Home_Woodwork_HomeTeam_median_6,Away_Shots_Target_AwayTeam_median_6,Final_Home_goals_Home_AllGames_median_6,Home_Offsides_AwayTeam_sum_6,Away_Shots_6Home_of_away_sum,Away_Corners_6Home_of_away_sum,Away_Shots_Target_HomeTeam_average_6,Home_Shots_Target_6Away_of_home_median,Home_Woodwork_6Away_of_home_mean,Away_Bookings_Points_HomeTeam_sum_6,Home_Fouls_6Home_of_away_median,Final_result_Home_AllGames_median_6,Home_Bookings_Points_6Home_of_away_sum,Home_Shots_AwayTeam_average_6,Crowd_Attendance_HomeTeam_median_6,Away_Shots_Target_Home_AllGames_sum_6,Away_Red_Cards_Away_AllGames_sum_6,Away_Offsides_Home_AllGames_sum_6,Away_Yellow_Cards_6Home_of_away_sum,Home_Offsides_Home_AllGames_median_6,BWCD,Home_Bookings_Points_Away_AllGames_sum_6,Half_Time_Home_Goals_AwayTeam_median_6,Away_Yellow_Cards_HomeTeam_median_6,Half_Time_Result_6Home_of_away_sum,Half_Time_Home_Goals_Home_AllGames_sum_6,Home_Offsides_Home_AllGames_sum_6,Home_Bookings_Points_Away_AllGames_Average_6,Away_Shots_HomeTeam_sum_6,Half_Time_Home_Goals_6Home_of_away_mean,Half_Time_Home_Goals_6Home_of_away_sum,Away_Woodwork_6Home_of_away_sum,Away_Shots_Target_Away_AllGames_sum_6,Away_Fouls_6Away_of_home_mean,Away_score_6Home_of_away_sum,Home_Offsides_AwayTeam_average_6,Away_score_AwayTeam_median_6,Away_Shots_Target_6Away_of_home_median,Away_Shots_Target_6Away_of_home_mean,Home_Red_Cards_Away_AllGames_sum_6,Away_Shots_Target_Away_AllGames_Average_6,Home_Bookings_Points_Home_AllGames_median_6,Final_Away_goals_6Home_of_away_sum,Home_Yellow_Cards_6Home_of_away_mean,Half_Time_Result_6Away_of_home_mean,B365AHA,Home_Red_Cards_HomeTeam_average_6,Home_Offsides_Home_AllGames_Average_6,Home_Corners_HomeTeam_sum_6,Final_Away_goals_AwayTeam_average_6,Half_Time_Result_6Away_of_home_median,Final_Away_goals_Away_AllGames_Average_6,Home_Bookings_Points_Home_AllGames_Average_6,Away_Offsides_6Home_of_away_sum,Home_Yellow_Cards_Home_AllGames_median_6,Away_Woodwork_AwayTeam_average_6,Away_Fouls_6Away_of_home_median,Home_Offsides_HomeTeam_average_6,Crowd_Attendance_Away_AllGames_median_6,AvgA,Final_Away_goals_6Home_of_away_median,Away_Shots_HomeTeam_median_6,Crowd_Attendance_Away_AllGames_Average_6,Home_Woodwork_AwayTeam_median_6,Away_Woodwork_6Home_of_away_median,Away_Shots_6Home_of_away_mean,Half_Time_Result_AwayTeam_sum_6,Home_Red_Cards_6Away_of_home_mean,Home_score_6Away_of_home_median,AHCh,Home_Yellow_Cards_HomeTeam_average_6,Away_Yellow_Cards_Away_AllGames_median_6,Crowd_Attendance_6Away_of_home_sum,Away_Bookings_Points_Home_AllGames_median_6,MaxAHA,VCCA,Half_Time_Home_Goals_Home_AllGames_Average_6,WHD,MaxC<2.5,Half_Time_Away_Goals_HomeTeam_average_6,Home_Fouls_AwayTeam_sum_6,Final_Away_goals_HomeTeam_average_6,Half_Time_Away_Goals_6Home_of_away_mean,Home_Yellow_Cards_Home_AllGames_sum_6,Home_score_HomeTeam_median_6,MaxC>2.5,Final_Away_goals_6Away_of_home_median,Away_Corners_HomeTeam_average_6,BbAHh,BbMx>2.5,Away_score_HomeTeam_average_6,PAHA,Away_Red_Cards_6Home_of_away_mean,Away_Shots_Target_HomeTeam_sum_6,Away_Fouls_HomeTeam_sum_6,IWCD,Home_Red_Cards_Home_AllGames_sum_6,Away_Shots_Target_6Home_of_away_sum,Home_Yellow_Cards_Away_AllGames_sum_6,B365CA,GBD,Away_Offsides_HomeTeam_median_6,Home_Yellow_Cards_HomeTeam_sum_6,B365>2.5,PCAHA,Half_Time_Result_6Home_of_away_median,Half_Time_Home_Goals_Away_AllGames_sum_6,Final_Home_goals_HomeTeam_median_6,SYA,Half_Time_Home_Goals_AwayTeam_sum_6,Home_score_6Home_of_away_sum,PSD,B365AH,Away_Corners_AwayTeam_median_6,Half_Time_Home_Goals_AwayTeam_average_6,Home_Offsides_HomeTeam_median_6,Away_Shots_Target_Home_AllGames_median_6,Away_Woodwork_AwayTeam_median_6,MaxA,Avg<2.5,Away_Yellow_Cards_6Away_of_home_sum,Away_Shots_Target_HomeTeam_median_6,BbAv>2.5,B365C>2.5,Away_Yellow_Cards_AwayTeam_average_6,Home_Shots_Target_Home_AllGames_Average_6,Away_Shots_Target_6Home_of_away_mean,Home_Fouls_Away_AllGames_median_6,Away_Fouls_HomeTeam_median_6,Away_Offsides_Away_AllGames_median_6,Home_Shots_Away_AllGames_sum_6,Final_result_AwayTeam_median_6,Final_Away_goals_Away_AllGames_sum_6,Final_Home_goals_Away_AllGames_sum_6,Away_Woodwork_6Away_of_home_median,Home_Red_Cards_HomeTeam_sum_6,Final_result_Away_AllGames_Average_6,Home_Shots_Target_AwayTeam_average_6,Half_Time_Away_Goals_HomeTeam_median_6,Home_Shots_6Home_of_away_sum,Away_Red_Cards_Away_AllGames_Average_6,Home_Corners_6Away_of_home_mean,Away_score_AwayTeam_sum_6,Home_Fouls_6Away_of_home_median,Home_Woodwork_Away_AllGames_median_6,Away_Woodwork_6Away_of_home_mean,Time,Away_score_Home_AllGames_median_6,Away_Shots_6Away_of_home_median,Home_Shots_Target_6Home_of_away_sum,Home_Fouls_6Home_of_away_mean,Home_Red_Cards_AwayTeam_sum_6,Away_Yellow_Cards_Away_AllGames_Average_6,Home_Offsides_AwayTeam_median_6,Away_Yellow_Cards_Away_AllGames_sum_6,Final_result_6Away_of_home_median,Away_Bookings_Points_6Away_of_home_sum,GBAHH,Half_Time_Away_Goals_6Away_of_home_sum,PCAHH,Home_Shots_Away_AllGames_median_6,Final_result_Away_AllGames_median_6,Home_Shots_6Away_of_home_sum,Away_Corners_6Home_of_away_median,Home_Fouls_6Away_of_home_sum,Home_score_Away_AllGames_Average_6,Away_Fouls_Home_AllGames_sum_6,PSCD,Away_Corners_AwayTeam_average_6,Away_Red_Cards_6Away_of_home_median,Final_result_HomeTeam_average_6,Final_Away_goals_Home_AllGames_median_6,Home_Shots_6Away_of_home_mean,Final_Home_goals_AwayTeam_median_6,Away_Shots_HomeTeam_average_6,VCA,Away_Yellow_Cards_AwayTeam_median_6,Away_Yellow_Cards_Home_AllGames_sum_6,AvgC>2.5,Home_Shots_Target_6Home_of_away_median,Home_Fouls_HomeTeam_sum_6,Crowd_Attendance_6Away_of_home_median,Half_Time_Home_Goals_6Away_of_home_mean,Away_Woodwork_AwayTeam_sum_6,Home_Yellow_Cards_AwayTeam_median_6,B365AHH,Away_Offsides_6Home_of_away_mean,Season,Away_Yellow_Cards_HomeTeam_average_6,Away_Corners_Home_AllGames_Average_6,Half_Time_Away_Goals_Away_AllGames_Average_6,Crowd_Attendance_6Home_of_away_median,Away_Bookings_Points_AwayTeam_sum_6,Away_Red_Cards_AwayTeam_median_6,VCD,Final_result_HomeTeam_sum_6,Away_Yellow_Cards_6Home_of_away_mean,Date,Away_Shots_AwayTeam_median_6,Away_Offsides_AwayTeam_average_6,Home_Offsides_HomeTeam_sum_6,Final_Home_goals_HomeTeam_average_6,Home_Corners_Home_AllGames_median_6,Home_Fouls_6Away_of_home_mean,Home_Yellow_Cards_6Away_of_home_median,Half_Time_Away_Goals_6Away_of_home_mean,Home_score_AwayTeam_average_6,MaxCH,B365C<2.5,Home_Red_Cards_6Away_of_home_sum,Home_Shots_Target_Away_AllGames_Average_6,Away_Shots_Away_AllGames_Average_6,Away_Corners_6Home_of_away_mean,Away_Fouls_Away_AllGames_median_6,Home_Shots_Target_Home_AllGames_median_6,Crowd_Attendance,Home_Red_Cards_Away_AllGames_Average_6,Away_Offsides_6Home_of_away_median,Final_Home_goals_Away_AllGames_Average_6,Away_Offsides_HomeTeam_average_6,WHCD,Final_Away_goals_HomeTeam_median_6,SOD,Home_Woodwork_HomeTeam_average_6,Away_Shots_6Home_of_away_median,Away_Shots_AwayTeam_average_6,MaxD,BSA,MaxAHH,Home_Yellow_Cards_Home_AllGames_Average_6,Home_Shots_Target_HomeTeam_median_6,Away_Bookings_Points_HomeTeam_median_6,Half_Time_Away_Goals_Home_AllGames_median_6,Home_Fouls_Away_AllGames_Average_6,Home_Corners_AwayTeam_median_6,Final_result_6Away_of_home_mean,Away_Fouls_6Home_of_away_mean,Crowd_Attendance_Home_AllGames_sum_6,Final_Home_goals_6Home_of_away_mean,SBH,Away_Offsides_Away_AllGames_sum_6,Max>2.5,WHH,Away_Bookings_Points_6Away_of_home_median,Half_Time_Away_Goals_AwayTeam_median_6,BbAv<2.5,AHh,Home_Shots_Home_AllGames_median_6,Crowd_Attendance_Away_AllGames_sum_6,SJH,Home_Bookings_Points_AwayTeam_sum_6,Away_Yellow_Cards_AwayTeam_sum_6,IWCH,Away_Corners_Away_AllGames_sum_6,B365CAHA,Final_result_HomeTeam_median_6,LBD,VCH,Home_Woodwork_AwayTeam_average_6,Final_result_AwayTeam_sum_6,Home_Corners_6Home_of_away_mean,Away_score_AwayTeam_average_6,B365CD,Home_Yellow_Cards_Away_AllGames_median_6,Home_Offsides_Away_AllGames_median_6,Half_Time_Result_Home_AllGames_Average_6,SJD,Half_Time_Away_Goals_Away_AllGames_sum_6,BbOU,Away_Fouls_Home_AllGames_median_6,AvgD,Away_Shots_Away_AllGames_median_6,BSH,Away_Shots_Target_AwayTeam_sum_6,Away_score_Home_AllGames_Average_6,Final_result_6Home_of_away_median,PSA,Half_Time_Result_Away_AllGames_median_6,Home_Bookings_Points_HomeTeam_median_6,Home_Red_Cards_6Away_of_home_median,Away_Bookings_Points_Away_AllGames_median_6,Home_Bookings_Points_Home_AllGames_sum_6,BbMxD,Final_result_6Home_of_away_mean,AvgCAHA,Max<2.5,Away_Corners_AwayTeam_sum_6,Half_Time_Result_HomeTeam_average_6,Half_Time_Away_Goals_AwayTeam_average_6,Half_Time_Home_Goals_Away_AllGames_Average_6,Away_Fouls_6Home_of_away_median,Away_Yellow_Cards_6Home_of_away_median,Home_Offsides_6Home_of_away_sum,Home_Shots_Target_AwayTeam_median_6,AvgAHA,Home_Bookings_Points_AwayTeam_median_6,Home_Red_Cards_6Home_of_away_median,Final_Away_goals_Home_AllGames_sum_6,Home_score_Home_AllGames_sum_6,Away_Bookings_Points_AwayTeam_median_6,LBA,Home_Bookings_Points_6Away_of_home_mean,Home_Shots_6Home_of_away_median,Away_Woodwork_Away_AllGames_Average_6,Away_Offsides_Home_AllGames_Average_6,Away_score_Home_AllGames_sum_6,Half_Time_Result_AwayTeam_average_6,Home_score_AwayTeam_median_6,AvgH,Home_Shots_Target_Away_AllGames_median_6,Home_Woodwork_Away_AllGames_Average_6,MaxCA,Final_result,Half_Time_Home_Goals_6Away_of_home_median,Final_Home_goals_6Away_of_home_median,Home_Offsides_6Home_of_away_median,Half_Time_Result_HomeTeam_sum_6,Away_Bookings_Points_Home_AllGames_Average_6,Home_Bookings_Points_AwayTeam_average_6,Away_Red_Cards_HomeTeam_median_6,Home_Woodwork_AwayTeam_sum_6,Home_Corners_Home_AllGames_sum_6,Home_Shots_Target_Home_AllGames_sum_6,SJA,Home_Woodwork_Home_AllGames_Average_6,Away_Offsides_HomeTeam_sum_6,Home_Red_Cards_AwayTeam_average_6,Home_Red_Cards_6Home_of_away_sum,Final_Home_goals_6Home_of_away_sum,Half_Time_Result_6Home_of_away_mean,Away_Red_Cards_HomeTeam_average_6,Half_Time_Home_Goals_HomeTeam_median_6,Home_Fouls_HomeTeam_average_6,Away_Fouls_6Home_of_away_sum,LBAH,SYD,PSCH,GBA,Away_Offsides_6Away_of_home_sum,Final_Home_goals_Home_AllGames_sum_6,Away_Offsides_Away_AllGames_Average_6,Home_Fouls_Home_AllGames_Average_6,Away_Red_Cards_AwayTeam_average_6,Home_Fouls_HomeTeam_median_6,Half_Time_Away_Goals_6Home_of_away_median,PC<2.5,Final_Home_goals_6Home_of_away_median,Away_Fouls_AwayTeam_sum_6,Final_result_Home_AllGames_Average_6,Home_Bookings_Points_Away_AllGames_median_6,Home_Corners_Away_AllGames_Average_6,Away_Corners_6Away_of_home_sum,Home_Offsides_Away_AllGames_Average_6,Away_Woodwork_HomeTeam_sum_6,Away_Woodwork_Away_AllGames_sum_6,Home_score_Away_AllGames_sum_6,BbMxAHH,Half_Time_Result_Away_AllGames_Average_6,Away_Yellow_Cards_Home_AllGames_Average_6,Away_Bookings_Points_6Home_of_away_sum,Home_score_HomeTeam_sum_6,IWD,Away_Shots_AwayTeam_sum_6,WHCA,BbAvAHA,Away_score_6Away_of_home_median,Home_Woodwork_Home_AllGames_sum_6,Away_Shots_6Away_of_home_sum,Final_Home_goals_HomeTeam_sum_6,Away_Fouls_Away_AllGames_Average_6,Away_Shots_Home_AllGames_Average_6,Away_Bookings_Points_Home_AllGames_sum_6,Crowd_Attendance_AwayTeam_median_6,Home_Woodwork_Home_AllGames_median_6,B365CH,Home_Shots_Home_AllGames_Average_6,BWCH,Half_Time_Home_Goals_6Home_of_away_median,Home_Fouls_AwayTeam_median_6,Final_Away_goals_6Away_of_home_sum,Away_score_6Away_of_home_sum,Away_score_Away_AllGames_sum_6,Home_Red_Cards_AwayTeam_median_6,Home_score_HomeTeam_average_6,Crowd_Attendance_AwayTeam_average_6,Home_Shots_Target_Away_AllGames_sum_6,Half_Time_Home_Goals_6Away_of_home_sum,Final_Away_goals_6Home_of_away_mean,Away_Yellow_Cards_Home_AllGames_median_6,WHA,LBAHH,Crowd_Attendance_Home_AllGames_median_6,Home_Red_Cards_Home_AllGames_Average_6,Home_Red_Cards_Home_AllGames_median_6,Final_result_Away_AllGames_sum_6,Home_Shots_6Away_of_home_median,Final_Home_goals_6Away_of_home_mean,Home_Bookings_Points_6Home_of_away_median,Home_Woodwork_HomeTeam_sum_6,BbAvH,Home_Corners_6Home_of_away_sum,Home_Corners_AwayTeam_sum_6,Away_Corners_Away_AllGames_Average_6,MaxCAHH,Away_Corners_6Away_of_home_mean,Away_Yellow_Cards_6Away_of_home_mean,Away_Fouls_Home_AllGames_Average_6,HomeTeam_Arsenal,HomeTeam_Aston Villa,HomeTeam_Birmingham,HomeTeam_Blackburn,HomeTeam_Blackpool,HomeTeam_Bolton,HomeTeam_Bournemouth,HomeTeam_Bradford,HomeTeam_Brighton,HomeTeam_Burnley,HomeTeam_Cardiff,HomeTeam_Charlton,HomeTeam_Chelsea,HomeTeam_Coventry,HomeTeam_Crystal Palace,HomeTeam_Derby,HomeTeam_Everton,HomeTeam_Fulham,HomeTeam_Huddersfield,HomeTeam_Hull,HomeTeam_Ipswich,HomeTeam_Leeds,HomeTeam_Leicester,HomeTeam_Liverpool,HomeTeam_Man City,HomeTeam_Man United,HomeTeam_Middlesbrough,HomeTeam_Newcastle,HomeTeam_Norwich,HomeTeam_Portsmouth,HomeTeam_QPR,HomeTeam_Reading,HomeTeam_Sheffield United,HomeTeam_Southampton,HomeTeam_Stoke,HomeTeam_Sunderland,HomeTeam_Swansea,HomeTeam_Tottenham,HomeTeam_Watford,HomeTeam_West Brom,HomeTeam_West Ham,HomeTeam_Wigan,HomeTeam_Wolves,AwayTeam_Arsenal,AwayTeam_Aston Villa,AwayTeam_Birmingham,AwayTeam_Blackburn,AwayTeam_Blackpool,AwayTeam_Bolton,AwayTeam_Bournemouth,AwayTeam_Bradford,AwayTeam_Brighton,AwayTeam_Burnley,AwayTeam_Cardiff,AwayTeam_Charlton,AwayTeam_Chelsea,AwayTeam_Coventry,AwayTeam_Crystal Palace,AwayTeam_Derby,AwayTeam_Everton,AwayTeam_Fulham,AwayTeam_Huddersfield,AwayTeam_Hull,AwayTeam_Ipswich,AwayTeam_Leeds,AwayTeam_Leicester,AwayTeam_Liverpool,AwayTeam_Man City,AwayTeam_Man United,AwayTeam_Middlesbrough,AwayTeam_Newcastle,AwayTeam_Norwich,AwayTeam_Portsmouth,AwayTeam_QPR,AwayTeam_Reading,AwayTeam_Sheffield United,AwayTeam_Southampton,AwayTeam_Stoke,AwayTeam_Sunderland,AwayTeam_Swansea,AwayTeam_Tottenham,AwayTeam_Watford,AwayTeam_West Brom,AwayTeam_West Ham,AwayTeam_Wigan,AwayTeam_Wolves,Referee_A D'Urso,Referee_A Madley,Referee_A Marriner,Referee_A Taylor,Referee_A Wiley,Referee_A. G. Wiley,Referee_A. P. D'Urso,Referee_A.G. Wiley,Referee_Alan Wiley,Referee_Andy D'Urso,Referee_Andy Hall,Referee_B Knight,Referee_B. Knight,"Referee_Barber, G. P.",Referee_Barry Knight,"Referee_Barry, N. S.","Referee_Bennett, S. G.",Referee_C Foy,Referee_C Kavanagh,Referee_C Pawson,Referee_C Wilkes,Referee_C. J. Foy,Referee_C. R. Wilkes,Referee_Clive Wilkes,Referee_D Coote,Referee_D Elleray,Referee_D England,Referee_D Gallagh,Referee_D Gallaghe,Referee_D Gallagher,Referee_D Pugh,"Referee_D'U

In [206]:
#1
df_p.loc[:,df_p.dtypes==object]

NameError: name 'df_p' is not defined

In [237]:
#2
numerics = ['int16', 'int32', 'int64', 'float16', 'float32', 'float64','uint8']
newdf = df_p.select_dtypes(exclude=numerics)

In [238]:
newdf.head()

  Time        Date
0   -1  2000-08-19
1   -1  2000-08-19
2   -1  2000-08-19
3   -1  2000-08-19
4   -1  2000-08-19

In [520]:
df_O.to_csv('df_O.csv')

In [ ]:
df_p.to_csv('df_p.csv')